In [1]:
from nnsight import LanguageModel
import torch

In [2]:
import einops

In [3]:
from nnsight import CONFIG
CONFIG.API.APIKEY = "c082b87e-d32b-426f-961f-bd636a711885"

In [4]:
# Load MATH-500 dataset using direct HTTP
import requests
import pandas as pd

# Get all 500 rows by making multiple API calls (limit is 100 per call)
all_rows = []
for offset in range(0, 500, 100):
    api_url = f"https://datasets-server.huggingface.co/rows?dataset=HuggingFaceH4/MATH-500&config=default&split=test&offset={offset}&length=100"
    response = requests.get(api_url)
    data = response.json()
    all_rows.extend([row['row'] for row in data['rows']])

# Convert to DataFrame
math_df = pd.DataFrame(all_rows)

print(f"Loaded {len(math_df)} problems")
print(f"Columns: {list(math_df.columns)}")
print(f"\nSample problem:")
print(f"Problem: {math_df.iloc[0]['problem']}")
print(f"Solution: {math_df.iloc[0]['solution'][:200]}...")

Loaded 500 problems
Columns: ['problem', 'solution', 'answer', 'subject', 'level', 'unique_id']

Sample problem:
Problem: Convert the point $(0,3)$ in rectangular coordinates to polar coordinates.  Enter your answer in the form $(r,\theta),$ where $r > 0$ and $0 \le \theta < 2 \pi.$
Solution: We have that $r = \sqrt{0^2 + 3^2} = 3.$  Also, if we draw the line connecting the origin and $(0,3),$ this line makes an angle of $\frac{\pi}{2}$ with the positive $x$-axis.

[asy]
unitsize(0.8 cm);
...

In [5]:
math_df.head()

,problem,solution,answer,subject,level,unique_id
0,"Convert the point $(0,3)$ in rectangular coord...",We have that $r = \sqrt{0^2 + 3^2} = 3.$ Also...,"\left( 3, \frac{\pi}{2} \right)",Precalculus,2,test/precalculus/807.json
1,Define\n\[p = \sum_{k = 1}^\infty \frac{1}{k^2...,We count the number of times $\frac{1}{n^3}$ a...,p - q,Intermediate Algebra,5,test/intermediate_algebra/1994.json
2,"If $f(x) = \frac{3x-2}{x-2}$, what is the valu...",$f(-2)+f(-1)+f(0)=\frac{3(-2)-2}{-2-2}+\frac{3...,\frac{14}{3},Algebra,3,test/algebra/2584.json
3,How many positive whole-number divisors does 1...,First prime factorize $196=2^2\cdot7^2$. The ...,9,Number Theory,3,test/number_theory/572.json
4,The results of a cross-country team's training...,Evelyn covered more distance in less time than...,\text{Evelyn},Algebra,2,test/algebra/1349.json

In [6]:
# Plan
# 1) Load first MATH-500 problem from existing df or fetch if missing
# 2) Initialize DeepSeek-R1-Distill-Qwen-1.5B locally
# 3) Build prompt with explicit thinking and boxed answer instructions
# 4) Generate 100 samples locally with moderate temperature/top_p
# 5) During generation, collect per-step last-layer hidden states and tokens
# 6) Decode, parse second <think> block, response after </think>, and final \boxed{...}
# 7) Compute combined hidden tensor batch size and assemble DataFrame

import re
import math
import json
import torch
import pandas as pd
from nnsight import LanguageModel

# Ensure math_df exists; if not, fetch quickly
try:
    _ = math_df
except NameError:
    import requests
    all_rows = []
    for offset in range(0, 100, 100):
        api_url = f"https://datasets-server.huggingface.co/rows?dataset=HuggingFaceH4/MATH-500&config=default&split=test&offset={offset}&length=100"
        data = requests.get(api_url).json()
        all_rows.extend([row['row'] for row in data['rows']])
    math_df = pd.DataFrame(all_rows)

first_problem = math_df.iloc[0]['problem']

In [7]:
model=LanguageModel("deepseek-ai/DeepSeek-R1-Distill-Llama-8B", device_map="auto")
print(model.model)

config.json:   0%|          | 0.00/826 [00:00<?, ?B/s]

tokenizer_config.json: 0.00B [00:00, ?B/s]

tokenizer.json: 0.00B [00:00, ?B/s]

LlamaModel(
  (embed_tokens): Embedding(128256, 4096)
  (layers): ModuleList(
    (0-31): 32 x LlamaDecoderLayer(
      (self_attn): LlamaAttention(
        (q_proj): Linear(in_features=4096, out_features=4096, bias=False)
        (k_proj): Linear(in_features=4096, out_features=1024, bias=False)
        (v_proj): Linear(in_features=4096, out_features=1024, bias=False)
        (o_proj): Linear(in_features=4096, out_features=4096, bias=False)
      )
      (mlp): LlamaMLP(
        (gate_proj): Linear(in_features=4096, out_features=14336, bias=False)
        (up_proj): Linear(in_features=4096, out_features=14336, bias=False)
        (down_proj): Linear(in_features=14336, out_features=4096, bias=False)
        (act_fn): SiLU()
      )
      (input_layernorm): LlamaRMSNorm((4096,), eps=1e-05)
      (post_attention_layernorm): LlamaRMSNorm((4096,), eps=1e-05)
    )
  )
  (norm): LlamaRMSNorm((4096,), eps=1e-05)
  (rotary_emb): LlamaRotaryEmbedding()
)

In [8]:
import os

In [9]:

def run_and_save_for_problem(problem_text, problem_id, num_samples=20, max_new_tokens=512, save_root="/workspace/uncertainty/rollouts"):
# Build prompt with thinking and boxed answer instructions
    os.makedirs(save_root, exist_ok=True)
    system_instructions = f"Solve the following math problem. Enclose your thoughts within <think>\n\n</think> tags. Your final answer should be denoted as **Answer:** and must be enclosed in \\boxed{{}}"
    chat = [
        {"role": "user", "content": f"{system_instructions}\n\nProblem: {problem_text}"},
    ]
    prompt = model.tokenizer.apply_chat_template(chat, tokenize=True, add_generation_prompt=True)

    num_samples = 35
    max_new_tokens = 2048


    # Capture hidden states for every new token across the whole batch of 100 prompts


    # Prepare batch prompts
    batch_prompts = [prompt] * num_samples
    promptlen = len(prompt)
    with model.generate(max_new_tokens=max_new_tokens, temperature=0.6, top_p=0.95, remote=True, do_sample=True) as tracer:
            with tracer.invoke(batch_prompts):
                hidden_collector = list().save()
                with tracer.all():
                # last layer hidden states for all sequences at current step
                    hidden_collector.append(model.model.layers[-1].output)
                # save generated token ids per sequence
            with tracer.invoke():
                token_batch = model.generator.output.save()
    hidden_states=torch.cat(hidden_collector, dim=1)
    keep_rows = (token_batch[:, promptlen:] == 128014).any(dim=1)
    token_batch = token_batch[keep_rows]
    b_idx, t_rel = (token_batch[:, promptlen:] == 128014).nonzero(as_tuple=True)
    t_abs = t_rel + promptlen
    hidden_states = hidden_states[b_idx, t_abs]
    sample = {
        "problem_id": problem_id,
        "hidden_states": hidden_states.cpu(),
        "token_batch": token_batch.cpu(),
        "system_instructions": system_instructions,
        "prompt": prompt,
    }            
    torch.save(sample, os.path.join(save_root, f"{problem_id}.pt"))

In [15]:
len(math_df)

500

In [11]:
problem_text= math_df['problem'][1]
problem_id= math_df['unique_id'][1].replace('/', '')

In [12]:
math_df

,problem,solution,answer,subject,level,unique_id
0,"Convert the point $(0,3)$ in rectangular coord...",We have that $r = \sqrt{0^2 + 3^2} = 3.$ Also...,"\left( 3, \frac{\pi}{2} \right)",Precalculus,2,test/precalculus/807.json
1,Define\n\[p = \sum_{k = 1}^\infty \frac{1}{k^2...,We count the number of times $\frac{1}{n^3}$ a...,p - q,Intermediate Algebra,5,test/intermediate_algebra/1994.json
2,"If $f(x) = \frac{3x-2}{x-2}$, what is the valu...",$f(-2)+f(-1)+f(0)=\frac{3(-2)-2}{-2-2}+\frac{3...,\frac{14}{3},Algebra,3,test/algebra/2584.json
3,How many positive whole-number divisors does 1...,First prime factorize $196=2^2\cdot7^2$. The ...,9,Number Theory,3,test/number_theory/572.json
4,The results of a cross-country team's training...,Evelyn covered more distance in less time than...,\text{Evelyn},Algebra,2,test/algebra/1349.json
...,...,...,...,...,...,...
495,What is the domain of the function $f(x) = \fr...,The inner logarithm is only defined if $x - 2 ...,"(2,12) \cup (12,102)",Intermediate Algebra,4,test/intermediate_algebra/1981.json
496,Let $z = 1+i$ and $w = \dfrac{3z+1}{5z+7}$. Fi...,"Plugging in, we have $w = \dfrac{3(1+i)+1}{5(1...",\frac{5}{13},Intermediate Algebra,3,test/intermediate_algebra/1232.json
497,An equiangular octagon has four sides of lengt...,The octagon can be partitioned into five squar...,\frac{7}{2},Geometry,5,test/geometry/561.json
498,A sequence $(a_n)$ is defined as follows:\n\[a...,"First, if $a_3 = a_1,$ then\n\[a_1 = a_3 = a_5...",-1,Intermediate Algebra,5,test/intermediate_algebra/1508.json
499,Altitudes $\overline{AD}$ and $\overline{BE}$ ...,"First, we build a diagram:\n\n[asy]\n\nsize(15...",106^\circ,Geometry,4,test/geometry/615.json

In [14]:
for i in range(75,len(math_df)):
    try:
        problem_text= math_df['problem'][i]
        problem_id= math_df['unique_id'][i].replace('/', '')
        run_and_save_for_problem(problem_text, problem_id)
    except Exception as e:
        print(f"Error on problem {i}: {e}")
        continue

[2025-08-29 14:19:43] [cbc45acf-4df5-44aa-bbde-efe42eaa9499] RECEIVED   : Your job has been received and is waiting to be queued.
[2025-08-29 14:19:43] [cbc45acf-4df5-44aa-bbde-efe42eaa9499] QUEUED     : Your job has been recieved by the coordinator and is waiting to be queued.
[2025-08-29 14:19:43] [cbc45acf-4df5-44aa-bbde-efe42eaa9499] QUEUED     : Task cbc45acf-4df5-44aa-bbde-efe42eaa9499 has been added to the queue. Currently at position 1
[2025-08-29 14:19:46] [cbc45acf-4df5-44aa-bbde-efe42eaa9499] QUEUED     : `nnsight.modeling.language.LanguageModel:{"repo_id": "deepseek-ai/DeepSeek-R1-Distill-Llama-8B", "revision": "main"}` is being deployed... stand by.
[2025-08-29 14:19:47] [cbc45acf-4df5-44aa-bbde-efe42eaa9499] QUEUED     : `nnsight.modeling.language.LanguageModel:{"repo_id": "deepseek-ai/DeepSeek-R1-Distill-Llama-8B", "revision": "main"}` is being deployed... stand by.
[2025-08-29 14:19:48] [cbc45acf-4df5-44aa-bbde-efe42eaa9499] QUEUED     : `nnsight.modeling.language.LanguageModel:{"repo_id": "deepseek-ai/DeepSeek-R1-Distill-Llama-8B", "revision": "main"}` is being deployed... stand by.
[2025-08-29 14:19:49] [cbc45acf-4df5-44aa-bbde-efe42eaa9499] QUEUED     : `nnsight.modeling.language.LanguageModel:{"repo_id": "deepseek-ai/DeepSeek-R1-Distill-Llama-8B", "revision": "main"}` is being deployed... stand by.
[2025-08-29 14:19:50] [cbc45acf-4df5-44aa-bbde-efe42eaa9499] QUEUED     : `nnsight.modeling.language.LanguageModel:{"repo_id": "deepseek-ai/DeepSeek-R1-Distill-Llama-8B", "revision": "main"}` is being deployed... stand by.
[2025-08-29 14:19:51] [cbc45acf-4df5-44aa-bbde-efe42eaa9499] QUEUED     : `nnsight.modeling.language.LanguageModel:{"repo_id": "deepseek-ai/DeepSeek-R1-Distill-Llama-8B", "revision": "main"}` is being deployed... stand by.
[2025-08-29 14:19:52] [cbc45acf-4df5-44aa-bbde-efe42eaa9499] QUEUED     : `nnsight.modeling.language.LanguageModel:{"repo_id": "deepseek-ai/DeepSeek-R1-Distill-Llama-8B", "revision": "main"}` is being deployed... stand by.
[2025-08-29 14:19:53] [cbc45acf-4df5-44aa-bbde-efe42eaa9499] QUEUED     : Dispatching task...
[2025-08-29 14:20:29] [cbc45acf-4df5-44aa-bbde-efe42eaa9499] RUNNING    : Your job has started running.
[2025-08-29 14:23:01] [cbc45acf-4df5-44aa-bbde-efe42eaa9499] COMPLETED  : Your job has been completed.

Downloading result:   0%|          | 0.00/612M [00:00<?, ?B/s]

[2025-08-29 14:23:30] [c860fe18-f025-4502-ac7e-c3a218af1ca1] RECEIVED   : Your job has been received and is waiting to be queued.
[2025-08-29 14:23:30] [c860fe18-f025-4502-ac7e-c3a218af1ca1] QUEUED     : Your job has been recieved by the coordinator and is waiting to be queued.
[2025-08-29 14:23:30] [c860fe18-f025-4502-ac7e-c3a218af1ca1] QUEUED     : Task c860fe18-f025-4502-ac7e-c3a218af1ca1 has been added to the queue. Currently at position 1
[2025-08-29 14:23:30] [c860fe18-f025-4502-ac7e-c3a218af1ca1] QUEUED     : Dispatching task...
[2025-08-29 14:23:30] [c860fe18-f025-4502-ac7e-c3a218af1ca1] RUNNING    : Your job has started running.
[2025-08-29 14:26:01] [c860fe18-f025-4502-ac7e-c3a218af1ca1] COMPLETED  : Your job has been completed.

Downloading result:   0%|          | 0.00/612M [00:00<?, ?B/s]

[2025-08-29 14:26:32] [449ec6bf-6396-46c8-b7bd-f4dd9ccf6810] RECEIVED   : Your job has been received and is waiting to be queued.
[2025-08-29 14:26:32] [449ec6bf-6396-46c8-b7bd-f4dd9ccf6810] QUEUED     : Your job has been recieved by the coordinator and is waiting to be queued.
[2025-08-29 14:26:32] [449ec6bf-6396-46c8-b7bd-f4dd9ccf6810] QUEUED     : Task 449ec6bf-6396-46c8-b7bd-f4dd9ccf6810 has been added to the queue. Currently at position 1
[2025-08-29 14:26:32] [449ec6bf-6396-46c8-b7bd-f4dd9ccf6810] QUEUED     : Dispatching task...
[2025-08-29 14:26:34] [449ec6bf-6396-46c8-b7bd-f4dd9ccf6810] RUNNING    : Your job has started running.
[2025-08-29 14:27:00] [449ec6bf-6396-46c8-b7bd-f4dd9ccf6810] COMPLETED  : Your job has been completed.

Downloading result:   0%|          | 0.00/151M [00:00<?, ?B/s]

[2025-08-29 14:27:08] [ac0de300-543f-43fa-803a-149f14c499b0] RECEIVED   : Your job has been received and is waiting to be queued.
[2025-08-29 14:27:08] [ac0de300-543f-43fa-803a-149f14c499b0] QUEUED     : Your job has been recieved by the coordinator and is waiting to be queued.
[2025-08-29 14:27:08] [ac0de300-543f-43fa-803a-149f14c499b0] QUEUED     : Task ac0de300-543f-43fa-803a-149f14c499b0 has been added to the queue. Currently at position 1
[2025-08-29 14:27:08] [ac0de300-543f-43fa-803a-149f14c499b0] QUEUED     : Dispatching task...
[2025-08-29 14:27:08] [ac0de300-543f-43fa-803a-149f14c499b0] RUNNING    : Your job has started running.
[2025-08-29 14:29:41] [ac0de300-543f-43fa-803a-149f14c499b0] COMPLETED  : Your job has been completed.

Downloading result:   0%|          | 0.00/621M [00:00<?, ?B/s]

[2025-08-29 14:30:07] [d21bfc8e-856b-4bf8-a3a9-09e40c90a696] RECEIVED   : Your job has been received and is waiting to be queued.
[2025-08-29 14:30:07] [d21bfc8e-856b-4bf8-a3a9-09e40c90a696] QUEUED     : Your job has been recieved by the coordinator and is waiting to be queued.
[2025-08-29 14:30:07] [d21bfc8e-856b-4bf8-a3a9-09e40c90a696] QUEUED     : Task d21bfc8e-856b-4bf8-a3a9-09e40c90a696 has been added to the queue. Currently at position 1
[2025-08-29 14:30:07] [d21bfc8e-856b-4bf8-a3a9-09e40c90a696] QUEUED     : Dispatching task...
[2025-08-29 14:30:07] [d21bfc8e-856b-4bf8-a3a9-09e40c90a696] RUNNING    : Your job has started running.
[2025-08-29 14:30:30] [d21bfc8e-856b-4bf8-a3a9-09e40c90a696] COMPLETED  : Your job has been completed.

Downloading result:   0%|          | 0.00/134M [00:00<?, ?B/s]

[2025-08-29 14:30:37] [5811e0b6-36af-4300-b689-842cfd629864] RECEIVED   : Your job has been received and is waiting to be queued.
[2025-08-29 14:30:37] [5811e0b6-36af-4300-b689-842cfd629864] QUEUED     : Your job has been recieved by the coordinator and is waiting to be queued.
[2025-08-29 14:30:37] [5811e0b6-36af-4300-b689-842cfd629864] QUEUED     : Task 5811e0b6-36af-4300-b689-842cfd629864 has been added to the queue. Currently at position 1
[2025-08-29 14:30:37] [5811e0b6-36af-4300-b689-842cfd629864] QUEUED     : Dispatching task...
[2025-08-29 14:30:39] [5811e0b6-36af-4300-b689-842cfd629864] RUNNING    : Your job has started running.
[2025-08-29 14:33:10] [5811e0b6-36af-4300-b689-842cfd629864] COMPLETED  : Your job has been completed.

Downloading result:   0%|          | 0.00/613M [00:00<?, ?B/s]

[2025-08-29 14:33:36] [54490557-a828-4acd-afea-85d5dbb24f6b] RECEIVED   : Your job has been received and is waiting to be queued.
[2025-08-29 14:33:36] [54490557-a828-4acd-afea-85d5dbb24f6b] QUEUED     : Your job has been recieved by the coordinator and is waiting to be queued.
[2025-08-29 14:33:36] [54490557-a828-4acd-afea-85d5dbb24f6b] QUEUED     : Task 54490557-a828-4acd-afea-85d5dbb24f6b has been added to the queue. Currently at position 1
[2025-08-29 14:33:36] [54490557-a828-4acd-afea-85d5dbb24f6b] QUEUED     : Dispatching task...
[2025-08-29 14:33:36] [54490557-a828-4acd-afea-85d5dbb24f6b] RUNNING    : Your job has started running.
[2025-08-29 14:34:19] [54490557-a828-4acd-afea-85d5dbb24f6b] COMPLETED  : Your job has been completed.

Downloading result:   0%|          | 0.00/236M [00:00<?, ?B/s]

[2025-08-29 14:34:31] [353545f7-83b1-47da-b819-0f620fa17005] RECEIVED   : Your job has been received and is waiting to be queued.
[2025-08-29 14:34:31] [353545f7-83b1-47da-b819-0f620fa17005] QUEUED     : Your job has been recieved by the coordinator and is waiting to be queued.
[2025-08-29 14:34:31] [353545f7-83b1-47da-b819-0f620fa17005] QUEUED     : Task 353545f7-83b1-47da-b819-0f620fa17005 has been added to the queue. Currently at position 1
[2025-08-29 14:34:31] [353545f7-83b1-47da-b819-0f620fa17005] QUEUED     : Dispatching task...
[2025-08-29 14:34:33] [353545f7-83b1-47da-b819-0f620fa17005] RUNNING    : Your job has started running.
[2025-08-29 14:37:06] [353545f7-83b1-47da-b819-0f620fa17005] COMPLETED  : Your job has been completed.

Downloading result:   0%|          | 0.00/626M [00:00<?, ?B/s]

[2025-08-29 14:37:30] [be6647dd-c5e5-48f6-8337-4f49931ee627] RECEIVED   : Your job has been received and is waiting to be queued.
[2025-08-29 14:37:30] [be6647dd-c5e5-48f6-8337-4f49931ee627] QUEUED     : Your job has been recieved by the coordinator and is waiting to be queued.
[2025-08-29 14:37:30] [be6647dd-c5e5-48f6-8337-4f49931ee627] QUEUED     : Task be6647dd-c5e5-48f6-8337-4f49931ee627 has been added to the queue. Currently at position 1
[2025-08-29 14:37:30] [be6647dd-c5e5-48f6-8337-4f49931ee627] QUEUED     : Dispatching task...
[2025-08-29 14:37:30] [be6647dd-c5e5-48f6-8337-4f49931ee627] RUNNING    : Your job has started running.
[2025-08-29 14:40:01] [be6647dd-c5e5-48f6-8337-4f49931ee627] COMPLETED  : Your job has been completed.

Downloading result:   0%|          | 0.00/606M [00:00<?, ?B/s]

[2025-08-29 14:40:27] [11578170-900c-4524-a1c3-99ea32bc92e6] RECEIVED   : Your job has been received and is waiting to be queued.
[2025-08-29 14:40:27] [11578170-900c-4524-a1c3-99ea32bc92e6] QUEUED     : Your job has been recieved by the coordinator and is waiting to be queued.
[2025-08-29 14:40:27] [11578170-900c-4524-a1c3-99ea32bc92e6] QUEUED     : Task 11578170-900c-4524-a1c3-99ea32bc92e6 has been added to the queue. Currently at position 1
[2025-08-29 14:40:27] [11578170-900c-4524-a1c3-99ea32bc92e6] QUEUED     : Dispatching task...
[2025-08-29 14:40:27] [11578170-900c-4524-a1c3-99ea32bc92e6] RUNNING    : Your job has started running.
[2025-08-29 14:43:00] [11578170-900c-4524-a1c3-99ea32bc92e6] COMPLETED  : Your job has been completed.

Downloading result:   0%|          | 0.00/616M [00:00<?, ?B/s]

[2025-08-29 14:43:23] [561e403d-6671-4c46-84dd-05f0f9ac3f0d] RECEIVED   : Your job has been received and is waiting to be queued.
[2025-08-29 14:43:23] [561e403d-6671-4c46-84dd-05f0f9ac3f0d] QUEUED     : Your job has been recieved by the coordinator and is waiting to be queued.
[2025-08-29 14:43:23] [561e403d-6671-4c46-84dd-05f0f9ac3f0d] QUEUED     : Task 561e403d-6671-4c46-84dd-05f0f9ac3f0d has been added to the queue. Currently at position 1
[2025-08-29 14:43:23] [561e403d-6671-4c46-84dd-05f0f9ac3f0d] QUEUED     : Dispatching task...
[2025-08-29 14:43:23] [561e403d-6671-4c46-84dd-05f0f9ac3f0d] RUNNING    : Your job has started running.
[2025-08-29 14:45:59] [561e403d-6671-4c46-84dd-05f0f9ac3f0d] COMPLETED  : Your job has been completed.

Downloading result:   0%|          | 0.00/618M [00:00<?, ?B/s]

[2025-08-29 14:46:25] [f5e962eb-651d-4de6-8392-059a0dd6bdf4] RECEIVED   : Your job has been received and is waiting to be queued.
[2025-08-29 14:46:25] [f5e962eb-651d-4de6-8392-059a0dd6bdf4] QUEUED     : Your job has been recieved by the coordinator and is waiting to be queued.
[2025-08-29 14:46:25] [f5e962eb-651d-4de6-8392-059a0dd6bdf4] QUEUED     : Task f5e962eb-651d-4de6-8392-059a0dd6bdf4 has been added to the queue. Currently at position 1
[2025-08-29 14:46:25] [f5e962eb-651d-4de6-8392-059a0dd6bdf4] QUEUED     : Dispatching task...
[2025-08-29 14:46:25] [f5e962eb-651d-4de6-8392-059a0dd6bdf4] RUNNING    : Your job has started running.
[2025-08-29 14:46:48] [f5e962eb-651d-4de6-8392-059a0dd6bdf4] COMPLETED  : Your job has been completed.

Downloading result:   0%|          | 0.00/140M [00:00<?, ?B/s]

[2025-08-29 14:46:56] [39bcde64-b73a-48b0-84c0-e64278e9f91a] RECEIVED   : Your job has been received and is waiting to be queued.
[2025-08-29 14:46:56] [39bcde64-b73a-48b0-84c0-e64278e9f91a] QUEUED     : Your job has been recieved by the coordinator and is waiting to be queued.
[2025-08-29 14:46:56] [39bcde64-b73a-48b0-84c0-e64278e9f91a] QUEUED     : Task 39bcde64-b73a-48b0-84c0-e64278e9f91a has been added to the queue. Currently at position 1
[2025-08-29 14:46:56] [39bcde64-b73a-48b0-84c0-e64278e9f91a] QUEUED     : Dispatching task...
[2025-08-29 14:46:56] [39bcde64-b73a-48b0-84c0-e64278e9f91a] RUNNING    : Your job has started running.
[2025-08-29 14:48:19] [39bcde64-b73a-48b0-84c0-e64278e9f91a] COMPLETED  : Your job has been completed.

Downloading result:   0%|          | 0.00/379M [00:00<?, ?B/s]

[2025-08-29 14:48:35] [fa1b324f-c8a5-4063-89b8-c399807458d5] RECEIVED   : Your job has been received and is waiting to be queued.
[2025-08-29 14:48:35] [fa1b324f-c8a5-4063-89b8-c399807458d5] QUEUED     : Your job has been recieved by the coordinator and is waiting to be queued.
[2025-08-29 14:48:35] [fa1b324f-c8a5-4063-89b8-c399807458d5] QUEUED     : Task fa1b324f-c8a5-4063-89b8-c399807458d5 has been added to the queue. Currently at position 1
[2025-08-29 14:48:35] [fa1b324f-c8a5-4063-89b8-c399807458d5] QUEUED     : Dispatching task...
[2025-08-29 14:48:36] [fa1b324f-c8a5-4063-89b8-c399807458d5] RUNNING    : Your job has started running.
[2025-08-29 14:51:10] [fa1b324f-c8a5-4063-89b8-c399807458d5] COMPLETED  : Your job has been completed.

Downloading result:   0%|          | 0.00/626M [00:00<?, ?B/s]

[2025-08-29 14:51:41] [53a2c751-d04d-40c2-a01a-e51bfefa49cf] RECEIVED   : Your job has been received and is waiting to be queued.
[2025-08-29 14:51:41] [53a2c751-d04d-40c2-a01a-e51bfefa49cf] QUEUED     : Your job has been recieved by the coordinator and is waiting to be queued.
[2025-08-29 14:51:41] [53a2c751-d04d-40c2-a01a-e51bfefa49cf] QUEUED     : Task 53a2c751-d04d-40c2-a01a-e51bfefa49cf has been added to the queue. Currently at position 1
[2025-08-29 14:51:41] [53a2c751-d04d-40c2-a01a-e51bfefa49cf] QUEUED     : Dispatching task...
[2025-08-29 14:51:41] [53a2c751-d04d-40c2-a01a-e51bfefa49cf] RUNNING    : Your job has started running.
[2025-08-29 14:53:55] [53a2c751-d04d-40c2-a01a-e51bfefa49cf] COMPLETED  : Your job has been completed.

Downloading result:   0%|          | 0.00/556M [00:00<?, ?B/s]

[2025-08-29 14:54:18] [47630bbc-a651-4bf4-8860-c6d634d5ea1b] RECEIVED   : Your job has been received and is waiting to be queued.
[2025-08-29 14:54:18] [47630bbc-a651-4bf4-8860-c6d634d5ea1b] QUEUED     : Your job has been recieved by the coordinator and is waiting to be queued.
[2025-08-29 14:54:18] [47630bbc-a651-4bf4-8860-c6d634d5ea1b] QUEUED     : Task 47630bbc-a651-4bf4-8860-c6d634d5ea1b has been added to the queue. Currently at position 1
[2025-08-29 14:54:18] [47630bbc-a651-4bf4-8860-c6d634d5ea1b] QUEUED     : Dispatching task...
[2025-08-29 14:54:19] [47630bbc-a651-4bf4-8860-c6d634d5ea1b] RUNNING    : Your job has started running.
[2025-08-29 14:54:50] [47630bbc-a651-4bf4-8860-c6d634d5ea1b] COMPLETED  : Your job has been completed.

Downloading result:   0%|          | 0.00/180M [00:00<?, ?B/s]

[2025-08-29 14:54:58] [540f1f85-45ed-49c1-88fb-a91f2118d30a] RECEIVED   : Your job has been received and is waiting to be queued.
[2025-08-29 14:54:58] [540f1f85-45ed-49c1-88fb-a91f2118d30a] QUEUED     : Your job has been recieved by the coordinator and is waiting to be queued.
[2025-08-29 14:54:58] [540f1f85-45ed-49c1-88fb-a91f2118d30a] QUEUED     : Task 540f1f85-45ed-49c1-88fb-a91f2118d30a has been added to the queue. Currently at position 1
[2025-08-29 14:54:58] [540f1f85-45ed-49c1-88fb-a91f2118d30a] QUEUED     : Dispatching task...
[2025-08-29 14:54:58] [540f1f85-45ed-49c1-88fb-a91f2118d30a] RUNNING    : Your job has started running.
[2025-08-29 14:56:21] [540f1f85-45ed-49c1-88fb-a91f2118d30a] COMPLETED  : Your job has been completed.

Downloading result:   0%|          | 0.00/397M [00:00<?, ?B/s]

[2025-08-29 14:56:49] [228f9075-7907-4edf-90bd-4317d85ea962] RECEIVED   : Your job has been received and is waiting to be queued.
[2025-08-29 14:56:49] [228f9075-7907-4edf-90bd-4317d85ea962] QUEUED     : Your job has been recieved by the coordinator and is waiting to be queued.
[2025-08-29 14:56:49] [228f9075-7907-4edf-90bd-4317d85ea962] QUEUED     : Task 228f9075-7907-4edf-90bd-4317d85ea962 has been added to the queue. Currently at position 1
[2025-08-29 14:56:49] [228f9075-7907-4edf-90bd-4317d85ea962] QUEUED     : Dispatching task...
[2025-08-29 14:56:49] [228f9075-7907-4edf-90bd-4317d85ea962] RUNNING    : Your job has started running.
[2025-08-29 14:58:01] [228f9075-7907-4edf-90bd-4317d85ea962] COMPLETED  : Your job has been completed.

Downloading result:   0%|          | 0.00/355M [00:00<?, ?B/s]

[2025-08-29 14:58:15] [62c3077a-5717-4e17-ab00-12a7a77f0a0e] RECEIVED   : Your job has been received and is waiting to be queued.
[2025-08-29 14:58:15] [62c3077a-5717-4e17-ab00-12a7a77f0a0e] QUEUED     : Your job has been recieved by the coordinator and is waiting to be queued.
[2025-08-29 14:58:15] [62c3077a-5717-4e17-ab00-12a7a77f0a0e] QUEUED     : Task 62c3077a-5717-4e17-ab00-12a7a77f0a0e has been added to the queue. Currently at position 1
[2025-08-29 14:58:15] [62c3077a-5717-4e17-ab00-12a7a77f0a0e] QUEUED     : Dispatching task...
[2025-08-29 14:58:16] [62c3077a-5717-4e17-ab00-12a7a77f0a0e] RUNNING    : Your job has started running.
[2025-08-29 14:59:18] [62c3077a-5717-4e17-ab00-12a7a77f0a0e] COMPLETED  : Your job has been completed.

Downloading result:   0%|          | 0.00/318M [00:00<?, ?B/s]

[2025-08-29 14:59:31] [634e3770-ed42-45f3-83d2-78a349f3a1dd] RECEIVED   : Your job has been received and is waiting to be queued.
[2025-08-29 14:59:31] [634e3770-ed42-45f3-83d2-78a349f3a1dd] QUEUED     : Your job has been recieved by the coordinator and is waiting to be queued.
[2025-08-29 14:59:31] [634e3770-ed42-45f3-83d2-78a349f3a1dd] QUEUED     : Task 634e3770-ed42-45f3-83d2-78a349f3a1dd has been added to the queue. Currently at position 1
[2025-08-29 14:59:31] [634e3770-ed42-45f3-83d2-78a349f3a1dd] QUEUED     : Dispatching task...
[2025-08-29 14:59:31] [634e3770-ed42-45f3-83d2-78a349f3a1dd] RUNNING    : Your job has started running.
[2025-08-29 15:02:19] [634e3770-ed42-45f3-83d2-78a349f3a1dd] COMPLETED  : Your job has been completed.

Downloading result:   0%|          | 0.00/699M [00:00<?, ?B/s]

[2025-08-29 15:02:44] [7cfb6ba9-f0dd-425c-af4f-814c3323b8ca] RECEIVED   : Your job has been received and is waiting to be queued.
[2025-08-29 15:02:44] [7cfb6ba9-f0dd-425c-af4f-814c3323b8ca] QUEUED     : Your job has been recieved by the coordinator and is waiting to be queued.
[2025-08-29 15:02:44] [7cfb6ba9-f0dd-425c-af4f-814c3323b8ca] QUEUED     : Task 7cfb6ba9-f0dd-425c-af4f-814c3323b8ca has been added to the queue. Currently at position 1
[2025-08-29 15:02:44] [7cfb6ba9-f0dd-425c-af4f-814c3323b8ca] QUEUED     : Dispatching task...
[2025-08-29 15:02:44] [7cfb6ba9-f0dd-425c-af4f-814c3323b8ca] RUNNING    : Your job has started running.
[2025-08-29 15:05:19] [7cfb6ba9-f0dd-425c-af4f-814c3323b8ca] COMPLETED  : Your job has been completed.

Downloading result:   0%|          | 0.00/623M [00:00<?, ?B/s]

[2025-08-29 15:05:42] [1be59f10-ead1-460b-896a-fa863aee8ba0] RECEIVED   : Your job has been received and is waiting to be queued.
[2025-08-29 15:05:42] [1be59f10-ead1-460b-896a-fa863aee8ba0] QUEUED     : Your job has been recieved by the coordinator and is waiting to be queued.
[2025-08-29 15:05:42] [1be59f10-ead1-460b-896a-fa863aee8ba0] QUEUED     : Task 1be59f10-ead1-460b-896a-fa863aee8ba0 has been added to the queue. Currently at position 1
[2025-08-29 15:05:42] [1be59f10-ead1-460b-896a-fa863aee8ba0] QUEUED     : Dispatching task...
[2025-08-29 15:05:43] [1be59f10-ead1-460b-896a-fa863aee8ba0] RUNNING    : Your job has started running.
[2025-08-29 15:08:18] [1be59f10-ead1-460b-896a-fa863aee8ba0] COMPLETED  : Your job has been completed.

Downloading result:   0%|          | 0.00/631M [00:00<?, ?B/s]

[2025-08-29 15:08:42] [3499165d-4935-4b12-970f-d9bd47657fe8] RECEIVED   : Your job has been received and is waiting to be queued.
[2025-08-29 15:08:42] [3499165d-4935-4b12-970f-d9bd47657fe8] QUEUED     : Your job has been recieved by the coordinator and is waiting to be queued.
[2025-08-29 15:08:42] [3499165d-4935-4b12-970f-d9bd47657fe8] QUEUED     : Task 3499165d-4935-4b12-970f-d9bd47657fe8 has been added to the queue. Currently at position 1
[2025-08-29 15:08:42] [3499165d-4935-4b12-970f-d9bd47657fe8] QUEUED     : Dispatching task...
[2025-08-29 15:08:43] [3499165d-4935-4b12-970f-d9bd47657fe8] RUNNING    : Your job has started running.
[2025-08-29 15:09:24] [3499165d-4935-4b12-970f-d9bd47657fe8] COMPLETED  : Your job has been completed.

Downloading result:   0%|          | 0.00/228M [00:00<?, ?B/s]

[2025-08-29 15:09:35] [d44206d3-693b-49bc-a877-059bfef74491] RECEIVED   : Your job has been received and is waiting to be queued.
[2025-08-29 15:09:35] [d44206d3-693b-49bc-a877-059bfef74491] QUEUED     : Your job has been recieved by the coordinator and is waiting to be queued.
[2025-08-29 15:09:35] [d44206d3-693b-49bc-a877-059bfef74491] QUEUED     : Task d44206d3-693b-49bc-a877-059bfef74491 has been added to the queue. Currently at position 1
[2025-08-29 15:09:35] [d44206d3-693b-49bc-a877-059bfef74491] QUEUED     : Dispatching task...
[2025-08-29 15:09:35] [d44206d3-693b-49bc-a877-059bfef74491] RUNNING    : Your job has started running.
[2025-08-29 15:09:55] [d44206d3-693b-49bc-a877-059bfef74491] COMPLETED  : Your job has been completed.

Downloading result:   0%|          | 0.00/113M [00:00<?, ?B/s]

[2025-08-29 15:10:01] [2a9f5829-c9e5-4cd3-a9c0-ea92b79f1d89] RECEIVED   : Your job has been received and is waiting to be queued.
[2025-08-29 15:10:01] [2a9f5829-c9e5-4cd3-a9c0-ea92b79f1d89] QUEUED     : Your job has been recieved by the coordinator and is waiting to be queued.
[2025-08-29 15:10:01] [2a9f5829-c9e5-4cd3-a9c0-ea92b79f1d89] QUEUED     : Task 2a9f5829-c9e5-4cd3-a9c0-ea92b79f1d89 has been added to the queue. Currently at position 1
[2025-08-29 15:10:01] [2a9f5829-c9e5-4cd3-a9c0-ea92b79f1d89] QUEUED     : Dispatching task...
[2025-08-29 15:10:02] [2a9f5829-c9e5-4cd3-a9c0-ea92b79f1d89] RUNNING    : Your job has started running.
[2025-08-29 15:12:37] [2a9f5829-c9e5-4cd3-a9c0-ea92b79f1d89] COMPLETED  : Your job has been completed.

Downloading result:   0%|          | 0.00/628M [00:00<?, ?B/s]

[2025-08-29 15:13:01] [8f8f01d6-4832-4e19-b013-4d8c9c09b7cf] RECEIVED   : Your job has been received and is waiting to be queued.
[2025-08-29 15:13:01] [8f8f01d6-4832-4e19-b013-4d8c9c09b7cf] QUEUED     : Your job has been recieved by the coordinator and is waiting to be queued.
[2025-08-29 15:13:01] [8f8f01d6-4832-4e19-b013-4d8c9c09b7cf] QUEUED     : Task 8f8f01d6-4832-4e19-b013-4d8c9c09b7cf has been added to the queue. Currently at position 1
[2025-08-29 15:13:01] [8f8f01d6-4832-4e19-b013-4d8c9c09b7cf] QUEUED     : Dispatching task...
[2025-08-29 15:13:02] [8f8f01d6-4832-4e19-b013-4d8c9c09b7cf] RUNNING    : Your job has started running.
[2025-08-29 15:15:43] [8f8f01d6-4832-4e19-b013-4d8c9c09b7cf] COMPLETED  : Your job has been completed.

Downloading result:   0%|          | 0.00/655M [00:00<?, ?B/s]

[2025-08-29 15:16:07] [2149e802-c3bd-4e99-8b92-3941e2bf303d] RECEIVED   : Your job has been received and is waiting to be queued.
[2025-08-29 15:16:07] [2149e802-c3bd-4e99-8b92-3941e2bf303d] QUEUED     : Your job has been recieved by the coordinator and is waiting to be queued.
[2025-08-29 15:16:07] [2149e802-c3bd-4e99-8b92-3941e2bf303d] QUEUED     : Task 2149e802-c3bd-4e99-8b92-3941e2bf303d has been added to the queue. Currently at position 1
[2025-08-29 15:16:07] [2149e802-c3bd-4e99-8b92-3941e2bf303d] QUEUED     : Dispatching task...
[2025-08-29 15:16:08] [2149e802-c3bd-4e99-8b92-3941e2bf303d] RUNNING    : Your job has started running.
[2025-08-29 15:18:48] [2149e802-c3bd-4e99-8b92-3941e2bf303d] COMPLETED  : Your job has been completed.

Downloading result:   0%|          | 0.00/654M [00:00<?, ?B/s]

[2025-08-29 15:19:14] [ee1f51ae-a05d-45bb-9297-0991a628d31e] RECEIVED   : Your job has been received and is waiting to be queued.
[2025-08-29 15:19:14] [ee1f51ae-a05d-45bb-9297-0991a628d31e] QUEUED     : Your job has been recieved by the coordinator and is waiting to be queued.
[2025-08-29 15:19:14] [ee1f51ae-a05d-45bb-9297-0991a628d31e] QUEUED     : Task ee1f51ae-a05d-45bb-9297-0991a628d31e has been added to the queue. Currently at position 1
[2025-08-29 15:19:14] [ee1f51ae-a05d-45bb-9297-0991a628d31e] QUEUED     : Dispatching task...
[2025-08-29 15:19:14] [ee1f51ae-a05d-45bb-9297-0991a628d31e] RUNNING    : Your job has started running.
[2025-08-29 15:20:26] [ee1f51ae-a05d-45bb-9297-0991a628d31e] COMPLETED  : Your job has been completed.

Downloading result:   0%|          | 0.00/349M [00:00<?, ?B/s]

[2025-08-29 15:20:40] [189ba695-0df9-4b0e-835f-1498dabd3db5] RECEIVED   : Your job has been received and is waiting to be queued.
[2025-08-29 15:20:40] [189ba695-0df9-4b0e-835f-1498dabd3db5] QUEUED     : Your job has been recieved by the coordinator and is waiting to be queued.
[2025-08-29 15:20:40] [189ba695-0df9-4b0e-835f-1498dabd3db5] QUEUED     : Task 189ba695-0df9-4b0e-835f-1498dabd3db5 has been added to the queue. Currently at position 1
[2025-08-29 15:20:41] [189ba695-0df9-4b0e-835f-1498dabd3db5] QUEUED     : Dispatching task...
[2025-08-29 15:20:41] [189ba695-0df9-4b0e-835f-1498dabd3db5] RUNNING    : Your job has started running.
[2025-08-29 15:23:17] [189ba695-0df9-4b0e-835f-1498dabd3db5] COMPLETED  : Your job has been completed.

Downloading result:   0%|          | 0.00/631M [00:00<?, ?B/s]

[2025-08-29 15:23:44] [b7f73530-0e45-42de-88f5-1759f784ea7c] RECEIVED   : Your job has been received and is waiting to be queued.
[2025-08-29 15:23:44] [b7f73530-0e45-42de-88f5-1759f784ea7c] QUEUED     : Your job has been recieved by the coordinator and is waiting to be queued.
[2025-08-29 15:23:44] [b7f73530-0e45-42de-88f5-1759f784ea7c] QUEUED     : Task b7f73530-0e45-42de-88f5-1759f784ea7c has been added to the queue. Currently at position 1
[2025-08-29 15:23:44] [b7f73530-0e45-42de-88f5-1759f784ea7c] QUEUED     : Dispatching task...
[2025-08-29 15:23:45] [b7f73530-0e45-42de-88f5-1759f784ea7c] RUNNING    : Your job has started running.
[2025-08-29 15:26:23] [b7f73530-0e45-42de-88f5-1759f784ea7c] COMPLETED  : Your job has been completed.

Downloading result:   0%|          | 0.00/623M [00:00<?, ?B/s]

[2025-08-29 15:26:46] [6723a849-51fd-4c23-8306-0e8e94000257] RECEIVED   : Your job has been received and is waiting to be queued.
[2025-08-29 15:26:46] [6723a849-51fd-4c23-8306-0e8e94000257] QUEUED     : Your job has been recieved by the coordinator and is waiting to be queued.
[2025-08-29 15:26:46] [6723a849-51fd-4c23-8306-0e8e94000257] QUEUED     : Task 6723a849-51fd-4c23-8306-0e8e94000257 has been added to the queue. Currently at position 1
[2025-08-29 15:26:47] [6723a849-51fd-4c23-8306-0e8e94000257] QUEUED     : Dispatching task...
[2025-08-29 15:26:47] [6723a849-51fd-4c23-8306-0e8e94000257] RUNNING    : Your job has started running.
[2025-08-29 15:29:31] [6723a849-51fd-4c23-8306-0e8e94000257] COMPLETED  : Your job has been completed.

Downloading result:   0%|          | 0.00/673M [00:00<?, ?B/s]

[2025-08-29 15:29:55] [a02274ea-0b24-42d9-8f94-75357dbac7df] RECEIVED   : Your job has been received and is waiting to be queued.
[2025-08-29 15:29:56] [a02274ea-0b24-42d9-8f94-75357dbac7df] QUEUED     : Your job has been recieved by the coordinator and is waiting to be queued.
[2025-08-29 15:29:56] [a02274ea-0b24-42d9-8f94-75357dbac7df] QUEUED     : Task a02274ea-0b24-42d9-8f94-75357dbac7df has been added to the queue. Currently at position 1
[2025-08-29 15:29:56] [a02274ea-0b24-42d9-8f94-75357dbac7df] QUEUED     : Dispatching task...
[2025-08-29 15:29:56] [a02274ea-0b24-42d9-8f94-75357dbac7df] RUNNING    : Your job has started running.
[2025-08-29 15:32:04] [a02274ea-0b24-42d9-8f94-75357dbac7df] COMPLETED  : Your job has been completed.

Downloading result:   0%|          | 0.00/543M [00:00<?, ?B/s]

[2025-08-29 15:32:25] [b289728b-be10-4166-9af8-ad1eb121bddd] RECEIVED   : Your job has been received and is waiting to be queued.
[2025-08-29 15:32:25] [b289728b-be10-4166-9af8-ad1eb121bddd] QUEUED     : Your job has been recieved by the coordinator and is waiting to be queued.
[2025-08-29 15:32:25] [b289728b-be10-4166-9af8-ad1eb121bddd] QUEUED     : Task b289728b-be10-4166-9af8-ad1eb121bddd has been added to the queue. Currently at position 1
[2025-08-29 15:32:25] [b289728b-be10-4166-9af8-ad1eb121bddd] QUEUED     : Dispatching task...
[2025-08-29 15:32:25] [b289728b-be10-4166-9af8-ad1eb121bddd] RUNNING    : Your job has started running.
[2025-08-29 15:33:13] [b289728b-be10-4166-9af8-ad1eb121bddd] COMPLETED  : Your job has been completed.

Downloading result:   0%|          | 0.00/252M [00:00<?, ?B/s]

[2025-08-29 15:33:23] [d9ab7a6a-bb97-48e0-b1ec-84ecd3b3685a] RECEIVED   : Your job has been received and is waiting to be queued.
[2025-08-29 15:33:23] [d9ab7a6a-bb97-48e0-b1ec-84ecd3b3685a] QUEUED     : Your job has been recieved by the coordinator and is waiting to be queued.
[2025-08-29 15:33:23] [d9ab7a6a-bb97-48e0-b1ec-84ecd3b3685a] QUEUED     : Task d9ab7a6a-bb97-48e0-b1ec-84ecd3b3685a has been added to the queue. Currently at position 1
[2025-08-29 15:33:23] [d9ab7a6a-bb97-48e0-b1ec-84ecd3b3685a] QUEUED     : Dispatching task...
[2025-08-29 15:33:23] [d9ab7a6a-bb97-48e0-b1ec-84ecd3b3685a] RUNNING    : Your job has started running.
[2025-08-29 15:35:59] [d9ab7a6a-bb97-48e0-b1ec-84ecd3b3685a] COMPLETED  : Your job has been completed.

Downloading result:   0%|          | 0.00/625M [00:00<?, ?B/s]

[2025-08-29 15:36:23] [5e0d81bc-8db6-4fd0-b4d0-b8bb378f3ede] RECEIVED   : Your job has been received and is waiting to be queued.
[2025-08-29 15:36:23] [5e0d81bc-8db6-4fd0-b4d0-b8bb378f3ede] QUEUED     : Your job has been recieved by the coordinator and is waiting to be queued.
[2025-08-29 15:36:23] [5e0d81bc-8db6-4fd0-b4d0-b8bb378f3ede] QUEUED     : Task 5e0d81bc-8db6-4fd0-b4d0-b8bb378f3ede has been added to the queue. Currently at position 1
[2025-08-29 15:36:23] [5e0d81bc-8db6-4fd0-b4d0-b8bb378f3ede] QUEUED     : Dispatching task...
[2025-08-29 15:36:23] [5e0d81bc-8db6-4fd0-b4d0-b8bb378f3ede] RUNNING    : Your job has started running.
[2025-08-29 15:39:00] [5e0d81bc-8db6-4fd0-b4d0-b8bb378f3ede] COMPLETED  : Your job has been completed.

Downloading result:   0%|          | 0.00/638M [00:00<?, ?B/s]

[2025-08-29 15:39:29] [a2d27de5-bb2f-433d-8ca7-6545bdcce6ec] RECEIVED   : Your job has been received and is waiting to be queued.
[2025-08-29 15:39:29] [a2d27de5-bb2f-433d-8ca7-6545bdcce6ec] QUEUED     : Your job has been recieved by the coordinator and is waiting to be queued.
[2025-08-29 15:39:29] [a2d27de5-bb2f-433d-8ca7-6545bdcce6ec] QUEUED     : Task a2d27de5-bb2f-433d-8ca7-6545bdcce6ec has been added to the queue. Currently at position 1
[2025-08-29 15:39:29] [a2d27de5-bb2f-433d-8ca7-6545bdcce6ec] QUEUED     : Dispatching task...
[2025-08-29 15:39:30] [a2d27de5-bb2f-433d-8ca7-6545bdcce6ec] RUNNING    : Your job has started running.
[2025-08-29 15:42:05] [a2d27de5-bb2f-433d-8ca7-6545bdcce6ec] COMPLETED  : Your job has been completed.

Downloading result:   0%|          | 0.00/633M [00:00<?, ?B/s]

[2025-08-29 15:42:47] [f3d07a2b-48ed-4c91-8cd0-d29074024163] RECEIVED   : Your job has been received and is waiting to be queued.
[2025-08-29 15:42:47] [f3d07a2b-48ed-4c91-8cd0-d29074024163] QUEUED     : Your job has been recieved by the coordinator and is waiting to be queued.
[2025-08-29 15:42:47] [f3d07a2b-48ed-4c91-8cd0-d29074024163] QUEUED     : Task f3d07a2b-48ed-4c91-8cd0-d29074024163 has been added to the queue. Currently at position 1
[2025-08-29 15:42:47] [f3d07a2b-48ed-4c91-8cd0-d29074024163] QUEUED     : Dispatching task...
[2025-08-29 15:42:47] [f3d07a2b-48ed-4c91-8cd0-d29074024163] RUNNING    : Your job has started running.
[2025-08-29 15:43:30] [f3d07a2b-48ed-4c91-8cd0-d29074024163] COMPLETED  : Your job has been completed.

Downloading result:   0%|          | 0.00/234M [00:00<?, ?B/s]

[2025-08-29 15:43:40] [f4737b3c-d0b6-4765-ac87-6e0f2938e492] RECEIVED   : Your job has been received and is waiting to be queued.
[2025-08-29 15:43:40] [f4737b3c-d0b6-4765-ac87-6e0f2938e492] QUEUED     : Your job has been recieved by the coordinator and is waiting to be queued.
[2025-08-29 15:43:40] [f4737b3c-d0b6-4765-ac87-6e0f2938e492] QUEUED     : Task f4737b3c-d0b6-4765-ac87-6e0f2938e492 has been added to the queue. Currently at position 1
[2025-08-29 15:43:40] [f4737b3c-d0b6-4765-ac87-6e0f2938e492] QUEUED     : Dispatching task...
[2025-08-29 15:43:40] [f4737b3c-d0b6-4765-ac87-6e0f2938e492] RUNNING    : Your job has started running.
[2025-08-29 15:46:14] [f4737b3c-d0b6-4765-ac87-6e0f2938e492] COMPLETED  : Your job has been completed.

Downloading result:   0%|          | 0.00/623M [00:00<?, ?B/s]

[2025-08-29 15:46:38] [eb3cab97-77ea-40c3-aa01-5a4e44dad64c] RECEIVED   : Your job has been received and is waiting to be queued.
[2025-08-29 15:46:38] [eb3cab97-77ea-40c3-aa01-5a4e44dad64c] QUEUED     : Your job has been recieved by the coordinator and is waiting to be queued.
[2025-08-29 15:46:38] [eb3cab97-77ea-40c3-aa01-5a4e44dad64c] QUEUED     : Task eb3cab97-77ea-40c3-aa01-5a4e44dad64c has been added to the queue. Currently at position 1
[2025-08-29 15:46:38] [eb3cab97-77ea-40c3-aa01-5a4e44dad64c] QUEUED     : Dispatching task...
[2025-08-29 15:46:38] [eb3cab97-77ea-40c3-aa01-5a4e44dad64c] RUNNING    : Your job has started running.
[2025-08-29 15:47:03] [eb3cab97-77ea-40c3-aa01-5a4e44dad64c] COMPLETED  : Your job has been completed.

Downloading result:   0%|          | 0.00/141M [00:00<?, ?B/s]

[2025-08-29 15:47:10] [6bc48cd1-0c47-43b8-a702-6b6fe4794408] RECEIVED   : Your job has been received and is waiting to be queued.
[2025-08-29 15:47:10] [6bc48cd1-0c47-43b8-a702-6b6fe4794408] QUEUED     : Your job has been recieved by the coordinator and is waiting to be queued.
[2025-08-29 15:47:10] [6bc48cd1-0c47-43b8-a702-6b6fe4794408] QUEUED     : Task 6bc48cd1-0c47-43b8-a702-6b6fe4794408 has been added to the queue. Currently at position 1
[2025-08-29 15:47:10] [6bc48cd1-0c47-43b8-a702-6b6fe4794408] QUEUED     : Dispatching task...
[2025-08-29 15:47:10] [6bc48cd1-0c47-43b8-a702-6b6fe4794408] RUNNING    : Your job has started running.
[2025-08-29 15:49:36] [6bc48cd1-0c47-43b8-a702-6b6fe4794408] COMPLETED  : Your job has been completed.

Downloading result:   0%|          | 0.00/601M [00:00<?, ?B/s]

[2025-08-29 15:50:01] [ef625911-cc30-4103-b96d-76030f8f9793] RECEIVED   : Your job has been received and is waiting to be queued.
[2025-08-29 15:50:01] [ef625911-cc30-4103-b96d-76030f8f9793] QUEUED     : Your job has been recieved by the coordinator and is waiting to be queued.
[2025-08-29 15:50:01] [ef625911-cc30-4103-b96d-76030f8f9793] QUEUED     : Task ef625911-cc30-4103-b96d-76030f8f9793 has been added to the queue. Currently at position 1
[2025-08-29 15:50:01] [ef625911-cc30-4103-b96d-76030f8f9793] QUEUED     : Dispatching task...
[2025-08-29 15:50:02] [ef625911-cc30-4103-b96d-76030f8f9793] RUNNING    : Your job has started running.
[2025-08-29 15:50:41] [ef625911-cc30-4103-b96d-76030f8f9793] COMPLETED  : Your job has been completed.

Downloading result:   0%|          | 0.00/212M [00:00<?, ?B/s]

[2025-08-29 15:50:50] [8fa6f9df-f79a-46c7-8878-569d99f674a4] RECEIVED   : Your job has been received and is waiting to be queued.
[2025-08-29 15:50:50] [8fa6f9df-f79a-46c7-8878-569d99f674a4] QUEUED     : Your job has been recieved by the coordinator and is waiting to be queued.
[2025-08-29 15:50:50] [8fa6f9df-f79a-46c7-8878-569d99f674a4] QUEUED     : Task 8fa6f9df-f79a-46c7-8878-569d99f674a4 has been added to the queue. Currently at position 1
[2025-08-29 15:50:50] [8fa6f9df-f79a-46c7-8878-569d99f674a4] QUEUED     : Dispatching task...
[2025-08-29 15:50:51] [8fa6f9df-f79a-46c7-8878-569d99f674a4] RUNNING    : Your job has started running.
[2025-08-29 15:51:22] [8fa6f9df-f79a-46c7-8878-569d99f674a4] COMPLETED  : Your job has been completed.

Downloading result:   0%|          | 0.00/172M [00:00<?, ?B/s]

[2025-08-29 15:51:30] [5c9c9b88-3835-42c1-8342-827177f9868d] RECEIVED   : Your job has been received and is waiting to be queued.
[2025-08-29 15:51:30] [5c9c9b88-3835-42c1-8342-827177f9868d] QUEUED     : Your job has been recieved by the coordinator and is waiting to be queued.
[2025-08-29 15:51:30] [5c9c9b88-3835-42c1-8342-827177f9868d] QUEUED     : Task 5c9c9b88-3835-42c1-8342-827177f9868d has been added to the queue. Currently at position 1
[2025-08-29 15:51:30] [5c9c9b88-3835-42c1-8342-827177f9868d] QUEUED     : Dispatching task...
[2025-08-29 15:51:31] [5c9c9b88-3835-42c1-8342-827177f9868d] RUNNING    : Your job has started running.
[2025-08-29 15:52:02] [5c9c9b88-3835-42c1-8342-827177f9868d] COMPLETED  : Your job has been completed.

Downloading result:   0%|          | 0.00/176M [00:00<?, ?B/s]

[2025-08-29 15:52:10] [7f846c91-d895-473a-8fd2-11fe9cce2e46] RECEIVED   : Your job has been received and is waiting to be queued.
[2025-08-29 15:52:10] [7f846c91-d895-473a-8fd2-11fe9cce2e46] QUEUED     : Your job has been recieved by the coordinator and is waiting to be queued.
[2025-08-29 15:52:10] [7f846c91-d895-473a-8fd2-11fe9cce2e46] QUEUED     : Task 7f846c91-d895-473a-8fd2-11fe9cce2e46 has been added to the queue. Currently at position 1
[2025-08-29 15:52:10] [7f846c91-d895-473a-8fd2-11fe9cce2e46] QUEUED     : Dispatching task...
[2025-08-29 15:52:11] [7f846c91-d895-473a-8fd2-11fe9cce2e46] RUNNING    : Your job has started running.
[2025-08-29 15:54:43] [7f846c91-d895-473a-8fd2-11fe9cce2e46] COMPLETED  : Your job has been completed.

Downloading result:   0%|          | 0.00/608M [00:00<?, ?B/s]

[2025-08-29 15:55:11] [804c0eeb-8cbd-48c4-a704-242f60cbdb24] RECEIVED   : Your job has been received and is waiting to be queued.
[2025-08-29 15:55:11] [804c0eeb-8cbd-48c4-a704-242f60cbdb24] QUEUED     : Your job has been recieved by the coordinator and is waiting to be queued.
[2025-08-29 15:55:11] [804c0eeb-8cbd-48c4-a704-242f60cbdb24] QUEUED     : Task 804c0eeb-8cbd-48c4-a704-242f60cbdb24 has been added to the queue. Currently at position 1
[2025-08-29 15:55:11] [804c0eeb-8cbd-48c4-a704-242f60cbdb24] QUEUED     : Dispatching task...
[2025-08-29 15:55:11] [804c0eeb-8cbd-48c4-a704-242f60cbdb24] RUNNING    : Your job has started running.
[2025-08-29 15:57:54] [804c0eeb-8cbd-48c4-a704-242f60cbdb24] COMPLETED  : Your job has been completed.

Downloading result:   0%|          | 0.00/644M [00:00<?, ?B/s]

[2025-08-29 15:58:19] [ae0123ea-efc2-46f0-bdf0-9f1eabe83c09] RECEIVED   : Your job has been received and is waiting to be queued.
[2025-08-29 15:58:19] [ae0123ea-efc2-46f0-bdf0-9f1eabe83c09] QUEUED     : Your job has been recieved by the coordinator and is waiting to be queued.
[2025-08-29 15:58:19] [ae0123ea-efc2-46f0-bdf0-9f1eabe83c09] QUEUED     : Task ae0123ea-efc2-46f0-bdf0-9f1eabe83c09 has been added to the queue. Currently at position 1
[2025-08-29 15:58:19] [ae0123ea-efc2-46f0-bdf0-9f1eabe83c09] QUEUED     : Dispatching task...
[2025-08-29 15:58:20] [ae0123ea-efc2-46f0-bdf0-9f1eabe83c09] RUNNING    : Your job has started running.
[2025-08-29 16:00:53] [ae0123ea-efc2-46f0-bdf0-9f1eabe83c09] COMPLETED  : Your job has been completed.

Downloading result:   0%|          | 0.00/616M [00:00<?, ?B/s]

[2025-08-29 16:01:19] [a8acbe72-3f86-4b84-8380-2053df954a67] RECEIVED   : Your job has been received and is waiting to be queued.
[2025-08-29 16:01:19] [a8acbe72-3f86-4b84-8380-2053df954a67] QUEUED     : Your job has been recieved by the coordinator and is waiting to be queued.
[2025-08-29 16:01:19] [a8acbe72-3f86-4b84-8380-2053df954a67] QUEUED     : Task a8acbe72-3f86-4b84-8380-2053df954a67 has been added to the queue. Currently at position 1
[2025-08-29 16:01:20] [a8acbe72-3f86-4b84-8380-2053df954a67] QUEUED     : Dispatching task...
[2025-08-29 16:01:20] [a8acbe72-3f86-4b84-8380-2053df954a67] RUNNING    : Your job has started running.
[2025-08-29 16:01:52] [a8acbe72-3f86-4b84-8380-2053df954a67] COMPLETED  : Your job has been completed.

Downloading result:   0%|          | 0.00/178M [00:00<?, ?B/s]

[2025-08-29 16:02:00] [8a050134-412e-468f-8f40-09a4731802e7] RECEIVED   : Your job has been received and is waiting to be queued.
[2025-08-29 16:02:00] [8a050134-412e-468f-8f40-09a4731802e7] QUEUED     : Your job has been recieved by the coordinator and is waiting to be queued.
[2025-08-29 16:02:00] [8a050134-412e-468f-8f40-09a4731802e7] QUEUED     : Task 8a050134-412e-468f-8f40-09a4731802e7 has been added to the queue. Currently at position 1
[2025-08-29 16:02:00] [8a050134-412e-468f-8f40-09a4731802e7] QUEUED     : Dispatching task...
[2025-08-29 16:02:01] [8a050134-412e-468f-8f40-09a4731802e7] RUNNING    : Your job has started running.
[2025-08-29 16:02:56] [8a050134-412e-468f-8f40-09a4731802e7] COMPLETED  : Your job has been completed.

Downloading result:   0%|          | 0.00/293M [00:00<?, ?B/s]

[2025-08-29 16:03:08] [2d22bc4e-d0fa-4838-ae6e-1d37eb0e28bc] RECEIVED   : Your job has been received and is waiting to be queued.
[2025-08-29 16:03:08] [2d22bc4e-d0fa-4838-ae6e-1d37eb0e28bc] QUEUED     : Your job has been recieved by the coordinator and is waiting to be queued.
[2025-08-29 16:03:08] [2d22bc4e-d0fa-4838-ae6e-1d37eb0e28bc] QUEUED     : Task 2d22bc4e-d0fa-4838-ae6e-1d37eb0e28bc has been added to the queue. Currently at position 1
[2025-08-29 16:03:08] [2d22bc4e-d0fa-4838-ae6e-1d37eb0e28bc] QUEUED     : Dispatching task...
[2025-08-29 16:03:09] [2d22bc4e-d0fa-4838-ae6e-1d37eb0e28bc] RUNNING    : Your job has started running.
[2025-08-29 16:05:51] [2d22bc4e-d0fa-4838-ae6e-1d37eb0e28bc] COMPLETED  : Your job has been completed.

Downloading result:   0%|          | 0.00/670M [00:00<?, ?B/s]

[2025-08-29 16:06:21] [8673459e-d4f9-41f3-9a66-e31ed304db45] RECEIVED   : Your job has been received and is waiting to be queued.
[2025-08-29 16:06:21] [8673459e-d4f9-41f3-9a66-e31ed304db45] QUEUED     : Your job has been recieved by the coordinator and is waiting to be queued.
[2025-08-29 16:06:21] [8673459e-d4f9-41f3-9a66-e31ed304db45] QUEUED     : Task 8673459e-d4f9-41f3-9a66-e31ed304db45 has been added to the queue. Currently at position 1
[2025-08-29 16:06:21] [8673459e-d4f9-41f3-9a66-e31ed304db45] QUEUED     : Dispatching task...
[2025-08-29 16:06:21] [8673459e-d4f9-41f3-9a66-e31ed304db45] RUNNING    : Your job has started running.
[2025-08-29 16:08:53] [8673459e-d4f9-41f3-9a66-e31ed304db45] COMPLETED  : Your job has been completed.

Downloading result:   0%|          | 0.00/610M [00:00<?, ?B/s]

[2025-08-29 16:09:17] [f0a7841b-46b9-40ef-a758-d2cd28535a04] RECEIVED   : Your job has been received and is waiting to be queued.
[2025-08-29 16:09:17] [f0a7841b-46b9-40ef-a758-d2cd28535a04] QUEUED     : Your job has been recieved by the coordinator and is waiting to be queued.
[2025-08-29 16:09:17] [f0a7841b-46b9-40ef-a758-d2cd28535a04] QUEUED     : Task f0a7841b-46b9-40ef-a758-d2cd28535a04 has been added to the queue. Currently at position 1
[2025-08-29 16:09:17] [f0a7841b-46b9-40ef-a758-d2cd28535a04] QUEUED     : Dispatching task...
[2025-08-29 16:09:17] [f0a7841b-46b9-40ef-a758-d2cd28535a04] RUNNING    : Your job has started running.
[2025-08-29 16:09:43] [f0a7841b-46b9-40ef-a758-d2cd28535a04] COMPLETED  : Your job has been completed.

Downloading result:   0%|          | 0.00/151M [00:00<?, ?B/s]

[2025-08-29 16:09:50] [963d3991-3120-41d0-8cd3-fb5d3f433be6] RECEIVED   : Your job has been received and is waiting to be queued.
[2025-08-29 16:09:50] [963d3991-3120-41d0-8cd3-fb5d3f433be6] QUEUED     : Your job has been recieved by the coordinator and is waiting to be queued.
[2025-08-29 16:09:50] [963d3991-3120-41d0-8cd3-fb5d3f433be6] QUEUED     : Task 963d3991-3120-41d0-8cd3-fb5d3f433be6 has been added to the queue. Currently at position 1
[2025-08-29 16:09:51] [963d3991-3120-41d0-8cd3-fb5d3f433be6] QUEUED     : Dispatching task...
[2025-08-29 16:09:51] [963d3991-3120-41d0-8cd3-fb5d3f433be6] RUNNING    : Your job has started running.
[2025-08-29 16:12:25] [963d3991-3120-41d0-8cd3-fb5d3f433be6] COMPLETED  : Your job has been completed.

Downloading result:   0%|          | 0.00/621M [00:00<?, ?B/s]

[2025-08-29 16:12:48] [578f0245-a23a-41f4-87ac-ce0d90b43a69] RECEIVED   : Your job has been received and is waiting to be queued.
[2025-08-29 16:12:48] [578f0245-a23a-41f4-87ac-ce0d90b43a69] QUEUED     : Your job has been recieved by the coordinator and is waiting to be queued.
[2025-08-29 16:12:48] [578f0245-a23a-41f4-87ac-ce0d90b43a69] QUEUED     : Task 578f0245-a23a-41f4-87ac-ce0d90b43a69 has been added to the queue. Currently at position 1
[2025-08-29 16:12:48] [578f0245-a23a-41f4-87ac-ce0d90b43a69] QUEUED     : Dispatching task...
[2025-08-29 16:12:50] [578f0245-a23a-41f4-87ac-ce0d90b43a69] RUNNING    : Your job has started running.
[2025-08-29 16:13:48] [578f0245-a23a-41f4-87ac-ce0d90b43a69] COMPLETED  : Your job has been completed.

Downloading result:   0%|          | 0.00/286M [00:00<?, ?B/s]

[2025-08-29 16:14:00] [9b3c85f3-b8f1-49b5-9bc8-4c2c6a6f8bea] RECEIVED   : Your job has been received and is waiting to be queued.
[2025-08-29 16:14:00] [9b3c85f3-b8f1-49b5-9bc8-4c2c6a6f8bea] QUEUED     : Your job has been recieved by the coordinator and is waiting to be queued.
[2025-08-29 16:14:00] [9b3c85f3-b8f1-49b5-9bc8-4c2c6a6f8bea] QUEUED     : Task 9b3c85f3-b8f1-49b5-9bc8-4c2c6a6f8bea has been added to the queue. Currently at position 1
[2025-08-29 16:14:00] [9b3c85f3-b8f1-49b5-9bc8-4c2c6a6f8bea] QUEUED     : Dispatching task...
[2025-08-29 16:14:00] [9b3c85f3-b8f1-49b5-9bc8-4c2c6a6f8bea] RUNNING    : Your job has started running.
[2025-08-29 16:14:39] [9b3c85f3-b8f1-49b5-9bc8-4c2c6a6f8bea] COMPLETED  : Your job has been completed.

Downloading result:   0%|          | 0.00/211M [00:00<?, ?B/s]

[2025-08-29 16:14:48] [8f438c71-a441-4dd6-94f4-44d6667ca869] RECEIVED   : Your job has been received and is waiting to be queued.
[2025-08-29 16:14:48] [8f438c71-a441-4dd6-94f4-44d6667ca869] QUEUED     : Your job has been recieved by the coordinator and is waiting to be queued.
[2025-08-29 16:14:48] [8f438c71-a441-4dd6-94f4-44d6667ca869] QUEUED     : Task 8f438c71-a441-4dd6-94f4-44d6667ca869 has been added to the queue. Currently at position 1
[2025-08-29 16:14:48] [8f438c71-a441-4dd6-94f4-44d6667ca869] QUEUED     : Dispatching task...
[2025-08-29 16:14:48] [8f438c71-a441-4dd6-94f4-44d6667ca869] RUNNING    : Your job has started running.
[2025-08-29 16:17:22] [8f438c71-a441-4dd6-94f4-44d6667ca869] COMPLETED  : Your job has been completed.

Downloading result:   0%|          | 0.00/616M [00:00<?, ?B/s]

[2025-08-29 16:17:44] [146618a8-768c-4d2d-9b7c-99c06d258a0c] RECEIVED   : Your job has been received and is waiting to be queued.
[2025-08-29 16:17:44] [146618a8-768c-4d2d-9b7c-99c06d258a0c] QUEUED     : Your job has been recieved by the coordinator and is waiting to be queued.
[2025-08-29 16:17:44] [146618a8-768c-4d2d-9b7c-99c06d258a0c] QUEUED     : Task 146618a8-768c-4d2d-9b7c-99c06d258a0c has been added to the queue. Currently at position 1
[2025-08-29 16:17:45] [146618a8-768c-4d2d-9b7c-99c06d258a0c] QUEUED     : Dispatching task...
[2025-08-29 16:17:45] [146618a8-768c-4d2d-9b7c-99c06d258a0c] RUNNING    : Your job has started running.
[2025-08-29 16:20:18] [146618a8-768c-4d2d-9b7c-99c06d258a0c] COMPLETED  : Your job has been completed.

Downloading result:   0%|          | 0.00/610M [00:00<?, ?B/s]

[2025-08-29 16:20:44] [8c528fd4-9729-42ed-b8c6-220af30a5f0c] RECEIVED   : Your job has been received and is waiting to be queued.
[2025-08-29 16:20:44] [8c528fd4-9729-42ed-b8c6-220af30a5f0c] QUEUED     : Your job has been recieved by the coordinator and is waiting to be queued.
[2025-08-29 16:20:44] [8c528fd4-9729-42ed-b8c6-220af30a5f0c] QUEUED     : Task 8c528fd4-9729-42ed-b8c6-220af30a5f0c has been added to the queue. Currently at position 1
[2025-08-29 16:20:44] [8c528fd4-9729-42ed-b8c6-220af30a5f0c] QUEUED     : Dispatching task...
[2025-08-29 16:20:44] [8c528fd4-9729-42ed-b8c6-220af30a5f0c] RUNNING    : Your job has started running.
[2025-08-29 16:21:59] [8c528fd4-9729-42ed-b8c6-220af30a5f0c] COMPLETED  : Your job has been completed.

Downloading result:   0%|          | 0.00/356M [00:00<?, ?B/s]

[2025-08-29 16:22:13] [727c81c5-1030-4e7c-b1a4-324a655ff5fc] RECEIVED   : Your job has been received and is waiting to be queued.
[2025-08-29 16:22:13] [727c81c5-1030-4e7c-b1a4-324a655ff5fc] QUEUED     : Your job has been recieved by the coordinator and is waiting to be queued.
[2025-08-29 16:22:13] [727c81c5-1030-4e7c-b1a4-324a655ff5fc] QUEUED     : Task 727c81c5-1030-4e7c-b1a4-324a655ff5fc has been added to the queue. Currently at position 1
[2025-08-29 16:22:14] [727c81c5-1030-4e7c-b1a4-324a655ff5fc] QUEUED     : Dispatching task...
[2025-08-29 16:22:14] [727c81c5-1030-4e7c-b1a4-324a655ff5fc] RUNNING    : Your job has started running.
[2025-08-29 16:22:51] [727c81c5-1030-4e7c-b1a4-324a655ff5fc] COMPLETED  : Your job has been completed.

Downloading result:   0%|          | 0.00/207M [00:00<?, ?B/s]

[2025-08-29 16:23:01] [7ae4059a-9896-45dd-8fc3-9f02015f109f] RECEIVED   : Your job has been received and is waiting to be queued.
[2025-08-29 16:23:01] [7ae4059a-9896-45dd-8fc3-9f02015f109f] QUEUED     : Your job has been recieved by the coordinator and is waiting to be queued.
[2025-08-29 16:23:01] [7ae4059a-9896-45dd-8fc3-9f02015f109f] QUEUED     : Task 7ae4059a-9896-45dd-8fc3-9f02015f109f has been added to the queue. Currently at position 1
[2025-08-29 16:23:01] [7ae4059a-9896-45dd-8fc3-9f02015f109f] QUEUED     : Dispatching task...
[2025-08-29 16:23:01] [7ae4059a-9896-45dd-8fc3-9f02015f109f] RUNNING    : Your job has started running.
[2025-08-29 16:24:17] [7ae4059a-9896-45dd-8fc3-9f02015f109f] COMPLETED  : Your job has been completed.

Downloading result:   0%|          | 0.00/368M [00:00<?, ?B/s]

[2025-08-29 16:24:32] [03646884-0c44-4d5a-90e6-bfc2e804b6a7] RECEIVED   : Your job has been received and is waiting to be queued.
[2025-08-29 16:24:32] [03646884-0c44-4d5a-90e6-bfc2e804b6a7] QUEUED     : Your job has been recieved by the coordinator and is waiting to be queued.
[2025-08-29 16:24:32] [03646884-0c44-4d5a-90e6-bfc2e804b6a7] QUEUED     : Task 03646884-0c44-4d5a-90e6-bfc2e804b6a7 has been added to the queue. Currently at position 1
[2025-08-29 16:24:32] [03646884-0c44-4d5a-90e6-bfc2e804b6a7] QUEUED     : Dispatching task...
[2025-08-29 16:24:32] [03646884-0c44-4d5a-90e6-bfc2e804b6a7] RUNNING    : Your job has started running.
[2025-08-29 16:27:09] [03646884-0c44-4d5a-90e6-bfc2e804b6a7] COMPLETED  : Your job has been completed.

Downloading result:   0%|          | 0.00/633M [00:00<?, ?B/s]

[2025-08-29 16:27:34] [f63fc007-66f1-4fa7-94c1-4a5d29fac1d1] RECEIVED   : Your job has been received and is waiting to be queued.
[2025-08-29 16:27:34] [f63fc007-66f1-4fa7-94c1-4a5d29fac1d1] QUEUED     : Your job has been recieved by the coordinator and is waiting to be queued.
[2025-08-29 16:27:34] [f63fc007-66f1-4fa7-94c1-4a5d29fac1d1] QUEUED     : Task f63fc007-66f1-4fa7-94c1-4a5d29fac1d1 has been added to the queue. Currently at position 1
[2025-08-29 16:27:34] [f63fc007-66f1-4fa7-94c1-4a5d29fac1d1] QUEUED     : Dispatching task...
[2025-08-29 16:27:34] [f63fc007-66f1-4fa7-94c1-4a5d29fac1d1] RUNNING    : Your job has started running.
[2025-08-29 16:28:57] [f63fc007-66f1-4fa7-94c1-4a5d29fac1d1] COMPLETED  : Your job has been completed.

Downloading result:   0%|          | 0.00/397M [00:00<?, ?B/s]

[2025-08-29 16:29:12] [1387983d-4818-49ee-af5f-0c4315186807] RECEIVED   : Your job has been received and is waiting to be queued.
[2025-08-29 16:29:12] [1387983d-4818-49ee-af5f-0c4315186807] QUEUED     : Your job has been recieved by the coordinator and is waiting to be queued.
[2025-08-29 16:29:12] [1387983d-4818-49ee-af5f-0c4315186807] QUEUED     : Task 1387983d-4818-49ee-af5f-0c4315186807 has been added to the queue. Currently at position 1
[2025-08-29 16:29:12] [1387983d-4818-49ee-af5f-0c4315186807] QUEUED     : Dispatching task...
[2025-08-29 16:29:12] [1387983d-4818-49ee-af5f-0c4315186807] RUNNING    : Your job has started running.
[2025-08-29 16:31:48] [1387983d-4818-49ee-af5f-0c4315186807] COMPLETED  : Your job has been completed.

Downloading result:   0%|          | 0.00/628M [00:00<?, ?B/s]

[2025-08-29 16:32:12] [be351a07-6dac-479d-8e8a-092203f38dd1] RECEIVED   : Your job has been received and is waiting to be queued.
[2025-08-29 16:32:12] [be351a07-6dac-479d-8e8a-092203f38dd1] QUEUED     : Your job has been recieved by the coordinator and is waiting to be queued.
[2025-08-29 16:32:12] [be351a07-6dac-479d-8e8a-092203f38dd1] QUEUED     : Task be351a07-6dac-479d-8e8a-092203f38dd1 has been added to the queue. Currently at position 1
[2025-08-29 16:32:12] [be351a07-6dac-479d-8e8a-092203f38dd1] QUEUED     : Dispatching task...
[2025-08-29 16:32:13] [be351a07-6dac-479d-8e8a-092203f38dd1] RUNNING    : Your job has started running.
[2025-08-29 16:33:07] [be351a07-6dac-479d-8e8a-092203f38dd1] COMPLETED  : Your job has been completed.

Downloading result:   0%|          | 0.00/284M [00:00<?, ?B/s]

[2025-08-29 16:33:19] [bb03bc3a-d0ea-4158-92d2-34e14da79d6c] RECEIVED   : Your job has been received and is waiting to be queued.
[2025-08-29 16:33:19] [bb03bc3a-d0ea-4158-92d2-34e14da79d6c] QUEUED     : Your job has been recieved by the coordinator and is waiting to be queued.
[2025-08-29 16:33:19] [bb03bc3a-d0ea-4158-92d2-34e14da79d6c] QUEUED     : Task bb03bc3a-d0ea-4158-92d2-34e14da79d6c has been added to the queue. Currently at position 1
[2025-08-29 16:33:19] [bb03bc3a-d0ea-4158-92d2-34e14da79d6c] QUEUED     : Dispatching task...
[2025-08-29 16:33:19] [bb03bc3a-d0ea-4158-92d2-34e14da79d6c] RUNNING    : Your job has started running.
[2025-08-29 16:35:54] [bb03bc3a-d0ea-4158-92d2-34e14da79d6c] COMPLETED  : Your job has been completed.

Downloading result:   0%|          | 0.00/624M [00:00<?, ?B/s]

[2025-08-29 16:36:17] [621ffb49-a8c1-4c7f-aa75-23a1675ac095] RECEIVED   : Your job has been received and is waiting to be queued.
[2025-08-29 16:36:17] [621ffb49-a8c1-4c7f-aa75-23a1675ac095] QUEUED     : Your job has been recieved by the coordinator and is waiting to be queued.
[2025-08-29 16:36:17] [621ffb49-a8c1-4c7f-aa75-23a1675ac095] QUEUED     : Task 621ffb49-a8c1-4c7f-aa75-23a1675ac095 has been added to the queue. Currently at position 1
[2025-08-29 16:36:17] [621ffb49-a8c1-4c7f-aa75-23a1675ac095] QUEUED     : Dispatching task...
[2025-08-29 16:36:18] [621ffb49-a8c1-4c7f-aa75-23a1675ac095] RUNNING    : Your job has started running.
[2025-08-29 16:38:51] [621ffb49-a8c1-4c7f-aa75-23a1675ac095] COMPLETED  : Your job has been completed.

Downloading result:   0%|          | 0.00/615M [00:00<?, ?B/s]

[2025-08-29 16:39:15] [1af0cfaf-b389-4f4e-975d-adb662347421] RECEIVED   : Your job has been received and is waiting to be queued.
[2025-08-29 16:39:15] [1af0cfaf-b389-4f4e-975d-adb662347421] QUEUED     : Your job has been recieved by the coordinator and is waiting to be queued.
[2025-08-29 16:39:15] [1af0cfaf-b389-4f4e-975d-adb662347421] QUEUED     : Task 1af0cfaf-b389-4f4e-975d-adb662347421 has been added to the queue. Currently at position 1
[2025-08-29 16:39:15] [1af0cfaf-b389-4f4e-975d-adb662347421] QUEUED     : Dispatching task...
[2025-08-29 16:39:15] [1af0cfaf-b389-4f4e-975d-adb662347421] RUNNING    : Your job has started running.
[2025-08-29 16:41:48] [1af0cfaf-b389-4f4e-975d-adb662347421] COMPLETED  : Your job has been completed.

Downloading result:   0%|          | 0.00/610M [00:00<?, ?B/s]

[2025-08-29 16:42:14] [3d577c41-a7da-4c84-9c1a-c52e4d51f68c] RECEIVED   : Your job has been received and is waiting to be queued.
[2025-08-29 16:42:14] [3d577c41-a7da-4c84-9c1a-c52e4d51f68c] QUEUED     : Your job has been recieved by the coordinator and is waiting to be queued.
[2025-08-29 16:42:14] [3d577c41-a7da-4c84-9c1a-c52e4d51f68c] QUEUED     : Task 3d577c41-a7da-4c84-9c1a-c52e4d51f68c has been added to the queue. Currently at position 1
[2025-08-29 16:42:14] [3d577c41-a7da-4c84-9c1a-c52e4d51f68c] QUEUED     : Dispatching task...
[2025-08-29 16:42:15] [3d577c41-a7da-4c84-9c1a-c52e4d51f68c] RUNNING    : Your job has started running.
[2025-08-29 16:43:31] [3d577c41-a7da-4c84-9c1a-c52e4d51f68c] COMPLETED  : Your job has been completed.

Downloading result:   0%|          | 0.00/374M [00:00<?, ?B/s]

[2025-08-29 16:43:46] [49786827-50ea-4362-99f1-b5e7c71cdd81] RECEIVED   : Your job has been received and is waiting to be queued.
[2025-08-29 16:43:46] [49786827-50ea-4362-99f1-b5e7c71cdd81] QUEUED     : Your job has been recieved by the coordinator and is waiting to be queued.
[2025-08-29 16:43:46] [49786827-50ea-4362-99f1-b5e7c71cdd81] QUEUED     : Task 49786827-50ea-4362-99f1-b5e7c71cdd81 has been added to the queue. Currently at position 1
[2025-08-29 16:43:46] [49786827-50ea-4362-99f1-b5e7c71cdd81] QUEUED     : Dispatching task...
[2025-08-29 16:43:46] [49786827-50ea-4362-99f1-b5e7c71cdd81] RUNNING    : Your job has started running.
[2025-08-29 16:46:21] [49786827-50ea-4362-99f1-b5e7c71cdd81] COMPLETED  : Your job has been completed.

Downloading result:   0%|          | 0.00/618M [00:00<?, ?B/s]

[2025-08-29 16:46:46] [8317677f-23f5-485d-9b5e-2dff8d652ee1] RECEIVED   : Your job has been received and is waiting to be queued.
[2025-08-29 16:46:46] [8317677f-23f5-485d-9b5e-2dff8d652ee1] QUEUED     : Your job has been recieved by the coordinator and is waiting to be queued.
[2025-08-29 16:46:46] [8317677f-23f5-485d-9b5e-2dff8d652ee1] QUEUED     : Task 8317677f-23f5-485d-9b5e-2dff8d652ee1 has been added to the queue. Currently at position 1
[2025-08-29 16:46:46] [8317677f-23f5-485d-9b5e-2dff8d652ee1] QUEUED     : Dispatching task...
[2025-08-29 16:46:46] [8317677f-23f5-485d-9b5e-2dff8d652ee1] RUNNING    : Your job has started running.
[2025-08-29 16:49:21] [8317677f-23f5-485d-9b5e-2dff8d652ee1] COMPLETED  : Your job has been completed.

Downloading result:   0%|          | 0.00/623M [00:00<?, ?B/s]

[2025-08-29 16:49:45] [5fb2a249-b9ca-4298-8bea-f84a41fff6ea] RECEIVED   : Your job has been received and is waiting to be queued.
[2025-08-29 16:49:45] [5fb2a249-b9ca-4298-8bea-f84a41fff6ea] QUEUED     : Your job has been recieved by the coordinator and is waiting to be queued.
[2025-08-29 16:49:45] [5fb2a249-b9ca-4298-8bea-f84a41fff6ea] QUEUED     : Task 5fb2a249-b9ca-4298-8bea-f84a41fff6ea has been added to the queue. Currently at position 1
[2025-08-29 16:49:45] [5fb2a249-b9ca-4298-8bea-f84a41fff6ea] QUEUED     : Dispatching task...
[2025-08-29 16:49:46] [5fb2a249-b9ca-4298-8bea-f84a41fff6ea] RUNNING    : Your job has started running.
[2025-08-29 16:50:13] [5fb2a249-b9ca-4298-8bea-f84a41fff6ea] COMPLETED  : Your job has been completed.

Downloading result:   0%|          | 0.00/164M [00:00<?, ?B/s]

[2025-08-29 16:50:21] [01ddca40-653a-4fe1-84d2-e4ed77633ca0] RECEIVED   : Your job has been received and is waiting to be queued.
[2025-08-29 16:50:21] [01ddca40-653a-4fe1-84d2-e4ed77633ca0] QUEUED     : Your job has been recieved by the coordinator and is waiting to be queued.
[2025-08-29 16:50:21] [01ddca40-653a-4fe1-84d2-e4ed77633ca0] QUEUED     : Task 01ddca40-653a-4fe1-84d2-e4ed77633ca0 has been added to the queue. Currently at position 1
[2025-08-29 16:50:21] [01ddca40-653a-4fe1-84d2-e4ed77633ca0] QUEUED     : Dispatching task...
[2025-08-29 16:50:22] [01ddca40-653a-4fe1-84d2-e4ed77633ca0] RUNNING    : Your job has started running.
[2025-08-29 16:52:56] [01ddca40-653a-4fe1-84d2-e4ed77633ca0] COMPLETED  : Your job has been completed.

Downloading result:   0%|          | 0.00/617M [00:00<?, ?B/s]

[2025-08-29 16:53:20] [90f5320a-673a-45ce-8d6d-24adea59aaff] RECEIVED   : Your job has been received and is waiting to be queued.
[2025-08-29 16:53:20] [90f5320a-673a-45ce-8d6d-24adea59aaff] QUEUED     : Your job has been recieved by the coordinator and is waiting to be queued.
[2025-08-29 16:53:20] [90f5320a-673a-45ce-8d6d-24adea59aaff] QUEUED     : Task 90f5320a-673a-45ce-8d6d-24adea59aaff has been added to the queue. Currently at position 1
[2025-08-29 16:53:20] [90f5320a-673a-45ce-8d6d-24adea59aaff] QUEUED     : Dispatching task...
[2025-08-29 16:53:21] [90f5320a-673a-45ce-8d6d-24adea59aaff] RUNNING    : Your job has started running.
[2025-08-29 16:53:56] [90f5320a-673a-45ce-8d6d-24adea59aaff] COMPLETED  : Your job has been completed.

Downloading result:   0%|          | 0.00/193M [00:00<?, ?B/s]

[2025-08-29 16:54:05] [e9b26917-6831-4b23-9f82-4dea442c50c4] RECEIVED   : Your job has been received and is waiting to be queued.
[2025-08-29 16:54:05] [e9b26917-6831-4b23-9f82-4dea442c50c4] QUEUED     : Your job has been recieved by the coordinator and is waiting to be queued.
[2025-08-29 16:54:05] [e9b26917-6831-4b23-9f82-4dea442c50c4] QUEUED     : Task e9b26917-6831-4b23-9f82-4dea442c50c4 has been added to the queue. Currently at position 1
[2025-08-29 16:54:05] [e9b26917-6831-4b23-9f82-4dea442c50c4] QUEUED     : Dispatching task...
[2025-08-29 16:54:05] [e9b26917-6831-4b23-9f82-4dea442c50c4] RUNNING    : Your job has started running.
[2025-08-29 16:56:39] [e9b26917-6831-4b23-9f82-4dea442c50c4] COMPLETED  : Your job has been completed.

Downloading result:   0%|          | 0.00/614M [00:00<?, ?B/s]

[2025-08-29 16:57:03] [45269539-e2cc-41cf-8611-9c1d271f9be9] RECEIVED   : Your job has been received and is waiting to be queued.
[2025-08-29 16:57:03] [45269539-e2cc-41cf-8611-9c1d271f9be9] QUEUED     : Your job has been recieved by the coordinator and is waiting to be queued.
[2025-08-29 16:57:03] [45269539-e2cc-41cf-8611-9c1d271f9be9] QUEUED     : Task 45269539-e2cc-41cf-8611-9c1d271f9be9 has been added to the queue. Currently at position 1
[2025-08-29 16:57:03] [45269539-e2cc-41cf-8611-9c1d271f9be9] QUEUED     : Dispatching task...
[2025-08-29 16:57:03] [45269539-e2cc-41cf-8611-9c1d271f9be9] RUNNING    : Your job has started running.
[2025-08-29 16:57:26] [45269539-e2cc-41cf-8611-9c1d271f9be9] COMPLETED  : Your job has been completed.

Downloading result:   0%|          | 0.00/138M [00:00<?, ?B/s]

[2025-08-29 16:57:33] [c9fa7eb9-491c-4deb-bdcc-6911b6263fe1] RECEIVED   : Your job has been received and is waiting to be queued.
[2025-08-29 16:57:33] [c9fa7eb9-491c-4deb-bdcc-6911b6263fe1] QUEUED     : Your job has been recieved by the coordinator and is waiting to be queued.
[2025-08-29 16:57:33] [c9fa7eb9-491c-4deb-bdcc-6911b6263fe1] QUEUED     : Task c9fa7eb9-491c-4deb-bdcc-6911b6263fe1 has been added to the queue. Currently at position 1
[2025-08-29 16:57:33] [c9fa7eb9-491c-4deb-bdcc-6911b6263fe1] QUEUED     : Dispatching task...
[2025-08-29 16:57:34] [c9fa7eb9-491c-4deb-bdcc-6911b6263fe1] RUNNING    : Your job has started running.
[2025-08-29 17:00:11] [c9fa7eb9-491c-4deb-bdcc-6911b6263fe1] COMPLETED  : Your job has been completed.

Downloading result:   0%|          | 0.00/617M [00:00<?, ?B/s]

[2025-08-29 17:00:35] [f4418191-af18-4d7d-ab48-9a4d1a9314d2] RECEIVED   : Your job has been received and is waiting to be queued.
[2025-08-29 17:00:35] [f4418191-af18-4d7d-ab48-9a4d1a9314d2] QUEUED     : Your job has been recieved by the coordinator and is waiting to be queued.
[2025-08-29 17:00:35] [f4418191-af18-4d7d-ab48-9a4d1a9314d2] QUEUED     : Task f4418191-af18-4d7d-ab48-9a4d1a9314d2 has been added to the queue. Currently at position 1
[2025-08-29 17:00:36] [f4418191-af18-4d7d-ab48-9a4d1a9314d2] QUEUED     : Dispatching task...
[2025-08-29 17:00:36] [f4418191-af18-4d7d-ab48-9a4d1a9314d2] RUNNING    : Your job has started running.
[2025-08-29 17:03:20] [f4418191-af18-4d7d-ab48-9a4d1a9314d2] COMPLETED  : Your job has been completed.

Downloading result:   0%|          | 0.00/664M [00:00<?, ?B/s]

[2025-08-29 17:03:45] [734c44c6-b722-4520-861e-6f38aba63f3c] RECEIVED   : Your job has been received and is waiting to be queued.
[2025-08-29 17:03:45] [734c44c6-b722-4520-861e-6f38aba63f3c] QUEUED     : Your job has been recieved by the coordinator and is waiting to be queued.
[2025-08-29 17:03:45] [734c44c6-b722-4520-861e-6f38aba63f3c] QUEUED     : Task 734c44c6-b722-4520-861e-6f38aba63f3c has been added to the queue. Currently at position 1
[2025-08-29 17:03:45] [734c44c6-b722-4520-861e-6f38aba63f3c] QUEUED     : Dispatching task...
[2025-08-29 17:03:45] [734c44c6-b722-4520-861e-6f38aba63f3c] RUNNING    : Your job has started running.
[2025-08-29 17:06:25] [734c44c6-b722-4520-861e-6f38aba63f3c] COMPLETED  : Your job has been completed.

Downloading result:   0%|          | 0.00/650M [00:00<?, ?B/s]

[2025-08-29 17:06:49] [ddc5e0b3-2bad-40a3-8e4f-4fed0f023836] RECEIVED   : Your job has been received and is waiting to be queued.
[2025-08-29 17:06:49] [ddc5e0b3-2bad-40a3-8e4f-4fed0f023836] QUEUED     : Your job has been recieved by the coordinator and is waiting to be queued.
[2025-08-29 17:06:49] [ddc5e0b3-2bad-40a3-8e4f-4fed0f023836] QUEUED     : Task ddc5e0b3-2bad-40a3-8e4f-4fed0f023836 has been added to the queue. Currently at position 1
[2025-08-29 17:06:50] [ddc5e0b3-2bad-40a3-8e4f-4fed0f023836] QUEUED     : Dispatching task...
[2025-08-29 17:06:50] [ddc5e0b3-2bad-40a3-8e4f-4fed0f023836] RUNNING    : Your job has started running.
[2025-08-29 17:09:25] [ddc5e0b3-2bad-40a3-8e4f-4fed0f023836] COMPLETED  : Your job has been completed.

Downloading result:   0%|          | 0.00/623M [00:00<?, ?B/s]

[2025-08-29 17:09:51] [d97aac6c-e720-4d9c-8d95-40ce8eb800ad] RECEIVED   : Your job has been received and is waiting to be queued.
[2025-08-29 17:09:51] [d97aac6c-e720-4d9c-8d95-40ce8eb800ad] QUEUED     : Your job has been recieved by the coordinator and is waiting to be queued.
[2025-08-29 17:09:51] [d97aac6c-e720-4d9c-8d95-40ce8eb800ad] QUEUED     : Task d97aac6c-e720-4d9c-8d95-40ce8eb800ad has been added to the queue. Currently at position 1
[2025-08-29 17:09:51] [d97aac6c-e720-4d9c-8d95-40ce8eb800ad] QUEUED     : Dispatching task...
[2025-08-29 17:09:51] [d97aac6c-e720-4d9c-8d95-40ce8eb800ad] RUNNING    : Your job has started running.
[2025-08-29 17:12:30] [d97aac6c-e720-4d9c-8d95-40ce8eb800ad] COMPLETED  : Your job has been completed.

Downloading result:   0%|          | 0.00/625M [00:00<?, ?B/s]

[2025-08-29 17:12:53] [f65be10e-54ff-4f26-badf-49b256206315] RECEIVED   : Your job has been received and is waiting to be queued.
[2025-08-29 17:12:53] [f65be10e-54ff-4f26-badf-49b256206315] QUEUED     : Your job has been recieved by the coordinator and is waiting to be queued.
[2025-08-29 17:12:53] [f65be10e-54ff-4f26-badf-49b256206315] QUEUED     : Task f65be10e-54ff-4f26-badf-49b256206315 has been added to the queue. Currently at position 1
[2025-08-29 17:12:53] [f65be10e-54ff-4f26-badf-49b256206315] QUEUED     : Dispatching task...
[2025-08-29 17:12:53] [f65be10e-54ff-4f26-badf-49b256206315] RUNNING    : Your job has started running.
[2025-08-29 17:15:33] [f65be10e-54ff-4f26-badf-49b256206315] COMPLETED  : Your job has been completed.

Downloading result:   0%|          | 0.00/641M [00:00<?, ?B/s]

[2025-08-29 17:16:04] [1369ba5e-1790-4f65-adc3-0d080c08ef75] RECEIVED   : Your job has been received and is waiting to be queued.
[2025-08-29 17:16:04] [1369ba5e-1790-4f65-adc3-0d080c08ef75] QUEUED     : Your job has been recieved by the coordinator and is waiting to be queued.
[2025-08-29 17:16:04] [1369ba5e-1790-4f65-adc3-0d080c08ef75] QUEUED     : Task 1369ba5e-1790-4f65-adc3-0d080c08ef75 has been added to the queue. Currently at position 1
[2025-08-29 17:16:04] [1369ba5e-1790-4f65-adc3-0d080c08ef75] QUEUED     : Dispatching task...
[2025-08-29 17:16:05] [1369ba5e-1790-4f65-adc3-0d080c08ef75] RUNNING    : Your job has started running.
[2025-08-29 17:16:50] [1369ba5e-1790-4f65-adc3-0d080c08ef75] COMPLETED  : Your job has been completed.

Downloading result:   0%|          | 0.00/250M [00:00<?, ?B/s]

[2025-08-29 17:17:00] [41c92c46-5a0c-4132-8594-9d7dd358f030] RECEIVED   : Your job has been received and is waiting to be queued.
[2025-08-29 17:17:00] [41c92c46-5a0c-4132-8594-9d7dd358f030] QUEUED     : Your job has been recieved by the coordinator and is waiting to be queued.
[2025-08-29 17:17:00] [41c92c46-5a0c-4132-8594-9d7dd358f030] QUEUED     : Task 41c92c46-5a0c-4132-8594-9d7dd358f030 has been added to the queue. Currently at position 1
[2025-08-29 17:17:00] [41c92c46-5a0c-4132-8594-9d7dd358f030] QUEUED     : Dispatching task...
[2025-08-29 17:17:00] [41c92c46-5a0c-4132-8594-9d7dd358f030] RUNNING    : Your job has started running.
[2025-08-29 17:19:42] [41c92c46-5a0c-4132-8594-9d7dd358f030] COMPLETED  : Your job has been completed.

Downloading result:   0%|          | 0.00/656M [00:00<?, ?B/s]

[2025-08-29 17:20:07] [5fde2bec-0b4e-4f52-becc-f05952412923] RECEIVED   : Your job has been received and is waiting to be queued.
[2025-08-29 17:20:07] [5fde2bec-0b4e-4f52-becc-f05952412923] QUEUED     : Your job has been recieved by the coordinator and is waiting to be queued.
[2025-08-29 17:20:07] [5fde2bec-0b4e-4f52-becc-f05952412923] QUEUED     : Task 5fde2bec-0b4e-4f52-becc-f05952412923 has been added to the queue. Currently at position 1
[2025-08-29 17:20:07] [5fde2bec-0b4e-4f52-becc-f05952412923] QUEUED     : Dispatching task...
[2025-08-29 17:20:07] [5fde2bec-0b4e-4f52-becc-f05952412923] RUNNING    : Your job has started running.
[2025-08-29 17:22:41] [5fde2bec-0b4e-4f52-becc-f05952412923] COMPLETED  : Your job has been completed.

Downloading result:   0%|          | 0.00/614M [00:00<?, ?B/s]

[2025-08-29 17:23:08] [a1ee1bb9-41f2-4fe1-aa0d-8de32091dc47] RECEIVED   : Your job has been received and is waiting to be queued.
[2025-08-29 17:23:08] [a1ee1bb9-41f2-4fe1-aa0d-8de32091dc47] QUEUED     : Your job has been recieved by the coordinator and is waiting to be queued.
[2025-08-29 17:23:08] [a1ee1bb9-41f2-4fe1-aa0d-8de32091dc47] QUEUED     : Task a1ee1bb9-41f2-4fe1-aa0d-8de32091dc47 has been added to the queue. Currently at position 1
[2025-08-29 17:23:08] [a1ee1bb9-41f2-4fe1-aa0d-8de32091dc47] QUEUED     : Dispatching task...
[2025-08-29 17:23:08] [a1ee1bb9-41f2-4fe1-aa0d-8de32091dc47] RUNNING    : Your job has started running.
[2025-08-29 17:24:00] [a1ee1bb9-41f2-4fe1-aa0d-8de32091dc47] COMPLETED  : Your job has been completed.

Downloading result:   0%|          | 0.00/269M [00:00<?, ?B/s]

[2025-08-29 17:24:14] [b7cd8f2a-92a1-4b67-b603-0033da6dcb1f] RECEIVED   : Your job has been received and is waiting to be queued.
[2025-08-29 17:24:14] [b7cd8f2a-92a1-4b67-b603-0033da6dcb1f] QUEUED     : Your job has been recieved by the coordinator and is waiting to be queued.
[2025-08-29 17:24:14] [b7cd8f2a-92a1-4b67-b603-0033da6dcb1f] QUEUED     : Task b7cd8f2a-92a1-4b67-b603-0033da6dcb1f has been added to the queue. Currently at position 1
[2025-08-29 17:24:14] [b7cd8f2a-92a1-4b67-b603-0033da6dcb1f] QUEUED     : Dispatching task...
[2025-08-29 17:24:15] [b7cd8f2a-92a1-4b67-b603-0033da6dcb1f] RUNNING    : Your job has started running.
[2025-08-29 17:25:01] [b7cd8f2a-92a1-4b67-b603-0033da6dcb1f] COMPLETED  : Your job has been completed.

Downloading result:   0%|          | 0.00/252M [00:00<?, ?B/s]

[2025-08-29 17:25:17] [2e609f00-3a09-4566-ac34-2ca360b3b46a] RECEIVED   : Your job has been received and is waiting to be queued.
[2025-08-29 17:25:17] [2e609f00-3a09-4566-ac34-2ca360b3b46a] QUEUED     : Your job has been recieved by the coordinator and is waiting to be queued.
[2025-08-29 17:25:17] [2e609f00-3a09-4566-ac34-2ca360b3b46a] QUEUED     : Task 2e609f00-3a09-4566-ac34-2ca360b3b46a has been added to the queue. Currently at position 1
[2025-08-29 17:25:17] [2e609f00-3a09-4566-ac34-2ca360b3b46a] QUEUED     : Dispatching task...
[2025-08-29 17:25:17] [2e609f00-3a09-4566-ac34-2ca360b3b46a] RUNNING    : Your job has started running.
[2025-08-29 17:26:11] [2e609f00-3a09-4566-ac34-2ca360b3b46a] COMPLETED  : Your job has been completed.

Downloading result:   0%|          | 0.00/277M [00:00<?, ?B/s]

[2025-08-29 17:26:24] [120d5523-5de9-4bbe-bc7b-ccc2ca0cd047] RECEIVED   : Your job has been received and is waiting to be queued.
[2025-08-29 17:26:24] [120d5523-5de9-4bbe-bc7b-ccc2ca0cd047] QUEUED     : Your job has been recieved by the coordinator and is waiting to be queued.
[2025-08-29 17:26:24] [120d5523-5de9-4bbe-bc7b-ccc2ca0cd047] QUEUED     : Task 120d5523-5de9-4bbe-bc7b-ccc2ca0cd047 has been added to the queue. Currently at position 1
[2025-08-29 17:26:24] [120d5523-5de9-4bbe-bc7b-ccc2ca0cd047] QUEUED     : Dispatching task...
[2025-08-29 17:26:24] [120d5523-5de9-4bbe-bc7b-ccc2ca0cd047] RUNNING    : Your job has started running.
[2025-08-29 17:28:55] [120d5523-5de9-4bbe-bc7b-ccc2ca0cd047] COMPLETED  : Your job has been completed.

Downloading result:   0%|          | 0.00/602M [00:00<?, ?B/s]

[2025-08-29 17:29:19] [08831fb1-ac53-4ec8-bbba-1a2db5558f93] RECEIVED   : Your job has been received and is waiting to be queued.
[2025-08-29 17:29:19] [08831fb1-ac53-4ec8-bbba-1a2db5558f93] QUEUED     : Your job has been recieved by the coordinator and is waiting to be queued.
[2025-08-29 17:29:19] [08831fb1-ac53-4ec8-bbba-1a2db5558f93] QUEUED     : Task 08831fb1-ac53-4ec8-bbba-1a2db5558f93 has been added to the queue. Currently at position 1
[2025-08-29 17:29:19] [08831fb1-ac53-4ec8-bbba-1a2db5558f93] QUEUED     : Dispatching task...
[2025-08-29 17:29:19] [08831fb1-ac53-4ec8-bbba-1a2db5558f93] RUNNING    : Your job has started running.
[2025-08-29 17:30:08] [08831fb1-ac53-4ec8-bbba-1a2db5558f93] COMPLETED  : Your job has been completed.

Downloading result:   0%|          | 0.00/264M [00:00<?, ?B/s]

[2025-08-29 17:30:21] [af5d0ebb-8c1e-44e6-b4e8-cc5bfc046fc9] RECEIVED   : Your job has been received and is waiting to be queued.
[2025-08-29 17:30:21] [af5d0ebb-8c1e-44e6-b4e8-cc5bfc046fc9] QUEUED     : Your job has been recieved by the coordinator and is waiting to be queued.
[2025-08-29 17:30:21] [af5d0ebb-8c1e-44e6-b4e8-cc5bfc046fc9] QUEUED     : Task af5d0ebb-8c1e-44e6-b4e8-cc5bfc046fc9 has been added to the queue. Currently at position 1
[2025-08-29 17:30:21] [af5d0ebb-8c1e-44e6-b4e8-cc5bfc046fc9] QUEUED     : Dispatching task...
[2025-08-29 17:30:21] [af5d0ebb-8c1e-44e6-b4e8-cc5bfc046fc9] RUNNING    : Your job has started running.
[2025-08-29 17:32:56] [af5d0ebb-8c1e-44e6-b4e8-cc5bfc046fc9] COMPLETED  : Your job has been completed.

Downloading result:   0%|          | 0.00/621M [00:00<?, ?B/s]

[2025-08-29 17:33:22] [7cb5a26e-aeec-4422-b2fe-34d09abda660] RECEIVED   : Your job has been received and is waiting to be queued.
[2025-08-29 17:33:22] [7cb5a26e-aeec-4422-b2fe-34d09abda660] QUEUED     : Your job has been recieved by the coordinator and is waiting to be queued.
[2025-08-29 17:33:22] [7cb5a26e-aeec-4422-b2fe-34d09abda660] QUEUED     : Task 7cb5a26e-aeec-4422-b2fe-34d09abda660 has been added to the queue. Currently at position 1
[2025-08-29 17:33:22] [7cb5a26e-aeec-4422-b2fe-34d09abda660] QUEUED     : Dispatching task...
[2025-08-29 17:33:22] [7cb5a26e-aeec-4422-b2fe-34d09abda660] RUNNING    : Your job has started running.
[2025-08-29 17:35:54] [7cb5a26e-aeec-4422-b2fe-34d09abda660] COMPLETED  : Your job has been completed.

Downloading result:   0%|          | 0.00/606M [00:00<?, ?B/s]

[2025-08-29 17:36:16] [2b4507d9-82cd-4f38-9822-a66e6c354baa] RECEIVED   : Your job has been received and is waiting to be queued.
[2025-08-29 17:36:16] [2b4507d9-82cd-4f38-9822-a66e6c354baa] QUEUED     : Your job has been recieved by the coordinator and is waiting to be queued.
[2025-08-29 17:36:16] [2b4507d9-82cd-4f38-9822-a66e6c354baa] QUEUED     : Task 2b4507d9-82cd-4f38-9822-a66e6c354baa has been added to the queue. Currently at position 1
[2025-08-29 17:36:17] [2b4507d9-82cd-4f38-9822-a66e6c354baa] QUEUED     : Dispatching task...
[2025-08-29 17:36:17] [2b4507d9-82cd-4f38-9822-a66e6c354baa] RUNNING    : Your job has started running.
[2025-08-29 17:36:59] [2b4507d9-82cd-4f38-9822-a66e6c354baa] COMPLETED  : Your job has been completed.

Downloading result:   0%|          | 0.00/214M [00:00<?, ?B/s]

[2025-08-29 17:37:08] [d0f105ea-d207-4b4a-9ece-e8bd8104aa0a] RECEIVED   : Your job has been received and is waiting to be queued.
[2025-08-29 17:37:08] [d0f105ea-d207-4b4a-9ece-e8bd8104aa0a] QUEUED     : Your job has been recieved by the coordinator and is waiting to be queued.
[2025-08-29 17:37:08] [d0f105ea-d207-4b4a-9ece-e8bd8104aa0a] QUEUED     : Task d0f105ea-d207-4b4a-9ece-e8bd8104aa0a has been added to the queue. Currently at position 1
[2025-08-29 17:37:08] [d0f105ea-d207-4b4a-9ece-e8bd8104aa0a] QUEUED     : Dispatching task...
[2025-08-29 17:37:08] [d0f105ea-d207-4b4a-9ece-e8bd8104aa0a] RUNNING    : Your job has started running.
[2025-08-29 17:39:50] [d0f105ea-d207-4b4a-9ece-e8bd8104aa0a] COMPLETED  : Your job has been completed.

Downloading result:   0%|          | 0.00/655M [00:00<?, ?B/s]

[2025-08-29 17:40:18] [4679f6aa-b62c-44d9-af6d-ddd8c8b1902d] RECEIVED   : Your job has been received and is waiting to be queued.
[2025-08-29 17:40:18] [4679f6aa-b62c-44d9-af6d-ddd8c8b1902d] QUEUED     : Your job has been recieved by the coordinator and is waiting to be queued.
[2025-08-29 17:40:18] [4679f6aa-b62c-44d9-af6d-ddd8c8b1902d] QUEUED     : Task 4679f6aa-b62c-44d9-af6d-ddd8c8b1902d has been added to the queue. Currently at position 1
[2025-08-29 17:40:18] [4679f6aa-b62c-44d9-af6d-ddd8c8b1902d] QUEUED     : Dispatching task...
[2025-08-29 17:40:18] [4679f6aa-b62c-44d9-af6d-ddd8c8b1902d] RUNNING    : Your job has started running.
[2025-08-29 17:40:44] [4679f6aa-b62c-44d9-af6d-ddd8c8b1902d] COMPLETED  : Your job has been completed.

Downloading result:   0%|          | 0.00/158M [00:00<?, ?B/s]

[2025-08-29 17:40:51] [e7a342a6-8104-4d56-81cf-208143618e3c] RECEIVED   : Your job has been received and is waiting to be queued.
[2025-08-29 17:40:51] [e7a342a6-8104-4d56-81cf-208143618e3c] QUEUED     : Your job has been recieved by the coordinator and is waiting to be queued.
[2025-08-29 17:40:51] [e7a342a6-8104-4d56-81cf-208143618e3c] QUEUED     : Task e7a342a6-8104-4d56-81cf-208143618e3c has been added to the queue. Currently at position 1
[2025-08-29 17:40:51] [e7a342a6-8104-4d56-81cf-208143618e3c] QUEUED     : Dispatching task...
[2025-08-29 17:40:53] [e7a342a6-8104-4d56-81cf-208143618e3c] RUNNING    : Your job has started running.
[2025-08-29 17:43:56] [e7a342a6-8104-4d56-81cf-208143618e3c] COMPLETED  : Your job has been completed.

Downloading result:   0%|          | 0.00/771M [00:00<?, ?B/s]

[2025-08-29 17:44:24] [33c08850-8419-46ec-a2fa-d807bb20c65f] RECEIVED   : Your job has been received and is waiting to be queued.
[2025-08-29 17:44:24] [33c08850-8419-46ec-a2fa-d807bb20c65f] QUEUED     : Your job has been recieved by the coordinator and is waiting to be queued.
[2025-08-29 17:44:24] [33c08850-8419-46ec-a2fa-d807bb20c65f] QUEUED     : Task 33c08850-8419-46ec-a2fa-d807bb20c65f has been added to the queue. Currently at position 1
[2025-08-29 17:44:24] [33c08850-8419-46ec-a2fa-d807bb20c65f] QUEUED     : Dispatching task...
[2025-08-29 17:44:24] [33c08850-8419-46ec-a2fa-d807bb20c65f] RUNNING    : Your job has started running.
[2025-08-29 17:44:58] [33c08850-8419-46ec-a2fa-d807bb20c65f] COMPLETED  : Your job has been completed.

Downloading result:   0%|          | 0.00/190M [00:00<?, ?B/s]

[2025-08-29 17:45:08] [2dc7fa42-b6d8-461d-89fe-c32fdd486b17] RECEIVED   : Your job has been received and is waiting to be queued.
[2025-08-29 17:45:08] [2dc7fa42-b6d8-461d-89fe-c32fdd486b17] QUEUED     : Your job has been recieved by the coordinator and is waiting to be queued.
[2025-08-29 17:45:08] [2dc7fa42-b6d8-461d-89fe-c32fdd486b17] QUEUED     : Task 2dc7fa42-b6d8-461d-89fe-c32fdd486b17 has been added to the queue. Currently at position 1
[2025-08-29 17:45:08] [2dc7fa42-b6d8-461d-89fe-c32fdd486b17] QUEUED     : Dispatching task...
[2025-08-29 17:45:09] [2dc7fa42-b6d8-461d-89fe-c32fdd486b17] RUNNING    : Your job has started running.
[2025-08-29 17:47:42] [2dc7fa42-b6d8-461d-89fe-c32fdd486b17] COMPLETED  : Your job has been completed.

Downloading result:   0%|          | 0.00/613M [00:00<?, ?B/s]

[2025-08-29 17:48:05] [1a6a3071-883e-4d44-9699-b8c854cf23f9] RECEIVED   : Your job has been received and is waiting to be queued.
[2025-08-29 17:48:05] [1a6a3071-883e-4d44-9699-b8c854cf23f9] QUEUED     : Your job has been recieved by the coordinator and is waiting to be queued.
[2025-08-29 17:48:05] [1a6a3071-883e-4d44-9699-b8c854cf23f9] QUEUED     : Task 1a6a3071-883e-4d44-9699-b8c854cf23f9 has been added to the queue. Currently at position 1
[2025-08-29 17:48:05] [1a6a3071-883e-4d44-9699-b8c854cf23f9] QUEUED     : Dispatching task...
[2025-08-29 17:48:06] [1a6a3071-883e-4d44-9699-b8c854cf23f9] RUNNING    : Your job has started running.
[2025-08-29 17:48:36] [1a6a3071-883e-4d44-9699-b8c854cf23f9] COMPLETED  : Your job has been completed.

Downloading result:   0%|          | 0.00/178M [00:00<?, ?B/s]

[2025-08-29 17:48:45] [f099cbaf-56b5-4c7d-8b0c-9bdcbc0977be] RECEIVED   : Your job has been received and is waiting to be queued.
[2025-08-29 17:48:45] [f099cbaf-56b5-4c7d-8b0c-9bdcbc0977be] QUEUED     : Your job has been recieved by the coordinator and is waiting to be queued.
[2025-08-29 17:48:45] [f099cbaf-56b5-4c7d-8b0c-9bdcbc0977be] QUEUED     : Task f099cbaf-56b5-4c7d-8b0c-9bdcbc0977be has been added to the queue. Currently at position 1
[2025-08-29 17:48:45] [f099cbaf-56b5-4c7d-8b0c-9bdcbc0977be] QUEUED     : Dispatching task...
[2025-08-29 17:48:46] [f099cbaf-56b5-4c7d-8b0c-9bdcbc0977be] RUNNING    : Your job has started running.
[2025-08-29 17:49:51] [f099cbaf-56b5-4c7d-8b0c-9bdcbc0977be] COMPLETED  : Your job has been completed.

Downloading result:   0%|          | 0.00/322M [00:00<?, ?B/s]

[2025-08-29 17:50:04] [2a3c6630-2aef-4237-b695-7dca44ace9f0] RECEIVED   : Your job has been received and is waiting to be queued.
[2025-08-29 17:50:04] [2a3c6630-2aef-4237-b695-7dca44ace9f0] QUEUED     : Your job has been recieved by the coordinator and is waiting to be queued.
[2025-08-29 17:50:04] [2a3c6630-2aef-4237-b695-7dca44ace9f0] QUEUED     : Task 2a3c6630-2aef-4237-b695-7dca44ace9f0 has been added to the queue. Currently at position 1
[2025-08-29 17:50:04] [2a3c6630-2aef-4237-b695-7dca44ace9f0] QUEUED     : Dispatching task...
[2025-08-29 17:50:05] [2a3c6630-2aef-4237-b695-7dca44ace9f0] RUNNING    : Your job has started running.
[2025-08-29 17:52:40] [2a3c6630-2aef-4237-b695-7dca44ace9f0] COMPLETED  : Your job has been completed.

Downloading result:   0%|          | 0.00/616M [00:00<?, ?B/s]

[2025-08-29 17:53:03] [d0f887e5-3aef-4da5-a6d4-6890ce6d36ca] RECEIVED   : Your job has been received and is waiting to be queued.
[2025-08-29 17:53:03] [d0f887e5-3aef-4da5-a6d4-6890ce6d36ca] QUEUED     : Your job has been recieved by the coordinator and is waiting to be queued.
[2025-08-29 17:53:03] [d0f887e5-3aef-4da5-a6d4-6890ce6d36ca] QUEUED     : Task d0f887e5-3aef-4da5-a6d4-6890ce6d36ca has been added to the queue. Currently at position 1
[2025-08-29 17:53:03] [d0f887e5-3aef-4da5-a6d4-6890ce6d36ca] QUEUED     : Dispatching task...
[2025-08-29 17:53:03] [d0f887e5-3aef-4da5-a6d4-6890ce6d36ca] RUNNING    : Your job has started running.
[2025-08-29 17:54:43] [d0f887e5-3aef-4da5-a6d4-6890ce6d36ca] COMPLETED  : Your job has been completed.

Downloading result:   0%|          | 0.00/444M [00:00<?, ?B/s]

[2025-08-29 17:55:00] [5bd64fb2-0ddc-4f62-8b27-da51f7c7a0db] RECEIVED   : Your job has been received and is waiting to be queued.
[2025-08-29 17:55:00] [5bd64fb2-0ddc-4f62-8b27-da51f7c7a0db] QUEUED     : Your job has been recieved by the coordinator and is waiting to be queued.
[2025-08-29 17:55:00] [5bd64fb2-0ddc-4f62-8b27-da51f7c7a0db] QUEUED     : Task 5bd64fb2-0ddc-4f62-8b27-da51f7c7a0db has been added to the queue. Currently at position 1
[2025-08-29 17:55:00] [5bd64fb2-0ddc-4f62-8b27-da51f7c7a0db] QUEUED     : Dispatching task...
[2025-08-29 17:55:01] [5bd64fb2-0ddc-4f62-8b27-da51f7c7a0db] RUNNING    : Your job has started running.
[2025-08-29 17:57:34] [5bd64fb2-0ddc-4f62-8b27-da51f7c7a0db] COMPLETED  : Your job has been completed.

Downloading result:   0%|          | 0.00/612M [00:00<?, ?B/s]

[2025-08-29 17:58:02] [82f496d6-8b77-4e7c-84ea-f5fe5646b182] RECEIVED   : Your job has been received and is waiting to be queued.
[2025-08-29 17:58:02] [82f496d6-8b77-4e7c-84ea-f5fe5646b182] QUEUED     : Your job has been recieved by the coordinator and is waiting to be queued.
[2025-08-29 17:58:02] [82f496d6-8b77-4e7c-84ea-f5fe5646b182] QUEUED     : Task 82f496d6-8b77-4e7c-84ea-f5fe5646b182 has been added to the queue. Currently at position 1
[2025-08-29 17:58:02] [82f496d6-8b77-4e7c-84ea-f5fe5646b182] QUEUED     : Dispatching task...
[2025-08-29 17:58:02] [82f496d6-8b77-4e7c-84ea-f5fe5646b182] RUNNING    : Your job has started running.
[2025-08-29 17:59:00] [82f496d6-8b77-4e7c-84ea-f5fe5646b182] COMPLETED  : Your job has been completed.

Downloading result:   0%|          | 0.00/296M [00:00<?, ?B/s]

[2025-08-29 17:59:12] [031492a5-3c10-46c1-afa0-8e2b6bbf5089] RECEIVED   : Your job has been received and is waiting to be queued.
[2025-08-29 17:59:12] [031492a5-3c10-46c1-afa0-8e2b6bbf5089] QUEUED     : Your job has been recieved by the coordinator and is waiting to be queued.
[2025-08-29 17:59:12] [031492a5-3c10-46c1-afa0-8e2b6bbf5089] QUEUED     : Task 031492a5-3c10-46c1-afa0-8e2b6bbf5089 has been added to the queue. Currently at position 1
[2025-08-29 17:59:12] [031492a5-3c10-46c1-afa0-8e2b6bbf5089] QUEUED     : Dispatching task...
[2025-08-29 17:59:13] [031492a5-3c10-46c1-afa0-8e2b6bbf5089] RUNNING    : Your job has started running.
[2025-08-29 18:01:56] [031492a5-3c10-46c1-afa0-8e2b6bbf5089] COMPLETED  : Your job has been completed.

Downloading result:   0%|          | 0.00/670M [00:00<?, ?B/s]

[2025-08-29 18:02:26] [f67280a6-593b-4c2d-bf82-f6ffcaadfe31] RECEIVED   : Your job has been received and is waiting to be queued.
[2025-08-29 18:02:26] [f67280a6-593b-4c2d-bf82-f6ffcaadfe31] QUEUED     : Your job has been recieved by the coordinator and is waiting to be queued.
[2025-08-29 18:02:26] [f67280a6-593b-4c2d-bf82-f6ffcaadfe31] QUEUED     : Task f67280a6-593b-4c2d-bf82-f6ffcaadfe31 has been added to the queue. Currently at position 1
[2025-08-29 18:02:26] [f67280a6-593b-4c2d-bf82-f6ffcaadfe31] QUEUED     : Dispatching task...
[2025-08-29 18:02:27] [f67280a6-593b-4c2d-bf82-f6ffcaadfe31] RUNNING    : Your job has started running.
[2025-08-29 18:03:02] [f67280a6-593b-4c2d-bf82-f6ffcaadfe31] COMPLETED  : Your job has been completed.

Downloading result:   0%|          | 0.00/197M [00:00<?, ?B/s]

[2025-08-29 18:03:10] [01bb5195-b453-4e28-b8f6-88f147202a89] RECEIVED   : Your job has been received and is waiting to be queued.
[2025-08-29 18:03:10] [01bb5195-b453-4e28-b8f6-88f147202a89] QUEUED     : Your job has been recieved by the coordinator and is waiting to be queued.
[2025-08-29 18:03:10] [01bb5195-b453-4e28-b8f6-88f147202a89] QUEUED     : Task 01bb5195-b453-4e28-b8f6-88f147202a89 has been added to the queue. Currently at position 1
[2025-08-29 18:03:10] [01bb5195-b453-4e28-b8f6-88f147202a89] QUEUED     : Dispatching task...
[2025-08-29 18:03:11] [01bb5195-b453-4e28-b8f6-88f147202a89] RUNNING    : Your job has started running.
[2025-08-29 18:05:47] [01bb5195-b453-4e28-b8f6-88f147202a89] COMPLETED  : Your job has been completed.

Downloading result:   0%|          | 0.00/629M [00:00<?, ?B/s]

[2025-08-29 18:06:12] [f27c3f8d-2a7e-4139-8b14-22d32b07c34c] RECEIVED   : Your job has been received and is waiting to be queued.
[2025-08-29 18:06:12] [f27c3f8d-2a7e-4139-8b14-22d32b07c34c] QUEUED     : Your job has been recieved by the coordinator and is waiting to be queued.
[2025-08-29 18:06:12] [f27c3f8d-2a7e-4139-8b14-22d32b07c34c] QUEUED     : Task f27c3f8d-2a7e-4139-8b14-22d32b07c34c has been added to the queue. Currently at position 1
[2025-08-29 18:06:12] [f27c3f8d-2a7e-4139-8b14-22d32b07c34c] QUEUED     : Dispatching task...
[2025-08-29 18:06:12] [f27c3f8d-2a7e-4139-8b14-22d32b07c34c] RUNNING    : Your job has started running.
[2025-08-29 18:08:14] [f27c3f8d-2a7e-4139-8b14-22d32b07c34c] COMPLETED  : Your job has been completed.

Downloading result:   0%|          | 0.00/517M [00:00<?, ?B/s]

[2025-08-29 18:08:35] [5492760e-2c1c-44b0-ae9c-63b3a218d1de] RECEIVED   : Your job has been received and is waiting to be queued.
[2025-08-29 18:08:35] [5492760e-2c1c-44b0-ae9c-63b3a218d1de] QUEUED     : Your job has been recieved by the coordinator and is waiting to be queued.
[2025-08-29 18:08:35] [5492760e-2c1c-44b0-ae9c-63b3a218d1de] QUEUED     : Task 5492760e-2c1c-44b0-ae9c-63b3a218d1de has been added to the queue. Currently at position 1
[2025-08-29 18:08:35] [5492760e-2c1c-44b0-ae9c-63b3a218d1de] QUEUED     : Dispatching task...
[2025-08-29 18:08:35] [5492760e-2c1c-44b0-ae9c-63b3a218d1de] RUNNING    : Your job has started running.
[2025-08-29 18:11:09] [5492760e-2c1c-44b0-ae9c-63b3a218d1de] COMPLETED  : Your job has been completed.

Downloading result:   0%|          | 0.00/609M [00:00<?, ?B/s]

[2025-08-29 18:11:37] [17862848-c066-46b0-b98f-8a78a4fa3a77] RECEIVED   : Your job has been received and is waiting to be queued.
[2025-08-29 18:11:37] [17862848-c066-46b0-b98f-8a78a4fa3a77] QUEUED     : Your job has been recieved by the coordinator and is waiting to be queued.
[2025-08-29 18:11:37] [17862848-c066-46b0-b98f-8a78a4fa3a77] QUEUED     : Task 17862848-c066-46b0-b98f-8a78a4fa3a77 has been added to the queue. Currently at position 1
[2025-08-29 18:11:37] [17862848-c066-46b0-b98f-8a78a4fa3a77] QUEUED     : Dispatching task...
[2025-08-29 18:11:37] [17862848-c066-46b0-b98f-8a78a4fa3a77] RUNNING    : Your job has started running.
[2025-08-29 18:12:06] [17862848-c066-46b0-b98f-8a78a4fa3a77] COMPLETED  : Your job has been completed.

Downloading result:   0%|          | 0.00/157M [00:00<?, ?B/s]

[2025-08-29 18:12:14] [ffd0f819-a9d1-4efd-a67e-50e55bb158a5] RECEIVED   : Your job has been received and is waiting to be queued.
[2025-08-29 18:12:14] [ffd0f819-a9d1-4efd-a67e-50e55bb158a5] QUEUED     : Your job has been recieved by the coordinator and is waiting to be queued.
[2025-08-29 18:12:14] [ffd0f819-a9d1-4efd-a67e-50e55bb158a5] QUEUED     : Task ffd0f819-a9d1-4efd-a67e-50e55bb158a5 has been added to the queue. Currently at position 1
[2025-08-29 18:12:14] [ffd0f819-a9d1-4efd-a67e-50e55bb158a5] QUEUED     : Dispatching task...
[2025-08-29 18:12:14] [ffd0f819-a9d1-4efd-a67e-50e55bb158a5] RUNNING    : Your job has started running.
[2025-08-29 18:14:50] [ffd0f819-a9d1-4efd-a67e-50e55bb158a5] COMPLETED  : Your job has been completed.

Downloading result:   0%|          | 0.00/627M [00:00<?, ?B/s]

[2025-08-29 18:15:14] [a63cff96-0785-457d-b01c-7e3a81d14709] RECEIVED   : Your job has been received and is waiting to be queued.
[2025-08-29 18:15:14] [a63cff96-0785-457d-b01c-7e3a81d14709] QUEUED     : Your job has been recieved by the coordinator and is waiting to be queued.
[2025-08-29 18:15:14] [a63cff96-0785-457d-b01c-7e3a81d14709] QUEUED     : Task a63cff96-0785-457d-b01c-7e3a81d14709 has been added to the queue. Currently at position 1
[2025-08-29 18:15:14] [a63cff96-0785-457d-b01c-7e3a81d14709] QUEUED     : Dispatching task...
[2025-08-29 18:15:14] [a63cff96-0785-457d-b01c-7e3a81d14709] RUNNING    : Your job has started running.
[2025-08-29 18:17:49] [a63cff96-0785-457d-b01c-7e3a81d14709] COMPLETED  : Your job has been completed.

Downloading result:   0%|          | 0.00/616M [00:00<?, ?B/s]

[2025-08-29 18:18:12] [c1618b97-3a25-45a8-a8c1-f98b7f529093] RECEIVED   : Your job has been received and is waiting to be queued.
[2025-08-29 18:18:12] [c1618b97-3a25-45a8-a8c1-f98b7f529093] QUEUED     : Your job has been recieved by the coordinator and is waiting to be queued.
[2025-08-29 18:18:12] [c1618b97-3a25-45a8-a8c1-f98b7f529093] QUEUED     : Task c1618b97-3a25-45a8-a8c1-f98b7f529093 has been added to the queue. Currently at position 1
[2025-08-29 18:18:12] [c1618b97-3a25-45a8-a8c1-f98b7f529093] QUEUED     : Dispatching task...
[2025-08-29 18:18:12] [c1618b97-3a25-45a8-a8c1-f98b7f529093] RUNNING    : Your job has started running.
[2025-08-29 18:18:35] [c1618b97-3a25-45a8-a8c1-f98b7f529093] COMPLETED  : Your job has been completed.

Downloading result:   0%|          | 0.00/130M [00:00<?, ?B/s]

[2025-08-29 18:18:42] [5fa73aa5-1c4c-4038-bee0-2ecb09e21c61] RECEIVED   : Your job has been received and is waiting to be queued.
[2025-08-29 18:18:42] [5fa73aa5-1c4c-4038-bee0-2ecb09e21c61] QUEUED     : Your job has been recieved by the coordinator and is waiting to be queued.
[2025-08-29 18:18:42] [5fa73aa5-1c4c-4038-bee0-2ecb09e21c61] QUEUED     : Task 5fa73aa5-1c4c-4038-bee0-2ecb09e21c61 has been added to the queue. Currently at position 1
[2025-08-29 18:18:42] [5fa73aa5-1c4c-4038-bee0-2ecb09e21c61] QUEUED     : Dispatching task...
[2025-08-29 18:18:42] [5fa73aa5-1c4c-4038-bee0-2ecb09e21c61] RUNNING    : Your job has started running.
[2025-08-29 18:21:04] [5fa73aa5-1c4c-4038-bee0-2ecb09e21c61] COMPLETED  : Your job has been completed.

Downloading result:   0%|          | 0.00/579M [00:00<?, ?B/s]

[2025-08-29 18:21:27] [48d4a09e-378b-47b7-870b-603e0bc204b3] RECEIVED   : Your job has been received and is waiting to be queued.
[2025-08-29 18:21:27] [48d4a09e-378b-47b7-870b-603e0bc204b3] QUEUED     : Your job has been recieved by the coordinator and is waiting to be queued.
[2025-08-29 18:21:27] [48d4a09e-378b-47b7-870b-603e0bc204b3] QUEUED     : Task 48d4a09e-378b-47b7-870b-603e0bc204b3 has been added to the queue. Currently at position 1
[2025-08-29 18:21:27] [48d4a09e-378b-47b7-870b-603e0bc204b3] QUEUED     : Dispatching task...
[2025-08-29 18:21:27] [48d4a09e-378b-47b7-870b-603e0bc204b3] RUNNING    : Your job has started running.
[2025-08-29 18:22:07] [48d4a09e-378b-47b7-870b-603e0bc204b3] COMPLETED  : Your job has been completed.

Downloading result:   0%|          | 0.00/217M [00:00<?, ?B/s]

[2025-08-29 18:22:16] [4a5dd6ae-fd74-40ce-bc76-f88816fa56f0] RECEIVED   : Your job has been received and is waiting to be queued.
[2025-08-29 18:22:16] [4a5dd6ae-fd74-40ce-bc76-f88816fa56f0] QUEUED     : Your job has been recieved by the coordinator and is waiting to be queued.
[2025-08-29 18:22:16] [4a5dd6ae-fd74-40ce-bc76-f88816fa56f0] QUEUED     : Task 4a5dd6ae-fd74-40ce-bc76-f88816fa56f0 has been added to the queue. Currently at position 1
[2025-08-29 18:22:16] [4a5dd6ae-fd74-40ce-bc76-f88816fa56f0] QUEUED     : Dispatching task...
[2025-08-29 18:22:17] [4a5dd6ae-fd74-40ce-bc76-f88816fa56f0] RUNNING    : Your job has started running.
[2025-08-29 18:25:02] [4a5dd6ae-fd74-40ce-bc76-f88816fa56f0] COMPLETED  : Your job has been completed.

Downloading result:   0%|          | 0.00/660M [00:00<?, ?B/s]

[2025-08-29 18:25:39] [3a7aafc2-b286-4a99-a261-c9f28ab05554] RECEIVED   : Your job has been received and is waiting to be queued.
[2025-08-29 18:25:39] [3a7aafc2-b286-4a99-a261-c9f28ab05554] QUEUED     : Your job has been recieved by the coordinator and is waiting to be queued.
[2025-08-29 18:25:39] [3a7aafc2-b286-4a99-a261-c9f28ab05554] QUEUED     : Task 3a7aafc2-b286-4a99-a261-c9f28ab05554 has been added to the queue. Currently at position 1
[2025-08-29 18:25:39] [3a7aafc2-b286-4a99-a261-c9f28ab05554] QUEUED     : Dispatching task...
[2025-08-29 18:25:40] [3a7aafc2-b286-4a99-a261-c9f28ab05554] RUNNING    : Your job has started running.

Error on problem 189: Traceback (most recent call last):
  File "/u/svcndifuser/ndif-deployment/repos/prod/ndif/src/services/ray/src/ray/deployments/modeling/base.py", line 213, in __call__
    result = await job_task
  File "/u/svcndifuser/miniconda3/lib/python3.10/asyncio/threads.py", line 25, in to_thread
    return await loop.run_in_executor(None, func_call)
  File "/u/svcndifuser/miniconda3/lib/python3.10/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/u/svcndifuser/miniconda3/lib/python3.10/site-packages/ray/util/tracing/tracing_helper.py", line 463, in _resume_span
    return method(self, *_args, **_kwargs)
  File "/u/svcndifuser/ndif-deployment/repos/prod/ndif/src/services/ray/src/ray/deployments/modeling/base.py", line 283, in execute
    result = RemoteExecutionBackend(request.interventions, self.execution_protector)(request.tracer)
  File "/u/svcndifuser/ndif-deployment/repos/prod/ndif/src/services/ray/src/ray/nn/backend.py", line 27, in __call__
    run(tracer, self.fn)
  File "/u/svcndifuser/ndif-deployment/repos/prod/ndif/src/services/ray/src/ray/nn/sandbox.py", line 16, in run
    raise wrap_exception(e,tracer.info) from None
nnsight.NNsightException:

Traceback (most recent call last):
  File "/u/svcndifuser/ndif-deployment/repos/prod/ndif/src/services/ray/src/ray/nn/sandbox.py", line 14, in run
    tracer.execute(fn)
  File "/u/svcndifuser/miniconda3/lib/python3.10/site-packages/nnsight/intervention/tracing/tracer.py", line 385, in execute
    self.model.interleave(self.fn, *args, **kwargs)
  File "/u/svcndifuser/miniconda3/lib/python3.10/site-packages/nnsight/modeling/mixins/meta.py", line 76, in interleave
    return super().interleave(fn, *args, **kwargs)
  File "/u/svcndifuser/miniconda3/lib/python3.10/site-packages/nnsight/intervention/envoy.py", line 733, in interleave
    fn(*args, **kwargs)
  File "/u/svcndifuser/miniconda3/lib/python3.10/site-packages/nnsight/modeling/language.py", line 173, in __nnsight_generate__
    output = self._model.generate(*args, streamer=streamer, **kwargs)
  File "/u/svcndifuser/miniconda3/lib/python3.10/site-packages/torch/utils/_contextlib.py", line 116, in decorate_context
    return func(*args, **kwargs)
  File "/u/svcndifuser/miniconda3/lib/python3.10/site-packages/transformers/generation/utils.py", line 2629, in generate
    result = self._sample(
  File "/u/svcndifuser/miniconda3/lib/python3.10/site-packages/transformers/generation/utils.py", line 3613, in _sample
    outputs = model_forward(**model_inputs, return_dict=True)
  File "/u/svcndifuser/miniconda3/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1751, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/u/svcndifuser/miniconda3/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1857, in _call_impl
    return inner()
  File "/u/svcndifuser/miniconda3/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1805, in inner
    result = forward_call(*args, **kwargs)
  File "/u/svcndifuser/miniconda3/lib/python3.10/site-packages/nnsight/intervention/interleaver.py", line 133, in skippable_forward
    return forward(*args, **kwargs)
  File "/u/svcndifuser/miniconda3/lib/python3.10/site-packages/transformers/utils/generic.py", line 959, in wrapper
    output = func(self, *args, **kwargs)
  File "/u/svcndifuser/miniconda3/lib/python3.10/site-packages/transformers/models/llama/modeling_llama.py", line 460, in forward
    outputs: BaseModelOutputWithPast = self.model(
  File "/u/svcndifuser/miniconda3/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1751, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/u/svcndifuser/miniconda3/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1857, in _call_impl
    return inner()
  File "/u/svcndifuser/miniconda3/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1805, in inner
    result = forward_call(*args, **kwargs)
  File "/u/svcndifuser/miniconda3/lib/python3.10/site-packages/nnsight/intervention/interleaver.py", line 133, in skippable_forward
    return forward(*args, **kwargs)
  File "/u/svcndifuser/miniconda3/lib/python3.10/site-packages/transformers/utils/generic.py", line 1083, in wrapper
    outputs = func(self, *args, **kwargs)
  File "/u/svcndifuser/miniconda3/lib/python3.10/site-packages/transformers/models/llama/modeling_llama.py", line 390, in forward
    hidden_states = decoder_layer(
  File "/u/svcndifuser/miniconda3/lib/python3.10/site-packages/transformers/modeling_layers.py", line 94, in __call__
    return super().__call__(*args, **kwargs)
  File "/u/svcndifuser/miniconda3/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1751, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/u/svcndifuser/miniconda3/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1857, in _call_impl
    return inner()
  File "/u/svcndifuser/miniconda3/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1805, in inner
    result = forward_call(*args, **kwargs)
  File "/u/svcndifuser/miniconda3/lib/python3.10/site-packages/nnsight/intervention/interleaver.py", line 133, in skippable_forward
    return forward(*args, **kwargs)
  File "/u/svcndifuser/miniconda3/lib/python3.10/site-packages/transformers/models/llama/modeling_llama.py", line 289, in forward
    hidden_states, _ = self.self_attn(
  File "/u/svcndifuser/miniconda3/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1751, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/u/svcndifuser/miniconda3/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1857, in _call_impl
    return inner()
  File "/u/svcndifuser/miniconda3/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1805, in inner
    result = forward_call(*args, **kwargs)
  File "/u/svcndifuser/miniconda3/lib/python3.10/site-packages/nnsight/intervention/interleaver.py", line 133, in skippable_forward
    return forward(*args, **kwargs)
  File "/u/svcndifuser/miniconda3/lib/python3.10/site-packages/transformers/models/llama/modeling_llama.py", line 242, in forward
    key_states, value_states = past_key_value.update(key_states, value_states, self.layer_idx, cache_kwargs)
  File "/u/svcndifuser/miniconda3/lib/python3.10/site-packages/transformers/cache_utils.py", line 992, in _wrapped_update
    key_tensors, value_tensors = fn(self, key_states, value_states, layer_idx, cache_kwargs)
  File "/u/svcndifuser/miniconda3/lib/python3.10/site-packages/transformers/cache_utils.py", line 1201, in update
    return self.layers[layer_idx].update(key_states, value_states, cache_kwargs)
  File "/u/svcndifuser/miniconda3/lib/python3.10/site-packages/transformers/cache_utils.py", line 103, in update
    self.values = torch.cat([self.values, value_states], dim=-2)

OutOfMemoryError: CUDA out of memory. Tried to allocate 174.00 MiB. GPU 0 has a total capacity of 44.34 GiB of which 152.81 MiB is free. Including non-PyTorch memory, this process has 44.18 GiB memory in use. Of the allocated memory 40.44 GiB is allocated by PyTorch, and 3.43 GiB is reserved by PyTorch but unallocated. If reserved but unallocated memory is large try setting PYTORCH_CUDA_ALLOC_CONF=expandable_segments:True to avoid fragmentation.  See documentation for Memory Management  (https://pytorch.org/docs/stable/notes/cuda.html#environment-variables)



Traceback (most recent call last):
  File "/u/svcndifuser/ndif-deployment/repos/prod/ndif/src/services/ray/src/ray/nn/sandbox.py", line 14, in run
    tracer.execute(fn)
  File "/u/svcndifuser/miniconda3/lib/python3.10/site-packages/nnsight/intervention/tracing/tracer.py", line 385, in execute
    self.model.interleave(self.fn, *args, **kwargs)
  File "/u/svcndifuser/miniconda3/lib/python3.10/site-packages/nnsight/modeling/mixins/meta.py", line 76, in interleave
    return super().interleave(fn, *args, **kwargs)
  File "/u/svcndifuser/miniconda3/lib/python3.10/site-packages/nnsight/intervention/envoy.py", line 733, in interleave
    fn(*args, **kwargs)
  File "/u/svcndifuser/miniconda3/lib/python3.10/site-packages/nnsight/modeling/language.py", line 173, in __nnsight_generate__
    output = self._model.generate(*args, streamer=streamer, **kwargs)
  File "/u/svcndifuser/miniconda3/lib/python3.10/site-packages/torch/utils/_contextlib.py", line 116, in decorate_context
    return func(*args, **kwargs)
  File "/u/svcndifuser/miniconda3/lib/python3.10/site-packages/transformers/generation/utils.py", line 2629, in generate
    result = self._sample(
  File "/u/svcndifuser/miniconda3/lib/python3.10/site-packages/transformers/generation/utils.py", line 3613, in _sample
    outputs = model_forward(**model_inputs, return_dict=True)
  File "/u/svcndifuser/miniconda3/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1751, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/u/svcndifuser/miniconda3/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1857, in _call_impl
    return inner()
  File "/u/svcndifuser/miniconda3/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1805, in inner
    result = forward_call(*args, **kwargs)
  File "/u/svcndifuser/miniconda3/lib/python3.10/site-packages/nnsight/intervention/interleaver.py", line 133, in skippable_forward
    return forward(*args, **kwargs)
  File "/u/svcndifuser/miniconda3/lib/python3.10/site-packages/transformers/utils/generic.py", line 959, in wrapper
    output = func(self, *args, **kwargs)
  File "/u/svcndifuser/miniconda3/lib/python3.10/site-packages/transformers/models/llama/modeling_llama.py", line 460, in forward
    outputs: BaseModelOutputWithPast = self.model(
  File "/u/svcndifuser/miniconda3/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1751, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/u/svcndifuser/miniconda3/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1857, in _call_impl
    return inner()
  File "/u/svcndifuser/miniconda3/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1805, in inner
    result = forward_call(*args, **kwargs)
  File "/u/svcndifuser/miniconda3/lib/python3.10/site-packages/nnsight/intervention/interleaver.py", line 133, in skippable_forward
    return forward(*args, **kwargs)
  File "/u/svcndifuser/miniconda3/lib/python3.10/site-packages/transformers/utils/generic.py", line 1083, in wrapper
    outputs = func(self, *args, **kwargs)
  File "/u/svcndifuser/miniconda3/lib/python3.10/site-packages/transformers/models/llama/modeling_llama.py", line 390, in forward
    hidden_states = decoder_layer(
  File "/u/svcndifuser/miniconda3/lib/python3.10/site-packages/transformers/modeling_layers.py", line 94, in __call__
    return super().__call__(*args, **kwargs)
  File "/u/svcndifuser/miniconda3/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1751, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/u/svcndifuser/miniconda3/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1857, in _call_impl
    return inner()
  File "/u/svcndifuser/miniconda3/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1805, in inner
    result = forward_call(*args, **kwargs)
  File "/u/svcndifuser/miniconda3/lib/python3.10/site-packages/nnsight/intervention/interleaver.py", line 133, in skippable_forward
    return forward(*args, **kwargs)
  File "/u/svcndifuser/miniconda3/lib/python3.10/site-packages/transformers/models/llama/modeling_llama.py", line 289, in forward
    hidden_states, _ = self.self_attn(
  File "/u/svcndifuser/miniconda3/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1751, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/u/svcndifuser/miniconda3/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1857, in _call_impl
    return inner()
  File "/u/svcndifuser/miniconda3/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1805, in inner
    result = forward_call(*args, **kwargs)
  File "/u/svcndifuser/miniconda3/lib/python3.10/site-packages/nnsight/intervention/interleaver.py", line 133, in skippable_forward
    return forward(*args, **kwargs)
  File "/u/svcndifuser/miniconda3/lib/python3.10/site-packages/transformers/models/llama/modeling_llama.py", line 242, in forward
    key_states, value_states = past_key_value.update(key_states, value_states, self.layer_idx, cache_kwargs)
  File "/u/svcndifuser/miniconda3/lib/python3.10/site-packages/transformers/cache_utils.py", line 992, in _wrapped_update
    key_tensors, value_tensors = fn(self, key_states, value_states, layer_idx, cache_kwargs)
  File "/u/svcndifuser/miniconda3/lib/python3.10/site-packages/transformers/cache_utils.py", line 1201, in update
    return self.layers[layer_idx].update(key_states, value_states, cache_kwargs)
  File "/u/svcndifuser/miniconda3/lib/python3.10/site-packages/transformers/cache_utils.py", line 103, in update
    self.values = torch.cat([self.values, value_states], dim=-2)

OutOfMemoryError: CUDA out of memory. Tried to allocate 174.00 MiB. GPU 0 has a total capacity of 44.34 GiB of which 152.81 MiB is free. Including non-PyTorch memory, this process has 44.18 GiB memory in use. Of the allocated memory 40.44 GiB is allocated by PyTorch, and 3.43 GiB is reserved by PyTorch but unallocated. If reserved but unallocated memory is large try setting PYTORCH_CUDA_ALLOC_CONF=expandable_segments:True to avoid fragmentation.  See documentation for Memory Management  (https://pytorch.org/docs/stable/notes/cuda.html#environment-variables)
Remote exception.

[2025-08-29 18:28:30] [d195ac4d-3cb8-432d-a650-2b2d4054ec9a] RECEIVED   : Your job has been received and is waiting to be queued.
[2025-08-29 18:28:30] [d195ac4d-3cb8-432d-a650-2b2d4054ec9a] QUEUED     : Your job has been recieved by the coordinator and is waiting to be queued.
[2025-08-29 18:28:30] [d195ac4d-3cb8-432d-a650-2b2d4054ec9a] QUEUED     : Task d195ac4d-3cb8-432d-a650-2b2d4054ec9a has been added to the queue. Currently at position 1
[2025-08-29 18:28:30] [d195ac4d-3cb8-432d-a650-2b2d4054ec9a] QUEUED     : Dispatching task...
[2025-08-29 18:28:30] [d195ac4d-3cb8-432d-a650-2b2d4054ec9a] RUNNING    : Your job has started running.

Error on problem 190: Traceback (most recent call last):
  File "/u/svcndifuser/ndif-deployment/repos/prod/ndif/src/services/ray/src/ray/deployments/modeling/base.py", line 213, in __call__
    result = await job_task
  File "/u/svcndifuser/miniconda3/lib/python3.10/asyncio/threads.py", line 25, in to_thread
    return await loop.run_in_executor(None, func_call)
  File "/u/svcndifuser/miniconda3/lib/python3.10/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/u/svcndifuser/miniconda3/lib/python3.10/site-packages/ray/util/tracing/tracing_helper.py", line 463, in _resume_span
    return method(self, *_args, **_kwargs)
  File "/u/svcndifuser/ndif-deployment/repos/prod/ndif/src/services/ray/src/ray/deployments/modeling/base.py", line 283, in execute
    result = RemoteExecutionBackend(request.interventions, self.execution_protector)(request.tracer)
  File "/u/svcndifuser/ndif-deployment/repos/prod/ndif/src/services/ray/src/ray/nn/backend.py", line 27, in __call__
    run(tracer, self.fn)
  File "/u/svcndifuser/ndif-deployment/repos/prod/ndif/src/services/ray/src/ray/nn/sandbox.py", line 16, in run
    raise wrap_exception(e,tracer.info) from None
nnsight.NNsightException:

Traceback (most recent call last):
  File "/u/svcndifuser/ndif-deployment/repos/prod/ndif/src/services/ray/src/ray/nn/sandbox.py", line 14, in run
    tracer.execute(fn)
  File "/u/svcndifuser/miniconda3/lib/python3.10/site-packages/nnsight/intervention/tracing/tracer.py", line 385, in execute
    self.model.interleave(self.fn, *args, **kwargs)
  File "/u/svcndifuser/miniconda3/lib/python3.10/site-packages/nnsight/modeling/mixins/meta.py", line 76, in interleave
    return super().interleave(fn, *args, **kwargs)
  File "/u/svcndifuser/miniconda3/lib/python3.10/site-packages/nnsight/intervention/envoy.py", line 733, in interleave
    fn(*args, **kwargs)
  File "/u/svcndifuser/miniconda3/lib/python3.10/site-packages/nnsight/modeling/language.py", line 173, in __nnsight_generate__
    output = self._model.generate(*args, streamer=streamer, **kwargs)
  File "/u/svcndifuser/miniconda3/lib/python3.10/site-packages/torch/utils/_contextlib.py", line 116, in decorate_context
    return func(*args, **kwargs)
  File "/u/svcndifuser/miniconda3/lib/python3.10/site-packages/transformers/generation/utils.py", line 2629, in generate
    result = self._sample(
  File "/u/svcndifuser/miniconda3/lib/python3.10/site-packages/transformers/generation/utils.py", line 3613, in _sample
    outputs = model_forward(**model_inputs, return_dict=True)
  File "/u/svcndifuser/miniconda3/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1751, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/u/svcndifuser/miniconda3/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1857, in _call_impl
    return inner()
  File "/u/svcndifuser/miniconda3/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1805, in inner
    result = forward_call(*args, **kwargs)
  File "/u/svcndifuser/miniconda3/lib/python3.10/site-packages/nnsight/intervention/interleaver.py", line 133, in skippable_forward
    return forward(*args, **kwargs)
  File "/u/svcndifuser/miniconda3/lib/python3.10/site-packages/transformers/utils/generic.py", line 959, in wrapper
    output = func(self, *args, **kwargs)
  File "/u/svcndifuser/miniconda3/lib/python3.10/site-packages/transformers/models/llama/modeling_llama.py", line 460, in forward
    outputs: BaseModelOutputWithPast = self.model(
  File "/u/svcndifuser/miniconda3/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1751, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/u/svcndifuser/miniconda3/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1857, in _call_impl
    return inner()
  File "/u/svcndifuser/miniconda3/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1805, in inner
    result = forward_call(*args, **kwargs)
  File "/u/svcndifuser/miniconda3/lib/python3.10/site-packages/nnsight/intervention/interleaver.py", line 133, in skippable_forward
    return forward(*args, **kwargs)
  File "/u/svcndifuser/miniconda3/lib/python3.10/site-packages/transformers/utils/generic.py", line 1083, in wrapper
    outputs = func(self, *args, **kwargs)
  File "/u/svcndifuser/miniconda3/lib/python3.10/site-packages/transformers/models/llama/modeling_llama.py", line 390, in forward
    hidden_states = decoder_layer(
  File "/u/svcndifuser/miniconda3/lib/python3.10/site-packages/transformers/modeling_layers.py", line 94, in __call__
    return super().__call__(*args, **kwargs)
  File "/u/svcndifuser/miniconda3/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1751, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/u/svcndifuser/miniconda3/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1857, in _call_impl
    return inner()
  File "/u/svcndifuser/miniconda3/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1805, in inner
    result = forward_call(*args, **kwargs)
  File "/u/svcndifuser/miniconda3/lib/python3.10/site-packages/nnsight/intervention/interleaver.py", line 133, in skippable_forward
    return forward(*args, **kwargs)
  File "/u/svcndifuser/miniconda3/lib/python3.10/site-packages/transformers/models/llama/modeling_llama.py", line 289, in forward
    hidden_states, _ = self.self_attn(
  File "/u/svcndifuser/miniconda3/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1751, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/u/svcndifuser/miniconda3/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1857, in _call_impl
    return inner()
  File "/u/svcndifuser/miniconda3/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1805, in inner
    result = forward_call(*args, **kwargs)
  File "/u/svcndifuser/miniconda3/lib/python3.10/site-packages/nnsight/intervention/interleaver.py", line 133, in skippable_forward
    return forward(*args, **kwargs)
  File "/u/svcndifuser/miniconda3/lib/python3.10/site-packages/transformers/models/llama/modeling_llama.py", line 242, in forward
    key_states, value_states = past_key_value.update(key_states, value_states, self.layer_idx, cache_kwargs)
  File "/u/svcndifuser/miniconda3/lib/python3.10/site-packages/transformers/cache_utils.py", line 992, in _wrapped_update
    key_tensors, value_tensors = fn(self, key_states, value_states, layer_idx, cache_kwargs)
  File "/u/svcndifuser/miniconda3/lib/python3.10/site-packages/transformers/cache_utils.py", line 1201, in update
    return self.layers[layer_idx].update(key_states, value_states, cache_kwargs)
  File "/u/svcndifuser/miniconda3/lib/python3.10/site-packages/transformers/cache_utils.py", line 102, in update
    self.keys = torch.cat([self.keys, key_states], dim=-2)

OutOfMemoryError: CUDA out of memory. Tried to allocate 28.00 MiB. GPU 0 has a total capacity of 44.34 GiB of which 8.81 MiB is free. Including non-PyTorch memory, this process has 44.32 GiB memory in use. Of the allocated memory 41.67 GiB is allocated by PyTorch, and 2.33 GiB is reserved by PyTorch but unallocated. If reserved but unallocated memory is large try setting PYTORCH_CUDA_ALLOC_CONF=expandable_segments:True to avoid fragmentation.  See documentation for Memory Management  (https://pytorch.org/docs/stable/notes/cuda.html#environment-variables)



Traceback (most recent call last):
  File "/u/svcndifuser/ndif-deployment/repos/prod/ndif/src/services/ray/src/ray/nn/sandbox.py", line 14, in run
    tracer.execute(fn)
  File "/u/svcndifuser/miniconda3/lib/python3.10/site-packages/nnsight/intervention/tracing/tracer.py", line 385, in execute
    self.model.interleave(self.fn, *args, **kwargs)
  File "/u/svcndifuser/miniconda3/lib/python3.10/site-packages/nnsight/modeling/mixins/meta.py", line 76, in interleave
    return super().interleave(fn, *args, **kwargs)
  File "/u/svcndifuser/miniconda3/lib/python3.10/site-packages/nnsight/intervention/envoy.py", line 733, in interleave
    fn(*args, **kwargs)
  File "/u/svcndifuser/miniconda3/lib/python3.10/site-packages/nnsight/modeling/language.py", line 173, in __nnsight_generate__
    output = self._model.generate(*args, streamer=streamer, **kwargs)
  File "/u/svcndifuser/miniconda3/lib/python3.10/site-packages/torch/utils/_contextlib.py", line 116, in decorate_context
    return func(*args, **kwargs)
  File "/u/svcndifuser/miniconda3/lib/python3.10/site-packages/transformers/generation/utils.py", line 2629, in generate
    result = self._sample(
  File "/u/svcndifuser/miniconda3/lib/python3.10/site-packages/transformers/generation/utils.py", line 3613, in _sample
    outputs = model_forward(**model_inputs, return_dict=True)
  File "/u/svcndifuser/miniconda3/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1751, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/u/svcndifuser/miniconda3/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1857, in _call_impl
    return inner()
  File "/u/svcndifuser/miniconda3/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1805, in inner
    result = forward_call(*args, **kwargs)
  File "/u/svcndifuser/miniconda3/lib/python3.10/site-packages/nnsight/intervention/interleaver.py", line 133, in skippable_forward
    return forward(*args, **kwargs)
  File "/u/svcndifuser/miniconda3/lib/python3.10/site-packages/transformers/utils/generic.py", line 959, in wrapper
    output = func(self, *args, **kwargs)
  File "/u/svcndifuser/miniconda3/lib/python3.10/site-packages/transformers/models/llama/modeling_llama.py", line 460, in forward
    outputs: BaseModelOutputWithPast = self.model(
  File "/u/svcndifuser/miniconda3/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1751, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/u/svcndifuser/miniconda3/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1857, in _call_impl
    return inner()
  File "/u/svcndifuser/miniconda3/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1805, in inner
    result = forward_call(*args, **kwargs)
  File "/u/svcndifuser/miniconda3/lib/python3.10/site-packages/nnsight/intervention/interleaver.py", line 133, in skippable_forward
    return forward(*args, **kwargs)
  File "/u/svcndifuser/miniconda3/lib/python3.10/site-packages/transformers/utils/generic.py", line 1083, in wrapper
    outputs = func(self, *args, **kwargs)
  File "/u/svcndifuser/miniconda3/lib/python3.10/site-packages/transformers/models/llama/modeling_llama.py", line 390, in forward
    hidden_states = decoder_layer(
  File "/u/svcndifuser/miniconda3/lib/python3.10/site-packages/transformers/modeling_layers.py", line 94, in __call__
    return super().__call__(*args, **kwargs)
  File "/u/svcndifuser/miniconda3/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1751, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/u/svcndifuser/miniconda3/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1857, in _call_impl
    return inner()
  File "/u/svcndifuser/miniconda3/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1805, in inner
    result = forward_call(*args, **kwargs)
  File "/u/svcndifuser/miniconda3/lib/python3.10/site-packages/nnsight/intervention/interleaver.py", line 133, in skippable_forward
    return forward(*args, **kwargs)
  File "/u/svcndifuser/miniconda3/lib/python3.10/site-packages/transformers/models/llama/modeling_llama.py", line 289, in forward
    hidden_states, _ = self.self_attn(
  File "/u/svcndifuser/miniconda3/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1751, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/u/svcndifuser/miniconda3/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1857, in _call_impl
    return inner()
  File "/u/svcndifuser/miniconda3/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1805, in inner
    result = forward_call(*args, **kwargs)
  File "/u/svcndifuser/miniconda3/lib/python3.10/site-packages/nnsight/intervention/interleaver.py", line 133, in skippable_forward
    return forward(*args, **kwargs)
  File "/u/svcndifuser/miniconda3/lib/python3.10/site-packages/transformers/models/llama/modeling_llama.py", line 242, in forward
    key_states, value_states = past_key_value.update(key_states, value_states, self.layer_idx, cache_kwargs)
  File "/u/svcndifuser/miniconda3/lib/python3.10/site-packages/transformers/cache_utils.py", line 992, in _wrapped_update
    key_tensors, value_tensors = fn(self, key_states, value_states, layer_idx, cache_kwargs)
  File "/u/svcndifuser/miniconda3/lib/python3.10/site-packages/transformers/cache_utils.py", line 1201, in update
    return self.layers[layer_idx].update(key_states, value_states, cache_kwargs)
  File "/u/svcndifuser/miniconda3/lib/python3.10/site-packages/transformers/cache_utils.py", line 102, in update
    self.keys = torch.cat([self.keys, key_states], dim=-2)

OutOfMemoryError: CUDA out of memory. Tried to allocate 28.00 MiB. GPU 0 has a total capacity of 44.34 GiB of which 8.81 MiB is free. Including non-PyTorch memory, this process has 44.32 GiB memory in use. Of the allocated memory 41.67 GiB is allocated by PyTorch, and 2.33 GiB is reserved by PyTorch but unallocated. If reserved but unallocated memory is large try setting PYTORCH_CUDA_ALLOC_CONF=expandable_segments:True to avoid fragmentation.  See documentation for Memory Management  (https://pytorch.org/docs/stable/notes/cuda.html#environment-variables)
Remote exception.

[2025-08-29 18:28:49] [809bd286-25ab-4fb1-b13e-1c9f34570a8c] RECEIVED   : Your job has been received and is waiting to be queued.
[2025-08-29 18:28:49] [809bd286-25ab-4fb1-b13e-1c9f34570a8c] QUEUED     : Your job has been recieved by the coordinator and is waiting to be queued.
[2025-08-29 18:28:49] [809bd286-25ab-4fb1-b13e-1c9f34570a8c] QUEUED     : Task 809bd286-25ab-4fb1-b13e-1c9f34570a8c has been added to the queue. Currently at position 1
[2025-08-29 18:28:49] [809bd286-25ab-4fb1-b13e-1c9f34570a8c] QUEUED     : Dispatching task...
[2025-08-29 18:28:50] [809bd286-25ab-4fb1-b13e-1c9f34570a8c] RUNNING    : Your job has started running.
[2025-08-29 18:29:14] [809bd286-25ab-4fb1-b13e-1c9f34570a8c] COMPLETED  : Your job has been completed.

Downloading result:   0%|          | 0.00/145M [00:00<?, ?B/s]

[2025-08-29 18:29:26] [620cab28-4aae-407b-85ba-67c940cbb9c7] RECEIVED   : Your job has been received and is waiting to be queued.
[2025-08-29 18:29:26] [620cab28-4aae-407b-85ba-67c940cbb9c7] QUEUED     : Your job has been recieved by the coordinator and is waiting to be queued.
[2025-08-29 18:29:26] [620cab28-4aae-407b-85ba-67c940cbb9c7] QUEUED     : Task 620cab28-4aae-407b-85ba-67c940cbb9c7 has been added to the queue. Currently at position 1
[2025-08-29 18:29:26] [620cab28-4aae-407b-85ba-67c940cbb9c7] QUEUED     : Dispatching task...
[2025-08-29 18:29:26] [620cab28-4aae-407b-85ba-67c940cbb9c7] RUNNING    : Your job has started running.
[2025-08-29 18:32:00] [620cab28-4aae-407b-85ba-67c940cbb9c7] COMPLETED  : Your job has been completed.

Downloading result:   0%|          | 0.00/611M [00:00<?, ?B/s]

[2025-08-29 18:32:23] [96de07de-6322-4b4b-9e15-3a67a0e39853] RECEIVED   : Your job has been received and is waiting to be queued.
[2025-08-29 18:32:23] [96de07de-6322-4b4b-9e15-3a67a0e39853] QUEUED     : Your job has been recieved by the coordinator and is waiting to be queued.
[2025-08-29 18:32:23] [96de07de-6322-4b4b-9e15-3a67a0e39853] QUEUED     : Task 96de07de-6322-4b4b-9e15-3a67a0e39853 has been added to the queue. Currently at position 1
[2025-08-29 18:32:23] [96de07de-6322-4b4b-9e15-3a67a0e39853] QUEUED     : Dispatching task...
[2025-08-29 18:32:24] [96de07de-6322-4b4b-9e15-3a67a0e39853] RUNNING    : Your job has started running.
[2025-08-29 18:34:37] [96de07de-6322-4b4b-9e15-3a67a0e39853] COMPLETED  : Your job has been completed.

Downloading result:   0%|          | 0.00/557M [00:00<?, ?B/s]

[2025-08-29 18:35:01] [c7c40317-9eed-4413-b72d-bfb18c3c065a] RECEIVED   : Your job has been received and is waiting to be queued.
[2025-08-29 18:35:01] [c7c40317-9eed-4413-b72d-bfb18c3c065a] QUEUED     : Your job has been recieved by the coordinator and is waiting to be queued.
[2025-08-29 18:35:01] [c7c40317-9eed-4413-b72d-bfb18c3c065a] QUEUED     : Task c7c40317-9eed-4413-b72d-bfb18c3c065a has been added to the queue. Currently at position 1
[2025-08-29 18:35:01] [c7c40317-9eed-4413-b72d-bfb18c3c065a] QUEUED     : Dispatching task...
[2025-08-29 18:35:02] [c7c40317-9eed-4413-b72d-bfb18c3c065a] RUNNING    : Your job has started running.
[2025-08-29 18:37:35] [c7c40317-9eed-4413-b72d-bfb18c3c065a] COMPLETED  : Your job has been completed.

Downloading result:   0%|          | 0.00/611M [00:00<?, ?B/s]

[2025-08-29 18:37:58] [98844644-de4a-4147-9077-aa49305d63e7] RECEIVED   : Your job has been received and is waiting to be queued.
[2025-08-29 18:37:58] [98844644-de4a-4147-9077-aa49305d63e7] QUEUED     : Your job has been recieved by the coordinator and is waiting to be queued.
[2025-08-29 18:37:58] [98844644-de4a-4147-9077-aa49305d63e7] QUEUED     : Task 98844644-de4a-4147-9077-aa49305d63e7 has been added to the queue. Currently at position 1
[2025-08-29 18:37:58] [98844644-de4a-4147-9077-aa49305d63e7] QUEUED     : Dispatching task...
[2025-08-29 18:37:58] [98844644-de4a-4147-9077-aa49305d63e7] RUNNING    : Your job has started running.
[2025-08-29 18:40:33] [98844644-de4a-4147-9077-aa49305d63e7] COMPLETED  : Your job has been completed.

Downloading result:   0%|          | 0.00/615M [00:00<?, ?B/s]

[2025-08-29 18:40:56] [da7da968-7d8d-4275-9298-b8ab720c2134] RECEIVED   : Your job has been received and is waiting to be queued.
[2025-08-29 18:40:56] [da7da968-7d8d-4275-9298-b8ab720c2134] QUEUED     : Your job has been recieved by the coordinator and is waiting to be queued.
[2025-08-29 18:40:56] [da7da968-7d8d-4275-9298-b8ab720c2134] QUEUED     : Task da7da968-7d8d-4275-9298-b8ab720c2134 has been added to the queue. Currently at position 1
[2025-08-29 18:40:56] [da7da968-7d8d-4275-9298-b8ab720c2134] QUEUED     : Dispatching task...
[2025-08-29 18:40:57] [da7da968-7d8d-4275-9298-b8ab720c2134] RUNNING    : Your job has started running.
[2025-08-29 18:41:27] [da7da968-7d8d-4275-9298-b8ab720c2134] COMPLETED  : Your job has been completed.

Downloading result:   0%|          | 0.00/167M [00:00<?, ?B/s]

[2025-08-29 18:41:35] [a572c440-7105-449e-9b1b-65c1d8d3bfe8] RECEIVED   : Your job has been received and is waiting to be queued.
[2025-08-29 18:41:35] [a572c440-7105-449e-9b1b-65c1d8d3bfe8] QUEUED     : Your job has been recieved by the coordinator and is waiting to be queued.
[2025-08-29 18:41:35] [a572c440-7105-449e-9b1b-65c1d8d3bfe8] QUEUED     : Task a572c440-7105-449e-9b1b-65c1d8d3bfe8 has been added to the queue. Currently at position 1
[2025-08-29 18:41:35] [a572c440-7105-449e-9b1b-65c1d8d3bfe8] QUEUED     : Dispatching task...
[2025-08-29 18:41:35] [a572c440-7105-449e-9b1b-65c1d8d3bfe8] RUNNING    : Your job has started running.
[2025-08-29 18:44:10] [a572c440-7105-449e-9b1b-65c1d8d3bfe8] COMPLETED  : Your job has been completed.

Downloading result:   0%|          | 0.00/619M [00:00<?, ?B/s]

[2025-08-29 18:44:34] [12f7abfc-6963-4fda-bc12-394f34eef35a] RECEIVED   : Your job has been received and is waiting to be queued.
[2025-08-29 18:44:34] [12f7abfc-6963-4fda-bc12-394f34eef35a] QUEUED     : Your job has been recieved by the coordinator and is waiting to be queued.
[2025-08-29 18:44:34] [12f7abfc-6963-4fda-bc12-394f34eef35a] QUEUED     : Task 12f7abfc-6963-4fda-bc12-394f34eef35a has been added to the queue. Currently at position 1
[2025-08-29 18:44:34] [12f7abfc-6963-4fda-bc12-394f34eef35a] QUEUED     : Dispatching task...
[2025-08-29 18:44:34] [12f7abfc-6963-4fda-bc12-394f34eef35a] RUNNING    : Your job has started running.
[2025-08-29 18:45:09] [12f7abfc-6963-4fda-bc12-394f34eef35a] COMPLETED  : Your job has been completed.

Downloading result:   0%|          | 0.00/196M [00:00<?, ?B/s]

[2025-08-29 18:45:17] [116a9985-97be-402d-867c-cffdd7eb786b] RECEIVED   : Your job has been received and is waiting to be queued.
[2025-08-29 18:45:17] [116a9985-97be-402d-867c-cffdd7eb786b] QUEUED     : Your job has been recieved by the coordinator and is waiting to be queued.
[2025-08-29 18:45:17] [116a9985-97be-402d-867c-cffdd7eb786b] QUEUED     : Task 116a9985-97be-402d-867c-cffdd7eb786b has been added to the queue. Currently at position 1
[2025-08-29 18:45:17] [116a9985-97be-402d-867c-cffdd7eb786b] QUEUED     : Dispatching task...
[2025-08-29 18:45:17] [116a9985-97be-402d-867c-cffdd7eb786b] RUNNING    : Your job has started running.
[2025-08-29 18:45:51] [116a9985-97be-402d-867c-cffdd7eb786b] COMPLETED  : Your job has been completed.

Downloading result:   0%|          | 0.00/193M [00:00<?, ?B/s]

[2025-08-29 18:46:00] [67219d3f-5ca2-4f0d-80a0-fc08ac835dcd] RECEIVED   : Your job has been received and is waiting to be queued.
[2025-08-29 18:46:00] [67219d3f-5ca2-4f0d-80a0-fc08ac835dcd] QUEUED     : Your job has been recieved by the coordinator and is waiting to be queued.
[2025-08-29 18:46:00] [67219d3f-5ca2-4f0d-80a0-fc08ac835dcd] QUEUED     : Task 67219d3f-5ca2-4f0d-80a0-fc08ac835dcd has been added to the queue. Currently at position 1
[2025-08-29 18:46:00] [67219d3f-5ca2-4f0d-80a0-fc08ac835dcd] QUEUED     : Dispatching task...
[2025-08-29 18:46:00] [67219d3f-5ca2-4f0d-80a0-fc08ac835dcd] RUNNING    : Your job has started running.
[2025-08-29 18:47:07] [67219d3f-5ca2-4f0d-80a0-fc08ac835dcd] COMPLETED  : Your job has been completed.

Downloading result:   0%|          | 0.00/330M [00:00<?, ?B/s]

[2025-08-29 18:47:21] [272975a5-fd46-4977-a1dc-f0fc7b2719c8] RECEIVED   : Your job has been received and is waiting to be queued.
[2025-08-29 18:47:21] [272975a5-fd46-4977-a1dc-f0fc7b2719c8] QUEUED     : Your job has been recieved by the coordinator and is waiting to be queued.
[2025-08-29 18:47:21] [272975a5-fd46-4977-a1dc-f0fc7b2719c8] QUEUED     : Task 272975a5-fd46-4977-a1dc-f0fc7b2719c8 has been added to the queue. Currently at position 1
[2025-08-29 18:47:21] [272975a5-fd46-4977-a1dc-f0fc7b2719c8] QUEUED     : Dispatching task...
[2025-08-29 18:47:21] [272975a5-fd46-4977-a1dc-f0fc7b2719c8] RUNNING    : Your job has started running.
[2025-08-29 18:49:57] [272975a5-fd46-4977-a1dc-f0fc7b2719c8] COMPLETED  : Your job has been completed.

Downloading result:   0%|          | 0.00/622M [00:00<?, ?B/s]

[2025-08-29 18:50:25] [b2da7c67-01ab-49ef-bc83-771a93954053] RECEIVED   : Your job has been received and is waiting to be queued.
[2025-08-29 18:50:25] [b2da7c67-01ab-49ef-bc83-771a93954053] QUEUED     : Your job has been recieved by the coordinator and is waiting to be queued.
[2025-08-29 18:50:25] [b2da7c67-01ab-49ef-bc83-771a93954053] QUEUED     : Task b2da7c67-01ab-49ef-bc83-771a93954053 has been added to the queue. Currently at position 1
[2025-08-29 18:50:25] [b2da7c67-01ab-49ef-bc83-771a93954053] QUEUED     : Dispatching task...
[2025-08-29 18:50:25] [b2da7c67-01ab-49ef-bc83-771a93954053] RUNNING    : Your job has started running.
[2025-08-29 18:52:05] [b2da7c67-01ab-49ef-bc83-771a93954053] COMPLETED  : Your job has been completed.

Downloading result:   0%|          | 0.00/458M [00:00<?, ?B/s]

[2025-08-29 18:52:33] [5fd16462-5e36-47d1-bca0-7ae941ed2936] RECEIVED   : Your job has been received and is waiting to be queued.
[2025-08-29 18:52:33] [5fd16462-5e36-47d1-bca0-7ae941ed2936] QUEUED     : Your job has been recieved by the coordinator and is waiting to be queued.
[2025-08-29 18:52:33] [5fd16462-5e36-47d1-bca0-7ae941ed2936] QUEUED     : Task 5fd16462-5e36-47d1-bca0-7ae941ed2936 has been added to the queue. Currently at position 1
[2025-08-29 18:52:33] [5fd16462-5e36-47d1-bca0-7ae941ed2936] QUEUED     : Dispatching task...
[2025-08-29 18:52:34] [5fd16462-5e36-47d1-bca0-7ae941ed2936] RUNNING    : Your job has started running.
[2025-08-29 18:55:08] [5fd16462-5e36-47d1-bca0-7ae941ed2936] COMPLETED  : Your job has been completed.

Downloading result:   0%|          | 0.00/616M [00:00<?, ?B/s]

[2025-08-29 18:55:31] [eed3a9ff-f345-4281-a699-4ed93c25c655] RECEIVED   : Your job has been received and is waiting to be queued.
[2025-08-29 18:55:31] [eed3a9ff-f345-4281-a699-4ed93c25c655] QUEUED     : Your job has been recieved by the coordinator and is waiting to be queued.
[2025-08-29 18:55:31] [eed3a9ff-f345-4281-a699-4ed93c25c655] QUEUED     : Task eed3a9ff-f345-4281-a699-4ed93c25c655 has been added to the queue. Currently at position 1
[2025-08-29 18:55:31] [eed3a9ff-f345-4281-a699-4ed93c25c655] QUEUED     : Dispatching task...
[2025-08-29 18:55:32] [eed3a9ff-f345-4281-a699-4ed93c25c655] RUNNING    : Your job has started running.

Error on problem 204: Traceback (most recent call last):
  File "/u/svcndifuser/ndif-deployment/repos/prod/ndif/src/services/ray/src/ray/deployments/modeling/base.py", line 213, in __call__
    result = await job_task
  File "/u/svcndifuser/miniconda3/lib/python3.10/asyncio/threads.py", line 25, in to_thread
    return await loop.run_in_executor(None, func_call)
  File "/u/svcndifuser/miniconda3/lib/python3.10/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/u/svcndifuser/miniconda3/lib/python3.10/site-packages/ray/util/tracing/tracing_helper.py", line 463, in _resume_span
    return method(self, *_args, **_kwargs)
  File "/u/svcndifuser/ndif-deployment/repos/prod/ndif/src/services/ray/src/ray/deployments/modeling/base.py", line 283, in execute
    result = RemoteExecutionBackend(request.interventions, self.execution_protector)(request.tracer)
  File "/u/svcndifuser/ndif-deployment/repos/prod/ndif/src/services/ray/src/ray/nn/backend.py", line 27, in __call__
    run(tracer, self.fn)
  File "/u/svcndifuser/ndif-deployment/repos/prod/ndif/src/services/ray/src/ray/nn/sandbox.py", line 16, in run
    raise wrap_exception(e,tracer.info) from None
nnsight.NNsightException:

Traceback (most recent call last):
  File "/u/svcndifuser/ndif-deployment/repos/prod/ndif/src/services/ray/src/ray/nn/sandbox.py", line 14, in run
    tracer.execute(fn)
  File "/u/svcndifuser/miniconda3/lib/python3.10/site-packages/nnsight/intervention/tracing/tracer.py", line 385, in execute
    self.model.interleave(self.fn, *args, **kwargs)
  File "/u/svcndifuser/miniconda3/lib/python3.10/site-packages/nnsight/modeling/mixins/meta.py", line 76, in interleave
    return super().interleave(fn, *args, **kwargs)
  File "/u/svcndifuser/miniconda3/lib/python3.10/site-packages/nnsight/intervention/envoy.py", line 733, in interleave
    fn(*args, **kwargs)
  File "/u/svcndifuser/miniconda3/lib/python3.10/site-packages/nnsight/modeling/language.py", line 173, in __nnsight_generate__
    output = self._model.generate(*args, streamer=streamer, **kwargs)
  File "/u/svcndifuser/miniconda3/lib/python3.10/site-packages/torch/utils/_contextlib.py", line 116, in decorate_context
    return func(*args, **kwargs)
  File "/u/svcndifuser/miniconda3/lib/python3.10/site-packages/transformers/generation/utils.py", line 2629, in generate
    result = self._sample(
  File "/u/svcndifuser/miniconda3/lib/python3.10/site-packages/transformers/generation/utils.py", line 3613, in _sample
    outputs = model_forward(**model_inputs, return_dict=True)
  File "/u/svcndifuser/miniconda3/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1751, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/u/svcndifuser/miniconda3/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1857, in _call_impl
    return inner()
  File "/u/svcndifuser/miniconda3/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1805, in inner
    result = forward_call(*args, **kwargs)
  File "/u/svcndifuser/miniconda3/lib/python3.10/site-packages/nnsight/intervention/interleaver.py", line 133, in skippable_forward
    return forward(*args, **kwargs)
  File "/u/svcndifuser/miniconda3/lib/python3.10/site-packages/transformers/utils/generic.py", line 959, in wrapper
    output = func(self, *args, **kwargs)
  File "/u/svcndifuser/miniconda3/lib/python3.10/site-packages/transformers/models/llama/modeling_llama.py", line 460, in forward
    outputs: BaseModelOutputWithPast = self.model(
  File "/u/svcndifuser/miniconda3/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1751, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/u/svcndifuser/miniconda3/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1857, in _call_impl
    return inner()
  File "/u/svcndifuser/miniconda3/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1805, in inner
    result = forward_call(*args, **kwargs)
  File "/u/svcndifuser/miniconda3/lib/python3.10/site-packages/nnsight/intervention/interleaver.py", line 133, in skippable_forward
    return forward(*args, **kwargs)
  File "/u/svcndifuser/miniconda3/lib/python3.10/site-packages/transformers/utils/generic.py", line 1083, in wrapper
    outputs = func(self, *args, **kwargs)
  File "/u/svcndifuser/miniconda3/lib/python3.10/site-packages/transformers/models/llama/modeling_llama.py", line 390, in forward
    hidden_states = decoder_layer(
  File "/u/svcndifuser/miniconda3/lib/python3.10/site-packages/transformers/modeling_layers.py", line 94, in __call__
    return super().__call__(*args, **kwargs)
  File "/u/svcndifuser/miniconda3/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1751, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/u/svcndifuser/miniconda3/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1857, in _call_impl
    return inner()
  File "/u/svcndifuser/miniconda3/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1805, in inner
    result = forward_call(*args, **kwargs)
  File "/u/svcndifuser/miniconda3/lib/python3.10/site-packages/nnsight/intervention/interleaver.py", line 133, in skippable_forward
    return forward(*args, **kwargs)
  File "/u/svcndifuser/miniconda3/lib/python3.10/site-packages/transformers/models/llama/modeling_llama.py", line 289, in forward
    hidden_states, _ = self.self_attn(
  File "/u/svcndifuser/miniconda3/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1751, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/u/svcndifuser/miniconda3/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1857, in _call_impl
    return inner()
  File "/u/svcndifuser/miniconda3/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1805, in inner
    result = forward_call(*args, **kwargs)
  File "/u/svcndifuser/miniconda3/lib/python3.10/site-packages/nnsight/intervention/interleaver.py", line 133, in skippable_forward
    return forward(*args, **kwargs)
  File "/u/svcndifuser/miniconda3/lib/python3.10/site-packages/transformers/models/llama/modeling_llama.py", line 242, in forward
    key_states, value_states = past_key_value.update(key_states, value_states, self.layer_idx, cache_kwargs)
  File "/u/svcndifuser/miniconda3/lib/python3.10/site-packages/transformers/cache_utils.py", line 992, in _wrapped_update
    key_tensors, value_tensors = fn(self, key_states, value_states, layer_idx, cache_kwargs)
  File "/u/svcndifuser/miniconda3/lib/python3.10/site-packages/transformers/cache_utils.py", line 1201, in update
    return self.layers[layer_idx].update(key_states, value_states, cache_kwargs)
  File "/u/svcndifuser/miniconda3/lib/python3.10/site-packages/transformers/cache_utils.py", line 102, in update
    self.keys = torch.cat([self.keys, key_states], dim=-2)

OutOfMemoryError: CUDA out of memory. Tried to allocate 148.00 MiB. GPU 0 has a total capacity of 44.34 GiB of which 146.81 MiB is free. Including non-PyTorch memory, this process has 44.19 GiB memory in use. Of the allocated memory 41.48 GiB is allocated by PyTorch, and 2.39 GiB is reserved by PyTorch but unallocated. If reserved but unallocated memory is large try setting PYTORCH_CUDA_ALLOC_CONF=expandable_segments:True to avoid fragmentation.  See documentation for Memory Management  (https://pytorch.org/docs/stable/notes/cuda.html#environment-variables)



Traceback (most recent call last):
  File "/u/svcndifuser/ndif-deployment/repos/prod/ndif/src/services/ray/src/ray/nn/sandbox.py", line 14, in run
    tracer.execute(fn)
  File "/u/svcndifuser/miniconda3/lib/python3.10/site-packages/nnsight/intervention/tracing/tracer.py", line 385, in execute
    self.model.interleave(self.fn, *args, **kwargs)
  File "/u/svcndifuser/miniconda3/lib/python3.10/site-packages/nnsight/modeling/mixins/meta.py", line 76, in interleave
    return super().interleave(fn, *args, **kwargs)
  File "/u/svcndifuser/miniconda3/lib/python3.10/site-packages/nnsight/intervention/envoy.py", line 733, in interleave
    fn(*args, **kwargs)
  File "/u/svcndifuser/miniconda3/lib/python3.10/site-packages/nnsight/modeling/language.py", line 173, in __nnsight_generate__
    output = self._model.generate(*args, streamer=streamer, **kwargs)
  File "/u/svcndifuser/miniconda3/lib/python3.10/site-packages/torch/utils/_contextlib.py", line 116, in decorate_context
    return func(*args, **kwargs)
  File "/u/svcndifuser/miniconda3/lib/python3.10/site-packages/transformers/generation/utils.py", line 2629, in generate
    result = self._sample(
  File "/u/svcndifuser/miniconda3/lib/python3.10/site-packages/transformers/generation/utils.py", line 3613, in _sample
    outputs = model_forward(**model_inputs, return_dict=True)
  File "/u/svcndifuser/miniconda3/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1751, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/u/svcndifuser/miniconda3/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1857, in _call_impl
    return inner()
  File "/u/svcndifuser/miniconda3/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1805, in inner
    result = forward_call(*args, **kwargs)
  File "/u/svcndifuser/miniconda3/lib/python3.10/site-packages/nnsight/intervention/interleaver.py", line 133, in skippable_forward
    return forward(*args, **kwargs)
  File "/u/svcndifuser/miniconda3/lib/python3.10/site-packages/transformers/utils/generic.py", line 959, in wrapper
    output = func(self, *args, **kwargs)
  File "/u/svcndifuser/miniconda3/lib/python3.10/site-packages/transformers/models/llama/modeling_llama.py", line 460, in forward
    outputs: BaseModelOutputWithPast = self.model(
  File "/u/svcndifuser/miniconda3/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1751, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/u/svcndifuser/miniconda3/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1857, in _call_impl
    return inner()
  File "/u/svcndifuser/miniconda3/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1805, in inner
    result = forward_call(*args, **kwargs)
  File "/u/svcndifuser/miniconda3/lib/python3.10/site-packages/nnsight/intervention/interleaver.py", line 133, in skippable_forward
    return forward(*args, **kwargs)
  File "/u/svcndifuser/miniconda3/lib/python3.10/site-packages/transformers/utils/generic.py", line 1083, in wrapper
    outputs = func(self, *args, **kwargs)
  File "/u/svcndifuser/miniconda3/lib/python3.10/site-packages/transformers/models/llama/modeling_llama.py", line 390, in forward
    hidden_states = decoder_layer(
  File "/u/svcndifuser/miniconda3/lib/python3.10/site-packages/transformers/modeling_layers.py", line 94, in __call__
    return super().__call__(*args, **kwargs)
  File "/u/svcndifuser/miniconda3/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1751, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/u/svcndifuser/miniconda3/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1857, in _call_impl
    return inner()
  File "/u/svcndifuser/miniconda3/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1805, in inner
    result = forward_call(*args, **kwargs)
  File "/u/svcndifuser/miniconda3/lib/python3.10/site-packages/nnsight/intervention/interleaver.py", line 133, in skippable_forward
    return forward(*args, **kwargs)
  File "/u/svcndifuser/miniconda3/lib/python3.10/site-packages/transformers/models/llama/modeling_llama.py", line 289, in forward
    hidden_states, _ = self.self_attn(
  File "/u/svcndifuser/miniconda3/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1751, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/u/svcndifuser/miniconda3/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1857, in _call_impl
    return inner()
  File "/u/svcndifuser/miniconda3/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1805, in inner
    result = forward_call(*args, **kwargs)
  File "/u/svcndifuser/miniconda3/lib/python3.10/site-packages/nnsight/intervention/interleaver.py", line 133, in skippable_forward
    return forward(*args, **kwargs)
  File "/u/svcndifuser/miniconda3/lib/python3.10/site-packages/transformers/models/llama/modeling_llama.py", line 242, in forward
    key_states, value_states = past_key_value.update(key_states, value_states, self.layer_idx, cache_kwargs)
  File "/u/svcndifuser/miniconda3/lib/python3.10/site-packages/transformers/cache_utils.py", line 992, in _wrapped_update
    key_tensors, value_tensors = fn(self, key_states, value_states, layer_idx, cache_kwargs)
  File "/u/svcndifuser/miniconda3/lib/python3.10/site-packages/transformers/cache_utils.py", line 1201, in update
    return self.layers[layer_idx].update(key_states, value_states, cache_kwargs)
  File "/u/svcndifuser/miniconda3/lib/python3.10/site-packages/transformers/cache_utils.py", line 102, in update
    self.keys = torch.cat([self.keys, key_states], dim=-2)

OutOfMemoryError: CUDA out of memory. Tried to allocate 148.00 MiB. GPU 0 has a total capacity of 44.34 GiB of which 146.81 MiB is free. Including non-PyTorch memory, this process has 44.19 GiB memory in use. Of the allocated memory 41.48 GiB is allocated by PyTorch, and 2.39 GiB is reserved by PyTorch but unallocated. If reserved but unallocated memory is large try setting PYTORCH_CUDA_ALLOC_CONF=expandable_segments:True to avoid fragmentation.  See documentation for Memory Management  (https://pytorch.org/docs/stable/notes/cuda.html#environment-variables)
Remote exception.

[2025-08-29 18:58:04] [d47abb06-d750-4765-a9bf-8ef62dc6ca5a] RECEIVED   : Your job has been received and is waiting to be queued.
[2025-08-29 18:58:04] [d47abb06-d750-4765-a9bf-8ef62dc6ca5a] QUEUED     : Your job has been recieved by the coordinator and is waiting to be queued.
[2025-08-29 18:58:04] [d47abb06-d750-4765-a9bf-8ef62dc6ca5a] QUEUED     : Task d47abb06-d750-4765-a9bf-8ef62dc6ca5a has been added to the queue. Currently at position 1
[2025-08-29 18:58:04] [d47abb06-d750-4765-a9bf-8ef62dc6ca5a] QUEUED     : Dispatching task...
[2025-08-29 18:58:04] [d47abb06-d750-4765-a9bf-8ef62dc6ca5a] RUNNING    : Your job has started running.

Error on problem 205: Traceback (most recent call last):
  File "/u/svcndifuser/ndif-deployment/repos/prod/ndif/src/services/ray/src/ray/deployments/modeling/base.py", line 213, in __call__
    result = await job_task
  File "/u/svcndifuser/miniconda3/lib/python3.10/asyncio/threads.py", line 25, in to_thread
    return await loop.run_in_executor(None, func_call)
  File "/u/svcndifuser/miniconda3/lib/python3.10/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/u/svcndifuser/miniconda3/lib/python3.10/site-packages/ray/util/tracing/tracing_helper.py", line 463, in _resume_span
    return method(self, *_args, **_kwargs)
  File "/u/svcndifuser/ndif-deployment/repos/prod/ndif/src/services/ray/src/ray/deployments/modeling/base.py", line 283, in execute
    result = RemoteExecutionBackend(request.interventions, self.execution_protector)(request.tracer)
  File "/u/svcndifuser/ndif-deployment/repos/prod/ndif/src/services/ray/src/ray/nn/backend.py", line 27, in __call__
    run(tracer, self.fn)
  File "/u/svcndifuser/ndif-deployment/repos/prod/ndif/src/services/ray/src/ray/nn/sandbox.py", line 16, in run
    raise wrap_exception(e,tracer.info) from None
nnsight.NNsightException:

Traceback (most recent call last):
  File "/u/svcndifuser/ndif-deployment/repos/prod/ndif/src/services/ray/src/ray/nn/sandbox.py", line 14, in run
    tracer.execute(fn)
  File "/u/svcndifuser/miniconda3/lib/python3.10/site-packages/nnsight/intervention/tracing/tracer.py", line 385, in execute
    self.model.interleave(self.fn, *args, **kwargs)
  File "/u/svcndifuser/miniconda3/lib/python3.10/site-packages/nnsight/modeling/mixins/meta.py", line 76, in interleave
    return super().interleave(fn, *args, **kwargs)
  File "/u/svcndifuser/miniconda3/lib/python3.10/site-packages/nnsight/intervention/envoy.py", line 733, in interleave
    fn(*args, **kwargs)
  File "/u/svcndifuser/miniconda3/lib/python3.10/site-packages/nnsight/modeling/language.py", line 173, in __nnsight_generate__
    output = self._model.generate(*args, streamer=streamer, **kwargs)
  File "/u/svcndifuser/miniconda3/lib/python3.10/site-packages/torch/utils/_contextlib.py", line 116, in decorate_context
    return func(*args, **kwargs)
  File "/u/svcndifuser/miniconda3/lib/python3.10/site-packages/transformers/generation/utils.py", line 2629, in generate
    result = self._sample(
  File "/u/svcndifuser/miniconda3/lib/python3.10/site-packages/transformers/generation/utils.py", line 3610, in _sample
    outputs = self(**model_inputs, return_dict=True)
  File "/u/svcndifuser/miniconda3/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1751, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/u/svcndifuser/miniconda3/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1857, in _call_impl
    return inner()
  File "/u/svcndifuser/miniconda3/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1805, in inner
    result = forward_call(*args, **kwargs)
  File "/u/svcndifuser/miniconda3/lib/python3.10/site-packages/nnsight/intervention/interleaver.py", line 133, in skippable_forward
    return forward(*args, **kwargs)
  File "/u/svcndifuser/miniconda3/lib/python3.10/site-packages/transformers/utils/generic.py", line 959, in wrapper
    output = func(self, *args, **kwargs)
  File "/u/svcndifuser/miniconda3/lib/python3.10/site-packages/transformers/models/llama/modeling_llama.py", line 460, in forward
    outputs: BaseModelOutputWithPast = self.model(
  File "/u/svcndifuser/miniconda3/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1751, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/u/svcndifuser/miniconda3/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1857, in _call_impl
    return inner()
  File "/u/svcndifuser/miniconda3/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1805, in inner
    result = forward_call(*args, **kwargs)
  File "/u/svcndifuser/miniconda3/lib/python3.10/site-packages/nnsight/intervention/interleaver.py", line 133, in skippable_forward
    return forward(*args, **kwargs)
  File "/u/svcndifuser/miniconda3/lib/python3.10/site-packages/transformers/utils/generic.py", line 1083, in wrapper
    outputs = func(self, *args, **kwargs)
  File "/u/svcndifuser/miniconda3/lib/python3.10/site-packages/transformers/models/llama/modeling_llama.py", line 390, in forward
    hidden_states = decoder_layer(
  File "/u/svcndifuser/miniconda3/lib/python3.10/site-packages/transformers/modeling_layers.py", line 94, in __call__
    return super().__call__(*args, **kwargs)
  File "/u/svcndifuser/miniconda3/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1751, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/u/svcndifuser/miniconda3/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1857, in _call_impl
    return inner()
  File "/u/svcndifuser/miniconda3/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1805, in inner
    result = forward_call(*args, **kwargs)
  File "/u/svcndifuser/miniconda3/lib/python3.10/site-packages/nnsight/intervention/interleaver.py", line 133, in skippable_forward
    return forward(*args, **kwargs)
  File "/u/svcndifuser/miniconda3/lib/python3.10/site-packages/transformers/models/llama/modeling_llama.py", line 304, in forward
    hidden_states = self.mlp(hidden_states)
  File "/u/svcndifuser/miniconda3/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1751, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/u/svcndifuser/miniconda3/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1857, in _call_impl
    return inner()
  File "/u/svcndifuser/miniconda3/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1805, in inner
    result = forward_call(*args, **kwargs)
  File "/u/svcndifuser/miniconda3/lib/python3.10/site-packages/nnsight/intervention/interleaver.py", line 133, in skippable_forward
    return forward(*args, **kwargs)
  File "/u/svcndifuser/miniconda3/lib/python3.10/site-packages/transformers/models/llama/modeling_llama.py", line 152, in forward
    down_proj = self.down_proj(self.act_fn(self.gate_proj(x)) * self.up_proj(x))

OutOfMemoryError: CUDA out of memory. Tried to allocate 184.00 MiB. GPU 0 has a total capacity of 44.34 GiB of which 146.81 MiB is free. Including non-PyTorch memory, this process has 44.19 GiB memory in use. Of the allocated memory 41.78 GiB is allocated by PyTorch, and 2.09 GiB is reserved by PyTorch but unallocated. If reserved but unallocated memory is large try setting PYTORCH_CUDA_ALLOC_CONF=expandable_segments:True to avoid fragmentation.  See documentation for Memory Management  (https://pytorch.org/docs/stable/notes/cuda.html#environment-variables)



Traceback (most recent call last):
  File "/u/svcndifuser/ndif-deployment/repos/prod/ndif/src/services/ray/src/ray/nn/sandbox.py", line 14, in run
    tracer.execute(fn)
  File "/u/svcndifuser/miniconda3/lib/python3.10/site-packages/nnsight/intervention/tracing/tracer.py", line 385, in execute
    self.model.interleave(self.fn, *args, **kwargs)
  File "/u/svcndifuser/miniconda3/lib/python3.10/site-packages/nnsight/modeling/mixins/meta.py", line 76, in interleave
    return super().interleave(fn, *args, **kwargs)
  File "/u/svcndifuser/miniconda3/lib/python3.10/site-packages/nnsight/intervention/envoy.py", line 733, in interleave
    fn(*args, **kwargs)
  File "/u/svcndifuser/miniconda3/lib/python3.10/site-packages/nnsight/modeling/language.py", line 173, in __nnsight_generate__
    output = self._model.generate(*args, streamer=streamer, **kwargs)
  File "/u/svcndifuser/miniconda3/lib/python3.10/site-packages/torch/utils/_contextlib.py", line 116, in decorate_context
    return func(*args, **kwargs)
  File "/u/svcndifuser/miniconda3/lib/python3.10/site-packages/transformers/generation/utils.py", line 2629, in generate
    result = self._sample(
  File "/u/svcndifuser/miniconda3/lib/python3.10/site-packages/transformers/generation/utils.py", line 3610, in _sample
    outputs = self(**model_inputs, return_dict=True)
  File "/u/svcndifuser/miniconda3/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1751, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/u/svcndifuser/miniconda3/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1857, in _call_impl
    return inner()
  File "/u/svcndifuser/miniconda3/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1805, in inner
    result = forward_call(*args, **kwargs)
  File "/u/svcndifuser/miniconda3/lib/python3.10/site-packages/nnsight/intervention/interleaver.py", line 133, in skippable_forward
    return forward(*args, **kwargs)
  File "/u/svcndifuser/miniconda3/lib/python3.10/site-packages/transformers/utils/generic.py", line 959, in wrapper
    output = func(self, *args, **kwargs)
  File "/u/svcndifuser/miniconda3/lib/python3.10/site-packages/transformers/models/llama/modeling_llama.py", line 460, in forward
    outputs: BaseModelOutputWithPast = self.model(
  File "/u/svcndifuser/miniconda3/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1751, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/u/svcndifuser/miniconda3/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1857, in _call_impl
    return inner()
  File "/u/svcndifuser/miniconda3/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1805, in inner
    result = forward_call(*args, **kwargs)
  File "/u/svcndifuser/miniconda3/lib/python3.10/site-packages/nnsight/intervention/interleaver.py", line 133, in skippable_forward
    return forward(*args, **kwargs)
  File "/u/svcndifuser/miniconda3/lib/python3.10/site-packages/transformers/utils/generic.py", line 1083, in wrapper
    outputs = func(self, *args, **kwargs)
  File "/u/svcndifuser/miniconda3/lib/python3.10/site-packages/transformers/models/llama/modeling_llama.py", line 390, in forward
    hidden_states = decoder_layer(
  File "/u/svcndifuser/miniconda3/lib/python3.10/site-packages/transformers/modeling_layers.py", line 94, in __call__
    return super().__call__(*args, **kwargs)
  File "/u/svcndifuser/miniconda3/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1751, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/u/svcndifuser/miniconda3/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1857, in _call_impl
    return inner()
  File "/u/svcndifuser/miniconda3/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1805, in inner
    result = forward_call(*args, **kwargs)
  File "/u/svcndifuser/miniconda3/lib/python3.10/site-packages/nnsight/intervention/interleaver.py", line 133, in skippable_forward
    return forward(*args, **kwargs)
  File "/u/svcndifuser/miniconda3/lib/python3.10/site-packages/transformers/models/llama/modeling_llama.py", line 304, in forward
    hidden_states = self.mlp(hidden_states)
  File "/u/svcndifuser/miniconda3/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1751, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/u/svcndifuser/miniconda3/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1857, in _call_impl
    return inner()
  File "/u/svcndifuser/miniconda3/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1805, in inner
    result = forward_call(*args, **kwargs)
  File "/u/svcndifuser/miniconda3/lib/python3.10/site-packages/nnsight/intervention/interleaver.py", line 133, in skippable_forward
    return forward(*args, **kwargs)
  File "/u/svcndifuser/miniconda3/lib/python3.10/site-packages/transformers/models/llama/modeling_llama.py", line 152, in forward
    down_proj = self.down_proj(self.act_fn(self.gate_proj(x)) * self.up_proj(x))

OutOfMemoryError: CUDA out of memory. Tried to allocate 184.00 MiB. GPU 0 has a total capacity of 44.34 GiB of which 146.81 MiB is free. Including non-PyTorch memory, this process has 44.19 GiB memory in use. Of the allocated memory 41.78 GiB is allocated by PyTorch, and 2.09 GiB is reserved by PyTorch but unallocated. If reserved but unallocated memory is large try setting PYTORCH_CUDA_ALLOC_CONF=expandable_segments:True to avoid fragmentation.  See documentation for Memory Management  (https://pytorch.org/docs/stable/notes/cuda.html#environment-variables)
Remote exception.

[2025-08-29 18:58:06] [1e1b6851-3065-42a6-bcbd-4b827792b65b] RECEIVED   : Your job has been received and is waiting to be queued.
[2025-08-29 18:58:06] [1e1b6851-3065-42a6-bcbd-4b827792b65b] QUEUED     : Your job has been recieved by the coordinator and is waiting to be queued.
[2025-08-29 18:58:06] [1e1b6851-3065-42a6-bcbd-4b827792b65b] QUEUED     : Task 1e1b6851-3065-42a6-bcbd-4b827792b65b has been added to the queue. Currently at position 1
[2025-08-29 18:58:06] [1e1b6851-3065-42a6-bcbd-4b827792b65b] QUEUED     : Dispatching task...
[2025-08-29 18:58:06] [1e1b6851-3065-42a6-bcbd-4b827792b65b] RUNNING    : Your job has started running.
[2025-08-29 18:59:46] [1e1b6851-3065-42a6-bcbd-4b827792b65b] COMPLETED  : Your job has been completed.

Downloading result:   0%|          | 0.00/459M [00:00<?, ?B/s]

[2025-08-29 19:00:03] [8b515071-b842-45ba-be69-65d0f701dbe6] RECEIVED   : Your job has been received and is waiting to be queued.
[2025-08-29 19:00:03] [8b515071-b842-45ba-be69-65d0f701dbe6] QUEUED     : Your job has been recieved by the coordinator and is waiting to be queued.
[2025-08-29 19:00:03] [8b515071-b842-45ba-be69-65d0f701dbe6] QUEUED     : Task 8b515071-b842-45ba-be69-65d0f701dbe6 has been added to the queue. Currently at position 1
[2025-08-29 19:00:04] [8b515071-b842-45ba-be69-65d0f701dbe6] QUEUED     : Dispatching task...
[2025-08-29 19:00:04] [8b515071-b842-45ba-be69-65d0f701dbe6] RUNNING    : Your job has started running.
[2025-08-29 19:00:42] [8b515071-b842-45ba-be69-65d0f701dbe6] COMPLETED  : Your job has been completed.

Downloading result:   0%|          | 0.00/212M [00:00<?, ?B/s]

[2025-08-29 19:00:51] [4e59dbfb-caa3-476f-bb25-cbcecab879d6] RECEIVED   : Your job has been received and is waiting to be queued.
[2025-08-29 19:00:51] [4e59dbfb-caa3-476f-bb25-cbcecab879d6] QUEUED     : Your job has been recieved by the coordinator and is waiting to be queued.
[2025-08-29 19:00:51] [4e59dbfb-caa3-476f-bb25-cbcecab879d6] QUEUED     : Task 4e59dbfb-caa3-476f-bb25-cbcecab879d6 has been added to the queue. Currently at position 1
[2025-08-29 19:00:51] [4e59dbfb-caa3-476f-bb25-cbcecab879d6] QUEUED     : Dispatching task...
[2025-08-29 19:00:52] [4e59dbfb-caa3-476f-bb25-cbcecab879d6] RUNNING    : Your job has started running.
[2025-08-29 19:01:44] [4e59dbfb-caa3-476f-bb25-cbcecab879d6] COMPLETED  : Your job has been completed.

Downloading result:   0%|          | 0.00/276M [00:00<?, ?B/s]

[2025-08-29 19:01:58] [138eb0cf-051b-4fba-a1da-6bc6ff2487a9] RECEIVED   : Your job has been received and is waiting to be queued.
[2025-08-29 19:01:58] [138eb0cf-051b-4fba-a1da-6bc6ff2487a9] QUEUED     : Your job has been recieved by the coordinator and is waiting to be queued.
[2025-08-29 19:01:58] [138eb0cf-051b-4fba-a1da-6bc6ff2487a9] QUEUED     : Task 138eb0cf-051b-4fba-a1da-6bc6ff2487a9 has been added to the queue. Currently at position 1
[2025-08-29 19:01:58] [138eb0cf-051b-4fba-a1da-6bc6ff2487a9] QUEUED     : Dispatching task...
[2025-08-29 19:01:58] [138eb0cf-051b-4fba-a1da-6bc6ff2487a9] RUNNING    : Your job has started running.

Error on problem 209: Traceback (most recent call last):
  File "/u/svcndifuser/ndif-deployment/repos/prod/ndif/src/services/ray/src/ray/deployments/modeling/base.py", line 213, in __call__
    result = await job_task
  File "/u/svcndifuser/miniconda3/lib/python3.10/asyncio/threads.py", line 25, in to_thread
    return await loop.run_in_executor(None, func_call)
  File "/u/svcndifuser/miniconda3/lib/python3.10/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/u/svcndifuser/miniconda3/lib/python3.10/site-packages/ray/util/tracing/tracing_helper.py", line 463, in _resume_span
    return method(self, *_args, **_kwargs)
  File "/u/svcndifuser/ndif-deployment/repos/prod/ndif/src/services/ray/src/ray/deployments/modeling/base.py", line 283, in execute
    result = RemoteExecutionBackend(request.interventions, self.execution_protector)(request.tracer)
  File "/u/svcndifuser/ndif-deployment/repos/prod/ndif/src/services/ray/src/ray/nn/backend.py", line 27, in __call__
    run(tracer, self.fn)
  File "/u/svcndifuser/ndif-deployment/repos/prod/ndif/src/services/ray/src/ray/nn/sandbox.py", line 16, in run
    raise wrap_exception(e,tracer.info) from None
nnsight.NNsightException:

Traceback (most recent call last):
  File "/u/svcndifuser/ndif-deployment/repos/prod/ndif/src/services/ray/src/ray/nn/sandbox.py", line 14, in run
    tracer.execute(fn)
  File "/u/svcndifuser/miniconda3/lib/python3.10/site-packages/nnsight/intervention/tracing/tracer.py", line 385, in execute
    self.model.interleave(self.fn, *args, **kwargs)
  File "/u/svcndifuser/miniconda3/lib/python3.10/site-packages/nnsight/modeling/mixins/meta.py", line 76, in interleave
    return super().interleave(fn, *args, **kwargs)
  File "/u/svcndifuser/miniconda3/lib/python3.10/site-packages/nnsight/intervention/envoy.py", line 733, in interleave
    fn(*args, **kwargs)
  File "/u/svcndifuser/miniconda3/lib/python3.10/site-packages/nnsight/modeling/language.py", line 173, in __nnsight_generate__
    output = self._model.generate(*args, streamer=streamer, **kwargs)
  File "/u/svcndifuser/miniconda3/lib/python3.10/site-packages/torch/utils/_contextlib.py", line 116, in decorate_context
    return func(*args, **kwargs)
  File "/u/svcndifuser/miniconda3/lib/python3.10/site-packages/transformers/generation/utils.py", line 2629, in generate
    result = self._sample(
  File "/u/svcndifuser/miniconda3/lib/python3.10/site-packages/transformers/generation/utils.py", line 3613, in _sample
    outputs = model_forward(**model_inputs, return_dict=True)
  File "/u/svcndifuser/miniconda3/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1751, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/u/svcndifuser/miniconda3/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1857, in _call_impl
    return inner()
  File "/u/svcndifuser/miniconda3/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1805, in inner
    result = forward_call(*args, **kwargs)
  File "/u/svcndifuser/miniconda3/lib/python3.10/site-packages/nnsight/intervention/interleaver.py", line 133, in skippable_forward
    return forward(*args, **kwargs)
  File "/u/svcndifuser/miniconda3/lib/python3.10/site-packages/transformers/utils/generic.py", line 959, in wrapper
    output = func(self, *args, **kwargs)
  File "/u/svcndifuser/miniconda3/lib/python3.10/site-packages/transformers/models/llama/modeling_llama.py", line 460, in forward
    outputs: BaseModelOutputWithPast = self.model(
  File "/u/svcndifuser/miniconda3/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1751, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/u/svcndifuser/miniconda3/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1857, in _call_impl
    return inner()
  File "/u/svcndifuser/miniconda3/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1805, in inner
    result = forward_call(*args, **kwargs)
  File "/u/svcndifuser/miniconda3/lib/python3.10/site-packages/nnsight/intervention/interleaver.py", line 133, in skippable_forward
    return forward(*args, **kwargs)
  File "/u/svcndifuser/miniconda3/lib/python3.10/site-packages/transformers/utils/generic.py", line 1083, in wrapper
    outputs = func(self, *args, **kwargs)
  File "/u/svcndifuser/miniconda3/lib/python3.10/site-packages/transformers/models/llama/modeling_llama.py", line 390, in forward
    hidden_states = decoder_layer(
  File "/u/svcndifuser/miniconda3/lib/python3.10/site-packages/transformers/modeling_layers.py", line 94, in __call__
    return super().__call__(*args, **kwargs)
  File "/u/svcndifuser/miniconda3/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1751, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/u/svcndifuser/miniconda3/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1857, in _call_impl
    return inner()
  File "/u/svcndifuser/miniconda3/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1805, in inner
    result = forward_call(*args, **kwargs)
  File "/u/svcndifuser/miniconda3/lib/python3.10/site-packages/nnsight/intervention/interleaver.py", line 133, in skippable_forward
    return forward(*args, **kwargs)
  File "/u/svcndifuser/miniconda3/lib/python3.10/site-packages/transformers/models/llama/modeling_llama.py", line 289, in forward
    hidden_states, _ = self.self_attn(
  File "/u/svcndifuser/miniconda3/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1751, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/u/svcndifuser/miniconda3/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1857, in _call_impl
    return inner()
  File "/u/svcndifuser/miniconda3/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1805, in inner
    result = forward_call(*args, **kwargs)
  File "/u/svcndifuser/miniconda3/lib/python3.10/site-packages/nnsight/intervention/interleaver.py", line 133, in skippable_forward
    return forward(*args, **kwargs)
  File "/u/svcndifuser/miniconda3/lib/python3.10/site-packages/transformers/models/llama/modeling_llama.py", line 242, in forward
    key_states, value_states = past_key_value.update(key_states, value_states, self.layer_idx, cache_kwargs)
  File "/u/svcndifuser/miniconda3/lib/python3.10/site-packages/transformers/cache_utils.py", line 992, in _wrapped_update
    key_tensors, value_tensors = fn(self, key_states, value_states, layer_idx, cache_kwargs)
  File "/u/svcndifuser/miniconda3/lib/python3.10/site-packages/transformers/cache_utils.py", line 1201, in update
    return self.layers[layer_idx].update(key_states, value_states, cache_kwargs)
  File "/u/svcndifuser/miniconda3/lib/python3.10/site-packages/transformers/cache_utils.py", line 102, in update
    self.keys = torch.cat([self.keys, key_states], dim=-2)

OutOfMemoryError: CUDA out of memory. Tried to allocate 136.00 MiB. GPU 0 has a total capacity of 44.34 GiB of which 134.81 MiB is free. Including non-PyTorch memory, this process has 44.20 GiB memory in use. Of the allocated memory 41.44 GiB is allocated by PyTorch, and 2.45 GiB is reserved by PyTorch but unallocated. If reserved but unallocated memory is large try setting PYTORCH_CUDA_ALLOC_CONF=expandable_segments:True to avoid fragmentation.  See documentation for Memory Management  (https://pytorch.org/docs/stable/notes/cuda.html#environment-variables)



Traceback (most recent call last):
  File "/u/svcndifuser/ndif-deployment/repos/prod/ndif/src/services/ray/src/ray/nn/sandbox.py", line 14, in run
    tracer.execute(fn)
  File "/u/svcndifuser/miniconda3/lib/python3.10/site-packages/nnsight/intervention/tracing/tracer.py", line 385, in execute
    self.model.interleave(self.fn, *args, **kwargs)
  File "/u/svcndifuser/miniconda3/lib/python3.10/site-packages/nnsight/modeling/mixins/meta.py", line 76, in interleave
    return super().interleave(fn, *args, **kwargs)
  File "/u/svcndifuser/miniconda3/lib/python3.10/site-packages/nnsight/intervention/envoy.py", line 733, in interleave
    fn(*args, **kwargs)
  File "/u/svcndifuser/miniconda3/lib/python3.10/site-packages/nnsight/modeling/language.py", line 173, in __nnsight_generate__
    output = self._model.generate(*args, streamer=streamer, **kwargs)
  File "/u/svcndifuser/miniconda3/lib/python3.10/site-packages/torch/utils/_contextlib.py", line 116, in decorate_context
    return func(*args, **kwargs)
  File "/u/svcndifuser/miniconda3/lib/python3.10/site-packages/transformers/generation/utils.py", line 2629, in generate
    result = self._sample(
  File "/u/svcndifuser/miniconda3/lib/python3.10/site-packages/transformers/generation/utils.py", line 3613, in _sample
    outputs = model_forward(**model_inputs, return_dict=True)
  File "/u/svcndifuser/miniconda3/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1751, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/u/svcndifuser/miniconda3/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1857, in _call_impl
    return inner()
  File "/u/svcndifuser/miniconda3/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1805, in inner
    result = forward_call(*args, **kwargs)
  File "/u/svcndifuser/miniconda3/lib/python3.10/site-packages/nnsight/intervention/interleaver.py", line 133, in skippable_forward
    return forward(*args, **kwargs)
  File "/u/svcndifuser/miniconda3/lib/python3.10/site-packages/transformers/utils/generic.py", line 959, in wrapper
    output = func(self, *args, **kwargs)
  File "/u/svcndifuser/miniconda3/lib/python3.10/site-packages/transformers/models/llama/modeling_llama.py", line 460, in forward
    outputs: BaseModelOutputWithPast = self.model(
  File "/u/svcndifuser/miniconda3/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1751, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/u/svcndifuser/miniconda3/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1857, in _call_impl
    return inner()
  File "/u/svcndifuser/miniconda3/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1805, in inner
    result = forward_call(*args, **kwargs)
  File "/u/svcndifuser/miniconda3/lib/python3.10/site-packages/nnsight/intervention/interleaver.py", line 133, in skippable_forward
    return forward(*args, **kwargs)
  File "/u/svcndifuser/miniconda3/lib/python3.10/site-packages/transformers/utils/generic.py", line 1083, in wrapper
    outputs = func(self, *args, **kwargs)
  File "/u/svcndifuser/miniconda3/lib/python3.10/site-packages/transformers/models/llama/modeling_llama.py", line 390, in forward
    hidden_states = decoder_layer(
  File "/u/svcndifuser/miniconda3/lib/python3.10/site-packages/transformers/modeling_layers.py", line 94, in __call__
    return super().__call__(*args, **kwargs)
  File "/u/svcndifuser/miniconda3/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1751, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/u/svcndifuser/miniconda3/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1857, in _call_impl
    return inner()
  File "/u/svcndifuser/miniconda3/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1805, in inner
    result = forward_call(*args, **kwargs)
  File "/u/svcndifuser/miniconda3/lib/python3.10/site-packages/nnsight/intervention/interleaver.py", line 133, in skippable_forward
    return forward(*args, **kwargs)
  File "/u/svcndifuser/miniconda3/lib/python3.10/site-packages/transformers/models/llama/modeling_llama.py", line 289, in forward
    hidden_states, _ = self.self_attn(
  File "/u/svcndifuser/miniconda3/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1751, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/u/svcndifuser/miniconda3/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1857, in _call_impl
    return inner()
  File "/u/svcndifuser/miniconda3/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1805, in inner
    result = forward_call(*args, **kwargs)
  File "/u/svcndifuser/miniconda3/lib/python3.10/site-packages/nnsight/intervention/interleaver.py", line 133, in skippable_forward
    return forward(*args, **kwargs)
  File "/u/svcndifuser/miniconda3/lib/python3.10/site-packages/transformers/models/llama/modeling_llama.py", line 242, in forward
    key_states, value_states = past_key_value.update(key_states, value_states, self.layer_idx, cache_kwargs)
  File "/u/svcndifuser/miniconda3/lib/python3.10/site-packages/transformers/cache_utils.py", line 992, in _wrapped_update
    key_tensors, value_tensors = fn(self, key_states, value_states, layer_idx, cache_kwargs)
  File "/u/svcndifuser/miniconda3/lib/python3.10/site-packages/transformers/cache_utils.py", line 1201, in update
    return self.layers[layer_idx].update(key_states, value_states, cache_kwargs)
  File "/u/svcndifuser/miniconda3/lib/python3.10/site-packages/transformers/cache_utils.py", line 102, in update
    self.keys = torch.cat([self.keys, key_states], dim=-2)

OutOfMemoryError: CUDA out of memory. Tried to allocate 136.00 MiB. GPU 0 has a total capacity of 44.34 GiB of which 134.81 MiB is free. Including non-PyTorch memory, this process has 44.20 GiB memory in use. Of the allocated memory 41.44 GiB is allocated by PyTorch, and 2.45 GiB is reserved by PyTorch but unallocated. If reserved but unallocated memory is large try setting PYTORCH_CUDA_ALLOC_CONF=expandable_segments:True to avoid fragmentation.  See documentation for Memory Management  (https://pytorch.org/docs/stable/notes/cuda.html#environment-variables)
Remote exception.

[2025-08-29 19:04:13] [59afad8d-9814-432b-b698-7d909ef8b48c] RECEIVED   : Your job has been received and is waiting to be queued.
[2025-08-29 19:04:13] [59afad8d-9814-432b-b698-7d909ef8b48c] QUEUED     : Your job has been recieved by the coordinator and is waiting to be queued.
[2025-08-29 19:04:13] [59afad8d-9814-432b-b698-7d909ef8b48c] QUEUED     : Task 59afad8d-9814-432b-b698-7d909ef8b48c has been added to the queue. Currently at position 1
[2025-08-29 19:04:13] [59afad8d-9814-432b-b698-7d909ef8b48c] QUEUED     : Dispatching task...
[2025-08-29 19:04:14] [59afad8d-9814-432b-b698-7d909ef8b48c] RUNNING    : Your job has started running.

Error on problem 210: Traceback (most recent call last):
  File "/u/svcndifuser/ndif-deployment/repos/prod/ndif/src/services/ray/src/ray/deployments/modeling/base.py", line 213, in __call__
    result = await job_task
  File "/u/svcndifuser/miniconda3/lib/python3.10/asyncio/threads.py", line 25, in to_thread
    return await loop.run_in_executor(None, func_call)
  File "/u/svcndifuser/miniconda3/lib/python3.10/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/u/svcndifuser/miniconda3/lib/python3.10/site-packages/ray/util/tracing/tracing_helper.py", line 463, in _resume_span
    return method(self, *_args, **_kwargs)
  File "/u/svcndifuser/ndif-deployment/repos/prod/ndif/src/services/ray/src/ray/deployments/modeling/base.py", line 283, in execute
    result = RemoteExecutionBackend(request.interventions, self.execution_protector)(request.tracer)
  File "/u/svcndifuser/ndif-deployment/repos/prod/ndif/src/services/ray/src/ray/nn/backend.py", line 27, in __call__
    run(tracer, self.fn)
  File "/u/svcndifuser/ndif-deployment/repos/prod/ndif/src/services/ray/src/ray/nn/sandbox.py", line 16, in run
    raise wrap_exception(e,tracer.info) from None
nnsight.NNsightException:

Traceback (most recent call last):
  File "/u/svcndifuser/ndif-deployment/repos/prod/ndif/src/services/ray/src/ray/nn/sandbox.py", line 14, in run
    tracer.execute(fn)
  File "/u/svcndifuser/miniconda3/lib/python3.10/site-packages/nnsight/intervention/tracing/tracer.py", line 385, in execute
    self.model.interleave(self.fn, *args, **kwargs)
  File "/u/svcndifuser/miniconda3/lib/python3.10/site-packages/nnsight/modeling/mixins/meta.py", line 76, in interleave
    return super().interleave(fn, *args, **kwargs)
  File "/u/svcndifuser/miniconda3/lib/python3.10/site-packages/nnsight/intervention/envoy.py", line 733, in interleave
    fn(*args, **kwargs)
  File "/u/svcndifuser/miniconda3/lib/python3.10/site-packages/nnsight/modeling/language.py", line 173, in __nnsight_generate__
    output = self._model.generate(*args, streamer=streamer, **kwargs)
  File "/u/svcndifuser/miniconda3/lib/python3.10/site-packages/torch/utils/_contextlib.py", line 116, in decorate_context
    return func(*args, **kwargs)
  File "/u/svcndifuser/miniconda3/lib/python3.10/site-packages/transformers/generation/utils.py", line 2629, in generate
    result = self._sample(
  File "/u/svcndifuser/miniconda3/lib/python3.10/site-packages/transformers/generation/utils.py", line 3610, in _sample
    outputs = self(**model_inputs, return_dict=True)
  File "/u/svcndifuser/miniconda3/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1751, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/u/svcndifuser/miniconda3/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1857, in _call_impl
    return inner()
  File "/u/svcndifuser/miniconda3/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1805, in inner
    result = forward_call(*args, **kwargs)
  File "/u/svcndifuser/miniconda3/lib/python3.10/site-packages/nnsight/intervention/interleaver.py", line 133, in skippable_forward
    return forward(*args, **kwargs)
  File "/u/svcndifuser/miniconda3/lib/python3.10/site-packages/transformers/utils/generic.py", line 959, in wrapper
    output = func(self, *args, **kwargs)
  File "/u/svcndifuser/miniconda3/lib/python3.10/site-packages/transformers/models/llama/modeling_llama.py", line 460, in forward
    outputs: BaseModelOutputWithPast = self.model(
  File "/u/svcndifuser/miniconda3/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1751, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/u/svcndifuser/miniconda3/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1857, in _call_impl
    return inner()
  File "/u/svcndifuser/miniconda3/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1805, in inner
    result = forward_call(*args, **kwargs)
  File "/u/svcndifuser/miniconda3/lib/python3.10/site-packages/nnsight/intervention/interleaver.py", line 133, in skippable_forward
    return forward(*args, **kwargs)
  File "/u/svcndifuser/miniconda3/lib/python3.10/site-packages/transformers/utils/generic.py", line 1083, in wrapper
    outputs = func(self, *args, **kwargs)
  File "/u/svcndifuser/miniconda3/lib/python3.10/site-packages/transformers/models/llama/modeling_llama.py", line 390, in forward
    hidden_states = decoder_layer(
  File "/u/svcndifuser/miniconda3/lib/python3.10/site-packages/transformers/modeling_layers.py", line 94, in __call__
    return super().__call__(*args, **kwargs)
  File "/u/svcndifuser/miniconda3/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1751, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/u/svcndifuser/miniconda3/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1857, in _call_impl
    return inner()
  File "/u/svcndifuser/miniconda3/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1805, in inner
    result = forward_call(*args, **kwargs)
  File "/u/svcndifuser/miniconda3/lib/python3.10/site-packages/nnsight/intervention/interleaver.py", line 133, in skippable_forward
    return forward(*args, **kwargs)
  File "/u/svcndifuser/miniconda3/lib/python3.10/site-packages/transformers/models/llama/modeling_llama.py", line 303, in forward
    hidden_states = self.post_attention_layernorm(hidden_states)
  File "/u/svcndifuser/miniconda3/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1751, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/u/svcndifuser/miniconda3/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1857, in _call_impl
    return inner()
  File "/u/svcndifuser/miniconda3/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1805, in inner
    result = forward_call(*args, **kwargs)
  File "/u/svcndifuser/miniconda3/lib/python3.10/site-packages/nnsight/intervention/interleaver.py", line 133, in skippable_forward
    return forward(*args, **kwargs)
  File "/u/svcndifuser/miniconda3/lib/python3.10/site-packages/transformers/models/llama/modeling_llama.py", line 64, in forward
    variance = hidden_states.pow(2).mean(-1, keepdim=True)

OutOfMemoryError: CUDA out of memory. Tried to allocate 134.00 MiB. GPU 0 has a total capacity of 44.34 GiB of which 832.00 KiB is free. Including non-PyTorch memory, this process has 44.33 GiB memory in use. Of the allocated memory 41.73 GiB is allocated by PyTorch, and 2.28 GiB is reserved by PyTorch but unallocated. If reserved but unallocated memory is large try setting PYTORCH_CUDA_ALLOC_CONF=expandable_segments:True to avoid fragmentation.  See documentation for Memory Management  (https://pytorch.org/docs/stable/notes/cuda.html#environment-variables)



Traceback (most recent call last):
  File "/u/svcndifuser/ndif-deployment/repos/prod/ndif/src/services/ray/src/ray/nn/sandbox.py", line 14, in run
    tracer.execute(fn)
  File "/u/svcndifuser/miniconda3/lib/python3.10/site-packages/nnsight/intervention/tracing/tracer.py", line 385, in execute
    self.model.interleave(self.fn, *args, **kwargs)
  File "/u/svcndifuser/miniconda3/lib/python3.10/site-packages/nnsight/modeling/mixins/meta.py", line 76, in interleave
    return super().interleave(fn, *args, **kwargs)
  File "/u/svcndifuser/miniconda3/lib/python3.10/site-packages/nnsight/intervention/envoy.py", line 733, in interleave
    fn(*args, **kwargs)
  File "/u/svcndifuser/miniconda3/lib/python3.10/site-packages/nnsight/modeling/language.py", line 173, in __nnsight_generate__
    output = self._model.generate(*args, streamer=streamer, **kwargs)
  File "/u/svcndifuser/miniconda3/lib/python3.10/site-packages/torch/utils/_contextlib.py", line 116, in decorate_context
    return func(*args, **kwargs)
  File "/u/svcndifuser/miniconda3/lib/python3.10/site-packages/transformers/generation/utils.py", line 2629, in generate
    result = self._sample(
  File "/u/svcndifuser/miniconda3/lib/python3.10/site-packages/transformers/generation/utils.py", line 3610, in _sample
    outputs = self(**model_inputs, return_dict=True)
  File "/u/svcndifuser/miniconda3/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1751, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/u/svcndifuser/miniconda3/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1857, in _call_impl
    return inner()
  File "/u/svcndifuser/miniconda3/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1805, in inner
    result = forward_call(*args, **kwargs)
  File "/u/svcndifuser/miniconda3/lib/python3.10/site-packages/nnsight/intervention/interleaver.py", line 133, in skippable_forward
    return forward(*args, **kwargs)
  File "/u/svcndifuser/miniconda3/lib/python3.10/site-packages/transformers/utils/generic.py", line 959, in wrapper
    output = func(self, *args, **kwargs)
  File "/u/svcndifuser/miniconda3/lib/python3.10/site-packages/transformers/models/llama/modeling_llama.py", line 460, in forward
    outputs: BaseModelOutputWithPast = self.model(
  File "/u/svcndifuser/miniconda3/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1751, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/u/svcndifuser/miniconda3/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1857, in _call_impl
    return inner()
  File "/u/svcndifuser/miniconda3/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1805, in inner
    result = forward_call(*args, **kwargs)
  File "/u/svcndifuser/miniconda3/lib/python3.10/site-packages/nnsight/intervention/interleaver.py", line 133, in skippable_forward
    return forward(*args, **kwargs)
  File "/u/svcndifuser/miniconda3/lib/python3.10/site-packages/transformers/utils/generic.py", line 1083, in wrapper
    outputs = func(self, *args, **kwargs)
  File "/u/svcndifuser/miniconda3/lib/python3.10/site-packages/transformers/models/llama/modeling_llama.py", line 390, in forward
    hidden_states = decoder_layer(
  File "/u/svcndifuser/miniconda3/lib/python3.10/site-packages/transformers/modeling_layers.py", line 94, in __call__
    return super().__call__(*args, **kwargs)
  File "/u/svcndifuser/miniconda3/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1751, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/u/svcndifuser/miniconda3/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1857, in _call_impl
    return inner()
  File "/u/svcndifuser/miniconda3/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1805, in inner
    result = forward_call(*args, **kwargs)
  File "/u/svcndifuser/miniconda3/lib/python3.10/site-packages/nnsight/intervention/interleaver.py", line 133, in skippable_forward
    return forward(*args, **kwargs)
  File "/u/svcndifuser/miniconda3/lib/python3.10/site-packages/transformers/models/llama/modeling_llama.py", line 303, in forward
    hidden_states = self.post_attention_layernorm(hidden_states)
  File "/u/svcndifuser/miniconda3/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1751, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/u/svcndifuser/miniconda3/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1857, in _call_impl
    return inner()
  File "/u/svcndifuser/miniconda3/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1805, in inner
    result = forward_call(*args, **kwargs)
  File "/u/svcndifuser/miniconda3/lib/python3.10/site-packages/nnsight/intervention/interleaver.py", line 133, in skippable_forward
    return forward(*args, **kwargs)
  File "/u/svcndifuser/miniconda3/lib/python3.10/site-packages/transformers/models/llama/modeling_llama.py", line 64, in forward
    variance = hidden_states.pow(2).mean(-1, keepdim=True)

OutOfMemoryError: CUDA out of memory. Tried to allocate 134.00 MiB. GPU 0 has a total capacity of 44.34 GiB of which 832.00 KiB is free. Including non-PyTorch memory, this process has 44.33 GiB memory in use. Of the allocated memory 41.73 GiB is allocated by PyTorch, and 2.28 GiB is reserved by PyTorch but unallocated. If reserved but unallocated memory is large try setting PYTORCH_CUDA_ALLOC_CONF=expandable_segments:True to avoid fragmentation.  See documentation for Memory Management  (https://pytorch.org/docs/stable/notes/cuda.html#environment-variables)
Remote exception.

[2025-08-29 19:04:15] [4c36ce0f-bff6-40e6-92bc-e55b31fa10b9] RECEIVED   : Your job has been received and is waiting to be queued.
[2025-08-29 19:04:15] [4c36ce0f-bff6-40e6-92bc-e55b31fa10b9] QUEUED     : Your job has been recieved by the coordinator and is waiting to be queued.
[2025-08-29 19:04:15] [4c36ce0f-bff6-40e6-92bc-e55b31fa10b9] QUEUED     : Task 4c36ce0f-bff6-40e6-92bc-e55b31fa10b9 has been added to the queue. Currently at position 1
[2025-08-29 19:04:15] [4c36ce0f-bff6-40e6-92bc-e55b31fa10b9] QUEUED     : Dispatching task...
[2025-08-29 19:04:15] [4c36ce0f-bff6-40e6-92bc-e55b31fa10b9] RUNNING    : Your job has started running.
[2025-08-29 19:04:53] [4c36ce0f-bff6-40e6-92bc-e55b31fa10b9] COMPLETED  : Your job has been completed.

Downloading result:   0%|          | 0.00/201M [00:00<?, ?B/s]

[2025-08-29 19:05:03] [a7edc73b-c27c-411c-b7e9-5e054666fad4] RECEIVED   : Your job has been received and is waiting to be queued.
[2025-08-29 19:05:03] [a7edc73b-c27c-411c-b7e9-5e054666fad4] QUEUED     : Your job has been recieved by the coordinator and is waiting to be queued.
[2025-08-29 19:05:03] [a7edc73b-c27c-411c-b7e9-5e054666fad4] QUEUED     : Task a7edc73b-c27c-411c-b7e9-5e054666fad4 has been added to the queue. Currently at position 1
[2025-08-29 19:05:03] [a7edc73b-c27c-411c-b7e9-5e054666fad4] QUEUED     : Dispatching task...
[2025-08-29 19:05:03] [a7edc73b-c27c-411c-b7e9-5e054666fad4] RUNNING    : Your job has started running.

Error on problem 212: Traceback (most recent call last):
  File "/u/svcndifuser/ndif-deployment/repos/prod/ndif/src/services/ray/src/ray/deployments/modeling/base.py", line 213, in __call__
    result = await job_task
  File "/u/svcndifuser/miniconda3/lib/python3.10/asyncio/threads.py", line 25, in to_thread
    return await loop.run_in_executor(None, func_call)
  File "/u/svcndifuser/miniconda3/lib/python3.10/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/u/svcndifuser/miniconda3/lib/python3.10/site-packages/ray/util/tracing/tracing_helper.py", line 463, in _resume_span
    return method(self, *_args, **_kwargs)
  File "/u/svcndifuser/ndif-deployment/repos/prod/ndif/src/services/ray/src/ray/deployments/modeling/base.py", line 283, in execute
    result = RemoteExecutionBackend(request.interventions, self.execution_protector)(request.tracer)
  File "/u/svcndifuser/ndif-deployment/repos/prod/ndif/src/services/ray/src/ray/nn/backend.py", line 27, in __call__
    run(tracer, self.fn)
  File "/u/svcndifuser/ndif-deployment/repos/prod/ndif/src/services/ray/src/ray/nn/sandbox.py", line 16, in run
    raise wrap_exception(e,tracer.info) from None
nnsight.NNsightException:

Traceback (most recent call last):
  File "/u/svcndifuser/ndif-deployment/repos/prod/ndif/src/services/ray/src/ray/nn/sandbox.py", line 14, in run
    tracer.execute(fn)
  File "/u/svcndifuser/miniconda3/lib/python3.10/site-packages/nnsight/intervention/tracing/tracer.py", line 385, in execute
    self.model.interleave(self.fn, *args, **kwargs)
  File "/u/svcndifuser/miniconda3/lib/python3.10/site-packages/nnsight/modeling/mixins/meta.py", line 76, in interleave
    return super().interleave(fn, *args, **kwargs)
  File "/u/svcndifuser/miniconda3/lib/python3.10/site-packages/nnsight/intervention/envoy.py", line 733, in interleave
    fn(*args, **kwargs)
  File "/u/svcndifuser/miniconda3/lib/python3.10/site-packages/nnsight/modeling/language.py", line 173, in __nnsight_generate__
    output = self._model.generate(*args, streamer=streamer, **kwargs)
  File "/u/svcndifuser/miniconda3/lib/python3.10/site-packages/torch/utils/_contextlib.py", line 116, in decorate_context
    return func(*args, **kwargs)
  File "/u/svcndifuser/miniconda3/lib/python3.10/site-packages/transformers/generation/utils.py", line 2629, in generate
    result = self._sample(
  File "/u/svcndifuser/miniconda3/lib/python3.10/site-packages/transformers/generation/utils.py", line 3613, in _sample
    outputs = model_forward(**model_inputs, return_dict=True)
  File "/u/svcndifuser/miniconda3/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1751, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/u/svcndifuser/miniconda3/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1857, in _call_impl
    return inner()
  File "/u/svcndifuser/miniconda3/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1805, in inner
    result = forward_call(*args, **kwargs)
  File "/u/svcndifuser/miniconda3/lib/python3.10/site-packages/nnsight/intervention/interleaver.py", line 133, in skippable_forward
    return forward(*args, **kwargs)
  File "/u/svcndifuser/miniconda3/lib/python3.10/site-packages/transformers/utils/generic.py", line 959, in wrapper
    output = func(self, *args, **kwargs)
  File "/u/svcndifuser/miniconda3/lib/python3.10/site-packages/transformers/models/llama/modeling_llama.py", line 460, in forward
    outputs: BaseModelOutputWithPast = self.model(
  File "/u/svcndifuser/miniconda3/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1751, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/u/svcndifuser/miniconda3/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1857, in _call_impl
    return inner()
  File "/u/svcndifuser/miniconda3/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1805, in inner
    result = forward_call(*args, **kwargs)
  File "/u/svcndifuser/miniconda3/lib/python3.10/site-packages/nnsight/intervention/interleaver.py", line 133, in skippable_forward
    return forward(*args, **kwargs)
  File "/u/svcndifuser/miniconda3/lib/python3.10/site-packages/transformers/utils/generic.py", line 1083, in wrapper
    outputs = func(self, *args, **kwargs)
  File "/u/svcndifuser/miniconda3/lib/python3.10/site-packages/transformers/models/llama/modeling_llama.py", line 390, in forward
    hidden_states = decoder_layer(
  File "/u/svcndifuser/miniconda3/lib/python3.10/site-packages/transformers/modeling_layers.py", line 94, in __call__
    return super().__call__(*args, **kwargs)
  File "/u/svcndifuser/miniconda3/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1751, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/u/svcndifuser/miniconda3/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1857, in _call_impl
    return inner()
  File "/u/svcndifuser/miniconda3/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1805, in inner
    result = forward_call(*args, **kwargs)
  File "/u/svcndifuser/miniconda3/lib/python3.10/site-packages/nnsight/intervention/interleaver.py", line 133, in skippable_forward
    return forward(*args, **kwargs)
  File "/u/svcndifuser/miniconda3/lib/python3.10/site-packages/transformers/models/llama/modeling_llama.py", line 289, in forward
    hidden_states, _ = self.self_attn(
  File "/u/svcndifuser/miniconda3/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1751, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/u/svcndifuser/miniconda3/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1857, in _call_impl
    return inner()
  File "/u/svcndifuser/miniconda3/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1805, in inner
    result = forward_call(*args, **kwargs)
  File "/u/svcndifuser/miniconda3/lib/python3.10/site-packages/nnsight/intervention/interleaver.py", line 133, in skippable_forward
    return forward(*args, **kwargs)
  File "/u/svcndifuser/miniconda3/lib/python3.10/site-packages/transformers/models/llama/modeling_llama.py", line 242, in forward
    key_states, value_states = past_key_value.update(key_states, value_states, self.layer_idx, cache_kwargs)
  File "/u/svcndifuser/miniconda3/lib/python3.10/site-packages/transformers/cache_utils.py", line 992, in _wrapped_update
    key_tensors, value_tensors = fn(self, key_states, value_states, layer_idx, cache_kwargs)
  File "/u/svcndifuser/miniconda3/lib/python3.10/site-packages/transformers/cache_utils.py", line 1201, in update
    return self.layers[layer_idx].update(key_states, value_states, cache_kwargs)
  File "/u/svcndifuser/miniconda3/lib/python3.10/site-packages/transformers/cache_utils.py", line 102, in update
    self.keys = torch.cat([self.keys, key_states], dim=-2)

OutOfMemoryError: CUDA out of memory. Tried to allocate 124.00 MiB. GPU 0 has a total capacity of 44.34 GiB of which 118.81 MiB is free. Including non-PyTorch memory, this process has 44.21 GiB memory in use. Of the allocated memory 41.35 GiB is allocated by PyTorch, and 2.55 GiB is reserved by PyTorch but unallocated. If reserved but unallocated memory is large try setting PYTORCH_CUDA_ALLOC_CONF=expandable_segments:True to avoid fragmentation.  See documentation for Memory Management  (https://pytorch.org/docs/stable/notes/cuda.html#environment-variables)



Traceback (most recent call last):
  File "/u/svcndifuser/ndif-deployment/repos/prod/ndif/src/services/ray/src/ray/nn/sandbox.py", line 14, in run
    tracer.execute(fn)
  File "/u/svcndifuser/miniconda3/lib/python3.10/site-packages/nnsight/intervention/tracing/tracer.py", line 385, in execute
    self.model.interleave(self.fn, *args, **kwargs)
  File "/u/svcndifuser/miniconda3/lib/python3.10/site-packages/nnsight/modeling/mixins/meta.py", line 76, in interleave
    return super().interleave(fn, *args, **kwargs)
  File "/u/svcndifuser/miniconda3/lib/python3.10/site-packages/nnsight/intervention/envoy.py", line 733, in interleave
    fn(*args, **kwargs)
  File "/u/svcndifuser/miniconda3/lib/python3.10/site-packages/nnsight/modeling/language.py", line 173, in __nnsight_generate__
    output = self._model.generate(*args, streamer=streamer, **kwargs)
  File "/u/svcndifuser/miniconda3/lib/python3.10/site-packages/torch/utils/_contextlib.py", line 116, in decorate_context
    return func(*args, **kwargs)
  File "/u/svcndifuser/miniconda3/lib/python3.10/site-packages/transformers/generation/utils.py", line 2629, in generate
    result = self._sample(
  File "/u/svcndifuser/miniconda3/lib/python3.10/site-packages/transformers/generation/utils.py", line 3613, in _sample
    outputs = model_forward(**model_inputs, return_dict=True)
  File "/u/svcndifuser/miniconda3/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1751, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/u/svcndifuser/miniconda3/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1857, in _call_impl
    return inner()
  File "/u/svcndifuser/miniconda3/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1805, in inner
    result = forward_call(*args, **kwargs)
  File "/u/svcndifuser/miniconda3/lib/python3.10/site-packages/nnsight/intervention/interleaver.py", line 133, in skippable_forward
    return forward(*args, **kwargs)
  File "/u/svcndifuser/miniconda3/lib/python3.10/site-packages/transformers/utils/generic.py", line 959, in wrapper
    output = func(self, *args, **kwargs)
  File "/u/svcndifuser/miniconda3/lib/python3.10/site-packages/transformers/models/llama/modeling_llama.py", line 460, in forward
    outputs: BaseModelOutputWithPast = self.model(
  File "/u/svcndifuser/miniconda3/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1751, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/u/svcndifuser/miniconda3/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1857, in _call_impl
    return inner()
  File "/u/svcndifuser/miniconda3/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1805, in inner
    result = forward_call(*args, **kwargs)
  File "/u/svcndifuser/miniconda3/lib/python3.10/site-packages/nnsight/intervention/interleaver.py", line 133, in skippable_forward
    return forward(*args, **kwargs)
  File "/u/svcndifuser/miniconda3/lib/python3.10/site-packages/transformers/utils/generic.py", line 1083, in wrapper
    outputs = func(self, *args, **kwargs)
  File "/u/svcndifuser/miniconda3/lib/python3.10/site-packages/transformers/models/llama/modeling_llama.py", line 390, in forward
    hidden_states = decoder_layer(
  File "/u/svcndifuser/miniconda3/lib/python3.10/site-packages/transformers/modeling_layers.py", line 94, in __call__
    return super().__call__(*args, **kwargs)
  File "/u/svcndifuser/miniconda3/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1751, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/u/svcndifuser/miniconda3/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1857, in _call_impl
    return inner()
  File "/u/svcndifuser/miniconda3/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1805, in inner
    result = forward_call(*args, **kwargs)
  File "/u/svcndifuser/miniconda3/lib/python3.10/site-packages/nnsight/intervention/interleaver.py", line 133, in skippable_forward
    return forward(*args, **kwargs)
  File "/u/svcndifuser/miniconda3/lib/python3.10/site-packages/transformers/models/llama/modeling_llama.py", line 289, in forward
    hidden_states, _ = self.self_attn(
  File "/u/svcndifuser/miniconda3/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1751, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/u/svcndifuser/miniconda3/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1857, in _call_impl
    return inner()
  File "/u/svcndifuser/miniconda3/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1805, in inner
    result = forward_call(*args, **kwargs)
  File "/u/svcndifuser/miniconda3/lib/python3.10/site-packages/nnsight/intervention/interleaver.py", line 133, in skippable_forward
    return forward(*args, **kwargs)
  File "/u/svcndifuser/miniconda3/lib/python3.10/site-packages/transformers/models/llama/modeling_llama.py", line 242, in forward
    key_states, value_states = past_key_value.update(key_states, value_states, self.layer_idx, cache_kwargs)
  File "/u/svcndifuser/miniconda3/lib/python3.10/site-packages/transformers/cache_utils.py", line 992, in _wrapped_update
    key_tensors, value_tensors = fn(self, key_states, value_states, layer_idx, cache_kwargs)
  File "/u/svcndifuser/miniconda3/lib/python3.10/site-packages/transformers/cache_utils.py", line 1201, in update
    return self.layers[layer_idx].update(key_states, value_states, cache_kwargs)
  File "/u/svcndifuser/miniconda3/lib/python3.10/site-packages/transformers/cache_utils.py", line 102, in update
    self.keys = torch.cat([self.keys, key_states], dim=-2)

OutOfMemoryError: CUDA out of memory. Tried to allocate 124.00 MiB. GPU 0 has a total capacity of 44.34 GiB of which 118.81 MiB is free. Including non-PyTorch memory, this process has 44.21 GiB memory in use. Of the allocated memory 41.35 GiB is allocated by PyTorch, and 2.55 GiB is reserved by PyTorch but unallocated. If reserved but unallocated memory is large try setting PYTORCH_CUDA_ALLOC_CONF=expandable_segments:True to avoid fragmentation.  See documentation for Memory Management  (https://pytorch.org/docs/stable/notes/cuda.html#environment-variables)
Remote exception.

[2025-08-29 19:07:00] [b9f086b1-c409-474c-8605-718c3427c854] RECEIVED   : Your job has been received and is waiting to be queued.
[2025-08-29 19:07:00] [b9f086b1-c409-474c-8605-718c3427c854] QUEUED     : Your job has been recieved by the coordinator and is waiting to be queued.
[2025-08-29 19:07:00] [b9f086b1-c409-474c-8605-718c3427c854] QUEUED     : Task b9f086b1-c409-474c-8605-718c3427c854 has been added to the queue. Currently at position 1
[2025-08-29 19:07:00] [b9f086b1-c409-474c-8605-718c3427c854] QUEUED     : Dispatching task...
[2025-08-29 19:07:01] [b9f086b1-c409-474c-8605-718c3427c854] RUNNING    : Your job has started running.

Error on problem 213: Traceback (most recent call last):
  File "/u/svcndifuser/ndif-deployment/repos/prod/ndif/src/services/ray/src/ray/deployments/modeling/base.py", line 213, in __call__
    result = await job_task
  File "/u/svcndifuser/miniconda3/lib/python3.10/asyncio/threads.py", line 25, in to_thread
    return await loop.run_in_executor(None, func_call)
  File "/u/svcndifuser/miniconda3/lib/python3.10/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/u/svcndifuser/miniconda3/lib/python3.10/site-packages/ray/util/tracing/tracing_helper.py", line 463, in _resume_span
    return method(self, *_args, **_kwargs)
  File "/u/svcndifuser/ndif-deployment/repos/prod/ndif/src/services/ray/src/ray/deployments/modeling/base.py", line 283, in execute
    result = RemoteExecutionBackend(request.interventions, self.execution_protector)(request.tracer)
  File "/u/svcndifuser/ndif-deployment/repos/prod/ndif/src/services/ray/src/ray/nn/backend.py", line 27, in __call__
    run(tracer, self.fn)
  File "/u/svcndifuser/ndif-deployment/repos/prod/ndif/src/services/ray/src/ray/nn/sandbox.py", line 16, in run
    raise wrap_exception(e,tracer.info) from None
nnsight.NNsightException:

Traceback (most recent call last):
  File "/u/svcndifuser/ndif-deployment/repos/prod/ndif/src/services/ray/src/ray/nn/sandbox.py", line 14, in run
    tracer.execute(fn)
  File "/u/svcndifuser/miniconda3/lib/python3.10/site-packages/nnsight/intervention/tracing/tracer.py", line 385, in execute
    self.model.interleave(self.fn, *args, **kwargs)
  File "/u/svcndifuser/miniconda3/lib/python3.10/site-packages/nnsight/modeling/mixins/meta.py", line 76, in interleave
    return super().interleave(fn, *args, **kwargs)
  File "/u/svcndifuser/miniconda3/lib/python3.10/site-packages/nnsight/intervention/envoy.py", line 733, in interleave
    fn(*args, **kwargs)
  File "/u/svcndifuser/miniconda3/lib/python3.10/site-packages/nnsight/modeling/language.py", line 173, in __nnsight_generate__
    output = self._model.generate(*args, streamer=streamer, **kwargs)
  File "/u/svcndifuser/miniconda3/lib/python3.10/site-packages/torch/utils/_contextlib.py", line 116, in decorate_context
    return func(*args, **kwargs)
  File "/u/svcndifuser/miniconda3/lib/python3.10/site-packages/transformers/generation/utils.py", line 2629, in generate
    result = self._sample(
  File "/u/svcndifuser/miniconda3/lib/python3.10/site-packages/transformers/generation/utils.py", line 3610, in _sample
    outputs = self(**model_inputs, return_dict=True)
  File "/u/svcndifuser/miniconda3/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1751, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/u/svcndifuser/miniconda3/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1857, in _call_impl
    return inner()
  File "/u/svcndifuser/miniconda3/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1805, in inner
    result = forward_call(*args, **kwargs)
  File "/u/svcndifuser/miniconda3/lib/python3.10/site-packages/nnsight/intervention/interleaver.py", line 133, in skippable_forward
    return forward(*args, **kwargs)
  File "/u/svcndifuser/miniconda3/lib/python3.10/site-packages/transformers/utils/generic.py", line 959, in wrapper
    output = func(self, *args, **kwargs)
  File "/u/svcndifuser/miniconda3/lib/python3.10/site-packages/transformers/models/llama/modeling_llama.py", line 460, in forward
    outputs: BaseModelOutputWithPast = self.model(
  File "/u/svcndifuser/miniconda3/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1751, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/u/svcndifuser/miniconda3/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1857, in _call_impl
    return inner()
  File "/u/svcndifuser/miniconda3/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1805, in inner
    result = forward_call(*args, **kwargs)
  File "/u/svcndifuser/miniconda3/lib/python3.10/site-packages/nnsight/intervention/interleaver.py", line 133, in skippable_forward
    return forward(*args, **kwargs)
  File "/u/svcndifuser/miniconda3/lib/python3.10/site-packages/transformers/utils/generic.py", line 1083, in wrapper
    outputs = func(self, *args, **kwargs)
  File "/u/svcndifuser/miniconda3/lib/python3.10/site-packages/transformers/models/llama/modeling_llama.py", line 390, in forward
    hidden_states = decoder_layer(
  File "/u/svcndifuser/miniconda3/lib/python3.10/site-packages/transformers/modeling_layers.py", line 94, in __call__
    return super().__call__(*args, **kwargs)
  File "/u/svcndifuser/miniconda3/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1751, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/u/svcndifuser/miniconda3/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1857, in _call_impl
    return inner()
  File "/u/svcndifuser/miniconda3/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1805, in inner
    result = forward_call(*args, **kwargs)
  File "/u/svcndifuser/miniconda3/lib/python3.10/site-packages/nnsight/intervention/interleaver.py", line 133, in skippable_forward
    return forward(*args, **kwargs)
  File "/u/svcndifuser/miniconda3/lib/python3.10/site-packages/transformers/models/llama/modeling_llama.py", line 304, in forward
    hidden_states = self.mlp(hidden_states)
  File "/u/svcndifuser/miniconda3/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1751, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/u/svcndifuser/miniconda3/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1857, in _call_impl
    return inner()
  File "/u/svcndifuser/miniconda3/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1805, in inner
    result = forward_call(*args, **kwargs)
  File "/u/svcndifuser/miniconda3/lib/python3.10/site-packages/nnsight/intervention/interleaver.py", line 133, in skippable_forward
    return forward(*args, **kwargs)
  File "/u/svcndifuser/miniconda3/lib/python3.10/site-packages/transformers/models/llama/modeling_llama.py", line 152, in forward
    down_proj = self.down_proj(self.act_fn(self.gate_proj(x)) * self.up_proj(x))

OutOfMemoryError: CUDA out of memory. Tried to allocate 108.00 MiB. GPU 0 has a total capacity of 44.34 GiB of which 8.81 MiB is free. Including non-PyTorch memory, this process has 44.32 GiB memory in use. Of the allocated memory 41.71 GiB is allocated by PyTorch, and 2.29 GiB is reserved by PyTorch but unallocated. If reserved but unallocated memory is large try setting PYTORCH_CUDA_ALLOC_CONF=expandable_segments:True to avoid fragmentation.  See documentation for Memory Management  (https://pytorch.org/docs/stable/notes/cuda.html#environment-variables)



Traceback (most recent call last):
  File "/u/svcndifuser/ndif-deployment/repos/prod/ndif/src/services/ray/src/ray/nn/sandbox.py", line 14, in run
    tracer.execute(fn)
  File "/u/svcndifuser/miniconda3/lib/python3.10/site-packages/nnsight/intervention/tracing/tracer.py", line 385, in execute
    self.model.interleave(self.fn, *args, **kwargs)
  File "/u/svcndifuser/miniconda3/lib/python3.10/site-packages/nnsight/modeling/mixins/meta.py", line 76, in interleave
    return super().interleave(fn, *args, **kwargs)
  File "/u/svcndifuser/miniconda3/lib/python3.10/site-packages/nnsight/intervention/envoy.py", line 733, in interleave
    fn(*args, **kwargs)
  File "/u/svcndifuser/miniconda3/lib/python3.10/site-packages/nnsight/modeling/language.py", line 173, in __nnsight_generate__
    output = self._model.generate(*args, streamer=streamer, **kwargs)
  File "/u/svcndifuser/miniconda3/lib/python3.10/site-packages/torch/utils/_contextlib.py", line 116, in decorate_context
    return func(*args, **kwargs)
  File "/u/svcndifuser/miniconda3/lib/python3.10/site-packages/transformers/generation/utils.py", line 2629, in generate
    result = self._sample(
  File "/u/svcndifuser/miniconda3/lib/python3.10/site-packages/transformers/generation/utils.py", line 3610, in _sample
    outputs = self(**model_inputs, return_dict=True)
  File "/u/svcndifuser/miniconda3/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1751, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/u/svcndifuser/miniconda3/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1857, in _call_impl
    return inner()
  File "/u/svcndifuser/miniconda3/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1805, in inner
    result = forward_call(*args, **kwargs)
  File "/u/svcndifuser/miniconda3/lib/python3.10/site-packages/nnsight/intervention/interleaver.py", line 133, in skippable_forward
    return forward(*args, **kwargs)
  File "/u/svcndifuser/miniconda3/lib/python3.10/site-packages/transformers/utils/generic.py", line 959, in wrapper
    output = func(self, *args, **kwargs)
  File "/u/svcndifuser/miniconda3/lib/python3.10/site-packages/transformers/models/llama/modeling_llama.py", line 460, in forward
    outputs: BaseModelOutputWithPast = self.model(
  File "/u/svcndifuser/miniconda3/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1751, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/u/svcndifuser/miniconda3/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1857, in _call_impl
    return inner()
  File "/u/svcndifuser/miniconda3/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1805, in inner
    result = forward_call(*args, **kwargs)
  File "/u/svcndifuser/miniconda3/lib/python3.10/site-packages/nnsight/intervention/interleaver.py", line 133, in skippable_forward
    return forward(*args, **kwargs)
  File "/u/svcndifuser/miniconda3/lib/python3.10/site-packages/transformers/utils/generic.py", line 1083, in wrapper
    outputs = func(self, *args, **kwargs)
  File "/u/svcndifuser/miniconda3/lib/python3.10/site-packages/transformers/models/llama/modeling_llama.py", line 390, in forward
    hidden_states = decoder_layer(
  File "/u/svcndifuser/miniconda3/lib/python3.10/site-packages/transformers/modeling_layers.py", line 94, in __call__
    return super().__call__(*args, **kwargs)
  File "/u/svcndifuser/miniconda3/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1751, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/u/svcndifuser/miniconda3/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1857, in _call_impl
    return inner()
  File "/u/svcndifuser/miniconda3/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1805, in inner
    result = forward_call(*args, **kwargs)
  File "/u/svcndifuser/miniconda3/lib/python3.10/site-packages/nnsight/intervention/interleaver.py", line 133, in skippable_forward
    return forward(*args, **kwargs)
  File "/u/svcndifuser/miniconda3/lib/python3.10/site-packages/transformers/models/llama/modeling_llama.py", line 304, in forward
    hidden_states = self.mlp(hidden_states)
  File "/u/svcndifuser/miniconda3/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1751, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/u/svcndifuser/miniconda3/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1857, in _call_impl
    return inner()
  File "/u/svcndifuser/miniconda3/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1805, in inner
    result = forward_call(*args, **kwargs)
  File "/u/svcndifuser/miniconda3/lib/python3.10/site-packages/nnsight/intervention/interleaver.py", line 133, in skippable_forward
    return forward(*args, **kwargs)
  File "/u/svcndifuser/miniconda3/lib/python3.10/site-packages/transformers/models/llama/modeling_llama.py", line 152, in forward
    down_proj = self.down_proj(self.act_fn(self.gate_proj(x)) * self.up_proj(x))

OutOfMemoryError: CUDA out of memory. Tried to allocate 108.00 MiB. GPU 0 has a total capacity of 44.34 GiB of which 8.81 MiB is free. Including non-PyTorch memory, this process has 44.32 GiB memory in use. Of the allocated memory 41.71 GiB is allocated by PyTorch, and 2.29 GiB is reserved by PyTorch but unallocated. If reserved but unallocated memory is large try setting PYTORCH_CUDA_ALLOC_CONF=expandable_segments:True to avoid fragmentation.  See documentation for Memory Management  (https://pytorch.org/docs/stable/notes/cuda.html#environment-variables)
Remote exception.

[2025-08-29 19:07:02] [72b2c227-4619-411e-9b5a-68dca83bb604] RECEIVED   : Your job has been received and is waiting to be queued.
[2025-08-29 19:07:02] [72b2c227-4619-411e-9b5a-68dca83bb604] QUEUED     : Your job has been recieved by the coordinator and is waiting to be queued.
[2025-08-29 19:07:02] [72b2c227-4619-411e-9b5a-68dca83bb604] QUEUED     : Task 72b2c227-4619-411e-9b5a-68dca83bb604 has been added to the queue. Currently at position 1
[2025-08-29 19:07:02] [72b2c227-4619-411e-9b5a-68dca83bb604] QUEUED     : Dispatching task...
[2025-08-29 19:07:02] [72b2c227-4619-411e-9b5a-68dca83bb604] RUNNING    : Your job has started running.

Error on problem 214: Traceback (most recent call last):
  File "/u/svcndifuser/ndif-deployment/repos/prod/ndif/src/services/ray/src/ray/deployments/modeling/base.py", line 213, in __call__
    result = await job_task
  File "/u/svcndifuser/miniconda3/lib/python3.10/asyncio/threads.py", line 25, in to_thread
    return await loop.run_in_executor(None, func_call)
  File "/u/svcndifuser/miniconda3/lib/python3.10/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/u/svcndifuser/miniconda3/lib/python3.10/site-packages/ray/util/tracing/tracing_helper.py", line 463, in _resume_span
    return method(self, *_args, **_kwargs)
  File "/u/svcndifuser/ndif-deployment/repos/prod/ndif/src/services/ray/src/ray/deployments/modeling/base.py", line 283, in execute
    result = RemoteExecutionBackend(request.interventions, self.execution_protector)(request.tracer)
  File "/u/svcndifuser/ndif-deployment/repos/prod/ndif/src/services/ray/src/ray/nn/backend.py", line 27, in __call__
    run(tracer, self.fn)
  File "/u/svcndifuser/ndif-deployment/repos/prod/ndif/src/services/ray/src/ray/nn/sandbox.py", line 16, in run
    raise wrap_exception(e,tracer.info) from None
nnsight.NNsightException:

Traceback (most recent call last):
  File "/u/svcndifuser/ndif-deployment/repos/prod/ndif/src/services/ray/src/ray/nn/sandbox.py", line 14, in run
    tracer.execute(fn)
  File "/u/svcndifuser/miniconda3/lib/python3.10/site-packages/nnsight/intervention/tracing/tracer.py", line 385, in execute
    self.model.interleave(self.fn, *args, **kwargs)
  File "/u/svcndifuser/miniconda3/lib/python3.10/site-packages/nnsight/modeling/mixins/meta.py", line 76, in interleave
    return super().interleave(fn, *args, **kwargs)
  File "/u/svcndifuser/miniconda3/lib/python3.10/site-packages/nnsight/intervention/envoy.py", line 733, in interleave
    fn(*args, **kwargs)
  File "/u/svcndifuser/miniconda3/lib/python3.10/site-packages/nnsight/modeling/language.py", line 173, in __nnsight_generate__
    output = self._model.generate(*args, streamer=streamer, **kwargs)
  File "/u/svcndifuser/miniconda3/lib/python3.10/site-packages/torch/utils/_contextlib.py", line 116, in decorate_context
    return func(*args, **kwargs)
  File "/u/svcndifuser/miniconda3/lib/python3.10/site-packages/transformers/generation/utils.py", line 2629, in generate
    result = self._sample(
  File "/u/svcndifuser/miniconda3/lib/python3.10/site-packages/transformers/generation/utils.py", line 3613, in _sample
    outputs = model_forward(**model_inputs, return_dict=True)
  File "/u/svcndifuser/miniconda3/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1751, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/u/svcndifuser/miniconda3/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1857, in _call_impl
    return inner()
  File "/u/svcndifuser/miniconda3/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1805, in inner
    result = forward_call(*args, **kwargs)
  File "/u/svcndifuser/miniconda3/lib/python3.10/site-packages/nnsight/intervention/interleaver.py", line 133, in skippable_forward
    return forward(*args, **kwargs)
  File "/u/svcndifuser/miniconda3/lib/python3.10/site-packages/transformers/utils/generic.py", line 959, in wrapper
    output = func(self, *args, **kwargs)
  File "/u/svcndifuser/miniconda3/lib/python3.10/site-packages/transformers/models/llama/modeling_llama.py", line 460, in forward
    outputs: BaseModelOutputWithPast = self.model(
  File "/u/svcndifuser/miniconda3/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1751, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/u/svcndifuser/miniconda3/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1857, in _call_impl
    return inner()
  File "/u/svcndifuser/miniconda3/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1805, in inner
    result = forward_call(*args, **kwargs)
  File "/u/svcndifuser/miniconda3/lib/python3.10/site-packages/nnsight/intervention/interleaver.py", line 133, in skippable_forward
    return forward(*args, **kwargs)
  File "/u/svcndifuser/miniconda3/lib/python3.10/site-packages/transformers/utils/generic.py", line 1083, in wrapper
    outputs = func(self, *args, **kwargs)
  File "/u/svcndifuser/miniconda3/lib/python3.10/site-packages/transformers/models/llama/modeling_llama.py", line 390, in forward
    hidden_states = decoder_layer(
  File "/u/svcndifuser/miniconda3/lib/python3.10/site-packages/transformers/modeling_layers.py", line 94, in __call__
    return super().__call__(*args, **kwargs)
  File "/u/svcndifuser/miniconda3/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1751, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/u/svcndifuser/miniconda3/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1857, in _call_impl
    return inner()
  File "/u/svcndifuser/miniconda3/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1805, in inner
    result = forward_call(*args, **kwargs)
  File "/u/svcndifuser/miniconda3/lib/python3.10/site-packages/nnsight/intervention/interleaver.py", line 133, in skippable_forward
    return forward(*args, **kwargs)
  File "/u/svcndifuser/miniconda3/lib/python3.10/site-packages/transformers/models/llama/modeling_llama.py", line 289, in forward
    hidden_states, _ = self.self_attn(
  File "/u/svcndifuser/miniconda3/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1751, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/u/svcndifuser/miniconda3/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1857, in _call_impl
    return inner()
  File "/u/svcndifuser/miniconda3/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1805, in inner
    result = forward_call(*args, **kwargs)
  File "/u/svcndifuser/miniconda3/lib/python3.10/site-packages/nnsight/intervention/interleaver.py", line 133, in skippable_forward
    return forward(*args, **kwargs)
  File "/u/svcndifuser/miniconda3/lib/python3.10/site-packages/transformers/models/llama/modeling_llama.py", line 242, in forward
    key_states, value_states = past_key_value.update(key_states, value_states, self.layer_idx, cache_kwargs)
  File "/u/svcndifuser/miniconda3/lib/python3.10/site-packages/transformers/cache_utils.py", line 992, in _wrapped_update
    key_tensors, value_tensors = fn(self, key_states, value_states, layer_idx, cache_kwargs)
  File "/u/svcndifuser/miniconda3/lib/python3.10/site-packages/transformers/cache_utils.py", line 1201, in update
    return self.layers[layer_idx].update(key_states, value_states, cache_kwargs)
  File "/u/svcndifuser/miniconda3/lib/python3.10/site-packages/transformers/cache_utils.py", line 103, in update
    self.values = torch.cat([self.values, value_states], dim=-2)

OutOfMemoryError: CUDA out of memory. Tried to allocate 116.00 MiB. GPU 0 has a total capacity of 44.34 GiB of which 114.81 MiB is free. Including non-PyTorch memory, this process has 44.22 GiB memory in use. Of the allocated memory 41.45 GiB is allocated by PyTorch, and 2.46 GiB is reserved by PyTorch but unallocated. If reserved but unallocated memory is large try setting PYTORCH_CUDA_ALLOC_CONF=expandable_segments:True to avoid fragmentation.  See documentation for Memory Management  (https://pytorch.org/docs/stable/notes/cuda.html#environment-variables)



Traceback (most recent call last):
  File "/u/svcndifuser/ndif-deployment/repos/prod/ndif/src/services/ray/src/ray/nn/sandbox.py", line 14, in run
    tracer.execute(fn)
  File "/u/svcndifuser/miniconda3/lib/python3.10/site-packages/nnsight/intervention/tracing/tracer.py", line 385, in execute
    self.model.interleave(self.fn, *args, **kwargs)
  File "/u/svcndifuser/miniconda3/lib/python3.10/site-packages/nnsight/modeling/mixins/meta.py", line 76, in interleave
    return super().interleave(fn, *args, **kwargs)
  File "/u/svcndifuser/miniconda3/lib/python3.10/site-packages/nnsight/intervention/envoy.py", line 733, in interleave
    fn(*args, **kwargs)
  File "/u/svcndifuser/miniconda3/lib/python3.10/site-packages/nnsight/modeling/language.py", line 173, in __nnsight_generate__
    output = self._model.generate(*args, streamer=streamer, **kwargs)
  File "/u/svcndifuser/miniconda3/lib/python3.10/site-packages/torch/utils/_contextlib.py", line 116, in decorate_context
    return func(*args, **kwargs)
  File "/u/svcndifuser/miniconda3/lib/python3.10/site-packages/transformers/generation/utils.py", line 2629, in generate
    result = self._sample(
  File "/u/svcndifuser/miniconda3/lib/python3.10/site-packages/transformers/generation/utils.py", line 3613, in _sample
    outputs = model_forward(**model_inputs, return_dict=True)
  File "/u/svcndifuser/miniconda3/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1751, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/u/svcndifuser/miniconda3/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1857, in _call_impl
    return inner()
  File "/u/svcndifuser/miniconda3/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1805, in inner
    result = forward_call(*args, **kwargs)
  File "/u/svcndifuser/miniconda3/lib/python3.10/site-packages/nnsight/intervention/interleaver.py", line 133, in skippable_forward
    return forward(*args, **kwargs)
  File "/u/svcndifuser/miniconda3/lib/python3.10/site-packages/transformers/utils/generic.py", line 959, in wrapper
    output = func(self, *args, **kwargs)
  File "/u/svcndifuser/miniconda3/lib/python3.10/site-packages/transformers/models/llama/modeling_llama.py", line 460, in forward
    outputs: BaseModelOutputWithPast = self.model(
  File "/u/svcndifuser/miniconda3/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1751, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/u/svcndifuser/miniconda3/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1857, in _call_impl
    return inner()
  File "/u/svcndifuser/miniconda3/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1805, in inner
    result = forward_call(*args, **kwargs)
  File "/u/svcndifuser/miniconda3/lib/python3.10/site-packages/nnsight/intervention/interleaver.py", line 133, in skippable_forward
    return forward(*args, **kwargs)
  File "/u/svcndifuser/miniconda3/lib/python3.10/site-packages/transformers/utils/generic.py", line 1083, in wrapper
    outputs = func(self, *args, **kwargs)
  File "/u/svcndifuser/miniconda3/lib/python3.10/site-packages/transformers/models/llama/modeling_llama.py", line 390, in forward
    hidden_states = decoder_layer(
  File "/u/svcndifuser/miniconda3/lib/python3.10/site-packages/transformers/modeling_layers.py", line 94, in __call__
    return super().__call__(*args, **kwargs)
  File "/u/svcndifuser/miniconda3/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1751, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/u/svcndifuser/miniconda3/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1857, in _call_impl
    return inner()
  File "/u/svcndifuser/miniconda3/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1805, in inner
    result = forward_call(*args, **kwargs)
  File "/u/svcndifuser/miniconda3/lib/python3.10/site-packages/nnsight/intervention/interleaver.py", line 133, in skippable_forward
    return forward(*args, **kwargs)
  File "/u/svcndifuser/miniconda3/lib/python3.10/site-packages/transformers/models/llama/modeling_llama.py", line 289, in forward
    hidden_states, _ = self.self_attn(
  File "/u/svcndifuser/miniconda3/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1751, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/u/svcndifuser/miniconda3/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1857, in _call_impl
    return inner()
  File "/u/svcndifuser/miniconda3/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1805, in inner
    result = forward_call(*args, **kwargs)
  File "/u/svcndifuser/miniconda3/lib/python3.10/site-packages/nnsight/intervention/interleaver.py", line 133, in skippable_forward
    return forward(*args, **kwargs)
  File "/u/svcndifuser/miniconda3/lib/python3.10/site-packages/transformers/models/llama/modeling_llama.py", line 242, in forward
    key_states, value_states = past_key_value.update(key_states, value_states, self.layer_idx, cache_kwargs)
  File "/u/svcndifuser/miniconda3/lib/python3.10/site-packages/transformers/cache_utils.py", line 992, in _wrapped_update
    key_tensors, value_tensors = fn(self, key_states, value_states, layer_idx, cache_kwargs)
  File "/u/svcndifuser/miniconda3/lib/python3.10/site-packages/transformers/cache_utils.py", line 1201, in update
    return self.layers[layer_idx].update(key_states, value_states, cache_kwargs)
  File "/u/svcndifuser/miniconda3/lib/python3.10/site-packages/transformers/cache_utils.py", line 103, in update
    self.values = torch.cat([self.values, value_states], dim=-2)

OutOfMemoryError: CUDA out of memory. Tried to allocate 116.00 MiB. GPU 0 has a total capacity of 44.34 GiB of which 114.81 MiB is free. Including non-PyTorch memory, this process has 44.22 GiB memory in use. Of the allocated memory 41.45 GiB is allocated by PyTorch, and 2.46 GiB is reserved by PyTorch but unallocated. If reserved but unallocated memory is large try setting PYTORCH_CUDA_ALLOC_CONF=expandable_segments:True to avoid fragmentation.  See documentation for Memory Management  (https://pytorch.org/docs/stable/notes/cuda.html#environment-variables)
Remote exception.

[2025-08-29 19:08:47] [8a87af74-d868-4aec-b61f-25d51de38682] RECEIVED   : Your job has been received and is waiting to be queued.
[2025-08-29 19:08:47] [8a87af74-d868-4aec-b61f-25d51de38682] QUEUED     : Your job has been recieved by the coordinator and is waiting to be queued.
[2025-08-29 19:08:47] [8a87af74-d868-4aec-b61f-25d51de38682] QUEUED     : Task 8a87af74-d868-4aec-b61f-25d51de38682 has been added to the queue. Currently at position 1
[2025-08-29 19:08:47] [8a87af74-d868-4aec-b61f-25d51de38682] QUEUED     : Dispatching task...
[2025-08-29 19:08:48] [8a87af74-d868-4aec-b61f-25d51de38682] RUNNING    : Your job has started running.

Error on problem 215: Traceback (most recent call last):
  File "/u/svcndifuser/ndif-deployment/repos/prod/ndif/src/services/ray/src/ray/deployments/modeling/base.py", line 213, in __call__
    result = await job_task
  File "/u/svcndifuser/miniconda3/lib/python3.10/asyncio/threads.py", line 25, in to_thread
    return await loop.run_in_executor(None, func_call)
  File "/u/svcndifuser/miniconda3/lib/python3.10/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/u/svcndifuser/miniconda3/lib/python3.10/site-packages/ray/util/tracing/tracing_helper.py", line 463, in _resume_span
    return method(self, *_args, **_kwargs)
  File "/u/svcndifuser/ndif-deployment/repos/prod/ndif/src/services/ray/src/ray/deployments/modeling/base.py", line 283, in execute
    result = RemoteExecutionBackend(request.interventions, self.execution_protector)(request.tracer)
  File "/u/svcndifuser/ndif-deployment/repos/prod/ndif/src/services/ray/src/ray/nn/backend.py", line 27, in __call__
    run(tracer, self.fn)
  File "/u/svcndifuser/ndif-deployment/repos/prod/ndif/src/services/ray/src/ray/nn/sandbox.py", line 16, in run
    raise wrap_exception(e,tracer.info) from None
nnsight.NNsightException:

Traceback (most recent call last):
  File "/u/svcndifuser/ndif-deployment/repos/prod/ndif/src/services/ray/src/ray/nn/sandbox.py", line 14, in run
    tracer.execute(fn)
  File "/u/svcndifuser/miniconda3/lib/python3.10/site-packages/nnsight/intervention/tracing/tracer.py", line 385, in execute
    self.model.interleave(self.fn, *args, **kwargs)
  File "/u/svcndifuser/miniconda3/lib/python3.10/site-packages/nnsight/modeling/mixins/meta.py", line 76, in interleave
    return super().interleave(fn, *args, **kwargs)
  File "/u/svcndifuser/miniconda3/lib/python3.10/site-packages/nnsight/intervention/envoy.py", line 733, in interleave
    fn(*args, **kwargs)
  File "/u/svcndifuser/miniconda3/lib/python3.10/site-packages/nnsight/modeling/language.py", line 173, in __nnsight_generate__
    output = self._model.generate(*args, streamer=streamer, **kwargs)
  File "/u/svcndifuser/miniconda3/lib/python3.10/site-packages/torch/utils/_contextlib.py", line 116, in decorate_context
    return func(*args, **kwargs)
  File "/u/svcndifuser/miniconda3/lib/python3.10/site-packages/transformers/generation/utils.py", line 2629, in generate
    result = self._sample(
  File "/u/svcndifuser/miniconda3/lib/python3.10/site-packages/transformers/generation/utils.py", line 3629, in _sample
    next_token_scores = logits_processor(input_ids, next_token_logits)
  File "/u/svcndifuser/miniconda3/lib/python3.10/site-packages/transformers/generation/logits_process.py", line 93, in __call__
    scores = processor(input_ids, scores)
  File "/u/svcndifuser/miniconda3/lib/python3.10/site-packages/transformers/generation/logits_process.py", line 518, in __call__
    sorted_logits, sorted_indices = torch.sort(scores, descending=False)

OutOfMemoryError: CUDA out of memory. Tried to allocate 54.00 MiB. GPU 0 has a total capacity of 44.34 GiB of which 30.81 MiB is free. Including non-PyTorch memory, this process has 44.30 GiB memory in use. Of the allocated memory 42.04 GiB is allocated by PyTorch, and 1.94 GiB is reserved by PyTorch but unallocated. If reserved but unallocated memory is large try setting PYTORCH_CUDA_ALLOC_CONF=expandable_segments:True to avoid fragmentation.  See documentation for Memory Management  (https://pytorch.org/docs/stable/notes/cuda.html#environment-variables)



Traceback (most recent call last):
  File "/u/svcndifuser/ndif-deployment/repos/prod/ndif/src/services/ray/src/ray/nn/sandbox.py", line 14, in run
    tracer.execute(fn)
  File "/u/svcndifuser/miniconda3/lib/python3.10/site-packages/nnsight/intervention/tracing/tracer.py", line 385, in execute
    self.model.interleave(self.fn, *args, **kwargs)
  File "/u/svcndifuser/miniconda3/lib/python3.10/site-packages/nnsight/modeling/mixins/meta.py", line 76, in interleave
    return super().interleave(fn, *args, **kwargs)
  File "/u/svcndifuser/miniconda3/lib/python3.10/site-packages/nnsight/intervention/envoy.py", line 733, in interleave
    fn(*args, **kwargs)
  File "/u/svcndifuser/miniconda3/lib/python3.10/site-packages/nnsight/modeling/language.py", line 173, in __nnsight_generate__
    output = self._model.generate(*args, streamer=streamer, **kwargs)
  File "/u/svcndifuser/miniconda3/lib/python3.10/site-packages/torch/utils/_contextlib.py", line 116, in decorate_context
    return func(*args, **kwargs)
  File "/u/svcndifuser/miniconda3/lib/python3.10/site-packages/transformers/generation/utils.py", line 2629, in generate
    result = self._sample(
  File "/u/svcndifuser/miniconda3/lib/python3.10/site-packages/transformers/generation/utils.py", line 3629, in _sample
    next_token_scores = logits_processor(input_ids, next_token_logits)
  File "/u/svcndifuser/miniconda3/lib/python3.10/site-packages/transformers/generation/logits_process.py", line 93, in __call__
    scores = processor(input_ids, scores)
  File "/u/svcndifuser/miniconda3/lib/python3.10/site-packages/transformers/generation/logits_process.py", line 518, in __call__
    sorted_logits, sorted_indices = torch.sort(scores, descending=False)

OutOfMemoryError: CUDA out of memory. Tried to allocate 54.00 MiB. GPU 0 has a total capacity of 44.34 GiB of which 30.81 MiB is free. Including non-PyTorch memory, this process has 44.30 GiB memory in use. Of the allocated memory 42.04 GiB is allocated by PyTorch, and 1.94 GiB is reserved by PyTorch but unallocated. If reserved but unallocated memory is large try setting PYTORCH_CUDA_ALLOC_CONF=expandable_segments:True to avoid fragmentation.  See documentation for Memory Management  (https://pytorch.org/docs/stable/notes/cuda.html#environment-variables)
Remote exception.

[2025-08-29 19:08:52] [6bd56bfd-ea3e-4fb0-bbb6-84d2116119a3] RECEIVED   : Your job has been received and is waiting to be queued.
[2025-08-29 19:08:52] [6bd56bfd-ea3e-4fb0-bbb6-84d2116119a3] QUEUED     : Your job has been recieved by the coordinator and is waiting to be queued.
[2025-08-29 19:08:52] [6bd56bfd-ea3e-4fb0-bbb6-84d2116119a3] QUEUED     : Task 6bd56bfd-ea3e-4fb0-bbb6-84d2116119a3 has been added to the queue. Currently at position 1
[2025-08-29 19:08:52] [6bd56bfd-ea3e-4fb0-bbb6-84d2116119a3] QUEUED     : Dispatching task...
[2025-08-29 19:08:52] [6bd56bfd-ea3e-4fb0-bbb6-84d2116119a3] RUNNING    : Your job has started running.
[2025-08-29 19:09:32] [6bd56bfd-ea3e-4fb0-bbb6-84d2116119a3] COMPLETED  : Your job has been completed.

Downloading result:   0%|          | 0.00/227M [00:00<?, ?B/s]

[2025-08-29 19:09:42] [30adcacd-8d48-40c4-8250-1ccd70c3cd18] RECEIVED   : Your job has been received and is waiting to be queued.
[2025-08-29 19:09:42] [30adcacd-8d48-40c4-8250-1ccd70c3cd18] QUEUED     : Your job has been recieved by the coordinator and is waiting to be queued.
[2025-08-29 19:09:42] [30adcacd-8d48-40c4-8250-1ccd70c3cd18] QUEUED     : Task 30adcacd-8d48-40c4-8250-1ccd70c3cd18 has been added to the queue. Currently at position 1
[2025-08-29 19:09:42] [30adcacd-8d48-40c4-8250-1ccd70c3cd18] QUEUED     : Dispatching task...
[2025-08-29 19:09:43] [30adcacd-8d48-40c4-8250-1ccd70c3cd18] RUNNING    : Your job has started running.

Error on problem 217: Traceback (most recent call last):
  File "/u/svcndifuser/ndif-deployment/repos/prod/ndif/src/services/ray/src/ray/deployments/modeling/base.py", line 213, in __call__
    result = await job_task
  File "/u/svcndifuser/miniconda3/lib/python3.10/asyncio/threads.py", line 25, in to_thread
    return await loop.run_in_executor(None, func_call)
  File "/u/svcndifuser/miniconda3/lib/python3.10/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/u/svcndifuser/miniconda3/lib/python3.10/site-packages/ray/util/tracing/tracing_helper.py", line 463, in _resume_span
    return method(self, *_args, **_kwargs)
  File "/u/svcndifuser/ndif-deployment/repos/prod/ndif/src/services/ray/src/ray/deployments/modeling/base.py", line 283, in execute
    result = RemoteExecutionBackend(request.interventions, self.execution_protector)(request.tracer)
  File "/u/svcndifuser/ndif-deployment/repos/prod/ndif/src/services/ray/src/ray/nn/backend.py", line 27, in __call__
    run(tracer, self.fn)
  File "/u/svcndifuser/ndif-deployment/repos/prod/ndif/src/services/ray/src/ray/nn/sandbox.py", line 16, in run
    raise wrap_exception(e,tracer.info) from None
nnsight.NNsightException:

Traceback (most recent call last):
  File "/u/svcndifuser/ndif-deployment/repos/prod/ndif/src/services/ray/src/ray/nn/sandbox.py", line 14, in run
    tracer.execute(fn)
  File "/u/svcndifuser/miniconda3/lib/python3.10/site-packages/nnsight/intervention/tracing/tracer.py", line 385, in execute
    self.model.interleave(self.fn, *args, **kwargs)
  File "/u/svcndifuser/miniconda3/lib/python3.10/site-packages/nnsight/modeling/mixins/meta.py", line 76, in interleave
    return super().interleave(fn, *args, **kwargs)
  File "/u/svcndifuser/miniconda3/lib/python3.10/site-packages/nnsight/intervention/envoy.py", line 733, in interleave
    fn(*args, **kwargs)
  File "/u/svcndifuser/miniconda3/lib/python3.10/site-packages/nnsight/modeling/language.py", line 173, in __nnsight_generate__
    output = self._model.generate(*args, streamer=streamer, **kwargs)
  File "/u/svcndifuser/miniconda3/lib/python3.10/site-packages/torch/utils/_contextlib.py", line 116, in decorate_context
    return func(*args, **kwargs)
  File "/u/svcndifuser/miniconda3/lib/python3.10/site-packages/transformers/generation/utils.py", line 2629, in generate
    result = self._sample(
  File "/u/svcndifuser/miniconda3/lib/python3.10/site-packages/transformers/generation/utils.py", line 3613, in _sample
    outputs = model_forward(**model_inputs, return_dict=True)
  File "/u/svcndifuser/miniconda3/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1751, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/u/svcndifuser/miniconda3/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1857, in _call_impl
    return inner()
  File "/u/svcndifuser/miniconda3/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1805, in inner
    result = forward_call(*args, **kwargs)
  File "/u/svcndifuser/miniconda3/lib/python3.10/site-packages/nnsight/intervention/interleaver.py", line 133, in skippable_forward
    return forward(*args, **kwargs)
  File "/u/svcndifuser/miniconda3/lib/python3.10/site-packages/transformers/utils/generic.py", line 959, in wrapper
    output = func(self, *args, **kwargs)
  File "/u/svcndifuser/miniconda3/lib/python3.10/site-packages/transformers/models/llama/modeling_llama.py", line 460, in forward
    outputs: BaseModelOutputWithPast = self.model(
  File "/u/svcndifuser/miniconda3/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1751, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/u/svcndifuser/miniconda3/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1857, in _call_impl
    return inner()
  File "/u/svcndifuser/miniconda3/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1805, in inner
    result = forward_call(*args, **kwargs)
  File "/u/svcndifuser/miniconda3/lib/python3.10/site-packages/nnsight/intervention/interleaver.py", line 133, in skippable_forward
    return forward(*args, **kwargs)
  File "/u/svcndifuser/miniconda3/lib/python3.10/site-packages/transformers/utils/generic.py", line 1083, in wrapper
    outputs = func(self, *args, **kwargs)
  File "/u/svcndifuser/miniconda3/lib/python3.10/site-packages/transformers/models/llama/modeling_llama.py", line 390, in forward
    hidden_states = decoder_layer(
  File "/u/svcndifuser/miniconda3/lib/python3.10/site-packages/transformers/modeling_layers.py", line 94, in __call__
    return super().__call__(*args, **kwargs)
  File "/u/svcndifuser/miniconda3/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1751, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/u/svcndifuser/miniconda3/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1857, in _call_impl
    return inner()
  File "/u/svcndifuser/miniconda3/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1805, in inner
    result = forward_call(*args, **kwargs)
  File "/u/svcndifuser/miniconda3/lib/python3.10/site-packages/nnsight/intervention/interleaver.py", line 133, in skippable_forward
    return forward(*args, **kwargs)
  File "/u/svcndifuser/miniconda3/lib/python3.10/site-packages/transformers/models/llama/modeling_llama.py", line 289, in forward
    hidden_states, _ = self.self_attn(
  File "/u/svcndifuser/miniconda3/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1751, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/u/svcndifuser/miniconda3/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1857, in _call_impl
    return inner()
  File "/u/svcndifuser/miniconda3/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1805, in inner
    result = forward_call(*args, **kwargs)
  File "/u/svcndifuser/miniconda3/lib/python3.10/site-packages/nnsight/intervention/interleaver.py", line 133, in skippable_forward
    return forward(*args, **kwargs)
  File "/u/svcndifuser/miniconda3/lib/python3.10/site-packages/transformers/models/llama/modeling_llama.py", line 242, in forward
    key_states, value_states = past_key_value.update(key_states, value_states, self.layer_idx, cache_kwargs)
  File "/u/svcndifuser/miniconda3/lib/python3.10/site-packages/transformers/cache_utils.py", line 992, in _wrapped_update
    key_tensors, value_tensors = fn(self, key_states, value_states, layer_idx, cache_kwargs)
  File "/u/svcndifuser/miniconda3/lib/python3.10/site-packages/transformers/cache_utils.py", line 1201, in update
    return self.layers[layer_idx].update(key_states, value_states, cache_kwargs)
  File "/u/svcndifuser/miniconda3/lib/python3.10/site-packages/transformers/cache_utils.py", line 102, in update
    self.keys = torch.cat([self.keys, key_states], dim=-2)

OutOfMemoryError: CUDA out of memory. Tried to allocate 106.00 MiB. GPU 0 has a total capacity of 44.34 GiB of which 104.81 MiB is free. Including non-PyTorch memory, this process has 44.23 GiB memory in use. Of the allocated memory 41.32 GiB is allocated by PyTorch, and 2.60 GiB is reserved by PyTorch but unallocated. If reserved but unallocated memory is large try setting PYTORCH_CUDA_ALLOC_CONF=expandable_segments:True to avoid fragmentation.  See documentation for Memory Management  (https://pytorch.org/docs/stable/notes/cuda.html#environment-variables)



Traceback (most recent call last):
  File "/u/svcndifuser/ndif-deployment/repos/prod/ndif/src/services/ray/src/ray/nn/sandbox.py", line 14, in run
    tracer.execute(fn)
  File "/u/svcndifuser/miniconda3/lib/python3.10/site-packages/nnsight/intervention/tracing/tracer.py", line 385, in execute
    self.model.interleave(self.fn, *args, **kwargs)
  File "/u/svcndifuser/miniconda3/lib/python3.10/site-packages/nnsight/modeling/mixins/meta.py", line 76, in interleave
    return super().interleave(fn, *args, **kwargs)
  File "/u/svcndifuser/miniconda3/lib/python3.10/site-packages/nnsight/intervention/envoy.py", line 733, in interleave
    fn(*args, **kwargs)
  File "/u/svcndifuser/miniconda3/lib/python3.10/site-packages/nnsight/modeling/language.py", line 173, in __nnsight_generate__
    output = self._model.generate(*args, streamer=streamer, **kwargs)
  File "/u/svcndifuser/miniconda3/lib/python3.10/site-packages/torch/utils/_contextlib.py", line 116, in decorate_context
    return func(*args, **kwargs)
  File "/u/svcndifuser/miniconda3/lib/python3.10/site-packages/transformers/generation/utils.py", line 2629, in generate
    result = self._sample(
  File "/u/svcndifuser/miniconda3/lib/python3.10/site-packages/transformers/generation/utils.py", line 3613, in _sample
    outputs = model_forward(**model_inputs, return_dict=True)
  File "/u/svcndifuser/miniconda3/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1751, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/u/svcndifuser/miniconda3/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1857, in _call_impl
    return inner()
  File "/u/svcndifuser/miniconda3/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1805, in inner
    result = forward_call(*args, **kwargs)
  File "/u/svcndifuser/miniconda3/lib/python3.10/site-packages/nnsight/intervention/interleaver.py", line 133, in skippable_forward
    return forward(*args, **kwargs)
  File "/u/svcndifuser/miniconda3/lib/python3.10/site-packages/transformers/utils/generic.py", line 959, in wrapper
    output = func(self, *args, **kwargs)
  File "/u/svcndifuser/miniconda3/lib/python3.10/site-packages/transformers/models/llama/modeling_llama.py", line 460, in forward
    outputs: BaseModelOutputWithPast = self.model(
  File "/u/svcndifuser/miniconda3/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1751, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/u/svcndifuser/miniconda3/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1857, in _call_impl
    return inner()
  File "/u/svcndifuser/miniconda3/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1805, in inner
    result = forward_call(*args, **kwargs)
  File "/u/svcndifuser/miniconda3/lib/python3.10/site-packages/nnsight/intervention/interleaver.py", line 133, in skippable_forward
    return forward(*args, **kwargs)
  File "/u/svcndifuser/miniconda3/lib/python3.10/site-packages/transformers/utils/generic.py", line 1083, in wrapper
    outputs = func(self, *args, **kwargs)
  File "/u/svcndifuser/miniconda3/lib/python3.10/site-packages/transformers/models/llama/modeling_llama.py", line 390, in forward
    hidden_states = decoder_layer(
  File "/u/svcndifuser/miniconda3/lib/python3.10/site-packages/transformers/modeling_layers.py", line 94, in __call__
    return super().__call__(*args, **kwargs)
  File "/u/svcndifuser/miniconda3/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1751, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/u/svcndifuser/miniconda3/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1857, in _call_impl
    return inner()
  File "/u/svcndifuser/miniconda3/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1805, in inner
    result = forward_call(*args, **kwargs)
  File "/u/svcndifuser/miniconda3/lib/python3.10/site-packages/nnsight/intervention/interleaver.py", line 133, in skippable_forward
    return forward(*args, **kwargs)
  File "/u/svcndifuser/miniconda3/lib/python3.10/site-packages/transformers/models/llama/modeling_llama.py", line 289, in forward
    hidden_states, _ = self.self_attn(
  File "/u/svcndifuser/miniconda3/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1751, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/u/svcndifuser/miniconda3/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1857, in _call_impl
    return inner()
  File "/u/svcndifuser/miniconda3/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1805, in inner
    result = forward_call(*args, **kwargs)
  File "/u/svcndifuser/miniconda3/lib/python3.10/site-packages/nnsight/intervention/interleaver.py", line 133, in skippable_forward
    return forward(*args, **kwargs)
  File "/u/svcndifuser/miniconda3/lib/python3.10/site-packages/transformers/models/llama/modeling_llama.py", line 242, in forward
    key_states, value_states = past_key_value.update(key_states, value_states, self.layer_idx, cache_kwargs)
  File "/u/svcndifuser/miniconda3/lib/python3.10/site-packages/transformers/cache_utils.py", line 992, in _wrapped_update
    key_tensors, value_tensors = fn(self, key_states, value_states, layer_idx, cache_kwargs)
  File "/u/svcndifuser/miniconda3/lib/python3.10/site-packages/transformers/cache_utils.py", line 1201, in update
    return self.layers[layer_idx].update(key_states, value_states, cache_kwargs)
  File "/u/svcndifuser/miniconda3/lib/python3.10/site-packages/transformers/cache_utils.py", line 102, in update
    self.keys = torch.cat([self.keys, key_states], dim=-2)

OutOfMemoryError: CUDA out of memory. Tried to allocate 106.00 MiB. GPU 0 has a total capacity of 44.34 GiB of which 104.81 MiB is free. Including non-PyTorch memory, this process has 44.23 GiB memory in use. Of the allocated memory 41.32 GiB is allocated by PyTorch, and 2.60 GiB is reserved by PyTorch but unallocated. If reserved but unallocated memory is large try setting PYTORCH_CUDA_ALLOC_CONF=expandable_segments:True to avoid fragmentation.  See documentation for Memory Management  (https://pytorch.org/docs/stable/notes/cuda.html#environment-variables)
Remote exception.

[2025-08-29 19:11:18] [3f199f26-64be-473b-bf98-deb5b71c4162] RECEIVED   : Your job has been received and is waiting to be queued.
[2025-08-29 19:11:18] [3f199f26-64be-473b-bf98-deb5b71c4162] QUEUED     : Your job has been recieved by the coordinator and is waiting to be queued.
[2025-08-29 19:11:18] [3f199f26-64be-473b-bf98-deb5b71c4162] QUEUED     : Task 3f199f26-64be-473b-bf98-deb5b71c4162 has been added to the queue. Currently at position 1
[2025-08-29 19:11:18] [3f199f26-64be-473b-bf98-deb5b71c4162] QUEUED     : Dispatching task...
[2025-08-29 19:11:18] [3f199f26-64be-473b-bf98-deb5b71c4162] RUNNING    : Your job has started running.

Error on problem 218: Traceback (most recent call last):
  File "/u/svcndifuser/ndif-deployment/repos/prod/ndif/src/services/ray/src/ray/deployments/modeling/base.py", line 213, in __call__
    result = await job_task
  File "/u/svcndifuser/miniconda3/lib/python3.10/asyncio/threads.py", line 25, in to_thread
    return await loop.run_in_executor(None, func_call)
  File "/u/svcndifuser/miniconda3/lib/python3.10/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/u/svcndifuser/miniconda3/lib/python3.10/site-packages/ray/util/tracing/tracing_helper.py", line 463, in _resume_span
    return method(self, *_args, **_kwargs)
  File "/u/svcndifuser/ndif-deployment/repos/prod/ndif/src/services/ray/src/ray/deployments/modeling/base.py", line 283, in execute
    result = RemoteExecutionBackend(request.interventions, self.execution_protector)(request.tracer)
  File "/u/svcndifuser/ndif-deployment/repos/prod/ndif/src/services/ray/src/ray/nn/backend.py", line 27, in __call__
    run(tracer, self.fn)
  File "/u/svcndifuser/ndif-deployment/repos/prod/ndif/src/services/ray/src/ray/nn/sandbox.py", line 16, in run
    raise wrap_exception(e,tracer.info) from None
nnsight.NNsightException:

Traceback (most recent call last):
  File "/u/svcndifuser/ndif-deployment/repos/prod/ndif/src/services/ray/src/ray/nn/sandbox.py", line 14, in run
    tracer.execute(fn)
  File "/u/svcndifuser/miniconda3/lib/python3.10/site-packages/nnsight/intervention/tracing/tracer.py", line 385, in execute
    self.model.interleave(self.fn, *args, **kwargs)
  File "/u/svcndifuser/miniconda3/lib/python3.10/site-packages/nnsight/modeling/mixins/meta.py", line 76, in interleave
    return super().interleave(fn, *args, **kwargs)
  File "/u/svcndifuser/miniconda3/lib/python3.10/site-packages/nnsight/intervention/envoy.py", line 733, in interleave
    fn(*args, **kwargs)
  File "/u/svcndifuser/miniconda3/lib/python3.10/site-packages/nnsight/modeling/language.py", line 173, in __nnsight_generate__
    output = self._model.generate(*args, streamer=streamer, **kwargs)
  File "/u/svcndifuser/miniconda3/lib/python3.10/site-packages/torch/utils/_contextlib.py", line 116, in decorate_context
    return func(*args, **kwargs)
  File "/u/svcndifuser/miniconda3/lib/python3.10/site-packages/transformers/generation/utils.py", line 2629, in generate
    result = self._sample(
  File "/u/svcndifuser/miniconda3/lib/python3.10/site-packages/transformers/generation/utils.py", line 3610, in _sample
    outputs = self(**model_inputs, return_dict=True)
  File "/u/svcndifuser/miniconda3/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1751, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/u/svcndifuser/miniconda3/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1857, in _call_impl
    return inner()
  File "/u/svcndifuser/miniconda3/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1805, in inner
    result = forward_call(*args, **kwargs)
  File "/u/svcndifuser/miniconda3/lib/python3.10/site-packages/nnsight/intervention/interleaver.py", line 133, in skippable_forward
    return forward(*args, **kwargs)
  File "/u/svcndifuser/miniconda3/lib/python3.10/site-packages/transformers/utils/generic.py", line 959, in wrapper
    output = func(self, *args, **kwargs)
  File "/u/svcndifuser/miniconda3/lib/python3.10/site-packages/transformers/models/llama/modeling_llama.py", line 460, in forward
    outputs: BaseModelOutputWithPast = self.model(
  File "/u/svcndifuser/miniconda3/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1751, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/u/svcndifuser/miniconda3/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1857, in _call_impl
    return inner()
  File "/u/svcndifuser/miniconda3/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1805, in inner
    result = forward_call(*args, **kwargs)
  File "/u/svcndifuser/miniconda3/lib/python3.10/site-packages/nnsight/intervention/interleaver.py", line 133, in skippable_forward
    return forward(*args, **kwargs)
  File "/u/svcndifuser/miniconda3/lib/python3.10/site-packages/transformers/utils/generic.py", line 1083, in wrapper
    outputs = func(self, *args, **kwargs)
  File "/u/svcndifuser/miniconda3/lib/python3.10/site-packages/transformers/models/llama/modeling_llama.py", line 390, in forward
    hidden_states = decoder_layer(
  File "/u/svcndifuser/miniconda3/lib/python3.10/site-packages/transformers/modeling_layers.py", line 94, in __call__
    return super().__call__(*args, **kwargs)
  File "/u/svcndifuser/miniconda3/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1751, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/u/svcndifuser/miniconda3/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1857, in _call_impl
    return inner()
  File "/u/svcndifuser/miniconda3/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1805, in inner
    result = forward_call(*args, **kwargs)
  File "/u/svcndifuser/miniconda3/lib/python3.10/site-packages/nnsight/intervention/interleaver.py", line 133, in skippable_forward
    return forward(*args, **kwargs)
  File "/u/svcndifuser/miniconda3/lib/python3.10/site-packages/transformers/models/llama/modeling_llama.py", line 304, in forward
    hidden_states = self.mlp(hidden_states)
  File "/u/svcndifuser/miniconda3/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1751, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/u/svcndifuser/miniconda3/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1857, in _call_impl
    return inner()
  File "/u/svcndifuser/miniconda3/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1805, in inner
    result = forward_call(*args, **kwargs)
  File "/u/svcndifuser/miniconda3/lib/python3.10/site-packages/nnsight/intervention/interleaver.py", line 133, in skippable_forward
    return forward(*args, **kwargs)
  File "/u/svcndifuser/miniconda3/lib/python3.10/site-packages/transformers/models/llama/modeling_llama.py", line 152, in forward
    down_proj = self.down_proj(self.act_fn(self.gate_proj(x)) * self.up_proj(x))

OutOfMemoryError: CUDA out of memory. Tried to allocate 76.00 MiB. GPU 0 has a total capacity of 44.34 GiB of which 26.81 MiB is free. Including non-PyTorch memory, this process has 44.30 GiB memory in use. Of the allocated memory 41.54 GiB is allocated by PyTorch, and 2.45 GiB is reserved by PyTorch but unallocated. If reserved but unallocated memory is large try setting PYTORCH_CUDA_ALLOC_CONF=expandable_segments:True to avoid fragmentation.  See documentation for Memory Management  (https://pytorch.org/docs/stable/notes/cuda.html#environment-variables)



Traceback (most recent call last):
  File "/u/svcndifuser/ndif-deployment/repos/prod/ndif/src/services/ray/src/ray/nn/sandbox.py", line 14, in run
    tracer.execute(fn)
  File "/u/svcndifuser/miniconda3/lib/python3.10/site-packages/nnsight/intervention/tracing/tracer.py", line 385, in execute
    self.model.interleave(self.fn, *args, **kwargs)
  File "/u/svcndifuser/miniconda3/lib/python3.10/site-packages/nnsight/modeling/mixins/meta.py", line 76, in interleave
    return super().interleave(fn, *args, **kwargs)
  File "/u/svcndifuser/miniconda3/lib/python3.10/site-packages/nnsight/intervention/envoy.py", line 733, in interleave
    fn(*args, **kwargs)
  File "/u/svcndifuser/miniconda3/lib/python3.10/site-packages/nnsight/modeling/language.py", line 173, in __nnsight_generate__
    output = self._model.generate(*args, streamer=streamer, **kwargs)
  File "/u/svcndifuser/miniconda3/lib/python3.10/site-packages/torch/utils/_contextlib.py", line 116, in decorate_context
    return func(*args, **kwargs)
  File "/u/svcndifuser/miniconda3/lib/python3.10/site-packages/transformers/generation/utils.py", line 2629, in generate
    result = self._sample(
  File "/u/svcndifuser/miniconda3/lib/python3.10/site-packages/transformers/generation/utils.py", line 3610, in _sample
    outputs = self(**model_inputs, return_dict=True)
  File "/u/svcndifuser/miniconda3/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1751, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/u/svcndifuser/miniconda3/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1857, in _call_impl
    return inner()
  File "/u/svcndifuser/miniconda3/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1805, in inner
    result = forward_call(*args, **kwargs)
  File "/u/svcndifuser/miniconda3/lib/python3.10/site-packages/nnsight/intervention/interleaver.py", line 133, in skippable_forward
    return forward(*args, **kwargs)
  File "/u/svcndifuser/miniconda3/lib/python3.10/site-packages/transformers/utils/generic.py", line 959, in wrapper
    output = func(self, *args, **kwargs)
  File "/u/svcndifuser/miniconda3/lib/python3.10/site-packages/transformers/models/llama/modeling_llama.py", line 460, in forward
    outputs: BaseModelOutputWithPast = self.model(
  File "/u/svcndifuser/miniconda3/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1751, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/u/svcndifuser/miniconda3/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1857, in _call_impl
    return inner()
  File "/u/svcndifuser/miniconda3/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1805, in inner
    result = forward_call(*args, **kwargs)
  File "/u/svcndifuser/miniconda3/lib/python3.10/site-packages/nnsight/intervention/interleaver.py", line 133, in skippable_forward
    return forward(*args, **kwargs)
  File "/u/svcndifuser/miniconda3/lib/python3.10/site-packages/transformers/utils/generic.py", line 1083, in wrapper
    outputs = func(self, *args, **kwargs)
  File "/u/svcndifuser/miniconda3/lib/python3.10/site-packages/transformers/models/llama/modeling_llama.py", line 390, in forward
    hidden_states = decoder_layer(
  File "/u/svcndifuser/miniconda3/lib/python3.10/site-packages/transformers/modeling_layers.py", line 94, in __call__
    return super().__call__(*args, **kwargs)
  File "/u/svcndifuser/miniconda3/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1751, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/u/svcndifuser/miniconda3/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1857, in _call_impl
    return inner()
  File "/u/svcndifuser/miniconda3/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1805, in inner
    result = forward_call(*args, **kwargs)
  File "/u/svcndifuser/miniconda3/lib/python3.10/site-packages/nnsight/intervention/interleaver.py", line 133, in skippable_forward
    return forward(*args, **kwargs)
  File "/u/svcndifuser/miniconda3/lib/python3.10/site-packages/transformers/models/llama/modeling_llama.py", line 304, in forward
    hidden_states = self.mlp(hidden_states)
  File "/u/svcndifuser/miniconda3/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1751, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/u/svcndifuser/miniconda3/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1857, in _call_impl
    return inner()
  File "/u/svcndifuser/miniconda3/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1805, in inner
    result = forward_call(*args, **kwargs)
  File "/u/svcndifuser/miniconda3/lib/python3.10/site-packages/nnsight/intervention/interleaver.py", line 133, in skippable_forward
    return forward(*args, **kwargs)
  File "/u/svcndifuser/miniconda3/lib/python3.10/site-packages/transformers/models/llama/modeling_llama.py", line 152, in forward
    down_proj = self.down_proj(self.act_fn(self.gate_proj(x)) * self.up_proj(x))

OutOfMemoryError: CUDA out of memory. Tried to allocate 76.00 MiB. GPU 0 has a total capacity of 44.34 GiB of which 26.81 MiB is free. Including non-PyTorch memory, this process has 44.30 GiB memory in use. Of the allocated memory 41.54 GiB is allocated by PyTorch, and 2.45 GiB is reserved by PyTorch but unallocated. If reserved but unallocated memory is large try setting PYTORCH_CUDA_ALLOC_CONF=expandable_segments:True to avoid fragmentation.  See documentation for Memory Management  (https://pytorch.org/docs/stable/notes/cuda.html#environment-variables)
Remote exception.

[2025-08-29 19:11:20] [c51d6fab-29d3-4dc3-a56c-a4f5190a168d] RECEIVED   : Your job has been received and is waiting to be queued.
[2025-08-29 19:11:20] [c51d6fab-29d3-4dc3-a56c-a4f5190a168d] QUEUED     : Your job has been recieved by the coordinator and is waiting to be queued.
[2025-08-29 19:11:20] [c51d6fab-29d3-4dc3-a56c-a4f5190a168d] QUEUED     : Task c51d6fab-29d3-4dc3-a56c-a4f5190a168d has been added to the queue. Currently at position 1
[2025-08-29 19:11:20] [c51d6fab-29d3-4dc3-a56c-a4f5190a168d] QUEUED     : Dispatching task...
[2025-08-29 19:11:20] [c51d6fab-29d3-4dc3-a56c-a4f5190a168d] RUNNING    : Your job has started running.

Error on problem 219: Traceback (most recent call last):
  File "/u/svcndifuser/ndif-deployment/repos/prod/ndif/src/services/ray/src/ray/deployments/modeling/base.py", line 213, in __call__
    result = await job_task
  File "/u/svcndifuser/miniconda3/lib/python3.10/asyncio/threads.py", line 25, in to_thread
    return await loop.run_in_executor(None, func_call)
  File "/u/svcndifuser/miniconda3/lib/python3.10/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/u/svcndifuser/miniconda3/lib/python3.10/site-packages/ray/util/tracing/tracing_helper.py", line 463, in _resume_span
    return method(self, *_args, **_kwargs)
  File "/u/svcndifuser/ndif-deployment/repos/prod/ndif/src/services/ray/src/ray/deployments/modeling/base.py", line 283, in execute
    result = RemoteExecutionBackend(request.interventions, self.execution_protector)(request.tracer)
  File "/u/svcndifuser/ndif-deployment/repos/prod/ndif/src/services/ray/src/ray/nn/backend.py", line 27, in __call__
    run(tracer, self.fn)
  File "/u/svcndifuser/ndif-deployment/repos/prod/ndif/src/services/ray/src/ray/nn/sandbox.py", line 16, in run
    raise wrap_exception(e,tracer.info) from None
nnsight.NNsightException:

Traceback (most recent call last):
  File "/u/svcndifuser/ndif-deployment/repos/prod/ndif/src/services/ray/src/ray/nn/sandbox.py", line 14, in run
    tracer.execute(fn)
  File "/u/svcndifuser/miniconda3/lib/python3.10/site-packages/nnsight/intervention/tracing/tracer.py", line 385, in execute
    self.model.interleave(self.fn, *args, **kwargs)
  File "/u/svcndifuser/miniconda3/lib/python3.10/site-packages/nnsight/modeling/mixins/meta.py", line 76, in interleave
    return super().interleave(fn, *args, **kwargs)
  File "/u/svcndifuser/miniconda3/lib/python3.10/site-packages/nnsight/intervention/envoy.py", line 733, in interleave
    fn(*args, **kwargs)
  File "/u/svcndifuser/miniconda3/lib/python3.10/site-packages/nnsight/modeling/language.py", line 173, in __nnsight_generate__
    output = self._model.generate(*args, streamer=streamer, **kwargs)
  File "/u/svcndifuser/miniconda3/lib/python3.10/site-packages/torch/utils/_contextlib.py", line 116, in decorate_context
    return func(*args, **kwargs)
  File "/u/svcndifuser/miniconda3/lib/python3.10/site-packages/transformers/generation/utils.py", line 2629, in generate
    result = self._sample(
  File "/u/svcndifuser/miniconda3/lib/python3.10/site-packages/transformers/generation/utils.py", line 3610, in _sample
    outputs = self(**model_inputs, return_dict=True)
  File "/u/svcndifuser/miniconda3/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1751, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/u/svcndifuser/miniconda3/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1857, in _call_impl
    return inner()
  File "/u/svcndifuser/miniconda3/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1805, in inner
    result = forward_call(*args, **kwargs)
  File "/u/svcndifuser/miniconda3/lib/python3.10/site-packages/nnsight/intervention/interleaver.py", line 133, in skippable_forward
    return forward(*args, **kwargs)
  File "/u/svcndifuser/miniconda3/lib/python3.10/site-packages/transformers/utils/generic.py", line 959, in wrapper
    output = func(self, *args, **kwargs)
  File "/u/svcndifuser/miniconda3/lib/python3.10/site-packages/transformers/models/llama/modeling_llama.py", line 460, in forward
    outputs: BaseModelOutputWithPast = self.model(
  File "/u/svcndifuser/miniconda3/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1751, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/u/svcndifuser/miniconda3/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1857, in _call_impl
    return inner()
  File "/u/svcndifuser/miniconda3/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1805, in inner
    result = forward_call(*args, **kwargs)
  File "/u/svcndifuser/miniconda3/lib/python3.10/site-packages/nnsight/intervention/interleaver.py", line 133, in skippable_forward
    return forward(*args, **kwargs)
  File "/u/svcndifuser/miniconda3/lib/python3.10/site-packages/transformers/utils/generic.py", line 1083, in wrapper
    outputs = func(self, *args, **kwargs)
  File "/u/svcndifuser/miniconda3/lib/python3.10/site-packages/transformers/models/llama/modeling_llama.py", line 390, in forward
    hidden_states = decoder_layer(
  File "/u/svcndifuser/miniconda3/lib/python3.10/site-packages/transformers/modeling_layers.py", line 94, in __call__
    return super().__call__(*args, **kwargs)
  File "/u/svcndifuser/miniconda3/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1751, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/u/svcndifuser/miniconda3/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1857, in _call_impl
    return inner()
  File "/u/svcndifuser/miniconda3/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1805, in inner
    result = forward_call(*args, **kwargs)
  File "/u/svcndifuser/miniconda3/lib/python3.10/site-packages/nnsight/intervention/interleaver.py", line 133, in skippable_forward
    return forward(*args, **kwargs)
  File "/u/svcndifuser/miniconda3/lib/python3.10/site-packages/transformers/models/llama/modeling_llama.py", line 304, in forward
    hidden_states = self.mlp(hidden_states)
  File "/u/svcndifuser/miniconda3/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1751, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/u/svcndifuser/miniconda3/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1857, in _call_impl
    return inner()
  File "/u/svcndifuser/miniconda3/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1805, in inner
    result = forward_call(*args, **kwargs)
  File "/u/svcndifuser/miniconda3/lib/python3.10/site-packages/nnsight/intervention/interleaver.py", line 133, in skippable_forward
    return forward(*args, **kwargs)
  File "/u/svcndifuser/miniconda3/lib/python3.10/site-packages/transformers/models/llama/modeling_llama.py", line 152, in forward
    down_proj = self.down_proj(self.act_fn(self.gate_proj(x)) * self.up_proj(x))

OutOfMemoryError: CUDA out of memory. Tried to allocate 714.00 MiB. GPU 0 has a total capacity of 44.34 GiB of which 450.81 MiB is free. Including non-PyTorch memory, this process has 43.89 GiB memory in use. Of the allocated memory 39.82 GiB is allocated by PyTorch, and 3.76 GiB is reserved by PyTorch but unallocated. If reserved but unallocated memory is large try setting PYTORCH_CUDA_ALLOC_CONF=expandable_segments:True to avoid fragmentation.  See documentation for Memory Management  (https://pytorch.org/docs/stable/notes/cuda.html#environment-variables)



Traceback (most recent call last):
  File "/u/svcndifuser/ndif-deployment/repos/prod/ndif/src/services/ray/src/ray/nn/sandbox.py", line 14, in run
    tracer.execute(fn)
  File "/u/svcndifuser/miniconda3/lib/python3.10/site-packages/nnsight/intervention/tracing/tracer.py", line 385, in execute
    self.model.interleave(self.fn, *args, **kwargs)
  File "/u/svcndifuser/miniconda3/lib/python3.10/site-packages/nnsight/modeling/mixins/meta.py", line 76, in interleave
    return super().interleave(fn, *args, **kwargs)
  File "/u/svcndifuser/miniconda3/lib/python3.10/site-packages/nnsight/intervention/envoy.py", line 733, in interleave
    fn(*args, **kwargs)
  File "/u/svcndifuser/miniconda3/lib/python3.10/site-packages/nnsight/modeling/language.py", line 173, in __nnsight_generate__
    output = self._model.generate(*args, streamer=streamer, **kwargs)
  File "/u/svcndifuser/miniconda3/lib/python3.10/site-packages/torch/utils/_contextlib.py", line 116, in decorate_context
    return func(*args, **kwargs)
  File "/u/svcndifuser/miniconda3/lib/python3.10/site-packages/transformers/generation/utils.py", line 2629, in generate
    result = self._sample(
  File "/u/svcndifuser/miniconda3/lib/python3.10/site-packages/transformers/generation/utils.py", line 3610, in _sample
    outputs = self(**model_inputs, return_dict=True)
  File "/u/svcndifuser/miniconda3/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1751, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/u/svcndifuser/miniconda3/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1857, in _call_impl
    return inner()
  File "/u/svcndifuser/miniconda3/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1805, in inner
    result = forward_call(*args, **kwargs)
  File "/u/svcndifuser/miniconda3/lib/python3.10/site-packages/nnsight/intervention/interleaver.py", line 133, in skippable_forward
    return forward(*args, **kwargs)
  File "/u/svcndifuser/miniconda3/lib/python3.10/site-packages/transformers/utils/generic.py", line 959, in wrapper
    output = func(self, *args, **kwargs)
  File "/u/svcndifuser/miniconda3/lib/python3.10/site-packages/transformers/models/llama/modeling_llama.py", line 460, in forward
    outputs: BaseModelOutputWithPast = self.model(
  File "/u/svcndifuser/miniconda3/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1751, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/u/svcndifuser/miniconda3/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1857, in _call_impl
    return inner()
  File "/u/svcndifuser/miniconda3/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1805, in inner
    result = forward_call(*args, **kwargs)
  File "/u/svcndifuser/miniconda3/lib/python3.10/site-packages/nnsight/intervention/interleaver.py", line 133, in skippable_forward
    return forward(*args, **kwargs)
  File "/u/svcndifuser/miniconda3/lib/python3.10/site-packages/transformers/utils/generic.py", line 1083, in wrapper
    outputs = func(self, *args, **kwargs)
  File "/u/svcndifuser/miniconda3/lib/python3.10/site-packages/transformers/models/llama/modeling_llama.py", line 390, in forward
    hidden_states = decoder_layer(
  File "/u/svcndifuser/miniconda3/lib/python3.10/site-packages/transformers/modeling_layers.py", line 94, in __call__
    return super().__call__(*args, **kwargs)
  File "/u/svcndifuser/miniconda3/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1751, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/u/svcndifuser/miniconda3/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1857, in _call_impl
    return inner()
  File "/u/svcndifuser/miniconda3/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1805, in inner
    result = forward_call(*args, **kwargs)
  File "/u/svcndifuser/miniconda3/lib/python3.10/site-packages/nnsight/intervention/interleaver.py", line 133, in skippable_forward
    return forward(*args, **kwargs)
  File "/u/svcndifuser/miniconda3/lib/python3.10/site-packages/transformers/models/llama/modeling_llama.py", line 304, in forward
    hidden_states = self.mlp(hidden_states)
  File "/u/svcndifuser/miniconda3/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1751, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/u/svcndifuser/miniconda3/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1857, in _call_impl
    return inner()
  File "/u/svcndifuser/miniconda3/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1805, in inner
    result = forward_call(*args, **kwargs)
  File "/u/svcndifuser/miniconda3/lib/python3.10/site-packages/nnsight/intervention/interleaver.py", line 133, in skippable_forward
    return forward(*args, **kwargs)
  File "/u/svcndifuser/miniconda3/lib/python3.10/site-packages/transformers/models/llama/modeling_llama.py", line 152, in forward
    down_proj = self.down_proj(self.act_fn(self.gate_proj(x)) * self.up_proj(x))

OutOfMemoryError: CUDA out of memory. Tried to allocate 714.00 MiB. GPU 0 has a total capacity of 44.34 GiB of which 450.81 MiB is free. Including non-PyTorch memory, this process has 43.89 GiB memory in use. Of the allocated memory 39.82 GiB is allocated by PyTorch, and 3.76 GiB is reserved by PyTorch but unallocated. If reserved but unallocated memory is large try setting PYTORCH_CUDA_ALLOC_CONF=expandable_segments:True to avoid fragmentation.  See documentation for Memory Management  (https://pytorch.org/docs/stable/notes/cuda.html#environment-variables)
Remote exception.

[2025-08-29 19:11:22] [2b768e4f-7010-4052-baf9-8379f2bade78] RECEIVED   : Your job has been received and is waiting to be queued.
[2025-08-29 19:11:22] [2b768e4f-7010-4052-baf9-8379f2bade78] QUEUED     : Your job has been recieved by the coordinator and is waiting to be queued.
[2025-08-29 19:11:22] [2b768e4f-7010-4052-baf9-8379f2bade78] QUEUED     : Task 2b768e4f-7010-4052-baf9-8379f2bade78 has been added to the queue. Currently at position 1
[2025-08-29 19:11:25] [2b768e4f-7010-4052-baf9-8379f2bade78] QUEUED     : Dispatching task...
[2025-08-29 19:11:25] [2b768e4f-7010-4052-baf9-8379f2bade78] RUNNING    : Your job has started running.

Error on problem 220: Traceback (most recent call last):
  File "/u/svcndifuser/ndif-deployment/repos/prod/ndif/src/services/ray/src/ray/deployments/modeling/base.py", line 213, in __call__
    result = await job_task
  File "/u/svcndifuser/miniconda3/lib/python3.10/asyncio/threads.py", line 25, in to_thread
    return await loop.run_in_executor(None, func_call)
  File "/u/svcndifuser/miniconda3/lib/python3.10/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/u/svcndifuser/miniconda3/lib/python3.10/site-packages/ray/util/tracing/tracing_helper.py", line 463, in _resume_span
    return method(self, *_args, **_kwargs)
  File "/u/svcndifuser/ndif-deployment/repos/prod/ndif/src/services/ray/src/ray/deployments/modeling/base.py", line 283, in execute
    result = RemoteExecutionBackend(request.interventions, self.execution_protector)(request.tracer)
  File "/u/svcndifuser/ndif-deployment/repos/prod/ndif/src/services/ray/src/ray/nn/backend.py", line 27, in __call__
    run(tracer, self.fn)
  File "/u/svcndifuser/ndif-deployment/repos/prod/ndif/src/services/ray/src/ray/nn/sandbox.py", line 16, in run
    raise wrap_exception(e,tracer.info) from None
nnsight.NNsightException:

Traceback (most recent call last):
  File "/u/svcndifuser/ndif-deployment/repos/prod/ndif/src/services/ray/src/ray/nn/sandbox.py", line 14, in run
    tracer.execute(fn)
  File "/u/svcndifuser/miniconda3/lib/python3.10/site-packages/nnsight/intervention/tracing/tracer.py", line 385, in execute
    self.model.interleave(self.fn, *args, **kwargs)
  File "/u/svcndifuser/miniconda3/lib/python3.10/site-packages/nnsight/modeling/mixins/meta.py", line 76, in interleave
    return super().interleave(fn, *args, **kwargs)
  File "/u/svcndifuser/miniconda3/lib/python3.10/site-packages/nnsight/intervention/envoy.py", line 733, in interleave
    fn(*args, **kwargs)
  File "/u/svcndifuser/miniconda3/lib/python3.10/site-packages/nnsight/modeling/language.py", line 173, in __nnsight_generate__
    output = self._model.generate(*args, streamer=streamer, **kwargs)
  File "/u/svcndifuser/miniconda3/lib/python3.10/site-packages/torch/utils/_contextlib.py", line 116, in decorate_context
    return func(*args, **kwargs)
  File "/u/svcndifuser/miniconda3/lib/python3.10/site-packages/transformers/generation/utils.py", line 2629, in generate
    result = self._sample(
  File "/u/svcndifuser/miniconda3/lib/python3.10/site-packages/transformers/generation/utils.py", line 3613, in _sample
    outputs = model_forward(**model_inputs, return_dict=True)
  File "/u/svcndifuser/miniconda3/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1751, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/u/svcndifuser/miniconda3/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1857, in _call_impl
    return inner()
  File "/u/svcndifuser/miniconda3/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1805, in inner
    result = forward_call(*args, **kwargs)
  File "/u/svcndifuser/miniconda3/lib/python3.10/site-packages/nnsight/intervention/interleaver.py", line 133, in skippable_forward
    return forward(*args, **kwargs)
  File "/u/svcndifuser/miniconda3/lib/python3.10/site-packages/transformers/utils/generic.py", line 959, in wrapper
    output = func(self, *args, **kwargs)
  File "/u/svcndifuser/miniconda3/lib/python3.10/site-packages/transformers/models/llama/modeling_llama.py", line 460, in forward
    outputs: BaseModelOutputWithPast = self.model(
  File "/u/svcndifuser/miniconda3/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1751, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/u/svcndifuser/miniconda3/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1857, in _call_impl
    return inner()
  File "/u/svcndifuser/miniconda3/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1805, in inner
    result = forward_call(*args, **kwargs)
  File "/u/svcndifuser/miniconda3/lib/python3.10/site-packages/nnsight/intervention/interleaver.py", line 133, in skippable_forward
    return forward(*args, **kwargs)
  File "/u/svcndifuser/miniconda3/lib/python3.10/site-packages/transformers/utils/generic.py", line 1083, in wrapper
    outputs = func(self, *args, **kwargs)
  File "/u/svcndifuser/miniconda3/lib/python3.10/site-packages/transformers/models/llama/modeling_llama.py", line 390, in forward
    hidden_states = decoder_layer(
  File "/u/svcndifuser/miniconda3/lib/python3.10/site-packages/transformers/modeling_layers.py", line 94, in __call__
    return super().__call__(*args, **kwargs)
  File "/u/svcndifuser/miniconda3/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1751, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/u/svcndifuser/miniconda3/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1857, in _call_impl
    return inner()
  File "/u/svcndifuser/miniconda3/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1805, in inner
    result = forward_call(*args, **kwargs)
  File "/u/svcndifuser/miniconda3/lib/python3.10/site-packages/nnsight/intervention/interleaver.py", line 133, in skippable_forward
    return forward(*args, **kwargs)
  File "/u/svcndifuser/miniconda3/lib/python3.10/site-packages/transformers/models/llama/modeling_llama.py", line 289, in forward
    hidden_states, _ = self.self_attn(
  File "/u/svcndifuser/miniconda3/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1751, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/u/svcndifuser/miniconda3/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1857, in _call_impl
    return inner()
  File "/u/svcndifuser/miniconda3/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1805, in inner
    result = forward_call(*args, **kwargs)
  File "/u/svcndifuser/miniconda3/lib/python3.10/site-packages/nnsight/intervention/interleaver.py", line 133, in skippable_forward
    return forward(*args, **kwargs)
  File "/u/svcndifuser/miniconda3/lib/python3.10/site-packages/transformers/models/llama/modeling_llama.py", line 242, in forward
    key_states, value_states = past_key_value.update(key_states, value_states, self.layer_idx, cache_kwargs)
  File "/u/svcndifuser/miniconda3/lib/python3.10/site-packages/transformers/cache_utils.py", line 992, in _wrapped_update
    key_tensors, value_tensors = fn(self, key_states, value_states, layer_idx, cache_kwargs)
  File "/u/svcndifuser/miniconda3/lib/python3.10/site-packages/transformers/cache_utils.py", line 1201, in update
    return self.layers[layer_idx].update(key_states, value_states, cache_kwargs)
  File "/u/svcndifuser/miniconda3/lib/python3.10/site-packages/transformers/cache_utils.py", line 103, in update
    self.values = torch.cat([self.values, value_states], dim=-2)

OutOfMemoryError: CUDA out of memory. Tried to allocate 40.00 MiB. GPU 0 has a total capacity of 44.34 GiB of which 6.81 MiB is free. Including non-PyTorch memory, this process has 44.32 GiB memory in use. Of the allocated memory 40.94 GiB is allocated by PyTorch, and 3.07 GiB is reserved by PyTorch but unallocated. If reserved but unallocated memory is large try setting PYTORCH_CUDA_ALLOC_CONF=expandable_segments:True to avoid fragmentation.  See documentation for Memory Management  (https://pytorch.org/docs/stable/notes/cuda.html#environment-variables)



Traceback (most recent call last):
  File "/u/svcndifuser/ndif-deployment/repos/prod/ndif/src/services/ray/src/ray/nn/sandbox.py", line 14, in run
    tracer.execute(fn)
  File "/u/svcndifuser/miniconda3/lib/python3.10/site-packages/nnsight/intervention/tracing/tracer.py", line 385, in execute
    self.model.interleave(self.fn, *args, **kwargs)
  File "/u/svcndifuser/miniconda3/lib/python3.10/site-packages/nnsight/modeling/mixins/meta.py", line 76, in interleave
    return super().interleave(fn, *args, **kwargs)
  File "/u/svcndifuser/miniconda3/lib/python3.10/site-packages/nnsight/intervention/envoy.py", line 733, in interleave
    fn(*args, **kwargs)
  File "/u/svcndifuser/miniconda3/lib/python3.10/site-packages/nnsight/modeling/language.py", line 173, in __nnsight_generate__
    output = self._model.generate(*args, streamer=streamer, **kwargs)
  File "/u/svcndifuser/miniconda3/lib/python3.10/site-packages/torch/utils/_contextlib.py", line 116, in decorate_context
    return func(*args, **kwargs)
  File "/u/svcndifuser/miniconda3/lib/python3.10/site-packages/transformers/generation/utils.py", line 2629, in generate
    result = self._sample(
  File "/u/svcndifuser/miniconda3/lib/python3.10/site-packages/transformers/generation/utils.py", line 3613, in _sample
    outputs = model_forward(**model_inputs, return_dict=True)
  File "/u/svcndifuser/miniconda3/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1751, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/u/svcndifuser/miniconda3/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1857, in _call_impl
    return inner()
  File "/u/svcndifuser/miniconda3/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1805, in inner
    result = forward_call(*args, **kwargs)
  File "/u/svcndifuser/miniconda3/lib/python3.10/site-packages/nnsight/intervention/interleaver.py", line 133, in skippable_forward
    return forward(*args, **kwargs)
  File "/u/svcndifuser/miniconda3/lib/python3.10/site-packages/transformers/utils/generic.py", line 959, in wrapper
    output = func(self, *args, **kwargs)
  File "/u/svcndifuser/miniconda3/lib/python3.10/site-packages/transformers/models/llama/modeling_llama.py", line 460, in forward
    outputs: BaseModelOutputWithPast = self.model(
  File "/u/svcndifuser/miniconda3/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1751, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/u/svcndifuser/miniconda3/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1857, in _call_impl
    return inner()
  File "/u/svcndifuser/miniconda3/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1805, in inner
    result = forward_call(*args, **kwargs)
  File "/u/svcndifuser/miniconda3/lib/python3.10/site-packages/nnsight/intervention/interleaver.py", line 133, in skippable_forward
    return forward(*args, **kwargs)
  File "/u/svcndifuser/miniconda3/lib/python3.10/site-packages/transformers/utils/generic.py", line 1083, in wrapper
    outputs = func(self, *args, **kwargs)
  File "/u/svcndifuser/miniconda3/lib/python3.10/site-packages/transformers/models/llama/modeling_llama.py", line 390, in forward
    hidden_states = decoder_layer(
  File "/u/svcndifuser/miniconda3/lib/python3.10/site-packages/transformers/modeling_layers.py", line 94, in __call__
    return super().__call__(*args, **kwargs)
  File "/u/svcndifuser/miniconda3/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1751, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/u/svcndifuser/miniconda3/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1857, in _call_impl
    return inner()
  File "/u/svcndifuser/miniconda3/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1805, in inner
    result = forward_call(*args, **kwargs)
  File "/u/svcndifuser/miniconda3/lib/python3.10/site-packages/nnsight/intervention/interleaver.py", line 133, in skippable_forward
    return forward(*args, **kwargs)
  File "/u/svcndifuser/miniconda3/lib/python3.10/site-packages/transformers/models/llama/modeling_llama.py", line 289, in forward
    hidden_states, _ = self.self_attn(
  File "/u/svcndifuser/miniconda3/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1751, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/u/svcndifuser/miniconda3/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1857, in _call_impl
    return inner()
  File "/u/svcndifuser/miniconda3/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1805, in inner
    result = forward_call(*args, **kwargs)
  File "/u/svcndifuser/miniconda3/lib/python3.10/site-packages/nnsight/intervention/interleaver.py", line 133, in skippable_forward
    return forward(*args, **kwargs)
  File "/u/svcndifuser/miniconda3/lib/python3.10/site-packages/transformers/models/llama/modeling_llama.py", line 242, in forward
    key_states, value_states = past_key_value.update(key_states, value_states, self.layer_idx, cache_kwargs)
  File "/u/svcndifuser/miniconda3/lib/python3.10/site-packages/transformers/cache_utils.py", line 992, in _wrapped_update
    key_tensors, value_tensors = fn(self, key_states, value_states, layer_idx, cache_kwargs)
  File "/u/svcndifuser/miniconda3/lib/python3.10/site-packages/transformers/cache_utils.py", line 1201, in update
    return self.layers[layer_idx].update(key_states, value_states, cache_kwargs)
  File "/u/svcndifuser/miniconda3/lib/python3.10/site-packages/transformers/cache_utils.py", line 103, in update
    self.values = torch.cat([self.values, value_states], dim=-2)

OutOfMemoryError: CUDA out of memory. Tried to allocate 40.00 MiB. GPU 0 has a total capacity of 44.34 GiB of which 6.81 MiB is free. Including non-PyTorch memory, this process has 44.32 GiB memory in use. Of the allocated memory 40.94 GiB is allocated by PyTorch, and 3.07 GiB is reserved by PyTorch but unallocated. If reserved but unallocated memory is large try setting PYTORCH_CUDA_ALLOC_CONF=expandable_segments:True to avoid fragmentation.  See documentation for Memory Management  (https://pytorch.org/docs/stable/notes/cuda.html#environment-variables)
Remote exception.

[2025-08-29 19:11:50] [d604659e-008d-4ade-9af1-ce220f6ef939] RECEIVED   : Your job has been received and is waiting to be queued.
[2025-08-29 19:11:50] [d604659e-008d-4ade-9af1-ce220f6ef939] QUEUED     : Your job has been recieved by the coordinator and is waiting to be queued.
[2025-08-29 19:11:50] [d604659e-008d-4ade-9af1-ce220f6ef939] QUEUED     : Task d604659e-008d-4ade-9af1-ce220f6ef939 has been added to the queue. Currently at position 1
[2025-08-29 19:11:50] [d604659e-008d-4ade-9af1-ce220f6ef939] QUEUED     : Dispatching task...
[2025-08-29 19:11:50] [d604659e-008d-4ade-9af1-ce220f6ef939] RUNNING    : Your job has started running.

Error on problem 221: Traceback (most recent call last):
  File "/u/svcndifuser/ndif-deployment/repos/prod/ndif/src/services/ray/src/ray/deployments/modeling/base.py", line 213, in __call__
    result = await job_task
  File "/u/svcndifuser/miniconda3/lib/python3.10/asyncio/threads.py", line 25, in to_thread
    return await loop.run_in_executor(None, func_call)
  File "/u/svcndifuser/miniconda3/lib/python3.10/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/u/svcndifuser/miniconda3/lib/python3.10/site-packages/ray/util/tracing/tracing_helper.py", line 463, in _resume_span
    return method(self, *_args, **_kwargs)
  File "/u/svcndifuser/ndif-deployment/repos/prod/ndif/src/services/ray/src/ray/deployments/modeling/base.py", line 283, in execute
    result = RemoteExecutionBackend(request.interventions, self.execution_protector)(request.tracer)
  File "/u/svcndifuser/ndif-deployment/repos/prod/ndif/src/services/ray/src/ray/nn/backend.py", line 27, in __call__
    run(tracer, self.fn)
  File "/u/svcndifuser/ndif-deployment/repos/prod/ndif/src/services/ray/src/ray/nn/sandbox.py", line 16, in run
    raise wrap_exception(e,tracer.info) from None
nnsight.NNsightException:

Traceback (most recent call last):
  File "/u/svcndifuser/ndif-deployment/repos/prod/ndif/src/services/ray/src/ray/nn/sandbox.py", line 14, in run
    tracer.execute(fn)
  File "/u/svcndifuser/miniconda3/lib/python3.10/site-packages/nnsight/intervention/tracing/tracer.py", line 385, in execute
    self.model.interleave(self.fn, *args, **kwargs)
  File "/u/svcndifuser/miniconda3/lib/python3.10/site-packages/nnsight/modeling/mixins/meta.py", line 76, in interleave
    return super().interleave(fn, *args, **kwargs)
  File "/u/svcndifuser/miniconda3/lib/python3.10/site-packages/nnsight/intervention/envoy.py", line 733, in interleave
    fn(*args, **kwargs)
  File "/u/svcndifuser/miniconda3/lib/python3.10/site-packages/nnsight/modeling/language.py", line 173, in __nnsight_generate__
    output = self._model.generate(*args, streamer=streamer, **kwargs)
  File "/u/svcndifuser/miniconda3/lib/python3.10/site-packages/torch/utils/_contextlib.py", line 116, in decorate_context
    return func(*args, **kwargs)
  File "/u/svcndifuser/miniconda3/lib/python3.10/site-packages/transformers/generation/utils.py", line 2629, in generate
    result = self._sample(
  File "/u/svcndifuser/miniconda3/lib/python3.10/site-packages/transformers/generation/utils.py", line 3613, in _sample
    outputs = model_forward(**model_inputs, return_dict=True)
  File "/u/svcndifuser/miniconda3/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1751, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/u/svcndifuser/miniconda3/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1857, in _call_impl
    return inner()
  File "/u/svcndifuser/miniconda3/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1805, in inner
    result = forward_call(*args, **kwargs)
  File "/u/svcndifuser/miniconda3/lib/python3.10/site-packages/nnsight/intervention/interleaver.py", line 133, in skippable_forward
    return forward(*args, **kwargs)
  File "/u/svcndifuser/miniconda3/lib/python3.10/site-packages/transformers/utils/generic.py", line 959, in wrapper
    output = func(self, *args, **kwargs)
  File "/u/svcndifuser/miniconda3/lib/python3.10/site-packages/transformers/models/llama/modeling_llama.py", line 460, in forward
    outputs: BaseModelOutputWithPast = self.model(
  File "/u/svcndifuser/miniconda3/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1751, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/u/svcndifuser/miniconda3/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1857, in _call_impl
    return inner()
  File "/u/svcndifuser/miniconda3/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1805, in inner
    result = forward_call(*args, **kwargs)
  File "/u/svcndifuser/miniconda3/lib/python3.10/site-packages/nnsight/intervention/interleaver.py", line 133, in skippable_forward
    return forward(*args, **kwargs)
  File "/u/svcndifuser/miniconda3/lib/python3.10/site-packages/transformers/utils/generic.py", line 1083, in wrapper
    outputs = func(self, *args, **kwargs)
  File "/u/svcndifuser/miniconda3/lib/python3.10/site-packages/transformers/models/llama/modeling_llama.py", line 390, in forward
    hidden_states = decoder_layer(
  File "/u/svcndifuser/miniconda3/lib/python3.10/site-packages/transformers/modeling_layers.py", line 94, in __call__
    return super().__call__(*args, **kwargs)
  File "/u/svcndifuser/miniconda3/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1751, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/u/svcndifuser/miniconda3/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1857, in _call_impl
    return inner()
  File "/u/svcndifuser/miniconda3/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1805, in inner
    result = forward_call(*args, **kwargs)
  File "/u/svcndifuser/miniconda3/lib/python3.10/site-packages/nnsight/intervention/interleaver.py", line 133, in skippable_forward
    return forward(*args, **kwargs)
  File "/u/svcndifuser/miniconda3/lib/python3.10/site-packages/transformers/models/llama/modeling_llama.py", line 289, in forward
    hidden_states, _ = self.self_attn(
  File "/u/svcndifuser/miniconda3/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1751, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/u/svcndifuser/miniconda3/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1857, in _call_impl
    return inner()
  File "/u/svcndifuser/miniconda3/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1805, in inner
    result = forward_call(*args, **kwargs)
  File "/u/svcndifuser/miniconda3/lib/python3.10/site-packages/nnsight/intervention/interleaver.py", line 133, in skippable_forward
    return forward(*args, **kwargs)
  File "/u/svcndifuser/miniconda3/lib/python3.10/site-packages/transformers/models/llama/modeling_llama.py", line 242, in forward
    key_states, value_states = past_key_value.update(key_states, value_states, self.layer_idx, cache_kwargs)
  File "/u/svcndifuser/miniconda3/lib/python3.10/site-packages/transformers/cache_utils.py", line 992, in _wrapped_update
    key_tensors, value_tensors = fn(self, key_states, value_states, layer_idx, cache_kwargs)
  File "/u/svcndifuser/miniconda3/lib/python3.10/site-packages/transformers/cache_utils.py", line 1201, in update
    return self.layers[layer_idx].update(key_states, value_states, cache_kwargs)
  File "/u/svcndifuser/miniconda3/lib/python3.10/site-packages/transformers/cache_utils.py", line 103, in update
    self.values = torch.cat([self.values, value_states], dim=-2)

OutOfMemoryError: CUDA out of memory. Tried to allocate 48.00 MiB. GPU 0 has a total capacity of 44.34 GiB of which 16.81 MiB is free. Including non-PyTorch memory, this process has 44.31 GiB memory in use. Of the allocated memory 40.52 GiB is allocated by PyTorch, and 3.48 GiB is reserved by PyTorch but unallocated. If reserved but unallocated memory is large try setting PYTORCH_CUDA_ALLOC_CONF=expandable_segments:True to avoid fragmentation.  See documentation for Memory Management  (https://pytorch.org/docs/stable/notes/cuda.html#environment-variables)



Traceback (most recent call last):
  File "/u/svcndifuser/ndif-deployment/repos/prod/ndif/src/services/ray/src/ray/nn/sandbox.py", line 14, in run
    tracer.execute(fn)
  File "/u/svcndifuser/miniconda3/lib/python3.10/site-packages/nnsight/intervention/tracing/tracer.py", line 385, in execute
    self.model.interleave(self.fn, *args, **kwargs)
  File "/u/svcndifuser/miniconda3/lib/python3.10/site-packages/nnsight/modeling/mixins/meta.py", line 76, in interleave
    return super().interleave(fn, *args, **kwargs)
  File "/u/svcndifuser/miniconda3/lib/python3.10/site-packages/nnsight/intervention/envoy.py", line 733, in interleave
    fn(*args, **kwargs)
  File "/u/svcndifuser/miniconda3/lib/python3.10/site-packages/nnsight/modeling/language.py", line 173, in __nnsight_generate__
    output = self._model.generate(*args, streamer=streamer, **kwargs)
  File "/u/svcndifuser/miniconda3/lib/python3.10/site-packages/torch/utils/_contextlib.py", line 116, in decorate_context
    return func(*args, **kwargs)
  File "/u/svcndifuser/miniconda3/lib/python3.10/site-packages/transformers/generation/utils.py", line 2629, in generate
    result = self._sample(
  File "/u/svcndifuser/miniconda3/lib/python3.10/site-packages/transformers/generation/utils.py", line 3613, in _sample
    outputs = model_forward(**model_inputs, return_dict=True)
  File "/u/svcndifuser/miniconda3/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1751, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/u/svcndifuser/miniconda3/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1857, in _call_impl
    return inner()
  File "/u/svcndifuser/miniconda3/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1805, in inner
    result = forward_call(*args, **kwargs)
  File "/u/svcndifuser/miniconda3/lib/python3.10/site-packages/nnsight/intervention/interleaver.py", line 133, in skippable_forward
    return forward(*args, **kwargs)
  File "/u/svcndifuser/miniconda3/lib/python3.10/site-packages/transformers/utils/generic.py", line 959, in wrapper
    output = func(self, *args, **kwargs)
  File "/u/svcndifuser/miniconda3/lib/python3.10/site-packages/transformers/models/llama/modeling_llama.py", line 460, in forward
    outputs: BaseModelOutputWithPast = self.model(
  File "/u/svcndifuser/miniconda3/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1751, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/u/svcndifuser/miniconda3/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1857, in _call_impl
    return inner()
  File "/u/svcndifuser/miniconda3/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1805, in inner
    result = forward_call(*args, **kwargs)
  File "/u/svcndifuser/miniconda3/lib/python3.10/site-packages/nnsight/intervention/interleaver.py", line 133, in skippable_forward
    return forward(*args, **kwargs)
  File "/u/svcndifuser/miniconda3/lib/python3.10/site-packages/transformers/utils/generic.py", line 1083, in wrapper
    outputs = func(self, *args, **kwargs)
  File "/u/svcndifuser/miniconda3/lib/python3.10/site-packages/transformers/models/llama/modeling_llama.py", line 390, in forward
    hidden_states = decoder_layer(
  File "/u/svcndifuser/miniconda3/lib/python3.10/site-packages/transformers/modeling_layers.py", line 94, in __call__
    return super().__call__(*args, **kwargs)
  File "/u/svcndifuser/miniconda3/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1751, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/u/svcndifuser/miniconda3/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1857, in _call_impl
    return inner()
  File "/u/svcndifuser/miniconda3/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1805, in inner
    result = forward_call(*args, **kwargs)
  File "/u/svcndifuser/miniconda3/lib/python3.10/site-packages/nnsight/intervention/interleaver.py", line 133, in skippable_forward
    return forward(*args, **kwargs)
  File "/u/svcndifuser/miniconda3/lib/python3.10/site-packages/transformers/models/llama/modeling_llama.py", line 289, in forward
    hidden_states, _ = self.self_attn(
  File "/u/svcndifuser/miniconda3/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1751, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/u/svcndifuser/miniconda3/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1857, in _call_impl
    return inner()
  File "/u/svcndifuser/miniconda3/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1805, in inner
    result = forward_call(*args, **kwargs)
  File "/u/svcndifuser/miniconda3/lib/python3.10/site-packages/nnsight/intervention/interleaver.py", line 133, in skippable_forward
    return forward(*args, **kwargs)
  File "/u/svcndifuser/miniconda3/lib/python3.10/site-packages/transformers/models/llama/modeling_llama.py", line 242, in forward
    key_states, value_states = past_key_value.update(key_states, value_states, self.layer_idx, cache_kwargs)
  File "/u/svcndifuser/miniconda3/lib/python3.10/site-packages/transformers/cache_utils.py", line 992, in _wrapped_update
    key_tensors, value_tensors = fn(self, key_states, value_states, layer_idx, cache_kwargs)
  File "/u/svcndifuser/miniconda3/lib/python3.10/site-packages/transformers/cache_utils.py", line 1201, in update
    return self.layers[layer_idx].update(key_states, value_states, cache_kwargs)
  File "/u/svcndifuser/miniconda3/lib/python3.10/site-packages/transformers/cache_utils.py", line 103, in update
    self.values = torch.cat([self.values, value_states], dim=-2)

OutOfMemoryError: CUDA out of memory. Tried to allocate 48.00 MiB. GPU 0 has a total capacity of 44.34 GiB of which 16.81 MiB is free. Including non-PyTorch memory, this process has 44.31 GiB memory in use. Of the allocated memory 40.52 GiB is allocated by PyTorch, and 3.48 GiB is reserved by PyTorch but unallocated. If reserved but unallocated memory is large try setting PYTORCH_CUDA_ALLOC_CONF=expandable_segments:True to avoid fragmentation.  See documentation for Memory Management  (https://pytorch.org/docs/stable/notes/cuda.html#environment-variables)
Remote exception.

[2025-08-29 19:12:24] [eae70716-e9b7-44bd-9e9b-64ac9e7264df] RECEIVED   : Your job has been received and is waiting to be queued.
[2025-08-29 19:12:24] [eae70716-e9b7-44bd-9e9b-64ac9e7264df] QUEUED     : Your job has been recieved by the coordinator and is waiting to be queued.
[2025-08-29 19:12:24] [eae70716-e9b7-44bd-9e9b-64ac9e7264df] QUEUED     : Task eae70716-e9b7-44bd-9e9b-64ac9e7264df has been added to the queue. Currently at position 1
[2025-08-29 19:12:24] [eae70716-e9b7-44bd-9e9b-64ac9e7264df] QUEUED     : Dispatching task...
[2025-08-29 19:12:25] [eae70716-e9b7-44bd-9e9b-64ac9e7264df] RUNNING    : Your job has started running.

Error on problem 222: Traceback (most recent call last):
  File "/u/svcndifuser/ndif-deployment/repos/prod/ndif/src/services/ray/src/ray/deployments/modeling/base.py", line 213, in __call__
    result = await job_task
  File "/u/svcndifuser/miniconda3/lib/python3.10/asyncio/threads.py", line 25, in to_thread
    return await loop.run_in_executor(None, func_call)
  File "/u/svcndifuser/miniconda3/lib/python3.10/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/u/svcndifuser/miniconda3/lib/python3.10/site-packages/ray/util/tracing/tracing_helper.py", line 463, in _resume_span
    return method(self, *_args, **_kwargs)
  File "/u/svcndifuser/ndif-deployment/repos/prod/ndif/src/services/ray/src/ray/deployments/modeling/base.py", line 283, in execute
    result = RemoteExecutionBackend(request.interventions, self.execution_protector)(request.tracer)
  File "/u/svcndifuser/ndif-deployment/repos/prod/ndif/src/services/ray/src/ray/nn/backend.py", line 27, in __call__
    run(tracer, self.fn)
  File "/u/svcndifuser/ndif-deployment/repos/prod/ndif/src/services/ray/src/ray/nn/sandbox.py", line 16, in run
    raise wrap_exception(e,tracer.info) from None
nnsight.NNsightException:

Traceback (most recent call last):
  File "/u/svcndifuser/ndif-deployment/repos/prod/ndif/src/services/ray/src/ray/nn/sandbox.py", line 14, in run
    tracer.execute(fn)
  File "/u/svcndifuser/miniconda3/lib/python3.10/site-packages/nnsight/intervention/tracing/tracer.py", line 385, in execute
    self.model.interleave(self.fn, *args, **kwargs)
  File "/u/svcndifuser/miniconda3/lib/python3.10/site-packages/nnsight/modeling/mixins/meta.py", line 76, in interleave
    return super().interleave(fn, *args, **kwargs)
  File "/u/svcndifuser/miniconda3/lib/python3.10/site-packages/nnsight/intervention/envoy.py", line 733, in interleave
    fn(*args, **kwargs)
  File "/u/svcndifuser/miniconda3/lib/python3.10/site-packages/nnsight/modeling/language.py", line 173, in __nnsight_generate__
    output = self._model.generate(*args, streamer=streamer, **kwargs)
  File "/u/svcndifuser/miniconda3/lib/python3.10/site-packages/torch/utils/_contextlib.py", line 116, in decorate_context
    return func(*args, **kwargs)
  File "/u/svcndifuser/miniconda3/lib/python3.10/site-packages/transformers/generation/utils.py", line 2629, in generate
    result = self._sample(
  File "/u/svcndifuser/miniconda3/lib/python3.10/site-packages/transformers/generation/utils.py", line 3613, in _sample
    outputs = model_forward(**model_inputs, return_dict=True)
  File "/u/svcndifuser/miniconda3/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1751, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/u/svcndifuser/miniconda3/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1857, in _call_impl
    return inner()
  File "/u/svcndifuser/miniconda3/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1805, in inner
    result = forward_call(*args, **kwargs)
  File "/u/svcndifuser/miniconda3/lib/python3.10/site-packages/nnsight/intervention/interleaver.py", line 133, in skippable_forward
    return forward(*args, **kwargs)
  File "/u/svcndifuser/miniconda3/lib/python3.10/site-packages/transformers/utils/generic.py", line 959, in wrapper
    output = func(self, *args, **kwargs)
  File "/u/svcndifuser/miniconda3/lib/python3.10/site-packages/transformers/models/llama/modeling_llama.py", line 460, in forward
    outputs: BaseModelOutputWithPast = self.model(
  File "/u/svcndifuser/miniconda3/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1751, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/u/svcndifuser/miniconda3/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1857, in _call_impl
    return inner()
  File "/u/svcndifuser/miniconda3/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1805, in inner
    result = forward_call(*args, **kwargs)
  File "/u/svcndifuser/miniconda3/lib/python3.10/site-packages/nnsight/intervention/interleaver.py", line 133, in skippable_forward
    return forward(*args, **kwargs)
  File "/u/svcndifuser/miniconda3/lib/python3.10/site-packages/transformers/utils/generic.py", line 1083, in wrapper
    outputs = func(self, *args, **kwargs)
  File "/u/svcndifuser/miniconda3/lib/python3.10/site-packages/transformers/models/llama/modeling_llama.py", line 390, in forward
    hidden_states = decoder_layer(
  File "/u/svcndifuser/miniconda3/lib/python3.10/site-packages/transformers/modeling_layers.py", line 94, in __call__
    return super().__call__(*args, **kwargs)
  File "/u/svcndifuser/miniconda3/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1751, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/u/svcndifuser/miniconda3/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1857, in _call_impl
    return inner()
  File "/u/svcndifuser/miniconda3/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1805, in inner
    result = forward_call(*args, **kwargs)
  File "/u/svcndifuser/miniconda3/lib/python3.10/site-packages/nnsight/intervention/interleaver.py", line 133, in skippable_forward
    return forward(*args, **kwargs)
  File "/u/svcndifuser/miniconda3/lib/python3.10/site-packages/transformers/models/llama/modeling_llama.py", line 289, in forward
    hidden_states, _ = self.self_attn(
  File "/u/svcndifuser/miniconda3/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1751, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/u/svcndifuser/miniconda3/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1857, in _call_impl
    return inner()
  File "/u/svcndifuser/miniconda3/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1805, in inner
    result = forward_call(*args, **kwargs)
  File "/u/svcndifuser/miniconda3/lib/python3.10/site-packages/nnsight/intervention/interleaver.py", line 133, in skippable_forward
    return forward(*args, **kwargs)
  File "/u/svcndifuser/miniconda3/lib/python3.10/site-packages/transformers/models/llama/modeling_llama.py", line 242, in forward
    key_states, value_states = past_key_value.update(key_states, value_states, self.layer_idx, cache_kwargs)
  File "/u/svcndifuser/miniconda3/lib/python3.10/site-packages/transformers/cache_utils.py", line 992, in _wrapped_update
    key_tensors, value_tensors = fn(self, key_states, value_states, layer_idx, cache_kwargs)
  File "/u/svcndifuser/miniconda3/lib/python3.10/site-packages/transformers/cache_utils.py", line 1201, in update
    return self.layers[layer_idx].update(key_states, value_states, cache_kwargs)
  File "/u/svcndifuser/miniconda3/lib/python3.10/site-packages/transformers/cache_utils.py", line 103, in update
    self.values = torch.cat([self.values, value_states], dim=-2)

OutOfMemoryError: CUDA out of memory. Tried to allocate 40.00 MiB. GPU 0 has a total capacity of 44.34 GiB of which 38.81 MiB is free. Including non-PyTorch memory, this process has 44.29 GiB memory in use. Of the allocated memory 40.77 GiB is allocated by PyTorch, and 3.21 GiB is reserved by PyTorch but unallocated. If reserved but unallocated memory is large try setting PYTORCH_CUDA_ALLOC_CONF=expandable_segments:True to avoid fragmentation.  See documentation for Memory Management  (https://pytorch.org/docs/stable/notes/cuda.html#environment-variables)



Traceback (most recent call last):
  File "/u/svcndifuser/ndif-deployment/repos/prod/ndif/src/services/ray/src/ray/nn/sandbox.py", line 14, in run
    tracer.execute(fn)
  File "/u/svcndifuser/miniconda3/lib/python3.10/site-packages/nnsight/intervention/tracing/tracer.py", line 385, in execute
    self.model.interleave(self.fn, *args, **kwargs)
  File "/u/svcndifuser/miniconda3/lib/python3.10/site-packages/nnsight/modeling/mixins/meta.py", line 76, in interleave
    return super().interleave(fn, *args, **kwargs)
  File "/u/svcndifuser/miniconda3/lib/python3.10/site-packages/nnsight/intervention/envoy.py", line 733, in interleave
    fn(*args, **kwargs)
  File "/u/svcndifuser/miniconda3/lib/python3.10/site-packages/nnsight/modeling/language.py", line 173, in __nnsight_generate__
    output = self._model.generate(*args, streamer=streamer, **kwargs)
  File "/u/svcndifuser/miniconda3/lib/python3.10/site-packages/torch/utils/_contextlib.py", line 116, in decorate_context
    return func(*args, **kwargs)
  File "/u/svcndifuser/miniconda3/lib/python3.10/site-packages/transformers/generation/utils.py", line 2629, in generate
    result = self._sample(
  File "/u/svcndifuser/miniconda3/lib/python3.10/site-packages/transformers/generation/utils.py", line 3613, in _sample
    outputs = model_forward(**model_inputs, return_dict=True)
  File "/u/svcndifuser/miniconda3/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1751, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/u/svcndifuser/miniconda3/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1857, in _call_impl
    return inner()
  File "/u/svcndifuser/miniconda3/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1805, in inner
    result = forward_call(*args, **kwargs)
  File "/u/svcndifuser/miniconda3/lib/python3.10/site-packages/nnsight/intervention/interleaver.py", line 133, in skippable_forward
    return forward(*args, **kwargs)
  File "/u/svcndifuser/miniconda3/lib/python3.10/site-packages/transformers/utils/generic.py", line 959, in wrapper
    output = func(self, *args, **kwargs)
  File "/u/svcndifuser/miniconda3/lib/python3.10/site-packages/transformers/models/llama/modeling_llama.py", line 460, in forward
    outputs: BaseModelOutputWithPast = self.model(
  File "/u/svcndifuser/miniconda3/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1751, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/u/svcndifuser/miniconda3/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1857, in _call_impl
    return inner()
  File "/u/svcndifuser/miniconda3/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1805, in inner
    result = forward_call(*args, **kwargs)
  File "/u/svcndifuser/miniconda3/lib/python3.10/site-packages/nnsight/intervention/interleaver.py", line 133, in skippable_forward
    return forward(*args, **kwargs)
  File "/u/svcndifuser/miniconda3/lib/python3.10/site-packages/transformers/utils/generic.py", line 1083, in wrapper
    outputs = func(self, *args, **kwargs)
  File "/u/svcndifuser/miniconda3/lib/python3.10/site-packages/transformers/models/llama/modeling_llama.py", line 390, in forward
    hidden_states = decoder_layer(
  File "/u/svcndifuser/miniconda3/lib/python3.10/site-packages/transformers/modeling_layers.py", line 94, in __call__
    return super().__call__(*args, **kwargs)
  File "/u/svcndifuser/miniconda3/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1751, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/u/svcndifuser/miniconda3/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1857, in _call_impl
    return inner()
  File "/u/svcndifuser/miniconda3/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1805, in inner
    result = forward_call(*args, **kwargs)
  File "/u/svcndifuser/miniconda3/lib/python3.10/site-packages/nnsight/intervention/interleaver.py", line 133, in skippable_forward
    return forward(*args, **kwargs)
  File "/u/svcndifuser/miniconda3/lib/python3.10/site-packages/transformers/models/llama/modeling_llama.py", line 289, in forward
    hidden_states, _ = self.self_attn(
  File "/u/svcndifuser/miniconda3/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1751, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/u/svcndifuser/miniconda3/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1857, in _call_impl
    return inner()
  File "/u/svcndifuser/miniconda3/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1805, in inner
    result = forward_call(*args, **kwargs)
  File "/u/svcndifuser/miniconda3/lib/python3.10/site-packages/nnsight/intervention/interleaver.py", line 133, in skippable_forward
    return forward(*args, **kwargs)
  File "/u/svcndifuser/miniconda3/lib/python3.10/site-packages/transformers/models/llama/modeling_llama.py", line 242, in forward
    key_states, value_states = past_key_value.update(key_states, value_states, self.layer_idx, cache_kwargs)
  File "/u/svcndifuser/miniconda3/lib/python3.10/site-packages/transformers/cache_utils.py", line 992, in _wrapped_update
    key_tensors, value_tensors = fn(self, key_states, value_states, layer_idx, cache_kwargs)
  File "/u/svcndifuser/miniconda3/lib/python3.10/site-packages/transformers/cache_utils.py", line 1201, in update
    return self.layers[layer_idx].update(key_states, value_states, cache_kwargs)
  File "/u/svcndifuser/miniconda3/lib/python3.10/site-packages/transformers/cache_utils.py", line 103, in update
    self.values = torch.cat([self.values, value_states], dim=-2)

OutOfMemoryError: CUDA out of memory. Tried to allocate 40.00 MiB. GPU 0 has a total capacity of 44.34 GiB of which 38.81 MiB is free. Including non-PyTorch memory, this process has 44.29 GiB memory in use. Of the allocated memory 40.77 GiB is allocated by PyTorch, and 3.21 GiB is reserved by PyTorch but unallocated. If reserved but unallocated memory is large try setting PYTORCH_CUDA_ALLOC_CONF=expandable_segments:True to avoid fragmentation.  See documentation for Memory Management  (https://pytorch.org/docs/stable/notes/cuda.html#environment-variables)
Remote exception.

[2025-08-29 19:12:48] [d8514257-7aa1-47e6-9948-84ca2568e382] RECEIVED   : Your job has been received and is waiting to be queued.
[2025-08-29 19:12:48] [d8514257-7aa1-47e6-9948-84ca2568e382] QUEUED     : Your job has been recieved by the coordinator and is waiting to be queued.
[2025-08-29 19:12:48] [d8514257-7aa1-47e6-9948-84ca2568e382] QUEUED     : Task d8514257-7aa1-47e6-9948-84ca2568e382 has been added to the queue. Currently at position 1
[2025-08-29 19:12:49] [d8514257-7aa1-47e6-9948-84ca2568e382] QUEUED     : Dispatching task...
[2025-08-29 19:12:49] [d8514257-7aa1-47e6-9948-84ca2568e382] RUNNING    : Your job has started running.

Error on problem 223: Traceback (most recent call last):
  File "/u/svcndifuser/ndif-deployment/repos/prod/ndif/src/services/ray/src/ray/deployments/modeling/base.py", line 213, in __call__
    result = await job_task
  File "/u/svcndifuser/miniconda3/lib/python3.10/asyncio/threads.py", line 25, in to_thread
    return await loop.run_in_executor(None, func_call)
  File "/u/svcndifuser/miniconda3/lib/python3.10/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/u/svcndifuser/miniconda3/lib/python3.10/site-packages/ray/util/tracing/tracing_helper.py", line 463, in _resume_span
    return method(self, *_args, **_kwargs)
  File "/u/svcndifuser/ndif-deployment/repos/prod/ndif/src/services/ray/src/ray/deployments/modeling/base.py", line 283, in execute
    result = RemoteExecutionBackend(request.interventions, self.execution_protector)(request.tracer)
  File "/u/svcndifuser/ndif-deployment/repos/prod/ndif/src/services/ray/src/ray/nn/backend.py", line 27, in __call__
    run(tracer, self.fn)
  File "/u/svcndifuser/ndif-deployment/repos/prod/ndif/src/services/ray/src/ray/nn/sandbox.py", line 16, in run
    raise wrap_exception(e,tracer.info) from None
nnsight.NNsightException:

Traceback (most recent call last):
  File "/u/svcndifuser/ndif-deployment/repos/prod/ndif/src/services/ray/src/ray/nn/sandbox.py", line 14, in run
    tracer.execute(fn)
  File "/u/svcndifuser/miniconda3/lib/python3.10/site-packages/nnsight/intervention/tracing/tracer.py", line 385, in execute
    self.model.interleave(self.fn, *args, **kwargs)
  File "/u/svcndifuser/miniconda3/lib/python3.10/site-packages/nnsight/modeling/mixins/meta.py", line 76, in interleave
    return super().interleave(fn, *args, **kwargs)
  File "/u/svcndifuser/miniconda3/lib/python3.10/site-packages/nnsight/intervention/envoy.py", line 733, in interleave
    fn(*args, **kwargs)
  File "/u/svcndifuser/miniconda3/lib/python3.10/site-packages/nnsight/modeling/language.py", line 173, in __nnsight_generate__
    output = self._model.generate(*args, streamer=streamer, **kwargs)
  File "/u/svcndifuser/miniconda3/lib/python3.10/site-packages/torch/utils/_contextlib.py", line 116, in decorate_context
    return func(*args, **kwargs)
  File "/u/svcndifuser/miniconda3/lib/python3.10/site-packages/transformers/generation/utils.py", line 2629, in generate
    result = self._sample(
  File "/u/svcndifuser/miniconda3/lib/python3.10/site-packages/transformers/generation/utils.py", line 3613, in _sample
    outputs = model_forward(**model_inputs, return_dict=True)
  File "/u/svcndifuser/miniconda3/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1751, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/u/svcndifuser/miniconda3/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1857, in _call_impl
    return inner()
  File "/u/svcndifuser/miniconda3/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1805, in inner
    result = forward_call(*args, **kwargs)
  File "/u/svcndifuser/miniconda3/lib/python3.10/site-packages/nnsight/intervention/interleaver.py", line 133, in skippable_forward
    return forward(*args, **kwargs)
  File "/u/svcndifuser/miniconda3/lib/python3.10/site-packages/transformers/utils/generic.py", line 959, in wrapper
    output = func(self, *args, **kwargs)
  File "/u/svcndifuser/miniconda3/lib/python3.10/site-packages/transformers/models/llama/modeling_llama.py", line 460, in forward
    outputs: BaseModelOutputWithPast = self.model(
  File "/u/svcndifuser/miniconda3/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1751, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/u/svcndifuser/miniconda3/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1857, in _call_impl
    return inner()
  File "/u/svcndifuser/miniconda3/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1805, in inner
    result = forward_call(*args, **kwargs)
  File "/u/svcndifuser/miniconda3/lib/python3.10/site-packages/nnsight/intervention/interleaver.py", line 133, in skippable_forward
    return forward(*args, **kwargs)
  File "/u/svcndifuser/miniconda3/lib/python3.10/site-packages/transformers/utils/generic.py", line 1083, in wrapper
    outputs = func(self, *args, **kwargs)
  File "/u/svcndifuser/miniconda3/lib/python3.10/site-packages/transformers/models/llama/modeling_llama.py", line 390, in forward
    hidden_states = decoder_layer(
  File "/u/svcndifuser/miniconda3/lib/python3.10/site-packages/transformers/modeling_layers.py", line 94, in __call__
    return super().__call__(*args, **kwargs)
  File "/u/svcndifuser/miniconda3/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1751, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/u/svcndifuser/miniconda3/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1857, in _call_impl
    return inner()
  File "/u/svcndifuser/miniconda3/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1805, in inner
    result = forward_call(*args, **kwargs)
  File "/u/svcndifuser/miniconda3/lib/python3.10/site-packages/nnsight/intervention/interleaver.py", line 133, in skippable_forward
    return forward(*args, **kwargs)
  File "/u/svcndifuser/miniconda3/lib/python3.10/site-packages/transformers/models/llama/modeling_llama.py", line 289, in forward
    hidden_states, _ = self.self_attn(
  File "/u/svcndifuser/miniconda3/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1751, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/u/svcndifuser/miniconda3/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1857, in _call_impl
    return inner()
  File "/u/svcndifuser/miniconda3/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1805, in inner
    result = forward_call(*args, **kwargs)
  File "/u/svcndifuser/miniconda3/lib/python3.10/site-packages/nnsight/intervention/interleaver.py", line 133, in skippable_forward
    return forward(*args, **kwargs)
  File "/u/svcndifuser/miniconda3/lib/python3.10/site-packages/transformers/models/llama/modeling_llama.py", line 242, in forward
    key_states, value_states = past_key_value.update(key_states, value_states, self.layer_idx, cache_kwargs)
  File "/u/svcndifuser/miniconda3/lib/python3.10/site-packages/transformers/cache_utils.py", line 992, in _wrapped_update
    key_tensors, value_tensors = fn(self, key_states, value_states, layer_idx, cache_kwargs)
  File "/u/svcndifuser/miniconda3/lib/python3.10/site-packages/transformers/cache_utils.py", line 1201, in update
    return self.layers[layer_idx].update(key_states, value_states, cache_kwargs)
  File "/u/svcndifuser/miniconda3/lib/python3.10/site-packages/transformers/cache_utils.py", line 103, in update
    self.values = torch.cat([self.values, value_states], dim=-2)

OutOfMemoryError: CUDA out of memory. Tried to allocate 40.00 MiB. GPU 0 has a total capacity of 44.34 GiB of which 28.81 MiB is free. Including non-PyTorch memory, this process has 44.30 GiB memory in use. Of the allocated memory 40.46 GiB is allocated by PyTorch, and 3.53 GiB is reserved by PyTorch but unallocated. If reserved but unallocated memory is large try setting PYTORCH_CUDA_ALLOC_CONF=expandable_segments:True to avoid fragmentation.  See documentation for Memory Management  (https://pytorch.org/docs/stable/notes/cuda.html#environment-variables)



Traceback (most recent call last):
  File "/u/svcndifuser/ndif-deployment/repos/prod/ndif/src/services/ray/src/ray/nn/sandbox.py", line 14, in run
    tracer.execute(fn)
  File "/u/svcndifuser/miniconda3/lib/python3.10/site-packages/nnsight/intervention/tracing/tracer.py", line 385, in execute
    self.model.interleave(self.fn, *args, **kwargs)
  File "/u/svcndifuser/miniconda3/lib/python3.10/site-packages/nnsight/modeling/mixins/meta.py", line 76, in interleave
    return super().interleave(fn, *args, **kwargs)
  File "/u/svcndifuser/miniconda3/lib/python3.10/site-packages/nnsight/intervention/envoy.py", line 733, in interleave
    fn(*args, **kwargs)
  File "/u/svcndifuser/miniconda3/lib/python3.10/site-packages/nnsight/modeling/language.py", line 173, in __nnsight_generate__
    output = self._model.generate(*args, streamer=streamer, **kwargs)
  File "/u/svcndifuser/miniconda3/lib/python3.10/site-packages/torch/utils/_contextlib.py", line 116, in decorate_context
    return func(*args, **kwargs)
  File "/u/svcndifuser/miniconda3/lib/python3.10/site-packages/transformers/generation/utils.py", line 2629, in generate
    result = self._sample(
  File "/u/svcndifuser/miniconda3/lib/python3.10/site-packages/transformers/generation/utils.py", line 3613, in _sample
    outputs = model_forward(**model_inputs, return_dict=True)
  File "/u/svcndifuser/miniconda3/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1751, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/u/svcndifuser/miniconda3/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1857, in _call_impl
    return inner()
  File "/u/svcndifuser/miniconda3/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1805, in inner
    result = forward_call(*args, **kwargs)
  File "/u/svcndifuser/miniconda3/lib/python3.10/site-packages/nnsight/intervention/interleaver.py", line 133, in skippable_forward
    return forward(*args, **kwargs)
  File "/u/svcndifuser/miniconda3/lib/python3.10/site-packages/transformers/utils/generic.py", line 959, in wrapper
    output = func(self, *args, **kwargs)
  File "/u/svcndifuser/miniconda3/lib/python3.10/site-packages/transformers/models/llama/modeling_llama.py", line 460, in forward
    outputs: BaseModelOutputWithPast = self.model(
  File "/u/svcndifuser/miniconda3/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1751, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/u/svcndifuser/miniconda3/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1857, in _call_impl
    return inner()
  File "/u/svcndifuser/miniconda3/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1805, in inner
    result = forward_call(*args, **kwargs)
  File "/u/svcndifuser/miniconda3/lib/python3.10/site-packages/nnsight/intervention/interleaver.py", line 133, in skippable_forward
    return forward(*args, **kwargs)
  File "/u/svcndifuser/miniconda3/lib/python3.10/site-packages/transformers/utils/generic.py", line 1083, in wrapper
    outputs = func(self, *args, **kwargs)
  File "/u/svcndifuser/miniconda3/lib/python3.10/site-packages/transformers/models/llama/modeling_llama.py", line 390, in forward
    hidden_states = decoder_layer(
  File "/u/svcndifuser/miniconda3/lib/python3.10/site-packages/transformers/modeling_layers.py", line 94, in __call__
    return super().__call__(*args, **kwargs)
  File "/u/svcndifuser/miniconda3/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1751, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/u/svcndifuser/miniconda3/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1857, in _call_impl
    return inner()
  File "/u/svcndifuser/miniconda3/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1805, in inner
    result = forward_call(*args, **kwargs)
  File "/u/svcndifuser/miniconda3/lib/python3.10/site-packages/nnsight/intervention/interleaver.py", line 133, in skippable_forward
    return forward(*args, **kwargs)
  File "/u/svcndifuser/miniconda3/lib/python3.10/site-packages/transformers/models/llama/modeling_llama.py", line 289, in forward
    hidden_states, _ = self.self_attn(
  File "/u/svcndifuser/miniconda3/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1751, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/u/svcndifuser/miniconda3/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1857, in _call_impl
    return inner()
  File "/u/svcndifuser/miniconda3/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1805, in inner
    result = forward_call(*args, **kwargs)
  File "/u/svcndifuser/miniconda3/lib/python3.10/site-packages/nnsight/intervention/interleaver.py", line 133, in skippable_forward
    return forward(*args, **kwargs)
  File "/u/svcndifuser/miniconda3/lib/python3.10/site-packages/transformers/models/llama/modeling_llama.py", line 242, in forward
    key_states, value_states = past_key_value.update(key_states, value_states, self.layer_idx, cache_kwargs)
  File "/u/svcndifuser/miniconda3/lib/python3.10/site-packages/transformers/cache_utils.py", line 992, in _wrapped_update
    key_tensors, value_tensors = fn(self, key_states, value_states, layer_idx, cache_kwargs)
  File "/u/svcndifuser/miniconda3/lib/python3.10/site-packages/transformers/cache_utils.py", line 1201, in update
    return self.layers[layer_idx].update(key_states, value_states, cache_kwargs)
  File "/u/svcndifuser/miniconda3/lib/python3.10/site-packages/transformers/cache_utils.py", line 103, in update
    self.values = torch.cat([self.values, value_states], dim=-2)

OutOfMemoryError: CUDA out of memory. Tried to allocate 40.00 MiB. GPU 0 has a total capacity of 44.34 GiB of which 28.81 MiB is free. Including non-PyTorch memory, this process has 44.30 GiB memory in use. Of the allocated memory 40.46 GiB is allocated by PyTorch, and 3.53 GiB is reserved by PyTorch but unallocated. If reserved but unallocated memory is large try setting PYTORCH_CUDA_ALLOC_CONF=expandable_segments:True to avoid fragmentation.  See documentation for Memory Management  (https://pytorch.org/docs/stable/notes/cuda.html#environment-variables)
Remote exception.

[2025-08-29 19:13:17] [1f45ae37-4530-4eed-92d8-1dcfc4d960c0] RECEIVED   : Your job has been received and is waiting to be queued.
[2025-08-29 19:13:17] [1f45ae37-4530-4eed-92d8-1dcfc4d960c0] QUEUED     : Your job has been recieved by the coordinator and is waiting to be queued.
[2025-08-29 19:13:17] [1f45ae37-4530-4eed-92d8-1dcfc4d960c0] QUEUED     : Task 1f45ae37-4530-4eed-92d8-1dcfc4d960c0 has been added to the queue. Currently at position 1
[2025-08-29 19:13:17] [1f45ae37-4530-4eed-92d8-1dcfc4d960c0] QUEUED     : Dispatching task...
[2025-08-29 19:13:17] [1f45ae37-4530-4eed-92d8-1dcfc4d960c0] RUNNING    : Your job has started running.

Error on problem 224: Traceback (most recent call last):
  File "/u/svcndifuser/ndif-deployment/repos/prod/ndif/src/services/ray/src/ray/deployments/modeling/base.py", line 213, in __call__
    result = await job_task
  File "/u/svcndifuser/miniconda3/lib/python3.10/asyncio/threads.py", line 25, in to_thread
    return await loop.run_in_executor(None, func_call)
  File "/u/svcndifuser/miniconda3/lib/python3.10/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/u/svcndifuser/miniconda3/lib/python3.10/site-packages/ray/util/tracing/tracing_helper.py", line 463, in _resume_span
    return method(self, *_args, **_kwargs)
  File "/u/svcndifuser/ndif-deployment/repos/prod/ndif/src/services/ray/src/ray/deployments/modeling/base.py", line 283, in execute
    result = RemoteExecutionBackend(request.interventions, self.execution_protector)(request.tracer)
  File "/u/svcndifuser/ndif-deployment/repos/prod/ndif/src/services/ray/src/ray/nn/backend.py", line 27, in __call__
    run(tracer, self.fn)
  File "/u/svcndifuser/ndif-deployment/repos/prod/ndif/src/services/ray/src/ray/nn/sandbox.py", line 16, in run
    raise wrap_exception(e,tracer.info) from None
nnsight.NNsightException:

Traceback (most recent call last):
  File "/u/svcndifuser/ndif-deployment/repos/prod/ndif/src/services/ray/src/ray/nn/sandbox.py", line 14, in run
    tracer.execute(fn)
  File "/u/svcndifuser/miniconda3/lib/python3.10/site-packages/nnsight/intervention/tracing/tracer.py", line 385, in execute
    self.model.interleave(self.fn, *args, **kwargs)
  File "/u/svcndifuser/miniconda3/lib/python3.10/site-packages/nnsight/modeling/mixins/meta.py", line 76, in interleave
    return super().interleave(fn, *args, **kwargs)
  File "/u/svcndifuser/miniconda3/lib/python3.10/site-packages/nnsight/intervention/envoy.py", line 733, in interleave
    fn(*args, **kwargs)
  File "/u/svcndifuser/miniconda3/lib/python3.10/site-packages/nnsight/modeling/language.py", line 173, in __nnsight_generate__
    output = self._model.generate(*args, streamer=streamer, **kwargs)
  File "/u/svcndifuser/miniconda3/lib/python3.10/site-packages/torch/utils/_contextlib.py", line 116, in decorate_context
    return func(*args, **kwargs)
  File "/u/svcndifuser/miniconda3/lib/python3.10/site-packages/transformers/generation/utils.py", line 2629, in generate
    result = self._sample(
  File "/u/svcndifuser/miniconda3/lib/python3.10/site-packages/transformers/generation/utils.py", line 3613, in _sample
    outputs = model_forward(**model_inputs, return_dict=True)
  File "/u/svcndifuser/miniconda3/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1751, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/u/svcndifuser/miniconda3/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1857, in _call_impl
    return inner()
  File "/u/svcndifuser/miniconda3/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1805, in inner
    result = forward_call(*args, **kwargs)
  File "/u/svcndifuser/miniconda3/lib/python3.10/site-packages/nnsight/intervention/interleaver.py", line 133, in skippable_forward
    return forward(*args, **kwargs)
  File "/u/svcndifuser/miniconda3/lib/python3.10/site-packages/transformers/utils/generic.py", line 959, in wrapper
    output = func(self, *args, **kwargs)
  File "/u/svcndifuser/miniconda3/lib/python3.10/site-packages/transformers/models/llama/modeling_llama.py", line 460, in forward
    outputs: BaseModelOutputWithPast = self.model(
  File "/u/svcndifuser/miniconda3/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1751, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/u/svcndifuser/miniconda3/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1857, in _call_impl
    return inner()
  File "/u/svcndifuser/miniconda3/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1805, in inner
    result = forward_call(*args, **kwargs)
  File "/u/svcndifuser/miniconda3/lib/python3.10/site-packages/nnsight/intervention/interleaver.py", line 133, in skippable_forward
    return forward(*args, **kwargs)
  File "/u/svcndifuser/miniconda3/lib/python3.10/site-packages/transformers/utils/generic.py", line 1083, in wrapper
    outputs = func(self, *args, **kwargs)
  File "/u/svcndifuser/miniconda3/lib/python3.10/site-packages/transformers/models/llama/modeling_llama.py", line 390, in forward
    hidden_states = decoder_layer(
  File "/u/svcndifuser/miniconda3/lib/python3.10/site-packages/transformers/modeling_layers.py", line 94, in __call__
    return super().__call__(*args, **kwargs)
  File "/u/svcndifuser/miniconda3/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1751, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/u/svcndifuser/miniconda3/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1857, in _call_impl
    return inner()
  File "/u/svcndifuser/miniconda3/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1805, in inner
    result = forward_call(*args, **kwargs)
  File "/u/svcndifuser/miniconda3/lib/python3.10/site-packages/nnsight/intervention/interleaver.py", line 133, in skippable_forward
    return forward(*args, **kwargs)
  File "/u/svcndifuser/miniconda3/lib/python3.10/site-packages/transformers/models/llama/modeling_llama.py", line 289, in forward
    hidden_states, _ = self.self_attn(
  File "/u/svcndifuser/miniconda3/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1751, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/u/svcndifuser/miniconda3/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1857, in _call_impl
    return inner()
  File "/u/svcndifuser/miniconda3/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1805, in inner
    result = forward_call(*args, **kwargs)
  File "/u/svcndifuser/miniconda3/lib/python3.10/site-packages/nnsight/intervention/interleaver.py", line 133, in skippable_forward
    return forward(*args, **kwargs)
  File "/u/svcndifuser/miniconda3/lib/python3.10/site-packages/transformers/models/llama/modeling_llama.py", line 242, in forward
    key_states, value_states = past_key_value.update(key_states, value_states, self.layer_idx, cache_kwargs)
  File "/u/svcndifuser/miniconda3/lib/python3.10/site-packages/transformers/cache_utils.py", line 992, in _wrapped_update
    key_tensors, value_tensors = fn(self, key_states, value_states, layer_idx, cache_kwargs)
  File "/u/svcndifuser/miniconda3/lib/python3.10/site-packages/transformers/cache_utils.py", line 1201, in update
    return self.layers[layer_idx].update(key_states, value_states, cache_kwargs)
  File "/u/svcndifuser/miniconda3/lib/python3.10/site-packages/transformers/cache_utils.py", line 103, in update
    self.values = torch.cat([self.values, value_states], dim=-2)

OutOfMemoryError: CUDA out of memory. Tried to allocate 40.00 MiB. GPU 0 has a total capacity of 44.34 GiB of which 12.81 MiB is free. Including non-PyTorch memory, this process has 44.32 GiB memory in use. Of the allocated memory 40.59 GiB is allocated by PyTorch, and 3.42 GiB is reserved by PyTorch but unallocated. If reserved but unallocated memory is large try setting PYTORCH_CUDA_ALLOC_CONF=expandable_segments:True to avoid fragmentation.  See documentation for Memory Management  (https://pytorch.org/docs/stable/notes/cuda.html#environment-variables)



Traceback (most recent call last):
  File "/u/svcndifuser/ndif-deployment/repos/prod/ndif/src/services/ray/src/ray/nn/sandbox.py", line 14, in run
    tracer.execute(fn)
  File "/u/svcndifuser/miniconda3/lib/python3.10/site-packages/nnsight/intervention/tracing/tracer.py", line 385, in execute
    self.model.interleave(self.fn, *args, **kwargs)
  File "/u/svcndifuser/miniconda3/lib/python3.10/site-packages/nnsight/modeling/mixins/meta.py", line 76, in interleave
    return super().interleave(fn, *args, **kwargs)
  File "/u/svcndifuser/miniconda3/lib/python3.10/site-packages/nnsight/intervention/envoy.py", line 733, in interleave
    fn(*args, **kwargs)
  File "/u/svcndifuser/miniconda3/lib/python3.10/site-packages/nnsight/modeling/language.py", line 173, in __nnsight_generate__
    output = self._model.generate(*args, streamer=streamer, **kwargs)
  File "/u/svcndifuser/miniconda3/lib/python3.10/site-packages/torch/utils/_contextlib.py", line 116, in decorate_context
    return func(*args, **kwargs)
  File "/u/svcndifuser/miniconda3/lib/python3.10/site-packages/transformers/generation/utils.py", line 2629, in generate
    result = self._sample(
  File "/u/svcndifuser/miniconda3/lib/python3.10/site-packages/transformers/generation/utils.py", line 3613, in _sample
    outputs = model_forward(**model_inputs, return_dict=True)
  File "/u/svcndifuser/miniconda3/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1751, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/u/svcndifuser/miniconda3/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1857, in _call_impl
    return inner()
  File "/u/svcndifuser/miniconda3/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1805, in inner
    result = forward_call(*args, **kwargs)
  File "/u/svcndifuser/miniconda3/lib/python3.10/site-packages/nnsight/intervention/interleaver.py", line 133, in skippable_forward
    return forward(*args, **kwargs)
  File "/u/svcndifuser/miniconda3/lib/python3.10/site-packages/transformers/utils/generic.py", line 959, in wrapper
    output = func(self, *args, **kwargs)
  File "/u/svcndifuser/miniconda3/lib/python3.10/site-packages/transformers/models/llama/modeling_llama.py", line 460, in forward
    outputs: BaseModelOutputWithPast = self.model(
  File "/u/svcndifuser/miniconda3/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1751, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/u/svcndifuser/miniconda3/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1857, in _call_impl
    return inner()
  File "/u/svcndifuser/miniconda3/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1805, in inner
    result = forward_call(*args, **kwargs)
  File "/u/svcndifuser/miniconda3/lib/python3.10/site-packages/nnsight/intervention/interleaver.py", line 133, in skippable_forward
    return forward(*args, **kwargs)
  File "/u/svcndifuser/miniconda3/lib/python3.10/site-packages/transformers/utils/generic.py", line 1083, in wrapper
    outputs = func(self, *args, **kwargs)
  File "/u/svcndifuser/miniconda3/lib/python3.10/site-packages/transformers/models/llama/modeling_llama.py", line 390, in forward
    hidden_states = decoder_layer(
  File "/u/svcndifuser/miniconda3/lib/python3.10/site-packages/transformers/modeling_layers.py", line 94, in __call__
    return super().__call__(*args, **kwargs)
  File "/u/svcndifuser/miniconda3/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1751, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/u/svcndifuser/miniconda3/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1857, in _call_impl
    return inner()
  File "/u/svcndifuser/miniconda3/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1805, in inner
    result = forward_call(*args, **kwargs)
  File "/u/svcndifuser/miniconda3/lib/python3.10/site-packages/nnsight/intervention/interleaver.py", line 133, in skippable_forward
    return forward(*args, **kwargs)
  File "/u/svcndifuser/miniconda3/lib/python3.10/site-packages/transformers/models/llama/modeling_llama.py", line 289, in forward
    hidden_states, _ = self.self_attn(
  File "/u/svcndifuser/miniconda3/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1751, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/u/svcndifuser/miniconda3/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1857, in _call_impl
    return inner()
  File "/u/svcndifuser/miniconda3/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1805, in inner
    result = forward_call(*args, **kwargs)
  File "/u/svcndifuser/miniconda3/lib/python3.10/site-packages/nnsight/intervention/interleaver.py", line 133, in skippable_forward
    return forward(*args, **kwargs)
  File "/u/svcndifuser/miniconda3/lib/python3.10/site-packages/transformers/models/llama/modeling_llama.py", line 242, in forward
    key_states, value_states = past_key_value.update(key_states, value_states, self.layer_idx, cache_kwargs)
  File "/u/svcndifuser/miniconda3/lib/python3.10/site-packages/transformers/cache_utils.py", line 992, in _wrapped_update
    key_tensors, value_tensors = fn(self, key_states, value_states, layer_idx, cache_kwargs)
  File "/u/svcndifuser/miniconda3/lib/python3.10/site-packages/transformers/cache_utils.py", line 1201, in update
    return self.layers[layer_idx].update(key_states, value_states, cache_kwargs)
  File "/u/svcndifuser/miniconda3/lib/python3.10/site-packages/transformers/cache_utils.py", line 103, in update
    self.values = torch.cat([self.values, value_states], dim=-2)

OutOfMemoryError: CUDA out of memory. Tried to allocate 40.00 MiB. GPU 0 has a total capacity of 44.34 GiB of which 12.81 MiB is free. Including non-PyTorch memory, this process has 44.32 GiB memory in use. Of the allocated memory 40.59 GiB is allocated by PyTorch, and 3.42 GiB is reserved by PyTorch but unallocated. If reserved but unallocated memory is large try setting PYTORCH_CUDA_ALLOC_CONF=expandable_segments:True to avoid fragmentation.  See documentation for Memory Management  (https://pytorch.org/docs/stable/notes/cuda.html#environment-variables)
Remote exception.

[2025-08-29 19:13:44] [0c3d19ef-3581-43fc-872e-6cf25e4d3c46] RECEIVED   : Your job has been received and is waiting to be queued.
[2025-08-29 19:13:44] [0c3d19ef-3581-43fc-872e-6cf25e4d3c46] QUEUED     : Your job has been recieved by the coordinator and is waiting to be queued.
[2025-08-29 19:13:44] [0c3d19ef-3581-43fc-872e-6cf25e4d3c46] QUEUED     : Task 0c3d19ef-3581-43fc-872e-6cf25e4d3c46 has been added to the queue. Currently at position 1
[2025-08-29 19:13:44] [0c3d19ef-3581-43fc-872e-6cf25e4d3c46] QUEUED     : Dispatching task...
[2025-08-29 19:13:45] [0c3d19ef-3581-43fc-872e-6cf25e4d3c46] RUNNING    : Your job has started running.

Error on problem 225: Traceback (most recent call last):
  File "/u/svcndifuser/ndif-deployment/repos/prod/ndif/src/services/ray/src/ray/deployments/modeling/base.py", line 213, in __call__
    result = await job_task
  File "/u/svcndifuser/miniconda3/lib/python3.10/asyncio/threads.py", line 25, in to_thread
    return await loop.run_in_executor(None, func_call)
  File "/u/svcndifuser/miniconda3/lib/python3.10/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/u/svcndifuser/miniconda3/lib/python3.10/site-packages/ray/util/tracing/tracing_helper.py", line 463, in _resume_span
    return method(self, *_args, **_kwargs)
  File "/u/svcndifuser/ndif-deployment/repos/prod/ndif/src/services/ray/src/ray/deployments/modeling/base.py", line 283, in execute
    result = RemoteExecutionBackend(request.interventions, self.execution_protector)(request.tracer)
  File "/u/svcndifuser/ndif-deployment/repos/prod/ndif/src/services/ray/src/ray/nn/backend.py", line 27, in __call__
    run(tracer, self.fn)
  File "/u/svcndifuser/ndif-deployment/repos/prod/ndif/src/services/ray/src/ray/nn/sandbox.py", line 16, in run
    raise wrap_exception(e,tracer.info) from None
nnsight.NNsightException:

Traceback (most recent call last):
  File "/u/svcndifuser/ndif-deployment/repos/prod/ndif/src/services/ray/src/ray/nn/sandbox.py", line 14, in run
    tracer.execute(fn)
  File "/u/svcndifuser/miniconda3/lib/python3.10/site-packages/nnsight/intervention/tracing/tracer.py", line 385, in execute
    self.model.interleave(self.fn, *args, **kwargs)
  File "/u/svcndifuser/miniconda3/lib/python3.10/site-packages/nnsight/modeling/mixins/meta.py", line 76, in interleave
    return super().interleave(fn, *args, **kwargs)
  File "/u/svcndifuser/miniconda3/lib/python3.10/site-packages/nnsight/intervention/envoy.py", line 733, in interleave
    fn(*args, **kwargs)
  File "/u/svcndifuser/miniconda3/lib/python3.10/site-packages/nnsight/modeling/language.py", line 173, in __nnsight_generate__
    output = self._model.generate(*args, streamer=streamer, **kwargs)
  File "/u/svcndifuser/miniconda3/lib/python3.10/site-packages/torch/utils/_contextlib.py", line 116, in decorate_context
    return func(*args, **kwargs)
  File "/u/svcndifuser/miniconda3/lib/python3.10/site-packages/transformers/generation/utils.py", line 2629, in generate
    result = self._sample(
  File "/u/svcndifuser/miniconda3/lib/python3.10/site-packages/transformers/generation/utils.py", line 3613, in _sample
    outputs = model_forward(**model_inputs, return_dict=True)
  File "/u/svcndifuser/miniconda3/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1751, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/u/svcndifuser/miniconda3/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1857, in _call_impl
    return inner()
  File "/u/svcndifuser/miniconda3/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1805, in inner
    result = forward_call(*args, **kwargs)
  File "/u/svcndifuser/miniconda3/lib/python3.10/site-packages/nnsight/intervention/interleaver.py", line 133, in skippable_forward
    return forward(*args, **kwargs)
  File "/u/svcndifuser/miniconda3/lib/python3.10/site-packages/transformers/utils/generic.py", line 959, in wrapper
    output = func(self, *args, **kwargs)
  File "/u/svcndifuser/miniconda3/lib/python3.10/site-packages/transformers/models/llama/modeling_llama.py", line 460, in forward
    outputs: BaseModelOutputWithPast = self.model(
  File "/u/svcndifuser/miniconda3/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1751, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/u/svcndifuser/miniconda3/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1857, in _call_impl
    return inner()
  File "/u/svcndifuser/miniconda3/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1805, in inner
    result = forward_call(*args, **kwargs)
  File "/u/svcndifuser/miniconda3/lib/python3.10/site-packages/nnsight/intervention/interleaver.py", line 133, in skippable_forward
    return forward(*args, **kwargs)
  File "/u/svcndifuser/miniconda3/lib/python3.10/site-packages/transformers/utils/generic.py", line 1083, in wrapper
    outputs = func(self, *args, **kwargs)
  File "/u/svcndifuser/miniconda3/lib/python3.10/site-packages/transformers/models/llama/modeling_llama.py", line 390, in forward
    hidden_states = decoder_layer(
  File "/u/svcndifuser/miniconda3/lib/python3.10/site-packages/transformers/modeling_layers.py", line 94, in __call__
    return super().__call__(*args, **kwargs)
  File "/u/svcndifuser/miniconda3/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1751, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/u/svcndifuser/miniconda3/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1857, in _call_impl
    return inner()
  File "/u/svcndifuser/miniconda3/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1805, in inner
    result = forward_call(*args, **kwargs)
  File "/u/svcndifuser/miniconda3/lib/python3.10/site-packages/nnsight/intervention/interleaver.py", line 133, in skippable_forward
    return forward(*args, **kwargs)
  File "/u/svcndifuser/miniconda3/lib/python3.10/site-packages/transformers/models/llama/modeling_llama.py", line 289, in forward
    hidden_states, _ = self.self_attn(
  File "/u/svcndifuser/miniconda3/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1751, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/u/svcndifuser/miniconda3/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1857, in _call_impl
    return inner()
  File "/u/svcndifuser/miniconda3/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1805, in inner
    result = forward_call(*args, **kwargs)
  File "/u/svcndifuser/miniconda3/lib/python3.10/site-packages/nnsight/intervention/interleaver.py", line 133, in skippable_forward
    return forward(*args, **kwargs)
  File "/u/svcndifuser/miniconda3/lib/python3.10/site-packages/transformers/models/llama/modeling_llama.py", line 242, in forward
    key_states, value_states = past_key_value.update(key_states, value_states, self.layer_idx, cache_kwargs)
  File "/u/svcndifuser/miniconda3/lib/python3.10/site-packages/transformers/cache_utils.py", line 992, in _wrapped_update
    key_tensors, value_tensors = fn(self, key_states, value_states, layer_idx, cache_kwargs)
  File "/u/svcndifuser/miniconda3/lib/python3.10/site-packages/transformers/cache_utils.py", line 1201, in update
    return self.layers[layer_idx].update(key_states, value_states, cache_kwargs)
  File "/u/svcndifuser/miniconda3/lib/python3.10/site-packages/transformers/cache_utils.py", line 102, in update
    self.keys = torch.cat([self.keys, key_states], dim=-2)

OutOfMemoryError: CUDA out of memory. Tried to allocate 38.00 MiB. GPU 0 has a total capacity of 44.34 GiB of which 26.81 MiB is free. Including non-PyTorch memory, this process has 44.30 GiB memory in use. Of the allocated memory 40.53 GiB is allocated by PyTorch, and 3.46 GiB is reserved by PyTorch but unallocated. If reserved but unallocated memory is large try setting PYTORCH_CUDA_ALLOC_CONF=expandable_segments:True to avoid fragmentation.  See documentation for Memory Management  (https://pytorch.org/docs/stable/notes/cuda.html#environment-variables)



Traceback (most recent call last):
  File "/u/svcndifuser/ndif-deployment/repos/prod/ndif/src/services/ray/src/ray/nn/sandbox.py", line 14, in run
    tracer.execute(fn)
  File "/u/svcndifuser/miniconda3/lib/python3.10/site-packages/nnsight/intervention/tracing/tracer.py", line 385, in execute
    self.model.interleave(self.fn, *args, **kwargs)
  File "/u/svcndifuser/miniconda3/lib/python3.10/site-packages/nnsight/modeling/mixins/meta.py", line 76, in interleave
    return super().interleave(fn, *args, **kwargs)
  File "/u/svcndifuser/miniconda3/lib/python3.10/site-packages/nnsight/intervention/envoy.py", line 733, in interleave
    fn(*args, **kwargs)
  File "/u/svcndifuser/miniconda3/lib/python3.10/site-packages/nnsight/modeling/language.py", line 173, in __nnsight_generate__
    output = self._model.generate(*args, streamer=streamer, **kwargs)
  File "/u/svcndifuser/miniconda3/lib/python3.10/site-packages/torch/utils/_contextlib.py", line 116, in decorate_context
    return func(*args, **kwargs)
  File "/u/svcndifuser/miniconda3/lib/python3.10/site-packages/transformers/generation/utils.py", line 2629, in generate
    result = self._sample(
  File "/u/svcndifuser/miniconda3/lib/python3.10/site-packages/transformers/generation/utils.py", line 3613, in _sample
    outputs = model_forward(**model_inputs, return_dict=True)
  File "/u/svcndifuser/miniconda3/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1751, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/u/svcndifuser/miniconda3/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1857, in _call_impl
    return inner()
  File "/u/svcndifuser/miniconda3/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1805, in inner
    result = forward_call(*args, **kwargs)
  File "/u/svcndifuser/miniconda3/lib/python3.10/site-packages/nnsight/intervention/interleaver.py", line 133, in skippable_forward
    return forward(*args, **kwargs)
  File "/u/svcndifuser/miniconda3/lib/python3.10/site-packages/transformers/utils/generic.py", line 959, in wrapper
    output = func(self, *args, **kwargs)
  File "/u/svcndifuser/miniconda3/lib/python3.10/site-packages/transformers/models/llama/modeling_llama.py", line 460, in forward
    outputs: BaseModelOutputWithPast = self.model(
  File "/u/svcndifuser/miniconda3/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1751, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/u/svcndifuser/miniconda3/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1857, in _call_impl
    return inner()
  File "/u/svcndifuser/miniconda3/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1805, in inner
    result = forward_call(*args, **kwargs)
  File "/u/svcndifuser/miniconda3/lib/python3.10/site-packages/nnsight/intervention/interleaver.py", line 133, in skippable_forward
    return forward(*args, **kwargs)
  File "/u/svcndifuser/miniconda3/lib/python3.10/site-packages/transformers/utils/generic.py", line 1083, in wrapper
    outputs = func(self, *args, **kwargs)
  File "/u/svcndifuser/miniconda3/lib/python3.10/site-packages/transformers/models/llama/modeling_llama.py", line 390, in forward
    hidden_states = decoder_layer(
  File "/u/svcndifuser/miniconda3/lib/python3.10/site-packages/transformers/modeling_layers.py", line 94, in __call__
    return super().__call__(*args, **kwargs)
  File "/u/svcndifuser/miniconda3/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1751, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/u/svcndifuser/miniconda3/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1857, in _call_impl
    return inner()
  File "/u/svcndifuser/miniconda3/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1805, in inner
    result = forward_call(*args, **kwargs)
  File "/u/svcndifuser/miniconda3/lib/python3.10/site-packages/nnsight/intervention/interleaver.py", line 133, in skippable_forward
    return forward(*args, **kwargs)
  File "/u/svcndifuser/miniconda3/lib/python3.10/site-packages/transformers/models/llama/modeling_llama.py", line 289, in forward
    hidden_states, _ = self.self_attn(
  File "/u/svcndifuser/miniconda3/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1751, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/u/svcndifuser/miniconda3/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1857, in _call_impl
    return inner()
  File "/u/svcndifuser/miniconda3/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1805, in inner
    result = forward_call(*args, **kwargs)
  File "/u/svcndifuser/miniconda3/lib/python3.10/site-packages/nnsight/intervention/interleaver.py", line 133, in skippable_forward
    return forward(*args, **kwargs)
  File "/u/svcndifuser/miniconda3/lib/python3.10/site-packages/transformers/models/llama/modeling_llama.py", line 242, in forward
    key_states, value_states = past_key_value.update(key_states, value_states, self.layer_idx, cache_kwargs)
  File "/u/svcndifuser/miniconda3/lib/python3.10/site-packages/transformers/cache_utils.py", line 992, in _wrapped_update
    key_tensors, value_tensors = fn(self, key_states, value_states, layer_idx, cache_kwargs)
  File "/u/svcndifuser/miniconda3/lib/python3.10/site-packages/transformers/cache_utils.py", line 1201, in update
    return self.layers[layer_idx].update(key_states, value_states, cache_kwargs)
  File "/u/svcndifuser/miniconda3/lib/python3.10/site-packages/transformers/cache_utils.py", line 102, in update
    self.keys = torch.cat([self.keys, key_states], dim=-2)

OutOfMemoryError: CUDA out of memory. Tried to allocate 38.00 MiB. GPU 0 has a total capacity of 44.34 GiB of which 26.81 MiB is free. Including non-PyTorch memory, this process has 44.30 GiB memory in use. Of the allocated memory 40.53 GiB is allocated by PyTorch, and 3.46 GiB is reserved by PyTorch but unallocated. If reserved but unallocated memory is large try setting PYTORCH_CUDA_ALLOC_CONF=expandable_segments:True to avoid fragmentation.  See documentation for Memory Management  (https://pytorch.org/docs/stable/notes/cuda.html#environment-variables)
Remote exception.

[2025-08-29 19:14:10] [5170b4cc-8622-4e2f-ba53-28eab798753c] RECEIVED   : Your job has been received and is waiting to be queued.
[2025-08-29 19:14:10] [5170b4cc-8622-4e2f-ba53-28eab798753c] QUEUED     : Your job has been recieved by the coordinator and is waiting to be queued.
[2025-08-29 19:14:10] [5170b4cc-8622-4e2f-ba53-28eab798753c] QUEUED     : Task 5170b4cc-8622-4e2f-ba53-28eab798753c has been added to the queue. Currently at position 1
[2025-08-29 19:14:10] [5170b4cc-8622-4e2f-ba53-28eab798753c] QUEUED     : Dispatching task...
[2025-08-29 19:14:12] [5170b4cc-8622-4e2f-ba53-28eab798753c] RUNNING    : Your job has started running.

Error on problem 226: Traceback (most recent call last):
  File "/u/svcndifuser/ndif-deployment/repos/prod/ndif/src/services/ray/src/ray/deployments/modeling/base.py", line 213, in __call__
    result = await job_task
  File "/u/svcndifuser/miniconda3/lib/python3.10/asyncio/threads.py", line 25, in to_thread
    return await loop.run_in_executor(None, func_call)
  File "/u/svcndifuser/miniconda3/lib/python3.10/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/u/svcndifuser/miniconda3/lib/python3.10/site-packages/ray/util/tracing/tracing_helper.py", line 463, in _resume_span
    return method(self, *_args, **_kwargs)
  File "/u/svcndifuser/ndif-deployment/repos/prod/ndif/src/services/ray/src/ray/deployments/modeling/base.py", line 283, in execute
    result = RemoteExecutionBackend(request.interventions, self.execution_protector)(request.tracer)
  File "/u/svcndifuser/ndif-deployment/repos/prod/ndif/src/services/ray/src/ray/nn/backend.py", line 27, in __call__
    run(tracer, self.fn)
  File "/u/svcndifuser/ndif-deployment/repos/prod/ndif/src/services/ray/src/ray/nn/sandbox.py", line 16, in run
    raise wrap_exception(e,tracer.info) from None
nnsight.NNsightException:

Traceback (most recent call last):
  File "/u/svcndifuser/ndif-deployment/repos/prod/ndif/src/services/ray/src/ray/nn/sandbox.py", line 14, in run
    tracer.execute(fn)
  File "/u/svcndifuser/miniconda3/lib/python3.10/site-packages/nnsight/intervention/tracing/tracer.py", line 385, in execute
    self.model.interleave(self.fn, *args, **kwargs)
  File "/u/svcndifuser/miniconda3/lib/python3.10/site-packages/nnsight/modeling/mixins/meta.py", line 76, in interleave
    return super().interleave(fn, *args, **kwargs)
  File "/u/svcndifuser/miniconda3/lib/python3.10/site-packages/nnsight/intervention/envoy.py", line 733, in interleave
    fn(*args, **kwargs)
  File "/u/svcndifuser/miniconda3/lib/python3.10/site-packages/nnsight/modeling/language.py", line 173, in __nnsight_generate__
    output = self._model.generate(*args, streamer=streamer, **kwargs)
  File "/u/svcndifuser/miniconda3/lib/python3.10/site-packages/torch/utils/_contextlib.py", line 116, in decorate_context
    return func(*args, **kwargs)
  File "/u/svcndifuser/miniconda3/lib/python3.10/site-packages/transformers/generation/utils.py", line 2629, in generate
    result = self._sample(
  File "/u/svcndifuser/miniconda3/lib/python3.10/site-packages/transformers/generation/utils.py", line 3613, in _sample
    outputs = model_forward(**model_inputs, return_dict=True)
  File "/u/svcndifuser/miniconda3/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1751, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/u/svcndifuser/miniconda3/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1857, in _call_impl
    return inner()
  File "/u/svcndifuser/miniconda3/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1805, in inner
    result = forward_call(*args, **kwargs)
  File "/u/svcndifuser/miniconda3/lib/python3.10/site-packages/nnsight/intervention/interleaver.py", line 133, in skippable_forward
    return forward(*args, **kwargs)
  File "/u/svcndifuser/miniconda3/lib/python3.10/site-packages/transformers/utils/generic.py", line 959, in wrapper
    output = func(self, *args, **kwargs)
  File "/u/svcndifuser/miniconda3/lib/python3.10/site-packages/transformers/models/llama/modeling_llama.py", line 460, in forward
    outputs: BaseModelOutputWithPast = self.model(
  File "/u/svcndifuser/miniconda3/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1751, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/u/svcndifuser/miniconda3/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1857, in _call_impl
    return inner()
  File "/u/svcndifuser/miniconda3/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1805, in inner
    result = forward_call(*args, **kwargs)
  File "/u/svcndifuser/miniconda3/lib/python3.10/site-packages/nnsight/intervention/interleaver.py", line 133, in skippable_forward
    return forward(*args, **kwargs)
  File "/u/svcndifuser/miniconda3/lib/python3.10/site-packages/transformers/utils/generic.py", line 1083, in wrapper
    outputs = func(self, *args, **kwargs)
  File "/u/svcndifuser/miniconda3/lib/python3.10/site-packages/transformers/models/llama/modeling_llama.py", line 390, in forward
    hidden_states = decoder_layer(
  File "/u/svcndifuser/miniconda3/lib/python3.10/site-packages/transformers/modeling_layers.py", line 94, in __call__
    return super().__call__(*args, **kwargs)
  File "/u/svcndifuser/miniconda3/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1751, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/u/svcndifuser/miniconda3/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1857, in _call_impl
    return inner()
  File "/u/svcndifuser/miniconda3/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1805, in inner
    result = forward_call(*args, **kwargs)
  File "/u/svcndifuser/miniconda3/lib/python3.10/site-packages/nnsight/intervention/interleaver.py", line 133, in skippable_forward
    return forward(*args, **kwargs)
  File "/u/svcndifuser/miniconda3/lib/python3.10/site-packages/transformers/models/llama/modeling_llama.py", line 289, in forward
    hidden_states, _ = self.self_attn(
  File "/u/svcndifuser/miniconda3/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1751, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/u/svcndifuser/miniconda3/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1857, in _call_impl
    return inner()
  File "/u/svcndifuser/miniconda3/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1805, in inner
    result = forward_call(*args, **kwargs)
  File "/u/svcndifuser/miniconda3/lib/python3.10/site-packages/nnsight/intervention/interleaver.py", line 133, in skippable_forward
    return forward(*args, **kwargs)
  File "/u/svcndifuser/miniconda3/lib/python3.10/site-packages/transformers/models/llama/modeling_llama.py", line 242, in forward
    key_states, value_states = past_key_value.update(key_states, value_states, self.layer_idx, cache_kwargs)
  File "/u/svcndifuser/miniconda3/lib/python3.10/site-packages/transformers/cache_utils.py", line 992, in _wrapped_update
    key_tensors, value_tensors = fn(self, key_states, value_states, layer_idx, cache_kwargs)
  File "/u/svcndifuser/miniconda3/lib/python3.10/site-packages/transformers/cache_utils.py", line 1201, in update
    return self.layers[layer_idx].update(key_states, value_states, cache_kwargs)
  File "/u/svcndifuser/miniconda3/lib/python3.10/site-packages/transformers/cache_utils.py", line 102, in update
    self.keys = torch.cat([self.keys, key_states], dim=-2)

OutOfMemoryError: CUDA out of memory. Tried to allocate 38.00 MiB. GPU 0 has a total capacity of 44.34 GiB of which 6.81 MiB is free. Including non-PyTorch memory, this process has 44.32 GiB memory in use. Of the allocated memory 40.50 GiB is allocated by PyTorch, and 3.51 GiB is reserved by PyTorch but unallocated. If reserved but unallocated memory is large try setting PYTORCH_CUDA_ALLOC_CONF=expandable_segments:True to avoid fragmentation.  See documentation for Memory Management  (https://pytorch.org/docs/stable/notes/cuda.html#environment-variables)



Traceback (most recent call last):
  File "/u/svcndifuser/ndif-deployment/repos/prod/ndif/src/services/ray/src/ray/nn/sandbox.py", line 14, in run
    tracer.execute(fn)
  File "/u/svcndifuser/miniconda3/lib/python3.10/site-packages/nnsight/intervention/tracing/tracer.py", line 385, in execute
    self.model.interleave(self.fn, *args, **kwargs)
  File "/u/svcndifuser/miniconda3/lib/python3.10/site-packages/nnsight/modeling/mixins/meta.py", line 76, in interleave
    return super().interleave(fn, *args, **kwargs)
  File "/u/svcndifuser/miniconda3/lib/python3.10/site-packages/nnsight/intervention/envoy.py", line 733, in interleave
    fn(*args, **kwargs)
  File "/u/svcndifuser/miniconda3/lib/python3.10/site-packages/nnsight/modeling/language.py", line 173, in __nnsight_generate__
    output = self._model.generate(*args, streamer=streamer, **kwargs)
  File "/u/svcndifuser/miniconda3/lib/python3.10/site-packages/torch/utils/_contextlib.py", line 116, in decorate_context
    return func(*args, **kwargs)
  File "/u/svcndifuser/miniconda3/lib/python3.10/site-packages/transformers/generation/utils.py", line 2629, in generate
    result = self._sample(
  File "/u/svcndifuser/miniconda3/lib/python3.10/site-packages/transformers/generation/utils.py", line 3613, in _sample
    outputs = model_forward(**model_inputs, return_dict=True)
  File "/u/svcndifuser/miniconda3/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1751, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/u/svcndifuser/miniconda3/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1857, in _call_impl
    return inner()
  File "/u/svcndifuser/miniconda3/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1805, in inner
    result = forward_call(*args, **kwargs)
  File "/u/svcndifuser/miniconda3/lib/python3.10/site-packages/nnsight/intervention/interleaver.py", line 133, in skippable_forward
    return forward(*args, **kwargs)
  File "/u/svcndifuser/miniconda3/lib/python3.10/site-packages/transformers/utils/generic.py", line 959, in wrapper
    output = func(self, *args, **kwargs)
  File "/u/svcndifuser/miniconda3/lib/python3.10/site-packages/transformers/models/llama/modeling_llama.py", line 460, in forward
    outputs: BaseModelOutputWithPast = self.model(
  File "/u/svcndifuser/miniconda3/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1751, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/u/svcndifuser/miniconda3/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1857, in _call_impl
    return inner()
  File "/u/svcndifuser/miniconda3/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1805, in inner
    result = forward_call(*args, **kwargs)
  File "/u/svcndifuser/miniconda3/lib/python3.10/site-packages/nnsight/intervention/interleaver.py", line 133, in skippable_forward
    return forward(*args, **kwargs)
  File "/u/svcndifuser/miniconda3/lib/python3.10/site-packages/transformers/utils/generic.py", line 1083, in wrapper
    outputs = func(self, *args, **kwargs)
  File "/u/svcndifuser/miniconda3/lib/python3.10/site-packages/transformers/models/llama/modeling_llama.py", line 390, in forward
    hidden_states = decoder_layer(
  File "/u/svcndifuser/miniconda3/lib/python3.10/site-packages/transformers/modeling_layers.py", line 94, in __call__
    return super().__call__(*args, **kwargs)
  File "/u/svcndifuser/miniconda3/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1751, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/u/svcndifuser/miniconda3/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1857, in _call_impl
    return inner()
  File "/u/svcndifuser/miniconda3/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1805, in inner
    result = forward_call(*args, **kwargs)
  File "/u/svcndifuser/miniconda3/lib/python3.10/site-packages/nnsight/intervention/interleaver.py", line 133, in skippable_forward
    return forward(*args, **kwargs)
  File "/u/svcndifuser/miniconda3/lib/python3.10/site-packages/transformers/models/llama/modeling_llama.py", line 289, in forward
    hidden_states, _ = self.self_attn(
  File "/u/svcndifuser/miniconda3/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1751, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/u/svcndifuser/miniconda3/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1857, in _call_impl
    return inner()
  File "/u/svcndifuser/miniconda3/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1805, in inner
    result = forward_call(*args, **kwargs)
  File "/u/svcndifuser/miniconda3/lib/python3.10/site-packages/nnsight/intervention/interleaver.py", line 133, in skippable_forward
    return forward(*args, **kwargs)
  File "/u/svcndifuser/miniconda3/lib/python3.10/site-packages/transformers/models/llama/modeling_llama.py", line 242, in forward
    key_states, value_states = past_key_value.update(key_states, value_states, self.layer_idx, cache_kwargs)
  File "/u/svcndifuser/miniconda3/lib/python3.10/site-packages/transformers/cache_utils.py", line 992, in _wrapped_update
    key_tensors, value_tensors = fn(self, key_states, value_states, layer_idx, cache_kwargs)
  File "/u/svcndifuser/miniconda3/lib/python3.10/site-packages/transformers/cache_utils.py", line 1201, in update
    return self.layers[layer_idx].update(key_states, value_states, cache_kwargs)
  File "/u/svcndifuser/miniconda3/lib/python3.10/site-packages/transformers/cache_utils.py", line 102, in update
    self.keys = torch.cat([self.keys, key_states], dim=-2)

OutOfMemoryError: CUDA out of memory. Tried to allocate 38.00 MiB. GPU 0 has a total capacity of 44.34 GiB of which 6.81 MiB is free. Including non-PyTorch memory, this process has 44.32 GiB memory in use. Of the allocated memory 40.50 GiB is allocated by PyTorch, and 3.51 GiB is reserved by PyTorch but unallocated. If reserved but unallocated memory is large try setting PYTORCH_CUDA_ALLOC_CONF=expandable_segments:True to avoid fragmentation.  See documentation for Memory Management  (https://pytorch.org/docs/stable/notes/cuda.html#environment-variables)
Remote exception.

[2025-08-29 19:14:37] [22f55b67-6702-4bc3-ae64-602e40df9976] RECEIVED   : Your job has been received and is waiting to be queued.
[2025-08-29 19:14:37] [22f55b67-6702-4bc3-ae64-602e40df9976] QUEUED     : Your job has been recieved by the coordinator and is waiting to be queued.
[2025-08-29 19:14:37] [22f55b67-6702-4bc3-ae64-602e40df9976] QUEUED     : Task 22f55b67-6702-4bc3-ae64-602e40df9976 has been added to the queue. Currently at position 1
[2025-08-29 19:14:37] [22f55b67-6702-4bc3-ae64-602e40df9976] QUEUED     : Dispatching task...
[2025-08-29 19:14:38] [22f55b67-6702-4bc3-ae64-602e40df9976] RUNNING    : Your job has started running.

Error on problem 227: Traceback (most recent call last):
  File "/u/svcndifuser/ndif-deployment/repos/prod/ndif/src/services/ray/src/ray/deployments/modeling/base.py", line 213, in __call__
    result = await job_task
  File "/u/svcndifuser/miniconda3/lib/python3.10/asyncio/threads.py", line 25, in to_thread
    return await loop.run_in_executor(None, func_call)
  File "/u/svcndifuser/miniconda3/lib/python3.10/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/u/svcndifuser/miniconda3/lib/python3.10/site-packages/ray/util/tracing/tracing_helper.py", line 463, in _resume_span
    return method(self, *_args, **_kwargs)
  File "/u/svcndifuser/ndif-deployment/repos/prod/ndif/src/services/ray/src/ray/deployments/modeling/base.py", line 283, in execute
    result = RemoteExecutionBackend(request.interventions, self.execution_protector)(request.tracer)
  File "/u/svcndifuser/ndif-deployment/repos/prod/ndif/src/services/ray/src/ray/nn/backend.py", line 27, in __call__
    run(tracer, self.fn)
  File "/u/svcndifuser/ndif-deployment/repos/prod/ndif/src/services/ray/src/ray/nn/sandbox.py", line 16, in run
    raise wrap_exception(e,tracer.info) from None
nnsight.NNsightException:

Traceback (most recent call last):
  File "/u/svcndifuser/ndif-deployment/repos/prod/ndif/src/services/ray/src/ray/nn/sandbox.py", line 14, in run
    tracer.execute(fn)
  File "/u/svcndifuser/miniconda3/lib/python3.10/site-packages/nnsight/intervention/tracing/tracer.py", line 385, in execute
    self.model.interleave(self.fn, *args, **kwargs)
  File "/u/svcndifuser/miniconda3/lib/python3.10/site-packages/nnsight/modeling/mixins/meta.py", line 76, in interleave
    return super().interleave(fn, *args, **kwargs)
  File "/u/svcndifuser/miniconda3/lib/python3.10/site-packages/nnsight/intervention/envoy.py", line 733, in interleave
    fn(*args, **kwargs)
  File "/u/svcndifuser/miniconda3/lib/python3.10/site-packages/nnsight/modeling/language.py", line 173, in __nnsight_generate__
    output = self._model.generate(*args, streamer=streamer, **kwargs)
  File "/u/svcndifuser/miniconda3/lib/python3.10/site-packages/torch/utils/_contextlib.py", line 116, in decorate_context
    return func(*args, **kwargs)
  File "/u/svcndifuser/miniconda3/lib/python3.10/site-packages/transformers/generation/utils.py", line 2629, in generate
    result = self._sample(
  File "/u/svcndifuser/miniconda3/lib/python3.10/site-packages/transformers/generation/utils.py", line 3613, in _sample
    outputs = model_forward(**model_inputs, return_dict=True)
  File "/u/svcndifuser/miniconda3/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1751, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/u/svcndifuser/miniconda3/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1857, in _call_impl
    return inner()
  File "/u/svcndifuser/miniconda3/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1805, in inner
    result = forward_call(*args, **kwargs)
  File "/u/svcndifuser/miniconda3/lib/python3.10/site-packages/nnsight/intervention/interleaver.py", line 133, in skippable_forward
    return forward(*args, **kwargs)
  File "/u/svcndifuser/miniconda3/lib/python3.10/site-packages/transformers/utils/generic.py", line 959, in wrapper
    output = func(self, *args, **kwargs)
  File "/u/svcndifuser/miniconda3/lib/python3.10/site-packages/transformers/models/llama/modeling_llama.py", line 460, in forward
    outputs: BaseModelOutputWithPast = self.model(
  File "/u/svcndifuser/miniconda3/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1751, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/u/svcndifuser/miniconda3/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1857, in _call_impl
    return inner()
  File "/u/svcndifuser/miniconda3/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1805, in inner
    result = forward_call(*args, **kwargs)
  File "/u/svcndifuser/miniconda3/lib/python3.10/site-packages/nnsight/intervention/interleaver.py", line 133, in skippable_forward
    return forward(*args, **kwargs)
  File "/u/svcndifuser/miniconda3/lib/python3.10/site-packages/transformers/utils/generic.py", line 1083, in wrapper
    outputs = func(self, *args, **kwargs)
  File "/u/svcndifuser/miniconda3/lib/python3.10/site-packages/transformers/models/llama/modeling_llama.py", line 390, in forward
    hidden_states = decoder_layer(
  File "/u/svcndifuser/miniconda3/lib/python3.10/site-packages/transformers/modeling_layers.py", line 94, in __call__
    return super().__call__(*args, **kwargs)
  File "/u/svcndifuser/miniconda3/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1751, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/u/svcndifuser/miniconda3/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1857, in _call_impl
    return inner()
  File "/u/svcndifuser/miniconda3/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1805, in inner
    result = forward_call(*args, **kwargs)
  File "/u/svcndifuser/miniconda3/lib/python3.10/site-packages/nnsight/intervention/interleaver.py", line 133, in skippable_forward
    return forward(*args, **kwargs)
  File "/u/svcndifuser/miniconda3/lib/python3.10/site-packages/transformers/models/llama/modeling_llama.py", line 289, in forward
    hidden_states, _ = self.self_attn(
  File "/u/svcndifuser/miniconda3/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1751, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/u/svcndifuser/miniconda3/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1857, in _call_impl
    return inner()
  File "/u/svcndifuser/miniconda3/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1805, in inner
    result = forward_call(*args, **kwargs)
  File "/u/svcndifuser/miniconda3/lib/python3.10/site-packages/nnsight/intervention/interleaver.py", line 133, in skippable_forward
    return forward(*args, **kwargs)
  File "/u/svcndifuser/miniconda3/lib/python3.10/site-packages/transformers/models/llama/modeling_llama.py", line 242, in forward
    key_states, value_states = past_key_value.update(key_states, value_states, self.layer_idx, cache_kwargs)
  File "/u/svcndifuser/miniconda3/lib/python3.10/site-packages/transformers/cache_utils.py", line 992, in _wrapped_update
    key_tensors, value_tensors = fn(self, key_states, value_states, layer_idx, cache_kwargs)
  File "/u/svcndifuser/miniconda3/lib/python3.10/site-packages/transformers/cache_utils.py", line 1201, in update
    return self.layers[layer_idx].update(key_states, value_states, cache_kwargs)
  File "/u/svcndifuser/miniconda3/lib/python3.10/site-packages/transformers/cache_utils.py", line 103, in update
    self.values = torch.cat([self.values, value_states], dim=-2)

OutOfMemoryError: CUDA out of memory. Tried to allocate 38.00 MiB. GPU 0 has a total capacity of 44.34 GiB of which 14.81 MiB is free. Including non-PyTorch memory, this process has 44.32 GiB memory in use. Of the allocated memory 40.65 GiB is allocated by PyTorch, and 3.36 GiB is reserved by PyTorch but unallocated. If reserved but unallocated memory is large try setting PYTORCH_CUDA_ALLOC_CONF=expandable_segments:True to avoid fragmentation.  See documentation for Memory Management  (https://pytorch.org/docs/stable/notes/cuda.html#environment-variables)



Traceback (most recent call last):
  File "/u/svcndifuser/ndif-deployment/repos/prod/ndif/src/services/ray/src/ray/nn/sandbox.py", line 14, in run
    tracer.execute(fn)
  File "/u/svcndifuser/miniconda3/lib/python3.10/site-packages/nnsight/intervention/tracing/tracer.py", line 385, in execute
    self.model.interleave(self.fn, *args, **kwargs)
  File "/u/svcndifuser/miniconda3/lib/python3.10/site-packages/nnsight/modeling/mixins/meta.py", line 76, in interleave
    return super().interleave(fn, *args, **kwargs)
  File "/u/svcndifuser/miniconda3/lib/python3.10/site-packages/nnsight/intervention/envoy.py", line 733, in interleave
    fn(*args, **kwargs)
  File "/u/svcndifuser/miniconda3/lib/python3.10/site-packages/nnsight/modeling/language.py", line 173, in __nnsight_generate__
    output = self._model.generate(*args, streamer=streamer, **kwargs)
  File "/u/svcndifuser/miniconda3/lib/python3.10/site-packages/torch/utils/_contextlib.py", line 116, in decorate_context
    return func(*args, **kwargs)
  File "/u/svcndifuser/miniconda3/lib/python3.10/site-packages/transformers/generation/utils.py", line 2629, in generate
    result = self._sample(
  File "/u/svcndifuser/miniconda3/lib/python3.10/site-packages/transformers/generation/utils.py", line 3613, in _sample
    outputs = model_forward(**model_inputs, return_dict=True)
  File "/u/svcndifuser/miniconda3/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1751, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/u/svcndifuser/miniconda3/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1857, in _call_impl
    return inner()
  File "/u/svcndifuser/miniconda3/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1805, in inner
    result = forward_call(*args, **kwargs)
  File "/u/svcndifuser/miniconda3/lib/python3.10/site-packages/nnsight/intervention/interleaver.py", line 133, in skippable_forward
    return forward(*args, **kwargs)
  File "/u/svcndifuser/miniconda3/lib/python3.10/site-packages/transformers/utils/generic.py", line 959, in wrapper
    output = func(self, *args, **kwargs)
  File "/u/svcndifuser/miniconda3/lib/python3.10/site-packages/transformers/models/llama/modeling_llama.py", line 460, in forward
    outputs: BaseModelOutputWithPast = self.model(
  File "/u/svcndifuser/miniconda3/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1751, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/u/svcndifuser/miniconda3/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1857, in _call_impl
    return inner()
  File "/u/svcndifuser/miniconda3/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1805, in inner
    result = forward_call(*args, **kwargs)
  File "/u/svcndifuser/miniconda3/lib/python3.10/site-packages/nnsight/intervention/interleaver.py", line 133, in skippable_forward
    return forward(*args, **kwargs)
  File "/u/svcndifuser/miniconda3/lib/python3.10/site-packages/transformers/utils/generic.py", line 1083, in wrapper
    outputs = func(self, *args, **kwargs)
  File "/u/svcndifuser/miniconda3/lib/python3.10/site-packages/transformers/models/llama/modeling_llama.py", line 390, in forward
    hidden_states = decoder_layer(
  File "/u/svcndifuser/miniconda3/lib/python3.10/site-packages/transformers/modeling_layers.py", line 94, in __call__
    return super().__call__(*args, **kwargs)
  File "/u/svcndifuser/miniconda3/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1751, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/u/svcndifuser/miniconda3/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1857, in _call_impl
    return inner()
  File "/u/svcndifuser/miniconda3/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1805, in inner
    result = forward_call(*args, **kwargs)
  File "/u/svcndifuser/miniconda3/lib/python3.10/site-packages/nnsight/intervention/interleaver.py", line 133, in skippable_forward
    return forward(*args, **kwargs)
  File "/u/svcndifuser/miniconda3/lib/python3.10/site-packages/transformers/models/llama/modeling_llama.py", line 289, in forward
    hidden_states, _ = self.self_attn(
  File "/u/svcndifuser/miniconda3/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1751, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/u/svcndifuser/miniconda3/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1857, in _call_impl
    return inner()
  File "/u/svcndifuser/miniconda3/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1805, in inner
    result = forward_call(*args, **kwargs)
  File "/u/svcndifuser/miniconda3/lib/python3.10/site-packages/nnsight/intervention/interleaver.py", line 133, in skippable_forward
    return forward(*args, **kwargs)
  File "/u/svcndifuser/miniconda3/lib/python3.10/site-packages/transformers/models/llama/modeling_llama.py", line 242, in forward
    key_states, value_states = past_key_value.update(key_states, value_states, self.layer_idx, cache_kwargs)
  File "/u/svcndifuser/miniconda3/lib/python3.10/site-packages/transformers/cache_utils.py", line 992, in _wrapped_update
    key_tensors, value_tensors = fn(self, key_states, value_states, layer_idx, cache_kwargs)
  File "/u/svcndifuser/miniconda3/lib/python3.10/site-packages/transformers/cache_utils.py", line 1201, in update
    return self.layers[layer_idx].update(key_states, value_states, cache_kwargs)
  File "/u/svcndifuser/miniconda3/lib/python3.10/site-packages/transformers/cache_utils.py", line 103, in update
    self.values = torch.cat([self.values, value_states], dim=-2)

OutOfMemoryError: CUDA out of memory. Tried to allocate 38.00 MiB. GPU 0 has a total capacity of 44.34 GiB of which 14.81 MiB is free. Including non-PyTorch memory, this process has 44.32 GiB memory in use. Of the allocated memory 40.65 GiB is allocated by PyTorch, and 3.36 GiB is reserved by PyTorch but unallocated. If reserved but unallocated memory is large try setting PYTORCH_CUDA_ALLOC_CONF=expandable_segments:True to avoid fragmentation.  See documentation for Memory Management  (https://pytorch.org/docs/stable/notes/cuda.html#environment-variables)
Remote exception.

[2025-08-29 19:15:02] [d3804821-e9a8-4383-82ea-8f714ca457da] RECEIVED   : Your job has been received and is waiting to be queued.
[2025-08-29 19:15:02] [d3804821-e9a8-4383-82ea-8f714ca457da] QUEUED     : Your job has been recieved by the coordinator and is waiting to be queued.
[2025-08-29 19:15:02] [d3804821-e9a8-4383-82ea-8f714ca457da] QUEUED     : Task d3804821-e9a8-4383-82ea-8f714ca457da has been added to the queue. Currently at position 1
[2025-08-29 19:15:02] [d3804821-e9a8-4383-82ea-8f714ca457da] QUEUED     : Dispatching task...
[2025-08-29 19:15:02] [d3804821-e9a8-4383-82ea-8f714ca457da] RUNNING    : Your job has started running.

Error on problem 228: Traceback (most recent call last):
  File "/u/svcndifuser/ndif-deployment/repos/prod/ndif/src/services/ray/src/ray/deployments/modeling/base.py", line 213, in __call__
    result = await job_task
  File "/u/svcndifuser/miniconda3/lib/python3.10/asyncio/threads.py", line 25, in to_thread
    return await loop.run_in_executor(None, func_call)
  File "/u/svcndifuser/miniconda3/lib/python3.10/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/u/svcndifuser/miniconda3/lib/python3.10/site-packages/ray/util/tracing/tracing_helper.py", line 463, in _resume_span
    return method(self, *_args, **_kwargs)
  File "/u/svcndifuser/ndif-deployment/repos/prod/ndif/src/services/ray/src/ray/deployments/modeling/base.py", line 283, in execute
    result = RemoteExecutionBackend(request.interventions, self.execution_protector)(request.tracer)
  File "/u/svcndifuser/ndif-deployment/repos/prod/ndif/src/services/ray/src/ray/nn/backend.py", line 27, in __call__
    run(tracer, self.fn)
  File "/u/svcndifuser/ndif-deployment/repos/prod/ndif/src/services/ray/src/ray/nn/sandbox.py", line 16, in run
    raise wrap_exception(e,tracer.info) from None
nnsight.NNsightException:

Traceback (most recent call last):
  File "/u/svcndifuser/ndif-deployment/repos/prod/ndif/src/services/ray/src/ray/nn/sandbox.py", line 14, in run
    tracer.execute(fn)
  File "/u/svcndifuser/miniconda3/lib/python3.10/site-packages/nnsight/intervention/tracing/tracer.py", line 385, in execute
    self.model.interleave(self.fn, *args, **kwargs)
  File "/u/svcndifuser/miniconda3/lib/python3.10/site-packages/nnsight/modeling/mixins/meta.py", line 76, in interleave
    return super().interleave(fn, *args, **kwargs)
  File "/u/svcndifuser/miniconda3/lib/python3.10/site-packages/nnsight/intervention/envoy.py", line 733, in interleave
    fn(*args, **kwargs)
  File "/u/svcndifuser/miniconda3/lib/python3.10/site-packages/nnsight/modeling/language.py", line 173, in __nnsight_generate__
    output = self._model.generate(*args, streamer=streamer, **kwargs)
  File "/u/svcndifuser/miniconda3/lib/python3.10/site-packages/torch/utils/_contextlib.py", line 116, in decorate_context
    return func(*args, **kwargs)
  File "/u/svcndifuser/miniconda3/lib/python3.10/site-packages/transformers/generation/utils.py", line 2629, in generate
    result = self._sample(
  File "/u/svcndifuser/miniconda3/lib/python3.10/site-packages/transformers/generation/utils.py", line 3629, in _sample
    next_token_scores = logits_processor(input_ids, next_token_logits)
  File "/u/svcndifuser/miniconda3/lib/python3.10/site-packages/transformers/generation/logits_process.py", line 93, in __call__
    scores = processor(input_ids, scores)
  File "/u/svcndifuser/miniconda3/lib/python3.10/site-packages/transformers/generation/logits_process.py", line 518, in __call__
    sorted_logits, sorted_indices = torch.sort(scores, descending=False)

OutOfMemoryError: CUDA out of memory. Tried to allocate 36.00 MiB. GPU 0 has a total capacity of 44.34 GiB of which 10.81 MiB is free. Including non-PyTorch memory, this process has 44.32 GiB memory in use. Of the allocated memory 40.67 GiB is allocated by PyTorch, and 3.33 GiB is reserved by PyTorch but unallocated. If reserved but unallocated memory is large try setting PYTORCH_CUDA_ALLOC_CONF=expandable_segments:True to avoid fragmentation.  See documentation for Memory Management  (https://pytorch.org/docs/stable/notes/cuda.html#environment-variables)



Traceback (most recent call last):
  File "/u/svcndifuser/ndif-deployment/repos/prod/ndif/src/services/ray/src/ray/nn/sandbox.py", line 14, in run
    tracer.execute(fn)
  File "/u/svcndifuser/miniconda3/lib/python3.10/site-packages/nnsight/intervention/tracing/tracer.py", line 385, in execute
    self.model.interleave(self.fn, *args, **kwargs)
  File "/u/svcndifuser/miniconda3/lib/python3.10/site-packages/nnsight/modeling/mixins/meta.py", line 76, in interleave
    return super().interleave(fn, *args, **kwargs)
  File "/u/svcndifuser/miniconda3/lib/python3.10/site-packages/nnsight/intervention/envoy.py", line 733, in interleave
    fn(*args, **kwargs)
  File "/u/svcndifuser/miniconda3/lib/python3.10/site-packages/nnsight/modeling/language.py", line 173, in __nnsight_generate__
    output = self._model.generate(*args, streamer=streamer, **kwargs)
  File "/u/svcndifuser/miniconda3/lib/python3.10/site-packages/torch/utils/_contextlib.py", line 116, in decorate_context
    return func(*args, **kwargs)
  File "/u/svcndifuser/miniconda3/lib/python3.10/site-packages/transformers/generation/utils.py", line 2629, in generate
    result = self._sample(
  File "/u/svcndifuser/miniconda3/lib/python3.10/site-packages/transformers/generation/utils.py", line 3629, in _sample
    next_token_scores = logits_processor(input_ids, next_token_logits)
  File "/u/svcndifuser/miniconda3/lib/python3.10/site-packages/transformers/generation/logits_process.py", line 93, in __call__
    scores = processor(input_ids, scores)
  File "/u/svcndifuser/miniconda3/lib/python3.10/site-packages/transformers/generation/logits_process.py", line 518, in __call__
    sorted_logits, sorted_indices = torch.sort(scores, descending=False)

OutOfMemoryError: CUDA out of memory. Tried to allocate 36.00 MiB. GPU 0 has a total capacity of 44.34 GiB of which 10.81 MiB is free. Including non-PyTorch memory, this process has 44.32 GiB memory in use. Of the allocated memory 40.67 GiB is allocated by PyTorch, and 3.33 GiB is reserved by PyTorch but unallocated. If reserved but unallocated memory is large try setting PYTORCH_CUDA_ALLOC_CONF=expandable_segments:True to avoid fragmentation.  See documentation for Memory Management  (https://pytorch.org/docs/stable/notes/cuda.html#environment-variables)
Remote exception.

[2025-08-29 19:15:21] [42c6212a-04d7-4867-9d54-521c9a5fb997] RECEIVED   : Your job has been received and is waiting to be queued.
[2025-08-29 19:15:21] [42c6212a-04d7-4867-9d54-521c9a5fb997] QUEUED     : Your job has been recieved by the coordinator and is waiting to be queued.
[2025-08-29 19:15:21] [42c6212a-04d7-4867-9d54-521c9a5fb997] QUEUED     : Task 42c6212a-04d7-4867-9d54-521c9a5fb997 has been added to the queue. Currently at position 1
[2025-08-29 19:15:21] [42c6212a-04d7-4867-9d54-521c9a5fb997] QUEUED     : Dispatching task...
[2025-08-29 19:15:21] [42c6212a-04d7-4867-9d54-521c9a5fb997] RUNNING    : Your job has started running.

Error on problem 229: Traceback (most recent call last):
  File "/u/svcndifuser/ndif-deployment/repos/prod/ndif/src/services/ray/src/ray/deployments/modeling/base.py", line 213, in __call__
    result = await job_task
  File "/u/svcndifuser/miniconda3/lib/python3.10/asyncio/threads.py", line 25, in to_thread
    return await loop.run_in_executor(None, func_call)
  File "/u/svcndifuser/miniconda3/lib/python3.10/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/u/svcndifuser/miniconda3/lib/python3.10/site-packages/ray/util/tracing/tracing_helper.py", line 463, in _resume_span
    return method(self, *_args, **_kwargs)
  File "/u/svcndifuser/ndif-deployment/repos/prod/ndif/src/services/ray/src/ray/deployments/modeling/base.py", line 283, in execute
    result = RemoteExecutionBackend(request.interventions, self.execution_protector)(request.tracer)
  File "/u/svcndifuser/ndif-deployment/repos/prod/ndif/src/services/ray/src/ray/nn/backend.py", line 27, in __call__
    run(tracer, self.fn)
  File "/u/svcndifuser/ndif-deployment/repos/prod/ndif/src/services/ray/src/ray/nn/sandbox.py", line 16, in run
    raise wrap_exception(e,tracer.info) from None
nnsight.NNsightException:

Traceback (most recent call last):
  File "/u/svcndifuser/ndif-deployment/repos/prod/ndif/src/services/ray/src/ray/nn/sandbox.py", line 14, in run
    tracer.execute(fn)
  File "/u/svcndifuser/miniconda3/lib/python3.10/site-packages/nnsight/intervention/tracing/tracer.py", line 385, in execute
    self.model.interleave(self.fn, *args, **kwargs)
  File "/u/svcndifuser/miniconda3/lib/python3.10/site-packages/nnsight/modeling/mixins/meta.py", line 76, in interleave
    return super().interleave(fn, *args, **kwargs)
  File "/u/svcndifuser/miniconda3/lib/python3.10/site-packages/nnsight/intervention/envoy.py", line 733, in interleave
    fn(*args, **kwargs)
  File "/u/svcndifuser/miniconda3/lib/python3.10/site-packages/nnsight/modeling/language.py", line 173, in __nnsight_generate__
    output = self._model.generate(*args, streamer=streamer, **kwargs)
  File "/u/svcndifuser/miniconda3/lib/python3.10/site-packages/torch/utils/_contextlib.py", line 116, in decorate_context
    return func(*args, **kwargs)
  File "/u/svcndifuser/miniconda3/lib/python3.10/site-packages/transformers/generation/utils.py", line 2629, in generate
    result = self._sample(
  File "/u/svcndifuser/miniconda3/lib/python3.10/site-packages/transformers/generation/utils.py", line 3629, in _sample
    next_token_scores = logits_processor(input_ids, next_token_logits)
  File "/u/svcndifuser/miniconda3/lib/python3.10/site-packages/transformers/generation/logits_process.py", line 93, in __call__
    scores = processor(input_ids, scores)
  File "/u/svcndifuser/miniconda3/lib/python3.10/site-packages/transformers/generation/logits_process.py", line 518, in __call__
    sorted_logits, sorted_indices = torch.sort(scores, descending=False)

OutOfMemoryError: CUDA out of memory. Tried to allocate 36.00 MiB. GPU 0 has a total capacity of 44.34 GiB of which 12.81 MiB is free. Including non-PyTorch memory, this process has 44.32 GiB memory in use. Of the allocated memory 40.47 GiB is allocated by PyTorch, and 3.53 GiB is reserved by PyTorch but unallocated. If reserved but unallocated memory is large try setting PYTORCH_CUDA_ALLOC_CONF=expandable_segments:True to avoid fragmentation.  See documentation for Memory Management  (https://pytorch.org/docs/stable/notes/cuda.html#environment-variables)



Traceback (most recent call last):
  File "/u/svcndifuser/ndif-deployment/repos/prod/ndif/src/services/ray/src/ray/nn/sandbox.py", line 14, in run
    tracer.execute(fn)
  File "/u/svcndifuser/miniconda3/lib/python3.10/site-packages/nnsight/intervention/tracing/tracer.py", line 385, in execute
    self.model.interleave(self.fn, *args, **kwargs)
  File "/u/svcndifuser/miniconda3/lib/python3.10/site-packages/nnsight/modeling/mixins/meta.py", line 76, in interleave
    return super().interleave(fn, *args, **kwargs)
  File "/u/svcndifuser/miniconda3/lib/python3.10/site-packages/nnsight/intervention/envoy.py", line 733, in interleave
    fn(*args, **kwargs)
  File "/u/svcndifuser/miniconda3/lib/python3.10/site-packages/nnsight/modeling/language.py", line 173, in __nnsight_generate__
    output = self._model.generate(*args, streamer=streamer, **kwargs)
  File "/u/svcndifuser/miniconda3/lib/python3.10/site-packages/torch/utils/_contextlib.py", line 116, in decorate_context
    return func(*args, **kwargs)
  File "/u/svcndifuser/miniconda3/lib/python3.10/site-packages/transformers/generation/utils.py", line 2629, in generate
    result = self._sample(
  File "/u/svcndifuser/miniconda3/lib/python3.10/site-packages/transformers/generation/utils.py", line 3629, in _sample
    next_token_scores = logits_processor(input_ids, next_token_logits)
  File "/u/svcndifuser/miniconda3/lib/python3.10/site-packages/transformers/generation/logits_process.py", line 93, in __call__
    scores = processor(input_ids, scores)
  File "/u/svcndifuser/miniconda3/lib/python3.10/site-packages/transformers/generation/logits_process.py", line 518, in __call__
    sorted_logits, sorted_indices = torch.sort(scores, descending=False)

OutOfMemoryError: CUDA out of memory. Tried to allocate 36.00 MiB. GPU 0 has a total capacity of 44.34 GiB of which 12.81 MiB is free. Including non-PyTorch memory, this process has 44.32 GiB memory in use. Of the allocated memory 40.47 GiB is allocated by PyTorch, and 3.53 GiB is reserved by PyTorch but unallocated. If reserved but unallocated memory is large try setting PYTORCH_CUDA_ALLOC_CONF=expandable_segments:True to avoid fragmentation.  See documentation for Memory Management  (https://pytorch.org/docs/stable/notes/cuda.html#environment-variables)
Remote exception.

[2025-08-29 19:15:41] [d010caf8-574c-4be4-a55a-91621beae906] RECEIVED   : Your job has been received and is waiting to be queued.
[2025-08-29 19:15:41] [d010caf8-574c-4be4-a55a-91621beae906] QUEUED     : Your job has been recieved by the coordinator and is waiting to be queued.
[2025-08-29 19:15:41] [d010caf8-574c-4be4-a55a-91621beae906] QUEUED     : Task d010caf8-574c-4be4-a55a-91621beae906 has been added to the queue. Currently at position 1
[2025-08-29 19:15:41] [d010caf8-574c-4be4-a55a-91621beae906] QUEUED     : Dispatching task...
[2025-08-29 19:15:41] [d010caf8-574c-4be4-a55a-91621beae906] RUNNING    : Your job has started running.

Error on problem 230: Traceback (most recent call last):
  File "/u/svcndifuser/ndif-deployment/repos/prod/ndif/src/services/ray/src/ray/deployments/modeling/base.py", line 213, in __call__
    result = await job_task
  File "/u/svcndifuser/miniconda3/lib/python3.10/asyncio/threads.py", line 25, in to_thread
    return await loop.run_in_executor(None, func_call)
  File "/u/svcndifuser/miniconda3/lib/python3.10/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/u/svcndifuser/miniconda3/lib/python3.10/site-packages/ray/util/tracing/tracing_helper.py", line 463, in _resume_span
    return method(self, *_args, **_kwargs)
  File "/u/svcndifuser/ndif-deployment/repos/prod/ndif/src/services/ray/src/ray/deployments/modeling/base.py", line 283, in execute
    result = RemoteExecutionBackend(request.interventions, self.execution_protector)(request.tracer)
  File "/u/svcndifuser/ndif-deployment/repos/prod/ndif/src/services/ray/src/ray/nn/backend.py", line 27, in __call__
    run(tracer, self.fn)
  File "/u/svcndifuser/ndif-deployment/repos/prod/ndif/src/services/ray/src/ray/nn/sandbox.py", line 16, in run
    raise wrap_exception(e,tracer.info) from None
nnsight.NNsightException:

Traceback (most recent call last):
  File "/u/svcndifuser/ndif-deployment/repos/prod/ndif/src/services/ray/src/ray/nn/sandbox.py", line 14, in run
    tracer.execute(fn)
  File "/u/svcndifuser/miniconda3/lib/python3.10/site-packages/nnsight/intervention/tracing/tracer.py", line 385, in execute
    self.model.interleave(self.fn, *args, **kwargs)
  File "/u/svcndifuser/miniconda3/lib/python3.10/site-packages/nnsight/modeling/mixins/meta.py", line 76, in interleave
    return super().interleave(fn, *args, **kwargs)
  File "/u/svcndifuser/miniconda3/lib/python3.10/site-packages/nnsight/intervention/envoy.py", line 733, in interleave
    fn(*args, **kwargs)
  File "/u/svcndifuser/miniconda3/lib/python3.10/site-packages/nnsight/modeling/language.py", line 173, in __nnsight_generate__
    output = self._model.generate(*args, streamer=streamer, **kwargs)
  File "/u/svcndifuser/miniconda3/lib/python3.10/site-packages/torch/utils/_contextlib.py", line 116, in decorate_context
    return func(*args, **kwargs)
  File "/u/svcndifuser/miniconda3/lib/python3.10/site-packages/transformers/generation/utils.py", line 2629, in generate
    result = self._sample(
  File "/u/svcndifuser/miniconda3/lib/python3.10/site-packages/transformers/generation/utils.py", line 3629, in _sample
    next_token_scores = logits_processor(input_ids, next_token_logits)
  File "/u/svcndifuser/miniconda3/lib/python3.10/site-packages/transformers/generation/logits_process.py", line 93, in __call__
    scores = processor(input_ids, scores)
  File "/u/svcndifuser/miniconda3/lib/python3.10/site-packages/transformers/generation/logits_process.py", line 518, in __call__
    sorted_logits, sorted_indices = torch.sort(scores, descending=False)

OutOfMemoryError: CUDA out of memory. Tried to allocate 54.00 MiB. GPU 0 has a total capacity of 44.34 GiB of which 32.81 MiB is free. Including non-PyTorch memory, this process has 44.30 GiB memory in use. Of the allocated memory 40.43 GiB is allocated by PyTorch, and 3.55 GiB is reserved by PyTorch but unallocated. If reserved but unallocated memory is large try setting PYTORCH_CUDA_ALLOC_CONF=expandable_segments:True to avoid fragmentation.  See documentation for Memory Management  (https://pytorch.org/docs/stable/notes/cuda.html#environment-variables)



Traceback (most recent call last):
  File "/u/svcndifuser/ndif-deployment/repos/prod/ndif/src/services/ray/src/ray/nn/sandbox.py", line 14, in run
    tracer.execute(fn)
  File "/u/svcndifuser/miniconda3/lib/python3.10/site-packages/nnsight/intervention/tracing/tracer.py", line 385, in execute
    self.model.interleave(self.fn, *args, **kwargs)
  File "/u/svcndifuser/miniconda3/lib/python3.10/site-packages/nnsight/modeling/mixins/meta.py", line 76, in interleave
    return super().interleave(fn, *args, **kwargs)
  File "/u/svcndifuser/miniconda3/lib/python3.10/site-packages/nnsight/intervention/envoy.py", line 733, in interleave
    fn(*args, **kwargs)
  File "/u/svcndifuser/miniconda3/lib/python3.10/site-packages/nnsight/modeling/language.py", line 173, in __nnsight_generate__
    output = self._model.generate(*args, streamer=streamer, **kwargs)
  File "/u/svcndifuser/miniconda3/lib/python3.10/site-packages/torch/utils/_contextlib.py", line 116, in decorate_context
    return func(*args, **kwargs)
  File "/u/svcndifuser/miniconda3/lib/python3.10/site-packages/transformers/generation/utils.py", line 2629, in generate
    result = self._sample(
  File "/u/svcndifuser/miniconda3/lib/python3.10/site-packages/transformers/generation/utils.py", line 3629, in _sample
    next_token_scores = logits_processor(input_ids, next_token_logits)
  File "/u/svcndifuser/miniconda3/lib/python3.10/site-packages/transformers/generation/logits_process.py", line 93, in __call__
    scores = processor(input_ids, scores)
  File "/u/svcndifuser/miniconda3/lib/python3.10/site-packages/transformers/generation/logits_process.py", line 518, in __call__
    sorted_logits, sorted_indices = torch.sort(scores, descending=False)

OutOfMemoryError: CUDA out of memory. Tried to allocate 54.00 MiB. GPU 0 has a total capacity of 44.34 GiB of which 32.81 MiB is free. Including non-PyTorch memory, this process has 44.30 GiB memory in use. Of the allocated memory 40.43 GiB is allocated by PyTorch, and 3.55 GiB is reserved by PyTorch but unallocated. If reserved but unallocated memory is large try setting PYTORCH_CUDA_ALLOC_CONF=expandable_segments:True to avoid fragmentation.  See documentation for Memory Management  (https://pytorch.org/docs/stable/notes/cuda.html#environment-variables)
Remote exception.

[2025-08-29 19:15:59] [0ed167e3-4c06-4d31-9b8c-674916fe2af0] RECEIVED   : Your job has been received and is waiting to be queued.
[2025-08-29 19:15:59] [0ed167e3-4c06-4d31-9b8c-674916fe2af0] QUEUED     : Your job has been recieved by the coordinator and is waiting to be queued.
[2025-08-29 19:15:59] [0ed167e3-4c06-4d31-9b8c-674916fe2af0] QUEUED     : Task 0ed167e3-4c06-4d31-9b8c-674916fe2af0 has been added to the queue. Currently at position 1
[2025-08-29 19:15:59] [0ed167e3-4c06-4d31-9b8c-674916fe2af0] QUEUED     : Dispatching task...
[2025-08-29 19:15:59] [0ed167e3-4c06-4d31-9b8c-674916fe2af0] RUNNING    : Your job has started running.

Error on problem 231: Traceback (most recent call last):
  File "/u/svcndifuser/ndif-deployment/repos/prod/ndif/src/services/ray/src/ray/deployments/modeling/base.py", line 213, in __call__
    result = await job_task
  File "/u/svcndifuser/miniconda3/lib/python3.10/asyncio/threads.py", line 25, in to_thread
    return await loop.run_in_executor(None, func_call)
  File "/u/svcndifuser/miniconda3/lib/python3.10/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/u/svcndifuser/miniconda3/lib/python3.10/site-packages/ray/util/tracing/tracing_helper.py", line 463, in _resume_span
    return method(self, *_args, **_kwargs)
  File "/u/svcndifuser/ndif-deployment/repos/prod/ndif/src/services/ray/src/ray/deployments/modeling/base.py", line 283, in execute
    result = RemoteExecutionBackend(request.interventions, self.execution_protector)(request.tracer)
  File "/u/svcndifuser/ndif-deployment/repos/prod/ndif/src/services/ray/src/ray/nn/backend.py", line 27, in __call__
    run(tracer, self.fn)
  File "/u/svcndifuser/ndif-deployment/repos/prod/ndif/src/services/ray/src/ray/nn/sandbox.py", line 16, in run
    raise wrap_exception(e,tracer.info) from None
nnsight.NNsightException:

Traceback (most recent call last):
  File "/u/svcndifuser/ndif-deployment/repos/prod/ndif/src/services/ray/src/ray/nn/sandbox.py", line 14, in run
    tracer.execute(fn)
  File "/u/svcndifuser/miniconda3/lib/python3.10/site-packages/nnsight/intervention/tracing/tracer.py", line 385, in execute
    self.model.interleave(self.fn, *args, **kwargs)
  File "/u/svcndifuser/miniconda3/lib/python3.10/site-packages/nnsight/modeling/mixins/meta.py", line 76, in interleave
    return super().interleave(fn, *args, **kwargs)
  File "/u/svcndifuser/miniconda3/lib/python3.10/site-packages/nnsight/intervention/envoy.py", line 733, in interleave
    fn(*args, **kwargs)
  File "/u/svcndifuser/miniconda3/lib/python3.10/site-packages/nnsight/modeling/language.py", line 173, in __nnsight_generate__
    output = self._model.generate(*args, streamer=streamer, **kwargs)
  File "/u/svcndifuser/miniconda3/lib/python3.10/site-packages/torch/utils/_contextlib.py", line 116, in decorate_context
    return func(*args, **kwargs)
  File "/u/svcndifuser/miniconda3/lib/python3.10/site-packages/transformers/generation/utils.py", line 2629, in generate
    result = self._sample(
  File "/u/svcndifuser/miniconda3/lib/python3.10/site-packages/transformers/generation/utils.py", line 3629, in _sample
    next_token_scores = logits_processor(input_ids, next_token_logits)
  File "/u/svcndifuser/miniconda3/lib/python3.10/site-packages/transformers/generation/logits_process.py", line 93, in __call__
    scores = processor(input_ids, scores)
  File "/u/svcndifuser/miniconda3/lib/python3.10/site-packages/transformers/generation/logits_process.py", line 518, in __call__
    sorted_logits, sorted_indices = torch.sort(scores, descending=False)

OutOfMemoryError: CUDA out of memory. Tried to allocate 54.00 MiB. GPU 0 has a total capacity of 44.34 GiB of which 50.81 MiB is free. Including non-PyTorch memory, this process has 44.28 GiB memory in use. Of the allocated memory 40.40 GiB is allocated by PyTorch, and 3.56 GiB is reserved by PyTorch but unallocated. If reserved but unallocated memory is large try setting PYTORCH_CUDA_ALLOC_CONF=expandable_segments:True to avoid fragmentation.  See documentation for Memory Management  (https://pytorch.org/docs/stable/notes/cuda.html#environment-variables)



Traceback (most recent call last):
  File "/u/svcndifuser/ndif-deployment/repos/prod/ndif/src/services/ray/src/ray/nn/sandbox.py", line 14, in run
    tracer.execute(fn)
  File "/u/svcndifuser/miniconda3/lib/python3.10/site-packages/nnsight/intervention/tracing/tracer.py", line 385, in execute
    self.model.interleave(self.fn, *args, **kwargs)
  File "/u/svcndifuser/miniconda3/lib/python3.10/site-packages/nnsight/modeling/mixins/meta.py", line 76, in interleave
    return super().interleave(fn, *args, **kwargs)
  File "/u/svcndifuser/miniconda3/lib/python3.10/site-packages/nnsight/intervention/envoy.py", line 733, in interleave
    fn(*args, **kwargs)
  File "/u/svcndifuser/miniconda3/lib/python3.10/site-packages/nnsight/modeling/language.py", line 173, in __nnsight_generate__
    output = self._model.generate(*args, streamer=streamer, **kwargs)
  File "/u/svcndifuser/miniconda3/lib/python3.10/site-packages/torch/utils/_contextlib.py", line 116, in decorate_context
    return func(*args, **kwargs)
  File "/u/svcndifuser/miniconda3/lib/python3.10/site-packages/transformers/generation/utils.py", line 2629, in generate
    result = self._sample(
  File "/u/svcndifuser/miniconda3/lib/python3.10/site-packages/transformers/generation/utils.py", line 3629, in _sample
    next_token_scores = logits_processor(input_ids, next_token_logits)
  File "/u/svcndifuser/miniconda3/lib/python3.10/site-packages/transformers/generation/logits_process.py", line 93, in __call__
    scores = processor(input_ids, scores)
  File "/u/svcndifuser/miniconda3/lib/python3.10/site-packages/transformers/generation/logits_process.py", line 518, in __call__
    sorted_logits, sorted_indices = torch.sort(scores, descending=False)

OutOfMemoryError: CUDA out of memory. Tried to allocate 54.00 MiB. GPU 0 has a total capacity of 44.34 GiB of which 50.81 MiB is free. Including non-PyTorch memory, this process has 44.28 GiB memory in use. Of the allocated memory 40.40 GiB is allocated by PyTorch, and 3.56 GiB is reserved by PyTorch but unallocated. If reserved but unallocated memory is large try setting PYTORCH_CUDA_ALLOC_CONF=expandable_segments:True to avoid fragmentation.  See documentation for Memory Management  (https://pytorch.org/docs/stable/notes/cuda.html#environment-variables)
Remote exception.

[2025-08-29 19:16:18] [316b59f0-642a-406f-8fde-bf74d7ecf259] RECEIVED   : Your job has been received and is waiting to be queued.
[2025-08-29 19:16:18] [316b59f0-642a-406f-8fde-bf74d7ecf259] QUEUED     : Your job has been recieved by the coordinator and is waiting to be queued.
[2025-08-29 19:16:18] [316b59f0-642a-406f-8fde-bf74d7ecf259] QUEUED     : Task 316b59f0-642a-406f-8fde-bf74d7ecf259 has been added to the queue. Currently at position 1
[2025-08-29 19:16:18] [316b59f0-642a-406f-8fde-bf74d7ecf259] QUEUED     : Dispatching task...
[2025-08-29 19:16:18] [316b59f0-642a-406f-8fde-bf74d7ecf259] RUNNING    : Your job has started running.

Error on problem 232: Traceback (most recent call last):
  File "/u/svcndifuser/ndif-deployment/repos/prod/ndif/src/services/ray/src/ray/deployments/modeling/base.py", line 213, in __call__
    result = await job_task
  File "/u/svcndifuser/miniconda3/lib/python3.10/asyncio/threads.py", line 25, in to_thread
    return await loop.run_in_executor(None, func_call)
  File "/u/svcndifuser/miniconda3/lib/python3.10/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/u/svcndifuser/miniconda3/lib/python3.10/site-packages/ray/util/tracing/tracing_helper.py", line 463, in _resume_span
    return method(self, *_args, **_kwargs)
  File "/u/svcndifuser/ndif-deployment/repos/prod/ndif/src/services/ray/src/ray/deployments/modeling/base.py", line 283, in execute
    result = RemoteExecutionBackend(request.interventions, self.execution_protector)(request.tracer)
  File "/u/svcndifuser/ndif-deployment/repos/prod/ndif/src/services/ray/src/ray/nn/backend.py", line 27, in __call__
    run(tracer, self.fn)
  File "/u/svcndifuser/ndif-deployment/repos/prod/ndif/src/services/ray/src/ray/nn/sandbox.py", line 16, in run
    raise wrap_exception(e,tracer.info) from None
nnsight.NNsightException:

Traceback (most recent call last):
  File "/u/svcndifuser/ndif-deployment/repos/prod/ndif/src/services/ray/src/ray/nn/sandbox.py", line 14, in run
    tracer.execute(fn)
  File "/u/svcndifuser/miniconda3/lib/python3.10/site-packages/nnsight/intervention/tracing/tracer.py", line 385, in execute
    self.model.interleave(self.fn, *args, **kwargs)
  File "/u/svcndifuser/miniconda3/lib/python3.10/site-packages/nnsight/modeling/mixins/meta.py", line 76, in interleave
    return super().interleave(fn, *args, **kwargs)
  File "/u/svcndifuser/miniconda3/lib/python3.10/site-packages/nnsight/intervention/envoy.py", line 733, in interleave
    fn(*args, **kwargs)
  File "/u/svcndifuser/miniconda3/lib/python3.10/site-packages/nnsight/modeling/language.py", line 173, in __nnsight_generate__
    output = self._model.generate(*args, streamer=streamer, **kwargs)
  File "/u/svcndifuser/miniconda3/lib/python3.10/site-packages/torch/utils/_contextlib.py", line 116, in decorate_context
    return func(*args, **kwargs)
  File "/u/svcndifuser/miniconda3/lib/python3.10/site-packages/transformers/generation/utils.py", line 2629, in generate
    result = self._sample(
  File "/u/svcndifuser/miniconda3/lib/python3.10/site-packages/transformers/generation/utils.py", line 3629, in _sample
    next_token_scores = logits_processor(input_ids, next_token_logits)
  File "/u/svcndifuser/miniconda3/lib/python3.10/site-packages/transformers/generation/logits_process.py", line 93, in __call__
    scores = processor(input_ids, scores)
  File "/u/svcndifuser/miniconda3/lib/python3.10/site-packages/transformers/generation/logits_process.py", line 518, in __call__
    sorted_logits, sorted_indices = torch.sort(scores, descending=False)

OutOfMemoryError: CUDA out of memory. Tried to allocate 54.00 MiB. GPU 0 has a total capacity of 44.34 GiB of which 50.81 MiB is free. Including non-PyTorch memory, this process has 44.28 GiB memory in use. Of the allocated memory 40.50 GiB is allocated by PyTorch, and 3.46 GiB is reserved by PyTorch but unallocated. If reserved but unallocated memory is large try setting PYTORCH_CUDA_ALLOC_CONF=expandable_segments:True to avoid fragmentation.  See documentation for Memory Management  (https://pytorch.org/docs/stable/notes/cuda.html#environment-variables)



Traceback (most recent call last):
  File "/u/svcndifuser/ndif-deployment/repos/prod/ndif/src/services/ray/src/ray/nn/sandbox.py", line 14, in run
    tracer.execute(fn)
  File "/u/svcndifuser/miniconda3/lib/python3.10/site-packages/nnsight/intervention/tracing/tracer.py", line 385, in execute
    self.model.interleave(self.fn, *args, **kwargs)
  File "/u/svcndifuser/miniconda3/lib/python3.10/site-packages/nnsight/modeling/mixins/meta.py", line 76, in interleave
    return super().interleave(fn, *args, **kwargs)
  File "/u/svcndifuser/miniconda3/lib/python3.10/site-packages/nnsight/intervention/envoy.py", line 733, in interleave
    fn(*args, **kwargs)
  File "/u/svcndifuser/miniconda3/lib/python3.10/site-packages/nnsight/modeling/language.py", line 173, in __nnsight_generate__
    output = self._model.generate(*args, streamer=streamer, **kwargs)
  File "/u/svcndifuser/miniconda3/lib/python3.10/site-packages/torch/utils/_contextlib.py", line 116, in decorate_context
    return func(*args, **kwargs)
  File "/u/svcndifuser/miniconda3/lib/python3.10/site-packages/transformers/generation/utils.py", line 2629, in generate
    result = self._sample(
  File "/u/svcndifuser/miniconda3/lib/python3.10/site-packages/transformers/generation/utils.py", line 3629, in _sample
    next_token_scores = logits_processor(input_ids, next_token_logits)
  File "/u/svcndifuser/miniconda3/lib/python3.10/site-packages/transformers/generation/logits_process.py", line 93, in __call__
    scores = processor(input_ids, scores)
  File "/u/svcndifuser/miniconda3/lib/python3.10/site-packages/transformers/generation/logits_process.py", line 518, in __call__
    sorted_logits, sorted_indices = torch.sort(scores, descending=False)

OutOfMemoryError: CUDA out of memory. Tried to allocate 54.00 MiB. GPU 0 has a total capacity of 44.34 GiB of which 50.81 MiB is free. Including non-PyTorch memory, this process has 44.28 GiB memory in use. Of the allocated memory 40.50 GiB is allocated by PyTorch, and 3.46 GiB is reserved by PyTorch but unallocated. If reserved but unallocated memory is large try setting PYTORCH_CUDA_ALLOC_CONF=expandable_segments:True to avoid fragmentation.  See documentation for Memory Management  (https://pytorch.org/docs/stable/notes/cuda.html#environment-variables)
Remote exception.

[2025-08-29 19:16:36] [03c447d4-5e9f-4efe-94b2-dd52d6c5c226] RECEIVED   : Your job has been received and is waiting to be queued.
[2025-08-29 19:16:36] [03c447d4-5e9f-4efe-94b2-dd52d6c5c226] QUEUED     : Your job has been recieved by the coordinator and is waiting to be queued.
[2025-08-29 19:16:36] [03c447d4-5e9f-4efe-94b2-dd52d6c5c226] QUEUED     : Task 03c447d4-5e9f-4efe-94b2-dd52d6c5c226 has been added to the queue. Currently at position 1
[2025-08-29 19:16:36] [03c447d4-5e9f-4efe-94b2-dd52d6c5c226] QUEUED     : Dispatching task...
[2025-08-29 19:16:37] [03c447d4-5e9f-4efe-94b2-dd52d6c5c226] RUNNING    : Your job has started running.

Error on problem 233: Traceback (most recent call last):
  File "/u/svcndifuser/ndif-deployment/repos/prod/ndif/src/services/ray/src/ray/deployments/modeling/base.py", line 213, in __call__
    result = await job_task
  File "/u/svcndifuser/miniconda3/lib/python3.10/asyncio/threads.py", line 25, in to_thread
    return await loop.run_in_executor(None, func_call)
  File "/u/svcndifuser/miniconda3/lib/python3.10/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/u/svcndifuser/miniconda3/lib/python3.10/site-packages/ray/util/tracing/tracing_helper.py", line 463, in _resume_span
    return method(self, *_args, **_kwargs)
  File "/u/svcndifuser/ndif-deployment/repos/prod/ndif/src/services/ray/src/ray/deployments/modeling/base.py", line 283, in execute
    result = RemoteExecutionBackend(request.interventions, self.execution_protector)(request.tracer)
  File "/u/svcndifuser/ndif-deployment/repos/prod/ndif/src/services/ray/src/ray/nn/backend.py", line 27, in __call__
    run(tracer, self.fn)
  File "/u/svcndifuser/ndif-deployment/repos/prod/ndif/src/services/ray/src/ray/nn/sandbox.py", line 16, in run
    raise wrap_exception(e,tracer.info) from None
nnsight.NNsightException:

Traceback (most recent call last):
  File "/u/svcndifuser/ndif-deployment/repos/prod/ndif/src/services/ray/src/ray/nn/sandbox.py", line 14, in run
    tracer.execute(fn)
  File "/u/svcndifuser/miniconda3/lib/python3.10/site-packages/nnsight/intervention/tracing/tracer.py", line 385, in execute
    self.model.interleave(self.fn, *args, **kwargs)
  File "/u/svcndifuser/miniconda3/lib/python3.10/site-packages/nnsight/modeling/mixins/meta.py", line 76, in interleave
    return super().interleave(fn, *args, **kwargs)
  File "/u/svcndifuser/miniconda3/lib/python3.10/site-packages/nnsight/intervention/envoy.py", line 733, in interleave
    fn(*args, **kwargs)
  File "/u/svcndifuser/miniconda3/lib/python3.10/site-packages/nnsight/modeling/language.py", line 173, in __nnsight_generate__
    output = self._model.generate(*args, streamer=streamer, **kwargs)
  File "/u/svcndifuser/miniconda3/lib/python3.10/site-packages/torch/utils/_contextlib.py", line 116, in decorate_context
    return func(*args, **kwargs)
  File "/u/svcndifuser/miniconda3/lib/python3.10/site-packages/transformers/generation/utils.py", line 2629, in generate
    result = self._sample(
  File "/u/svcndifuser/miniconda3/lib/python3.10/site-packages/transformers/generation/utils.py", line 3629, in _sample
    next_token_scores = logits_processor(input_ids, next_token_logits)
  File "/u/svcndifuser/miniconda3/lib/python3.10/site-packages/transformers/generation/logits_process.py", line 93, in __call__
    scores = processor(input_ids, scores)
  File "/u/svcndifuser/miniconda3/lib/python3.10/site-packages/transformers/generation/logits_process.py", line 518, in __call__
    sorted_logits, sorted_indices = torch.sort(scores, descending=False)

OutOfMemoryError: CUDA out of memory. Tried to allocate 54.00 MiB. GPU 0 has a total capacity of 44.34 GiB of which 46.81 MiB is free. Including non-PyTorch memory, this process has 44.29 GiB memory in use. Of the allocated memory 40.56 GiB is allocated by PyTorch, and 3.42 GiB is reserved by PyTorch but unallocated. If reserved but unallocated memory is large try setting PYTORCH_CUDA_ALLOC_CONF=expandable_segments:True to avoid fragmentation.  See documentation for Memory Management  (https://pytorch.org/docs/stable/notes/cuda.html#environment-variables)



Traceback (most recent call last):
  File "/u/svcndifuser/ndif-deployment/repos/prod/ndif/src/services/ray/src/ray/nn/sandbox.py", line 14, in run
    tracer.execute(fn)
  File "/u/svcndifuser/miniconda3/lib/python3.10/site-packages/nnsight/intervention/tracing/tracer.py", line 385, in execute
    self.model.interleave(self.fn, *args, **kwargs)
  File "/u/svcndifuser/miniconda3/lib/python3.10/site-packages/nnsight/modeling/mixins/meta.py", line 76, in interleave
    return super().interleave(fn, *args, **kwargs)
  File "/u/svcndifuser/miniconda3/lib/python3.10/site-packages/nnsight/intervention/envoy.py", line 733, in interleave
    fn(*args, **kwargs)
  File "/u/svcndifuser/miniconda3/lib/python3.10/site-packages/nnsight/modeling/language.py", line 173, in __nnsight_generate__
    output = self._model.generate(*args, streamer=streamer, **kwargs)
  File "/u/svcndifuser/miniconda3/lib/python3.10/site-packages/torch/utils/_contextlib.py", line 116, in decorate_context
    return func(*args, **kwargs)
  File "/u/svcndifuser/miniconda3/lib/python3.10/site-packages/transformers/generation/utils.py", line 2629, in generate
    result = self._sample(
  File "/u/svcndifuser/miniconda3/lib/python3.10/site-packages/transformers/generation/utils.py", line 3629, in _sample
    next_token_scores = logits_processor(input_ids, next_token_logits)
  File "/u/svcndifuser/miniconda3/lib/python3.10/site-packages/transformers/generation/logits_process.py", line 93, in __call__
    scores = processor(input_ids, scores)
  File "/u/svcndifuser/miniconda3/lib/python3.10/site-packages/transformers/generation/logits_process.py", line 518, in __call__
    sorted_logits, sorted_indices = torch.sort(scores, descending=False)

OutOfMemoryError: CUDA out of memory. Tried to allocate 54.00 MiB. GPU 0 has a total capacity of 44.34 GiB of which 46.81 MiB is free. Including non-PyTorch memory, this process has 44.29 GiB memory in use. Of the allocated memory 40.56 GiB is allocated by PyTorch, and 3.42 GiB is reserved by PyTorch but unallocated. If reserved but unallocated memory is large try setting PYTORCH_CUDA_ALLOC_CONF=expandable_segments:True to avoid fragmentation.  See documentation for Memory Management  (https://pytorch.org/docs/stable/notes/cuda.html#environment-variables)
Remote exception.

[2025-08-29 19:16:52] [5ae71b33-a2be-4a13-8712-74ef5d1ee271] RECEIVED   : Your job has been received and is waiting to be queued.
[2025-08-29 19:16:52] [5ae71b33-a2be-4a13-8712-74ef5d1ee271] QUEUED     : Your job has been recieved by the coordinator and is waiting to be queued.
[2025-08-29 19:16:52] [5ae71b33-a2be-4a13-8712-74ef5d1ee271] QUEUED     : Task 5ae71b33-a2be-4a13-8712-74ef5d1ee271 has been added to the queue. Currently at position 1
[2025-08-29 19:16:52] [5ae71b33-a2be-4a13-8712-74ef5d1ee271] QUEUED     : Dispatching task...
[2025-08-29 19:16:53] [5ae71b33-a2be-4a13-8712-74ef5d1ee271] RUNNING    : Your job has started running.

Error on problem 234: Traceback (most recent call last):
  File "/u/svcndifuser/ndif-deployment/repos/prod/ndif/src/services/ray/src/ray/deployments/modeling/base.py", line 213, in __call__
    result = await job_task
  File "/u/svcndifuser/miniconda3/lib/python3.10/asyncio/threads.py", line 25, in to_thread
    return await loop.run_in_executor(None, func_call)
  File "/u/svcndifuser/miniconda3/lib/python3.10/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/u/svcndifuser/miniconda3/lib/python3.10/site-packages/ray/util/tracing/tracing_helper.py", line 463, in _resume_span
    return method(self, *_args, **_kwargs)
  File "/u/svcndifuser/ndif-deployment/repos/prod/ndif/src/services/ray/src/ray/deployments/modeling/base.py", line 283, in execute
    result = RemoteExecutionBackend(request.interventions, self.execution_protector)(request.tracer)
  File "/u/svcndifuser/ndif-deployment/repos/prod/ndif/src/services/ray/src/ray/nn/backend.py", line 27, in __call__
    run(tracer, self.fn)
  File "/u/svcndifuser/ndif-deployment/repos/prod/ndif/src/services/ray/src/ray/nn/sandbox.py", line 16, in run
    raise wrap_exception(e,tracer.info) from None
nnsight.NNsightException:

Traceback (most recent call last):
  File "/u/svcndifuser/ndif-deployment/repos/prod/ndif/src/services/ray/src/ray/nn/sandbox.py", line 14, in run
    tracer.execute(fn)
  File "/u/svcndifuser/miniconda3/lib/python3.10/site-packages/nnsight/intervention/tracing/tracer.py", line 385, in execute
    self.model.interleave(self.fn, *args, **kwargs)
  File "/u/svcndifuser/miniconda3/lib/python3.10/site-packages/nnsight/modeling/mixins/meta.py", line 76, in interleave
    return super().interleave(fn, *args, **kwargs)
  File "/u/svcndifuser/miniconda3/lib/python3.10/site-packages/nnsight/intervention/envoy.py", line 733, in interleave
    fn(*args, **kwargs)
  File "/u/svcndifuser/miniconda3/lib/python3.10/site-packages/nnsight/modeling/language.py", line 173, in __nnsight_generate__
    output = self._model.generate(*args, streamer=streamer, **kwargs)
  File "/u/svcndifuser/miniconda3/lib/python3.10/site-packages/torch/utils/_contextlib.py", line 116, in decorate_context
    return func(*args, **kwargs)
  File "/u/svcndifuser/miniconda3/lib/python3.10/site-packages/transformers/generation/utils.py", line 2629, in generate
    result = self._sample(
  File "/u/svcndifuser/miniconda3/lib/python3.10/site-packages/transformers/generation/utils.py", line 3629, in _sample
    next_token_scores = logits_processor(input_ids, next_token_logits)
  File "/u/svcndifuser/miniconda3/lib/python3.10/site-packages/transformers/generation/logits_process.py", line 93, in __call__
    scores = processor(input_ids, scores)
  File "/u/svcndifuser/miniconda3/lib/python3.10/site-packages/transformers/generation/logits_process.py", line 518, in __call__
    sorted_logits, sorted_indices = torch.sort(scores, descending=False)

OutOfMemoryError: CUDA out of memory. Tried to allocate 54.00 MiB. GPU 0 has a total capacity of 44.34 GiB of which 20.81 MiB is free. Including non-PyTorch memory, this process has 44.31 GiB memory in use. Of the allocated memory 40.57 GiB is allocated by PyTorch, and 3.43 GiB is reserved by PyTorch but unallocated. If reserved but unallocated memory is large try setting PYTORCH_CUDA_ALLOC_CONF=expandable_segments:True to avoid fragmentation.  See documentation for Memory Management  (https://pytorch.org/docs/stable/notes/cuda.html#environment-variables)



Traceback (most recent call last):
  File "/u/svcndifuser/ndif-deployment/repos/prod/ndif/src/services/ray/src/ray/nn/sandbox.py", line 14, in run
    tracer.execute(fn)
  File "/u/svcndifuser/miniconda3/lib/python3.10/site-packages/nnsight/intervention/tracing/tracer.py", line 385, in execute
    self.model.interleave(self.fn, *args, **kwargs)
  File "/u/svcndifuser/miniconda3/lib/python3.10/site-packages/nnsight/modeling/mixins/meta.py", line 76, in interleave
    return super().interleave(fn, *args, **kwargs)
  File "/u/svcndifuser/miniconda3/lib/python3.10/site-packages/nnsight/intervention/envoy.py", line 733, in interleave
    fn(*args, **kwargs)
  File "/u/svcndifuser/miniconda3/lib/python3.10/site-packages/nnsight/modeling/language.py", line 173, in __nnsight_generate__
    output = self._model.generate(*args, streamer=streamer, **kwargs)
  File "/u/svcndifuser/miniconda3/lib/python3.10/site-packages/torch/utils/_contextlib.py", line 116, in decorate_context
    return func(*args, **kwargs)
  File "/u/svcndifuser/miniconda3/lib/python3.10/site-packages/transformers/generation/utils.py", line 2629, in generate
    result = self._sample(
  File "/u/svcndifuser/miniconda3/lib/python3.10/site-packages/transformers/generation/utils.py", line 3629, in _sample
    next_token_scores = logits_processor(input_ids, next_token_logits)
  File "/u/svcndifuser/miniconda3/lib/python3.10/site-packages/transformers/generation/logits_process.py", line 93, in __call__
    scores = processor(input_ids, scores)
  File "/u/svcndifuser/miniconda3/lib/python3.10/site-packages/transformers/generation/logits_process.py", line 518, in __call__
    sorted_logits, sorted_indices = torch.sort(scores, descending=False)

OutOfMemoryError: CUDA out of memory. Tried to allocate 54.00 MiB. GPU 0 has a total capacity of 44.34 GiB of which 20.81 MiB is free. Including non-PyTorch memory, this process has 44.31 GiB memory in use. Of the allocated memory 40.57 GiB is allocated by PyTorch, and 3.43 GiB is reserved by PyTorch but unallocated. If reserved but unallocated memory is large try setting PYTORCH_CUDA_ALLOC_CONF=expandable_segments:True to avoid fragmentation.  See documentation for Memory Management  (https://pytorch.org/docs/stable/notes/cuda.html#environment-variables)
Remote exception.

[2025-08-29 19:17:10] [217af6ce-9be3-4448-a953-c421fd8e0c03] RECEIVED   : Your job has been received and is waiting to be queued.
[2025-08-29 19:17:10] [217af6ce-9be3-4448-a953-c421fd8e0c03] QUEUED     : Your job has been recieved by the coordinator and is waiting to be queued.
[2025-08-29 19:17:10] [217af6ce-9be3-4448-a953-c421fd8e0c03] QUEUED     : Task 217af6ce-9be3-4448-a953-c421fd8e0c03 has been added to the queue. Currently at position 1
[2025-08-29 19:17:10] [217af6ce-9be3-4448-a953-c421fd8e0c03] QUEUED     : Dispatching task...
[2025-08-29 19:17:11] [217af6ce-9be3-4448-a953-c421fd8e0c03] RUNNING    : Your job has started running.

Error on problem 235: Traceback (most recent call last):
  File "/u/svcndifuser/ndif-deployment/repos/prod/ndif/src/services/ray/src/ray/deployments/modeling/base.py", line 213, in __call__
    result = await job_task
  File "/u/svcndifuser/miniconda3/lib/python3.10/asyncio/threads.py", line 25, in to_thread
    return await loop.run_in_executor(None, func_call)
  File "/u/svcndifuser/miniconda3/lib/python3.10/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/u/svcndifuser/miniconda3/lib/python3.10/site-packages/ray/util/tracing/tracing_helper.py", line 463, in _resume_span
    return method(self, *_args, **_kwargs)
  File "/u/svcndifuser/ndif-deployment/repos/prod/ndif/src/services/ray/src/ray/deployments/modeling/base.py", line 283, in execute
    result = RemoteExecutionBackend(request.interventions, self.execution_protector)(request.tracer)
  File "/u/svcndifuser/ndif-deployment/repos/prod/ndif/src/services/ray/src/ray/nn/backend.py", line 27, in __call__
    run(tracer, self.fn)
  File "/u/svcndifuser/ndif-deployment/repos/prod/ndif/src/services/ray/src/ray/nn/sandbox.py", line 16, in run
    raise wrap_exception(e,tracer.info) from None
nnsight.NNsightException:

Traceback (most recent call last):
  File "/u/svcndifuser/ndif-deployment/repos/prod/ndif/src/services/ray/src/ray/nn/sandbox.py", line 14, in run
    tracer.execute(fn)
  File "/u/svcndifuser/miniconda3/lib/python3.10/site-packages/nnsight/intervention/tracing/tracer.py", line 385, in execute
    self.model.interleave(self.fn, *args, **kwargs)
  File "/u/svcndifuser/miniconda3/lib/python3.10/site-packages/nnsight/modeling/mixins/meta.py", line 76, in interleave
    return super().interleave(fn, *args, **kwargs)
  File "/u/svcndifuser/miniconda3/lib/python3.10/site-packages/nnsight/intervention/envoy.py", line 733, in interleave
    fn(*args, **kwargs)
  File "/u/svcndifuser/miniconda3/lib/python3.10/site-packages/nnsight/modeling/language.py", line 173, in __nnsight_generate__
    output = self._model.generate(*args, streamer=streamer, **kwargs)
  File "/u/svcndifuser/miniconda3/lib/python3.10/site-packages/torch/utils/_contextlib.py", line 116, in decorate_context
    return func(*args, **kwargs)
  File "/u/svcndifuser/miniconda3/lib/python3.10/site-packages/transformers/generation/utils.py", line 2629, in generate
    result = self._sample(
  File "/u/svcndifuser/miniconda3/lib/python3.10/site-packages/transformers/generation/utils.py", line 3629, in _sample
    next_token_scores = logits_processor(input_ids, next_token_logits)
  File "/u/svcndifuser/miniconda3/lib/python3.10/site-packages/transformers/generation/logits_process.py", line 93, in __call__
    scores = processor(input_ids, scores)
  File "/u/svcndifuser/miniconda3/lib/python3.10/site-packages/transformers/generation/logits_process.py", line 518, in __call__
    sorted_logits, sorted_indices = torch.sort(scores, descending=False)

OutOfMemoryError: CUDA out of memory. Tried to allocate 54.00 MiB. GPU 0 has a total capacity of 44.34 GiB of which 52.81 MiB is free. Including non-PyTorch memory, this process has 44.28 GiB memory in use. Of the allocated memory 40.67 GiB is allocated by PyTorch, and 3.29 GiB is reserved by PyTorch but unallocated. If reserved but unallocated memory is large try setting PYTORCH_CUDA_ALLOC_CONF=expandable_segments:True to avoid fragmentation.  See documentation for Memory Management  (https://pytorch.org/docs/stable/notes/cuda.html#environment-variables)



Traceback (most recent call last):
  File "/u/svcndifuser/ndif-deployment/repos/prod/ndif/src/services/ray/src/ray/nn/sandbox.py", line 14, in run
    tracer.execute(fn)
  File "/u/svcndifuser/miniconda3/lib/python3.10/site-packages/nnsight/intervention/tracing/tracer.py", line 385, in execute
    self.model.interleave(self.fn, *args, **kwargs)
  File "/u/svcndifuser/miniconda3/lib/python3.10/site-packages/nnsight/modeling/mixins/meta.py", line 76, in interleave
    return super().interleave(fn, *args, **kwargs)
  File "/u/svcndifuser/miniconda3/lib/python3.10/site-packages/nnsight/intervention/envoy.py", line 733, in interleave
    fn(*args, **kwargs)
  File "/u/svcndifuser/miniconda3/lib/python3.10/site-packages/nnsight/modeling/language.py", line 173, in __nnsight_generate__
    output = self._model.generate(*args, streamer=streamer, **kwargs)
  File "/u/svcndifuser/miniconda3/lib/python3.10/site-packages/torch/utils/_contextlib.py", line 116, in decorate_context
    return func(*args, **kwargs)
  File "/u/svcndifuser/miniconda3/lib/python3.10/site-packages/transformers/generation/utils.py", line 2629, in generate
    result = self._sample(
  File "/u/svcndifuser/miniconda3/lib/python3.10/site-packages/transformers/generation/utils.py", line 3629, in _sample
    next_token_scores = logits_processor(input_ids, next_token_logits)
  File "/u/svcndifuser/miniconda3/lib/python3.10/site-packages/transformers/generation/logits_process.py", line 93, in __call__
    scores = processor(input_ids, scores)
  File "/u/svcndifuser/miniconda3/lib/python3.10/site-packages/transformers/generation/logits_process.py", line 518, in __call__
    sorted_logits, sorted_indices = torch.sort(scores, descending=False)

OutOfMemoryError: CUDA out of memory. Tried to allocate 54.00 MiB. GPU 0 has a total capacity of 44.34 GiB of which 52.81 MiB is free. Including non-PyTorch memory, this process has 44.28 GiB memory in use. Of the allocated memory 40.67 GiB is allocated by PyTorch, and 3.29 GiB is reserved by PyTorch but unallocated. If reserved but unallocated memory is large try setting PYTORCH_CUDA_ALLOC_CONF=expandable_segments:True to avoid fragmentation.  See documentation for Memory Management  (https://pytorch.org/docs/stable/notes/cuda.html#environment-variables)
Remote exception.

[2025-08-29 19:17:29] [0e1f48c2-4859-48a8-af31-6970978466c6] RECEIVED   : Your job has been received and is waiting to be queued.
[2025-08-29 19:17:29] [0e1f48c2-4859-48a8-af31-6970978466c6] QUEUED     : Your job has been recieved by the coordinator and is waiting to be queued.
[2025-08-29 19:17:29] [0e1f48c2-4859-48a8-af31-6970978466c6] QUEUED     : Task 0e1f48c2-4859-48a8-af31-6970978466c6 has been added to the queue. Currently at position 1
[2025-08-29 19:17:29] [0e1f48c2-4859-48a8-af31-6970978466c6] QUEUED     : Dispatching task...
[2025-08-29 19:17:30] [0e1f48c2-4859-48a8-af31-6970978466c6] RUNNING    : Your job has started running.

Error on problem 236: Traceback (most recent call last):
  File "/u/svcndifuser/ndif-deployment/repos/prod/ndif/src/services/ray/src/ray/deployments/modeling/base.py", line 213, in __call__
    result = await job_task
  File "/u/svcndifuser/miniconda3/lib/python3.10/asyncio/threads.py", line 25, in to_thread
    return await loop.run_in_executor(None, func_call)
  File "/u/svcndifuser/miniconda3/lib/python3.10/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/u/svcndifuser/miniconda3/lib/python3.10/site-packages/ray/util/tracing/tracing_helper.py", line 463, in _resume_span
    return method(self, *_args, **_kwargs)
  File "/u/svcndifuser/ndif-deployment/repos/prod/ndif/src/services/ray/src/ray/deployments/modeling/base.py", line 283, in execute
    result = RemoteExecutionBackend(request.interventions, self.execution_protector)(request.tracer)
  File "/u/svcndifuser/ndif-deployment/repos/prod/ndif/src/services/ray/src/ray/nn/backend.py", line 27, in __call__
    run(tracer, self.fn)
  File "/u/svcndifuser/ndif-deployment/repos/prod/ndif/src/services/ray/src/ray/nn/sandbox.py", line 16, in run
    raise wrap_exception(e,tracer.info) from None
nnsight.NNsightException:

Traceback (most recent call last):
  File "/u/svcndifuser/ndif-deployment/repos/prod/ndif/src/services/ray/src/ray/nn/sandbox.py", line 14, in run
    tracer.execute(fn)
  File "/u/svcndifuser/miniconda3/lib/python3.10/site-packages/nnsight/intervention/tracing/tracer.py", line 385, in execute
    self.model.interleave(self.fn, *args, **kwargs)
  File "/u/svcndifuser/miniconda3/lib/python3.10/site-packages/nnsight/modeling/mixins/meta.py", line 76, in interleave
    return super().interleave(fn, *args, **kwargs)
  File "/u/svcndifuser/miniconda3/lib/python3.10/site-packages/nnsight/intervention/envoy.py", line 733, in interleave
    fn(*args, **kwargs)
  File "/u/svcndifuser/miniconda3/lib/python3.10/site-packages/nnsight/modeling/language.py", line 173, in __nnsight_generate__
    output = self._model.generate(*args, streamer=streamer, **kwargs)
  File "/u/svcndifuser/miniconda3/lib/python3.10/site-packages/torch/utils/_contextlib.py", line 116, in decorate_context
    return func(*args, **kwargs)
  File "/u/svcndifuser/miniconda3/lib/python3.10/site-packages/transformers/generation/utils.py", line 2629, in generate
    result = self._sample(
  File "/u/svcndifuser/miniconda3/lib/python3.10/site-packages/transformers/generation/utils.py", line 3629, in _sample
    next_token_scores = logits_processor(input_ids, next_token_logits)
  File "/u/svcndifuser/miniconda3/lib/python3.10/site-packages/transformers/generation/logits_process.py", line 93, in __call__
    scores = processor(input_ids, scores)
  File "/u/svcndifuser/miniconda3/lib/python3.10/site-packages/transformers/generation/logits_process.py", line 518, in __call__
    sorted_logits, sorted_indices = torch.sort(scores, descending=False)

OutOfMemoryError: CUDA out of memory. Tried to allocate 36.00 MiB. GPU 0 has a total capacity of 44.34 GiB of which 26.81 MiB is free. Including non-PyTorch memory, this process has 44.30 GiB memory in use. Of the allocated memory 40.70 GiB is allocated by PyTorch, and 3.29 GiB is reserved by PyTorch but unallocated. If reserved but unallocated memory is large try setting PYTORCH_CUDA_ALLOC_CONF=expandable_segments:True to avoid fragmentation.  See documentation for Memory Management  (https://pytorch.org/docs/stable/notes/cuda.html#environment-variables)



Traceback (most recent call last):
  File "/u/svcndifuser/ndif-deployment/repos/prod/ndif/src/services/ray/src/ray/nn/sandbox.py", line 14, in run
    tracer.execute(fn)
  File "/u/svcndifuser/miniconda3/lib/python3.10/site-packages/nnsight/intervention/tracing/tracer.py", line 385, in execute
    self.model.interleave(self.fn, *args, **kwargs)
  File "/u/svcndifuser/miniconda3/lib/python3.10/site-packages/nnsight/modeling/mixins/meta.py", line 76, in interleave
    return super().interleave(fn, *args, **kwargs)
  File "/u/svcndifuser/miniconda3/lib/python3.10/site-packages/nnsight/intervention/envoy.py", line 733, in interleave
    fn(*args, **kwargs)
  File "/u/svcndifuser/miniconda3/lib/python3.10/site-packages/nnsight/modeling/language.py", line 173, in __nnsight_generate__
    output = self._model.generate(*args, streamer=streamer, **kwargs)
  File "/u/svcndifuser/miniconda3/lib/python3.10/site-packages/torch/utils/_contextlib.py", line 116, in decorate_context
    return func(*args, **kwargs)
  File "/u/svcndifuser/miniconda3/lib/python3.10/site-packages/transformers/generation/utils.py", line 2629, in generate
    result = self._sample(
  File "/u/svcndifuser/miniconda3/lib/python3.10/site-packages/transformers/generation/utils.py", line 3629, in _sample
    next_token_scores = logits_processor(input_ids, next_token_logits)
  File "/u/svcndifuser/miniconda3/lib/python3.10/site-packages/transformers/generation/logits_process.py", line 93, in __call__
    scores = processor(input_ids, scores)
  File "/u/svcndifuser/miniconda3/lib/python3.10/site-packages/transformers/generation/logits_process.py", line 518, in __call__
    sorted_logits, sorted_indices = torch.sort(scores, descending=False)

OutOfMemoryError: CUDA out of memory. Tried to allocate 36.00 MiB. GPU 0 has a total capacity of 44.34 GiB of which 26.81 MiB is free. Including non-PyTorch memory, this process has 44.30 GiB memory in use. Of the allocated memory 40.70 GiB is allocated by PyTorch, and 3.29 GiB is reserved by PyTorch but unallocated. If reserved but unallocated memory is large try setting PYTORCH_CUDA_ALLOC_CONF=expandable_segments:True to avoid fragmentation.  See documentation for Memory Management  (https://pytorch.org/docs/stable/notes/cuda.html#environment-variables)
Remote exception.

[2025-08-29 19:17:47] [dcab0d97-4a77-4852-bd3e-da056cb7fa40] RECEIVED   : Your job has been received and is waiting to be queued.
[2025-08-29 19:17:47] [dcab0d97-4a77-4852-bd3e-da056cb7fa40] QUEUED     : Your job has been recieved by the coordinator and is waiting to be queued.
[2025-08-29 19:17:47] [dcab0d97-4a77-4852-bd3e-da056cb7fa40] QUEUED     : Task dcab0d97-4a77-4852-bd3e-da056cb7fa40 has been added to the queue. Currently at position 1
[2025-08-29 19:17:47] [dcab0d97-4a77-4852-bd3e-da056cb7fa40] QUEUED     : Dispatching task...
[2025-08-29 19:17:48] [dcab0d97-4a77-4852-bd3e-da056cb7fa40] RUNNING    : Your job has started running.

Error on problem 237: Traceback (most recent call last):
  File "/u/svcndifuser/ndif-deployment/repos/prod/ndif/src/services/ray/src/ray/deployments/modeling/base.py", line 213, in __call__
    result = await job_task
  File "/u/svcndifuser/miniconda3/lib/python3.10/asyncio/threads.py", line 25, in to_thread
    return await loop.run_in_executor(None, func_call)
  File "/u/svcndifuser/miniconda3/lib/python3.10/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/u/svcndifuser/miniconda3/lib/python3.10/site-packages/ray/util/tracing/tracing_helper.py", line 463, in _resume_span
    return method(self, *_args, **_kwargs)
  File "/u/svcndifuser/ndif-deployment/repos/prod/ndif/src/services/ray/src/ray/deployments/modeling/base.py", line 283, in execute
    result = RemoteExecutionBackend(request.interventions, self.execution_protector)(request.tracer)
  File "/u/svcndifuser/ndif-deployment/repos/prod/ndif/src/services/ray/src/ray/nn/backend.py", line 27, in __call__
    run(tracer, self.fn)
  File "/u/svcndifuser/ndif-deployment/repos/prod/ndif/src/services/ray/src/ray/nn/sandbox.py", line 16, in run
    raise wrap_exception(e,tracer.info) from None
nnsight.NNsightException:

Traceback (most recent call last):
  File "/u/svcndifuser/ndif-deployment/repos/prod/ndif/src/services/ray/src/ray/nn/sandbox.py", line 14, in run
    tracer.execute(fn)
  File "/u/svcndifuser/miniconda3/lib/python3.10/site-packages/nnsight/intervention/tracing/tracer.py", line 385, in execute
    self.model.interleave(self.fn, *args, **kwargs)
  File "/u/svcndifuser/miniconda3/lib/python3.10/site-packages/nnsight/modeling/mixins/meta.py", line 76, in interleave
    return super().interleave(fn, *args, **kwargs)
  File "/u/svcndifuser/miniconda3/lib/python3.10/site-packages/nnsight/intervention/envoy.py", line 733, in interleave
    fn(*args, **kwargs)
  File "/u/svcndifuser/miniconda3/lib/python3.10/site-packages/nnsight/modeling/language.py", line 173, in __nnsight_generate__
    output = self._model.generate(*args, streamer=streamer, **kwargs)
  File "/u/svcndifuser/miniconda3/lib/python3.10/site-packages/torch/utils/_contextlib.py", line 116, in decorate_context
    return func(*args, **kwargs)
  File "/u/svcndifuser/miniconda3/lib/python3.10/site-packages/transformers/generation/utils.py", line 2629, in generate
    result = self._sample(
  File "/u/svcndifuser/miniconda3/lib/python3.10/site-packages/transformers/generation/utils.py", line 3629, in _sample
    next_token_scores = logits_processor(input_ids, next_token_logits)
  File "/u/svcndifuser/miniconda3/lib/python3.10/site-packages/transformers/generation/logits_process.py", line 93, in __call__
    scores = processor(input_ids, scores)
  File "/u/svcndifuser/miniconda3/lib/python3.10/site-packages/transformers/generation/logits_process.py", line 518, in __call__
    sorted_logits, sorted_indices = torch.sort(scores, descending=False)

OutOfMemoryError: CUDA out of memory. Tried to allocate 54.00 MiB. GPU 0 has a total capacity of 44.34 GiB of which 44.81 MiB is free. Including non-PyTorch memory, this process has 44.29 GiB memory in use. Of the allocated memory 40.84 GiB is allocated by PyTorch, and 3.13 GiB is reserved by PyTorch but unallocated. If reserved but unallocated memory is large try setting PYTORCH_CUDA_ALLOC_CONF=expandable_segments:True to avoid fragmentation.  See documentation for Memory Management  (https://pytorch.org/docs/stable/notes/cuda.html#environment-variables)



Traceback (most recent call last):
  File "/u/svcndifuser/ndif-deployment/repos/prod/ndif/src/services/ray/src/ray/nn/sandbox.py", line 14, in run
    tracer.execute(fn)
  File "/u/svcndifuser/miniconda3/lib/python3.10/site-packages/nnsight/intervention/tracing/tracer.py", line 385, in execute
    self.model.interleave(self.fn, *args, **kwargs)
  File "/u/svcndifuser/miniconda3/lib/python3.10/site-packages/nnsight/modeling/mixins/meta.py", line 76, in interleave
    return super().interleave(fn, *args, **kwargs)
  File "/u/svcndifuser/miniconda3/lib/python3.10/site-packages/nnsight/intervention/envoy.py", line 733, in interleave
    fn(*args, **kwargs)
  File "/u/svcndifuser/miniconda3/lib/python3.10/site-packages/nnsight/modeling/language.py", line 173, in __nnsight_generate__
    output = self._model.generate(*args, streamer=streamer, **kwargs)
  File "/u/svcndifuser/miniconda3/lib/python3.10/site-packages/torch/utils/_contextlib.py", line 116, in decorate_context
    return func(*args, **kwargs)
  File "/u/svcndifuser/miniconda3/lib/python3.10/site-packages/transformers/generation/utils.py", line 2629, in generate
    result = self._sample(
  File "/u/svcndifuser/miniconda3/lib/python3.10/site-packages/transformers/generation/utils.py", line 3629, in _sample
    next_token_scores = logits_processor(input_ids, next_token_logits)
  File "/u/svcndifuser/miniconda3/lib/python3.10/site-packages/transformers/generation/logits_process.py", line 93, in __call__
    scores = processor(input_ids, scores)
  File "/u/svcndifuser/miniconda3/lib/python3.10/site-packages/transformers/generation/logits_process.py", line 518, in __call__
    sorted_logits, sorted_indices = torch.sort(scores, descending=False)

OutOfMemoryError: CUDA out of memory. Tried to allocate 54.00 MiB. GPU 0 has a total capacity of 44.34 GiB of which 44.81 MiB is free. Including non-PyTorch memory, this process has 44.29 GiB memory in use. Of the allocated memory 40.84 GiB is allocated by PyTorch, and 3.13 GiB is reserved by PyTorch but unallocated. If reserved but unallocated memory is large try setting PYTORCH_CUDA_ALLOC_CONF=expandable_segments:True to avoid fragmentation.  See documentation for Memory Management  (https://pytorch.org/docs/stable/notes/cuda.html#environment-variables)
Remote exception.

[2025-08-29 19:18:06] [002fd471-dbed-4216-8426-93a4af327e83] RECEIVED   : Your job has been received and is waiting to be queued.
[2025-08-29 19:18:06] [002fd471-dbed-4216-8426-93a4af327e83] QUEUED     : Your job has been recieved by the coordinator and is waiting to be queued.
[2025-08-29 19:18:06] [002fd471-dbed-4216-8426-93a4af327e83] QUEUED     : Task 002fd471-dbed-4216-8426-93a4af327e83 has been added to the queue. Currently at position 1
[2025-08-29 19:18:06] [002fd471-dbed-4216-8426-93a4af327e83] QUEUED     : Dispatching task...
[2025-08-29 19:18:06] [002fd471-dbed-4216-8426-93a4af327e83] RUNNING    : Your job has started running.

KeyboardInterrupt:

In [ ]:
print(token_batch.shape)
print(token_batch[0][-1])
print(hidden_collector[-1].shape)
torch.cat(hidden_collector, dim=1).shape

In [ ]:
model.tokenizer.decode(token_batch[0])

In [ ]:
hidden_states=torch.cat(hidden_collector, dim=1)
keep_rows = (token_batch[:, promptlen:] == 128014).any(dim=1)
token_batch = token_batch[keep_rows]
b_idx, t_rel = (token_batch[:, promptlen:] == 128014).nonzero(as_tuple=True)
t_abs = t_rel + promptlen
hidden_states = hidden_states[b_idx, t_abs]

In [ ]:
hidden_states.shape

In [ ]:
import glob

In [ ]:
paths = sorted(glob.glob("/workspace/uncertainty/rollouts/*.pt"))
samples = [torch.load(p, map_location="cpu") for p in paths]

In [ ]:
generated_token_ids = []
think_blocks = []
responses = []
final_answers = []

# Post-process hidden states

# Helpers
_defective_close_variants = ["<\\think>", "< /think>", "</ think>"]

def _normalize_think_tags(text: str) -> str:
    out = text
    for bad in _defective_close_variants:
        out = out.replace(bad, "</think>")
    return out

def extract_second_think_and_response(text: str):
    norm = _normalize_think_tags(text)
    matches = list(re.finditer(r"<think>([\s\S]*?)</think>", norm))
    if len(matches) >= 2:
        second = matches[1]
        return matches[1].group(1).strip(), norm[second.end():].strip()
    if len(matches) == 1:
        first = matches[0]
        return first.group(1).strip(), norm[first.end():].strip()
    return "", norm.strip()

def extract_boxed_balanced(text: str):
    m = re.search(r"\\boxed\s*\{", text)
    if not m:
        return ""
    i = m.end()
    depth = 1
    while i < len(text) and depth > 0:
        ch = text[i]
        if ch == '{':
            depth += 1
        elif ch == '}':
            depth -= 1
        i += 1
    if depth == 0:
        return text[m.end(): i - 1].strip()
    return ""

# Decode and parse
token_ids_per_seq = token_batch
for i in range(len(token_ids_per_seq)):
    full_text = model.tokenizer.decode(token_ids_per_seq[i], skip_special_tokens=False)
    gen_only = full_text[len(prompt):]

    think_text, response_after = extract_second_think_and_response(gen_only)
    final = extract_boxed_balanced(response_after) or extract_boxed_balanced(gen_only)

    generated_token_ids.append(token_ids_per_seq[i])
    think_blocks.append(think_text)
    responses.append(response_after)
    final_answers.append(final)

results_df = pd.DataFrame({
    "think": think_blocks,
    "response": responses,
    "final": final_answers,
    "num_tokens": [len(x) for x in generated_token_ids],
})

print("Rows:", len(results_df))
results_df.head()

In [ ]:
results_df['response'][0]

In [ ]:
results_df['think'][0]